force-app/main/default/objects/Case/fields/CPL_Joins__c.field-meta.xml
<CustomField>
    <fullName>CPL_Joins__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CPL Joins</label>
    <referenceTo>CPL_Joins__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/isCPLJoin__c.field-meta.xml
<CustomField>
    <fullName>isCPLJoin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCPLJoin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <description>It contains values for Case Sub Type</description>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Headsets</fullName>
            </value>
            <value>
                <fullName>Mouse/Key Board/Monitors</fullName>
            </value>
            <value>
                <fullName>Printers</fullName>
            </value>
            <value>
                <fullName>Bright pattern</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Clearview</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
            <value>
                <fullName>Driver Issues</fullName>
            </value>
            <value>
                <fullName>Data Issues</fullName>
            </value>
            <value>
                <fullName>Media - Routes to Travis</fullName>
            </value>
            <value>
                <fullName>Police Officers/Public Relations</fullName>
            </value>
            <value>
                <fullName>Pen</fullName>
            </value>
            <value>
                <fullName>Notepad</fullName>
            </value>
            <value>
                <fullName>New Art work</fullName>
            </value>
            <value>
                <fullName>Proofs</fullName>
            </value>
            <value>
                <fullName>Request for docusign</fullName>
            </value>
            <value>
                <fullName>Red Line Agreement</fullName>
            </value>
            <value>
                <fullName>Status Update</fullName>
            </value>
            <value>
                <fullName>Portal</fullName>
            </value>
            <value>
                <fullName>Surveys</fullName>
            </value>
            <value>
                <fullName>Telemarketing/Lead Qual</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Changes to Art Work</fullName>
            </value>
            <value>
                <fullName>Hot Leads</fullName>
            </value>
            <value>
                <fullName>Client Products/Services</fullName>
            </value>
            <value>
                <fullName>Consumer Attorney complaint</fullName>
            </value>
            <value>
                <fullName>Inbound Telephone Call</fullName>
            </value>
            <value>
                <fullName>Email Creation</fullName>
            </value>
            <value>
                <fullName>Salesforce Activation</fullName>
            </value>
            <value>
                <fullName>Email Deactivation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with User</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/IT.recordType-meta.xml
<RecordType>
    <fullName>IT</fullName>
    <active>true</active>
    <businessProcess>Case Support Process</businessProcess>
    <description>Hardware, Software, Salesforce, zDrive, AWS</description>
    <label>IT</label>
</RecordType>

force-app/main/default/objects/CPL_Case_Settings__c/CPL_Case_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It will hold CPL  Case Queue detail and User field details</description>
    <label>CPL Case Settings</label>
</CustomObject>

force-app/main/default/objects/CPL_Case_Settings__c/fields/Id_Value__c.field-meta.xml
<CustomField>
    <fullName>Id_Value__c</fullName>
    <description>It holds the Id of User and Queue</description>
    <label>Id Value</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPL_Joins__c/CPL_Joins__c.object-meta.xml
<CustomObject>
    <label>CPL Joins</label>
    <nameField>
        <displayFormat>SC-{0}</displayFormat>
        <label>CPL Join Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPL Joins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CPL_Joins__c/fields/Active_CPL_Join__c.field-meta.xml
<CustomField>
    <fullName>Active_CPL_Join__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active CPL Join</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPL_Joins__c/fields/Billing_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Billing_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The destination CPL business opportunity.</description>
    <label>Billing Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>SPECCARD1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CPL_Joins__c/fields/Lead_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Lead_Distribution__c</fullName>
    <label>Lead Distribution</label>
    <referenceTo>Lead_Distribution__c</referenceTo>
    <relationshipLabel>CPL Joins</relationshipLabel>
    <relationshipName>CPL_Joins</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CPL_Joins__c/fields/Pending_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Pending_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Case Creation functionality</description>
    <label>Pending Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPL_Joins__c/fields/Producing_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Producing_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The nuhome CPL industry opp with the main DID number.</description>
    <label>Producing Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>CPL Spec Card Prod</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>CPL Joins (Producing Opportunity)</relationshipLabel>
    <relationshipName>SPECCARD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Distribution__c/Lead_Distribution__c.object-meta.xml
<CustomObject>
    <label>Lead Distribution</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Lead Distribution ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CPLJoinCaseCreationHandler.cls
/***********************************************************************
CreatedBy : MST
Description : It will create case when Pending_Cancelled is checked. And 
The process of case creation should be triggered when there is only one record 
for which ‘Active CPL Join’ checked.
************************************************************************/

public class CPLJoinCaseCreationHandler
{
   Static Map<String,CPL_Case_Settings__c> caseSettingsMap = CPL_Case_Settings__c.getAll();
   Static List<Case> caseList = new List<Case>();
   static Set<Id> leadDistributionIds = new Set<Id>();
   static Map<Id, List<CPL_Joins__c>> activeCPLMap = new Map<Id, List<CPL_Joins__c>>();
   static String  caseRecTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Inside & Outside Sales').getRecordTypeId();
  
  
   public static void createcase(Map<Id, CPL_Joins__c> newRecMap)
   {
     // Processing all new/updating records.
     for(CPL_Joins__c currRec : newRecMap.values())
     {
        // checking Pending_Cancelled is true
        if(currRec.Pending_Cancelled__c == True && currRec.Active_CPL_Join__c == True)
          {
             // fetching LeadDisctribution id of this CPL join record and assign it to this Set.
              leadDistributionIds.add(currRec.Lead_Distribution__c);
          
          }
     
     }
   
     if(leadDistributionIds.size() > 0)
     {
        // Its identifing how many CPL join records are active cpl join for Lead Distribution records.
        for(CPL_Joins__c currCPl : [SELECT Id, Lead_Distribution__c, Active_CPL_Join__c FROM CPL_Joins__c 
                                    WHERE  Lead_Distribution__c IN :leadDistributionIds AND Active_CPL_Join__c = true ])
        {
           if(activeCPLMap.containskey(currCPl.Lead_Distribution__c))
             activeCPLMap.get(currCPl.Lead_Distribution__c).add(currCPl);
           else
             activeCPLMap.put(currCPl.Lead_Distribution__c,new List<CPL_Joins__c>{currCPl});
        }
     
     }
           
      for(CPL_Joins__c currRec : [SELECT Id,Name,Producing_Opportunity__r.AccountId, Billing_Opportunity__r.Name,
                                  Producing_Opportunity__r.Name, Lead_Distribution__c, Pending_Cancelled__c, Active_CPL_Join__c
                                  FROM CPL_Joins__c WHERE Id IN :newRecMap.keySet()])
      {
          if(currRec.Pending_Cancelled__c == True && 
              currRec.Active_CPL_Join__c == True  &&
              activeCPLMap.containskey(currRec.Lead_Distribution__c) )
          {
               // It is checking, this cpl join is only one active cpl join for this lead distribution or not.
               // if it is yes, it would create case for the CPL join or else it won't create case.
                if(activeCPLMap.get(currRec.Lead_Distribution__c).size() == 1)
                {
                    Case newCase = new Case();
                   
                    newCase.AccountId = currRec.Producing_Opportunity__r.AccountID;
                    newCase.User__c = caseSettingsMap.get('User').id_value__c;
                    newCase.OwnerId= caseSettingsMap.get('Queue').id_value__c;
                    newCase.Origin = 'Auto';
                    newCase.Priority = 'High';
                    newCase.Description = currRec.Name + '_' + currRec.Billing_Opportunity__r.Name + '_' + currRec.Producing_Opportunity__r.Name ;
                    newCase.Type = 'Opportunity';
                    newCase.Sub_Type__c = 'Spec CPL';
                    newCase.Reason = 'Cancelled Customer';
                    newCase.Subject = 'Cancelled Customer; Need New';
                    newCase.CPL_Joins__c = currRec.id;
                    newCase.RecordtypeId = caseRecTypeId;
                    newCase.isCPLJoin__c = true;
                    caseList.add(newCase);
                 }  
                
          }
      
      }
      
      if(caseList.size() > 0)
        insert caseList;
   }

}