force-app/main/default/objects/Case/fields/Created_By__c.field-meta.xml
<CustomField>
    <fullName>Created_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Created By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Created_By_Id__c.field-meta.xml
<CustomField>
    <fullName>Created_By_Id__c</fullName>
    <label>Created By Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <description>It contains values for Case Sub Type</description>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Headsets</fullName>
            </value>
            <value>
                <fullName>Mouse/Key Board/Monitors</fullName>
            </value>
            <value>
                <fullName>Printers</fullName>
            </value>
            <value>
                <fullName>Bright pattern</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Clearview</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
            <value>
                <fullName>Driver Issues</fullName>
            </value>
            <value>
                <fullName>Data Issues</fullName>
            </value>
            <value>
                <fullName>Media - Routes to Travis</fullName>
            </value>
            <value>
                <fullName>Police Officers/Public Relations</fullName>
            </value>
            <value>
                <fullName>Pen</fullName>
            </value>
            <value>
                <fullName>Notepad</fullName>
            </value>
            <value>
                <fullName>New Art work</fullName>
            </value>
            <value>
                <fullName>Proofs</fullName>
            </value>
            <value>
                <fullName>Request for docusign</fullName>
            </value>
            <value>
                <fullName>Red Line Agreement</fullName>
            </value>
            <value>
                <fullName>Status Update</fullName>
            </value>
            <value>
                <fullName>Portal</fullName>
            </value>
            <value>
                <fullName>Surveys</fullName>
            </value>
            <value>
                <fullName>Telemarketing/Lead Qual</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Changes to Art Work</fullName>
            </value>
            <value>
                <fullName>Hot Leads</fullName>
            </value>
            <value>
                <fullName>Client Products/Services</fullName>
            </value>
            <value>
                <fullName>Consumer Attorney complaint</fullName>
            </value>
            <value>
                <fullName>Inbound Telephone Call</fullName>
            </value>
            <value>
                <fullName>Email Creation</fullName>
            </value>
            <value>
                <fullName>Salesforce Activation</fullName>
            </value>
            <value>
                <fullName>Email Deactivation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/nuHome_WebtoCaseController.cls
/******************************************************************************************

Created by: MST
Description : This VF and Controller is enabled for 'Force.com - App Subscription license' users to create case using site link.
*******************************************************************************************/

public class nuHome_WebtoCaseController
{
  public Case caseobj {get;set;}
  public String RecordType{get;set;}
  public boolean displayCaseEditPage{get;set;}
  public boolean displayDetailPage{get;set;}
  public List<Attachment> newAttachments {get; set;}
  public integer NUM_ATTACHMENTS_TO_ADD;
  public Id userId{get;set;}
  public nuHome_WebtoCaseController()
  {
      caseobj = new Case();
      displayDetailPage = false;
      NUM_ATTACHMENTS_TO_ADD = 4;
      String steps = '1';
      newAttachments = new List<Attachment>();
      steps =  apexpages.currentpage().getparameters().get('step');
      
       
      String RecordTypeId = apexpages.currentpage().getparameters().get('RecordTypeid');
      userId = apexpages.currentpage().getparameters().get('userId');
     
      
      //String caseId =  apexpages.currentpage().getparameters().get('Id');
      caseObj.Created_By__c = userId;
      caseObj.Created_By_Id__c = userId;
      if(RecordTypeId != Null)
      {
        caseObj.RecordTypeId = RecordTypeId;
        
      }
      
      if(steps == '1')
      {
          displayCaseEditPage = false;
      }
      else if(steps == '2')
      {
           displayCaseEditPage = true;
      }
      else if(steps == '3')
      {
           displayDetailPage = true;
      }
      
    /*  If(caseId != Null)
      {
        caseobj = [SELECT id, RecordTypeId,CaseNumber,Contact.Name,Status,Priority,Type,Reason,Sub_Type__c,
                   Subject,SuppliedEmail,SuppliedPhone,SuppliedCompany,Description FROM Case WHERE Id = :caseId Limit 1];
      }*/
  
  } 
  // creating case.
  public PageReference casecreate()
  {
      try
      {
      
          //Fetching the assignment rules on case
            AssignmentRule AR = new AssignmentRule();
            AR = [select id from AssignmentRule where SobjectType = 'Case' and Active = true limit 1];

         //Creating the DMLOptions for "Assign using active assignment rules" checkbox
            Database.DMLOptions dmlOpts = new Database.DMLOptions();
            dmlOpts.assignmentRuleHeader.assignmentRuleId= AR.id;
        
          caseObj.setOptions(dmlOpts);
          insert caseobj;
          
          List<Attachment> toInsert=new List<Attachment>();
            for (Attachment newAtt : newAttachments)
            {
                if (newAtt.Body!=null)
                {
                    newAtt.parentId=caseObj.ID;
                    toInsert.add(newAtt);
                }
            }
        
            insert toInsert;
            newAttachments.clear();
         
          
          
          
          pageReference pgRef = new pageReference('https://nuhome--c.na16.visual.force.com/apex/nuHome_Case' );
          pgRef.setRedirect(True);
          return pgRef; 
          
      }
      Catch(DMLException e)
      {
        system.debug('eeeee'+e.getMessage());
      }
    return null;
  }
  
  // Getting all the Record Type info.
    public list<selectoption> GetTypeValues(){
        List<SelectOption> options = new List<SelectOption>();
        for(recordtype records:[select Id,Name from recordtype where SobjectType='Case']){
            options.add(new SelectOption(records.Id,records.Name));
        }
        return options;
    }

  // Based on the Record Type selection, Page will render picklist values.
   public pageReference chooseRT()
   {
            displayCaseEditPage = true;
            pageReference pgRef = new pageReference('/apex/nuHome_WebtoCase?RecordTypeid='+recordtype+'&Step=2'+'&userId='+userId);
            pgRef.setRedirect(True);
            return pgRef;
           
   
   }
    // Back to case list page.
   public pageReference Cancel()
   {
            pageReference pgRef = new pageReference('https://nuhome--c.na16.visual.force.com/apex/nuHome_Case' );
            pgRef.setRedirect(True);
            return pgRef;
   
   }
   
   // Adding more attachments row.
   public void addMore()
    {
        for (Integer idx=0; idx<NUM_ATTACHMENTS_TO_ADD; idx++)
        {
            newAttachments.add(new Attachment());
        }
    }
}