force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/Closed_Won_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Won_Date__c</fullName>
    <formula>Home_Service__r.Closed_Won_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closed Won Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <label>Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Commission_Status__c.field-meta.xml
<CustomField>
    <fullName>Commission_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Commission Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Paid_By__c.field-meta.xml
<CustomField>
    <fullName>Paid_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paid By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personnel</label>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Closed_Won_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Won_Date__c</fullName>
    <label>Closed Won Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <formula>Total_Commission__c  /  Total_Gross_Sale__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Commissions_Record_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commissions_Record_Amount__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Commissions Record Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.FirstName),&apos;&apos;,Account__r.FirstName)</formula>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.LastName),&apos;&apos;,Account__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Sale_Commission_Paid__c.field-meta.xml
<CustomField>
    <fullName>Sale_Commission_Paid__c</fullName>
    <label>Sale Commission Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/SF_User__c.field-meta.xml
<CustomField>
    <fullName>SF_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Personnels2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CommissionTriggerHelper.cls
/*
 * Diaco
 * @author             Jull Quintero Daza
 * Project:            Commission Trigger
 * TestClass:          CommissionTriggerTest
 * Description:        Helper
 *
 * Changes (Version)
 * _________________________________________
 *            No.        Date            Author                    Description
 *            ____    __________        __________________      _____________________________________
 * @version    1.0    06/10/2020         Jull Quintero D         Initial implementation of the class.
 **/

public class CommissionTriggerHelper {

/**
 * @Author Álvaro Ortega (AO) | 17/10/2019  
 * @Author Jull Quintero | 07/10/2020  
 * @Description:
 * Assign Commission Name
 * Assign Commission owner when personnel user is not null and is activate
 * This method is after Insert
 * 
 * This method is used in:
 * CommissionTrigger
 * 
 * @param Set<Id> commissionIds
 **/
public static void assignCommissionNameAndUser(Set<Id> commissionIds) {
    List<Commission__c> commissions = new List<Commission__c>(); 
    Map<Id,Commission__c> commissionMap = new Map<Id,Commission__c> 
                                    ([SELECT Id,CreatedDate,LastModifiedDate,Home_Service__c,
                                        Home_Service__r.RecordType.Name,Home_Service__r.Closed_Won_Date__c,
                                        Personnel__c,Personnel__r.First_Name__c,Personnel__r.Last_Name__c,
                                        Personnel__r.SF_User__c,Personnel__r.SF_User__r.IsActive
                                    FROM Commission__c 
                                    WHERE Id IN :commissionIds ORDER BY Home_Service__c]);

    Map<Id,Id> HScommissions=new Map<Id,Id>();
    for (Id commissionId : commissionMap.keySet()) {
        Commission__c commission = commissionMap.get(commissionId);
        HScommissions.put(commission.Id,commission.Home_Service__c);
    }
    Map<Id,Home_Services__c> homeServicesMap = new Map<Id,Home_Services__c>
                                            ([SELECT Id, (SELECT Id, Name FROM Commissions__r) 
                                            FROM Home_Services__c 
                                            WHERE Id IN :HScommissions.values()]); 
    integer countCommissions;
    Integer auxCount=0;
    Id oldHsId;
    for (Id commissionId : HScommissions.keySet()) {
        Id hsId = HScommissions.get(commissionId);
        Commission__c commission = commissionMap.get(commissionId);
        Home_Services__c homeService = homeServicesMap.get(hsId);

        //Assign Name
        //auxCount = hsId == oldHsId ?  auxCount+=1 : 0; 
        if ( hsId != oldHsId ) {
            countCommissions = homeService.Commissions__r.size();
            auxCount=0;
        }else{
            auxCount+=1;
        }
        integer nummber = countCommissions - auxCount;
        string name = '';
        if( commission.Personnel__c != null ) {
            name = commission.Personnel__r.First_Name__c + ' ' + commission.Personnel__r.Last_Name__c;
        }
        commission.Name=name + ' - M' + nummber + ' ' + commission.Home_Service__r.RecordType.Name;

        // Assign User
        if( commission.Personnel__r.SF_User__c != null && commission.Personnel__r.SF_User__r.IsActive ){
            commission.OwnerId=commission.Personnel__r.SF_User__c;
        }
        commissions.add(commission);
        oldHsId = hsId;
    }

    TriggerHandler.bypass('CommissionTrigger');
        if(!commissions.isEmpty()) update commissions;       
    TriggerHandler.clearBypass('CommissionTrigger');
}

/**
 * @Author * | * 
 * @Author Jull Quintero | 06/10/2020  
 * @Description:
 * If the new commission was created with the paid status
 * If the commission was deleted with the paid status
 * If the commission was updated with change to Commission Status  or Commission Amount
 * This method is after Insert, after Update, after Delete
 * 
 * This method is used in:
 * CommissionTrigger
 * 
 * @param Boolean isUpdate
 * @param Commission__c newCommissions
 * @param Map<Id,Commission__c> oldCommission
 **/
    public static void homeServiceCommissionPaid(Boolean isUpdate,List<Commission__c> newCommissions,Map<Id,Commission__c> oldCommssMap) {
        //set representing the HomeServices whose total paid commissions field will be update, a Set to avoid duplicated operations
        Set<String> hsToUpdate = new Set<String>();

        integer commssonsLength = newCommissions.size();
        for (Integer i = 0; i < commssonsLength; i++) {
            Commission__c commission = newCommissions[i];
            if( isUpdate ){
                if((commission.Commission_Status__c != oldCommssMap.get(commission.Id).Commission_Status__c) ||
                    commission.Commission_Amount__c != oldCommssMap.get(commission.Id).Commission_Amount__c){
                    hsToUpdate.add(commission.Home_Service__c);
                }
            }else{
                if( commission.Commission_Status__c=='Paid' ) hsToUpdate.add(commission.Home_Service__c);
            }
        }
        
        if( !hsToUpdate.isEmpty() ) {
            if( !System.isFuture() && !System.isBatch() ) {
                updateTotalCommissionPaidField(hsToUpdate);
                updateCommissionRecordAmountField(hsToUpdate);
            }
        } 
    }

        /**
     * @Author 
     * @Description:
     * Update  Field Homeservice Sale Commission Paid with Total Commission Amount when Commission Status is paid 
     * 
     * This method is used in:
     * homeServiceCommissionPaid
     * 
     * @param Set<Id> HomeService Id
     **/
    @future
    private static void updateTotalCommissionPaidField(set<String> homeServicesToUpdate) {
        list<Home_Services__c> homeServices=new list<Home_Services__c>();
        list<AggregateResult> commissionsAggregated=[SELECT SUM(Commission_Amount__c) sums,Home_Service__c 
                                                    FROM Commission__c 
                                                    WHERE (Home_Service__c IN :homeServicesToUpdate and Commission_Status__c='Paid') GROUP BY Home_Service__c];
        
        for(AggregateResult result : commissionsAggregated){
            Home_Services__c hs= new Home_Services__c(Id=(String)result.get('Home_Service__c'),Sale_Commission_Paid__c=(Decimal)result.get('sums'));
            homeServices.add(hs); 
        }
        
        if(commissionsAggregated.size()<1){
            for(String hsId:homeServicesToUpdate){
                Home_Services__c hs= new Home_Services__c(Id=hsId,Sale_Commission_Paid__c=null);
                homeServices.add(hs); 
            }
        }

        update homeServices;
    }

    /**
    * @Author 
    * @Description:
    * Update  field Homeservice Commissions Record Amount with Total Commission Amount when Commission Status is changes or is paid 
    * or is changes  Commission Amount
    * 
    * This method is used in:
    * homeServiceCommissionPaid
    * 
    * @param Set<Id> HomeService Id
    **/
    @future
    private static void updateCommissionRecordAmountField(set<String> homeServicesToUpdate) {
        list<Home_Services__c> homeServices=new list<Home_Services__c>();
        list<AggregateResult> commissionsAggregated=
            [SELECT SUM(Commission_Amount__c) sums,Home_Service__c 
            FROM Commission__c 
            WHERE Home_Service__c IN :homeServicesToUpdate GROUP BY Home_Service__c];

        for(AggregateResult result : commissionsAggregated){
            Home_Services__c hs= new Home_Services__c(Id=(String)result.get('Home_Service__c'),Commissions_Record_Amount__c=(Decimal)result.get('sums'));
            homeServices.add(hs); 
        }

        if(commissionsAggregated.size()<1){
            for(String hsId:homeServicesToUpdate){
                Home_Services__c hs= new Home_Services__c(Id=hsId,Commissions_Record_Amount__c=null);
                homeServices.add(hs); 
            }
        }
        
        update homeServices;
    }
}