force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <label>Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line Item</label>
    <referenceTo>Line_Item__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personnel</label>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <formula>Total_Commission__c  /  Total_Gross_Sale__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Sales_Rep_Personnel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Personnel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep Personnel</label>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Home Services (Sales Rep Personnel)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Bill_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Start_Date__c</fullName>
    <label>Bill Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commission</label>
    <referenceTo>Commission__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Line Items (HS)</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Monthly_Investment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Investment__c</fullName>
    <label>Monthly Investment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Service_Check__c.field-meta.xml
<CustomField>
    <fullName>Service_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DiacoScheduleCommissionOnLineItem.cls
global class DiacoScheduleCommissionOnLineItem {
    
    global DiacoScheduleCommissionOnLineItem() {
        
        system.debug('Inicio Prueba de creación de comisiones mensuales por LineItem');
        actions();  
        deleteJob();
        assignjob();
        system.debug('Fin Prueba de creación de comisiones mensuales por LineItem');
    }
    public static Decimal decimalMod(decimal x, integer y){
        Decimal remainder = 0;
        if(x != 0){
            Decimal firstResult = x / y; 
            Decimal flooredResult = math.floor(firstResult);
            Decimal flooredProduct = flooredResult * y;
            remainder = x - flooredProduct; 
        }
        return remainder;
    }
    
    public static void actions() {
        DateTime myDateTime = system.now();
		//system.debug('Start actions'); 
		List<Line_Item__c> lis = [SELECT Id, Name, Monthly_Investment__c, Home_Service__c, CreatedDate FROM Line_Item__c WHERE Service_Check__c = true and Active__c = true];
        
        List<Line_Item__c> newLis = new List<Line_Item__c>();
        List<String> HSIds = new List<String>();
        
        
        for(Line_Item__c lineItem : lis ){
            //system.debug(myDateTime.getTime()+' - '+lineItem.CreatedDate.getTime());
            // system.debug(myDateTime.getTime() - lineItem.CreatedDate.getTime());
            /*long days = (myDateTime.getTime() - lineItem.CreatedDate.getTime()) / 86400000;
            if(decimaMod(days / 30, 1)){
                // 
            }*/
           //  DateTime aux = DateTime.newInstance(lineItem.Bill_Start_Date__c, Time.newInstance(0,0,0,0));
            decimal days = ((myDateTime.getTime() - lineItem.CreatedDate.getTime()) / 86400000).intValue();
            decimal toTest = (days / 30);
            //system.debug(lineItem.Name + ': ' + minutes +' - '+(toTest));
            
            if(decimalMod(toTest, 1) == 0){
                //createCommission(lineItem);
               // system.debug(lineItem.Name + ' - Nueva comisión.');
               newLis.add(lineItem);
               HSIds.add(lineItem.Home_Service__c);
            }
            system.debug(days);
            
            //system.debug(lineItem.Name + ': ' + days);
            system.debug('---------------------');
        }
        List<Home_Services__c> HSs = [SELECT Id, Sales_Rep_Personnel__c FROM Home_Services__c WHERE id in :HSIds];
        
        List<Commission__c> cms = new List<Commission__c>();
        for(Line_Item__c lineItem : newLis){
             for(Home_Services__c homeService : HSs ){
                 if(lineItem.Home_Service__c == homeService.Id){
                     cms.add(createCommission(lineItem, homeService.Sales_Rep_Personnel__c));
                     break;
                 }
             }
        }
        insert cms;
      
        
        
        //system.debug('End actions'); 
    }
    
    public static Commission__c createCommission(Line_Item__c lineItem, string personnelId) {
        
        Commission__c nc =  new Commission__c();
        nc.Name = lineItem.Name+' - Commision';
        nc.Home_Service__c = lineItem.Home_Service__c;
        // Home_Services__c hs = [SELECT Id, Sales_Rep_Personnel__c FROM Home_Services__c WHERE id=:nc.Home_Service__c ];
        nc.Personnel__c = personnelId;
        // nc.Personnel__c = lineItem.Home_Service__c.
        nc.Commission_Amount__c = lineItem.Monthly_Investment__c * 0.2;
        system.debug(nc.Commission_Amount__c);
       	//insert nc;
       	return nc;
        
        
        /*/**despues de 30 dias, partiendo de la fecha inicial se cambie a cancelado. 
        List<Contract> contracts = new List<Contract>();
        
        Contract[] capitaIntencion = [SELECT Id, StartDate FROM Contract WHERE F1_ModalidadPago__c = 'CARTA DE INTENCIÓN'];
        if(capitaIntencion.size() > 0 ) {
            
            for(Contract c: capitaIntencion) {
                date startDate = (date)c.StartDate;
                if( (startDate + 30) == system.today() ) {
                    
                    c.Status = 'Activated';
                    contracts.add(c);
                }
                
                try{
                    
                    update contracts;
                }catch(Exception e){
                    system.debug('Exception: ' + e.getMessage());                    
                }
            }
        }*/      
    }
    
    public static void assignjob() {
        //system.debug('Start assignJob');
        
        DateTime myDateTime = system.now().addMinutes(24*60);
        // f1_CambioEstadoCartadeIntencion shedule = new f1_CambioEstadoCartadeIntencion();
        DiacoScheduleCommissionOnLineItemCaller shedule = new DiacoScheduleCommissionOnLineItemCaller();
       	String title = 'Create Commission monthly during a year of Line Item';
        String sch = '0 '+myDateTime.minute()+' '+myDateTime.hour()+' '+myDateTime.day()+' '+myDateTime.month()+' ?';
        // system.debug(sch);
        system.schedule(title, sch, shedule);     
        
        //system.debug('End assignJob');
    }
    
    public static void deleteJob() {
        String title = 'Create Commission monthly during a year of Line Item';
        for(CronTrigger con  : [SELECT Id, CronJobDetail.Name, CronJobDetail.Id, State FROM CronTrigger]){
            if(con.CronJobDetail.Name == title){
                System.abortJob(con.Id);
            }
        }
    }
}