force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <label>Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Commission_Status__c.field-meta.xml
<CustomField>
    <fullName>Commission_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Commission Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <formula>Total_Commission__c  /  Total_Gross_Sale__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Commissions_Record_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commissions_Record_Amount__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Commissions Record Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Sale_Commission_Paid__c.field-meta.xml
<CustomField>
    <fullName>Sale_Commission_Paid__c</fullName>
    <label>Sale Commission Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DiacoCommissionRelatedMethods.cls
public class DiacoCommissionRelatedMethods {
    @future
    public static void updateTotalCommissionPaidField(set<String> homeServicesToUpdate){
        list<Home_Services__c> homeServices=new list<Home_Services__c>();
        list<AggregateResult> commissionsAggregated=
            [SELECT SUM(Commission_Amount__c) sums,Home_Service__c FROM Commission__c WHERE (Home_Service__c IN :homeServicesToUpdate and Commission_Status__c='Paid') GROUP BY Home_Service__c];
        system.debug('Resultado de la consulta');
        
        system.debug(commissionsAggregated);
        
        system.debug('hs a actualizar');
        
        system.debug(homeServicesToUpdate);
        for(AggregateResult result : commissionsAggregated){
            Home_Services__c hs= new Home_Services__c(Id=(String)result.get('Home_Service__c'),Sale_Commission_Paid__c=(Decimal)result.get('sums'));
            homeServices.add(hs); 
        }
        
        if(commissionsAggregated.size()<1){
            for(String hsId:homeServicesToUpdate){
                Home_Services__c hs= new Home_Services__c(Id=hsId,Sale_Commission_Paid__c=null);
                homeServices.add(hs); 
            }
            system.debug('lista vacia');
        }
        upsert homeServices;
    }
    
    
    @future
    public static void updateCommissionRecordAmountField(set<String> homeServicesToUpdate){
        list<Home_Services__c> homeServices=new list<Home_Services__c>();
        list<AggregateResult> commissionsAggregated=
            [SELECT SUM(Commission_Amount__c) sums,Home_Service__c FROM Commission__c WHERE Home_Service__c IN :homeServicesToUpdate GROUP BY Home_Service__c];
        //if(commissionsAggregated.size()<1)homeServices.add(hs); 
        for(AggregateResult result : commissionsAggregated){
            Home_Services__c hs= new Home_Services__c(Id=(String)result.get('Home_Service__c'),Commissions_Record_Amount__c=(Decimal)result.get('sums'));
            homeServices.add(hs); 
        }
        if(commissionsAggregated.size()<1){
            for(String hsId:homeServicesToUpdate){
                Home_Services__c hs= new Home_Services__c(Id=hsId,Commissions_Record_Amount__c=null);
                homeServices.add(hs); 
            }
            system.debug('lista vacia');
        }
        
        upsert homeServices;
    }
 
}