force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <label>Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Commission_Status__c.field-meta.xml
<CustomField>
    <fullName>Commission_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Commission Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Paid__c.field-meta.xml
<CustomField>
    <fullName>Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personnel</label>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/ApptSetter__c.field-meta.xml
<CustomField>
    <fullName>ApptSetter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appointment Setter</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Personnel__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Personnel__c.Appt_Setter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Home Services (Appointment Setter)</relationshipLabel>
    <relationshipName>Home_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <formula>Total_Commission__c  /  Total_Gross_Sale__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Sale_Commission_Paid__c.field-meta.xml
<CustomField>
    <fullName>Sale_Commission_Paid__c</fullName>
    <label>Sale Commission Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/fields/Kunnect_ID__c.field-meta.xml
<CustomField>
    <fullName>Kunnect_ID__c</fullName>
    <inlineHelpText>This is a Required field.  If this person does not have a Kunnect account please put &quot;none&quot;</inlineHelpText>
    <label>Kunnect ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CommissionTriggerTest.cls
@IsTest
private class CommissionTriggerTest { //DiacoCommissionTriggerUnifiedTest
    @isTest static void TestInsertCommissionForUpdate() {
        
        Personnel__c personnel=new Personnel__c(name='personnel test',Kunnect_ID__c='none');
        insert personnel;
        Home_Services__c hs=new Home_Services__c(Name='test hs',ApptSetter__c=personnel.Id);
        insert hs;
        List<Commission__c> commissions = new List<Commission__c>();
        for (Integer i = 0; i < 10; i++) {
            commissions.add(
                new Commission__c
                (
                    Name='test commission',
                    Approved__c=true,Paid__c=true,
                    Commission_Status__c='Paid',
                    Commission_Amount__c=1000,
                    Home_Service__c=hs.Id,
                    Personnel__c=personnel.Id
                ));  
        }
        Test.startTest();
            insert commissions;
        Test.stopTest();  
        System.debug('after insert test');
        System.debug([SELECT id,Sale_Commission_Paid__c FROM Home_Services__c].Sale_Commission_Paid__c==1000);
    }

    @isTest static void TestUpdateCommissionForUpdate() {
        
        Personnel__c personnel=new Personnel__c(name='personnel test',Kunnect_ID__c='none');
        insert personnel;
        Home_Services__c hs=new Home_Services__c(Name='test hs',ApptSetter__c=personnel.Id);
        insert hs;

        Commission__c commission = new Commission__c(Name='test commission',Approved__c=true,Paid__c=true,Commission_Status__c='Paid',Home_Service__c=hs.Id,Commission_Amount__c=100);
        insert commission;
        
        Commission__c commission2 = new Commission__c(Name='test commission',Approved__c=true,Paid__c=true,Commission_Status__c='Paid',Home_Service__c=hs.Id,Commission_Amount__c=200);
        insert commission2;
        // Perform test
        System.debug('Before update test');
        
        Test.startTest();
        commission.Paid__c=false;
        commission.Commission_Status__c='Approved';
        commission2.Commission_Amount__c=500;
        update commission;
        update commission2;
        Test.stopTest();  
        
        System.debug('after update test');
        System.debug([SELECT id,Sale_Commission_Paid__c FROM Home_Services__c].Sale_Commission_Paid__c==500);
    }

    @isTest static void TestDeleteCommissionForUpdate() {
        
        Personnel__c personnel=new Personnel__c(name='personnel test',Kunnect_ID__c='none');
        insert personnel;
        Home_Services__c hs=new Home_Services__c(Name='test hs',ApptSetter__c=personnel.Id);
        insert hs;
        

        Commission__c commission2 = new Commission__c(Name='test commission',Approved__c=true,Paid__c=true,Commission_Status__c='Paid',Home_Service__c=hs.Id,Commission_Amount__c=200);
        insert commission2;
        
        System.debug('Before delete test');
        
        Test.startTest();
        delete commission2;
        Test.stopTest();  
        
        System.debug('after delete test');
        System.debug([SELECT id,Sale_Commission_Paid__c FROM Home_Services__c].Sale_Commission_Paid__c==0);
    }

}