force-app/main/default/objects/DocusignCredentials__c/DocusignCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>DocusignCredentials</label>
</CustomObject>

force-app/main/default/objects/DocusignCredentials__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocusignCredentials__c/fields/IntegratorKey__c.field-meta.xml
<CustomField>
    <fullName>IntegratorKey__c</fullName>
    <label>IntegratorKey</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocusignCredentials__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocusignCredentials__c/fields/TemplateID__c.field-meta.xml
<CustomField>
    <fullName>TemplateID__c</fullName>
    <label>TemplateID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocusignCredentials__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <label>UserName</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/nuHome_Docusign.cls
/*********************************************************
Creted By: MST
Description : Webservice class to void the docusign envelope.
**********************************************************/
global class nuHome_Docusign
{
    webservice static void voidMethod(String Docusignenvid)
    { 
        system.debug('#########envelope called');
        Map<String,DocusignCredentials__c> documap = DocusignCredentials__c.getall();
        String accountID = documap.get('DousignCredential1').AccountId__c;
        String UserName = documap.get('DousignCredential1').UserName__c;
        String Password = documap.get('DousignCredential1').Password__c;
        String IntegratorKey = documap.get('DousignCredential1').IntegratorKey__c;
        String TemplateID = documap.get('DousignCredential1').TemplateID__c;
        String useremail = UserInfo.getUserEmail();
        string endpoint = 'https://www.docusign.net/restapi/v2/accounts/'+accountID+'/envelopes';
        

        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpoint+'/'+Docusignenvid);
        req.setMethod('PUT');
        String authorizationHeader = '<DocuSignCredentials><Username>'+UserName+'</Username><Password>'+Password+'</Password><IntegratorKey>'+IntegratorKey+'</IntegratorKey></DocuSignCredentials>';
        req.setHeader('X-DocuSign-Authentication', authorizationHeader);
        req.setHeader('Accept','application/json');
        req.setHeader('Host','demo.docusign.net');
        req.setHeader('Content-Length','162100');
        req.setHeader('Content-Type','application/json');
        req.setHeader('Content-Disposition','form-data');
        system.debug('Header Debug'+authorizationHeader);
        //Docusign Request payload with recipient informations and the account is to be merged in the docusign document.
        
        String json=        '{'+
            '"status":"voided",'+
            '"voidedReason":"\n\nNuHome Agreement Cancelled."'+
            '}';
        
        req.setBody(json);
        
        Http http = new Http();
        HTTPResponse res;
                if(!test.isRunningTest()){
        res = http.send(req);
                        
        system.debug('Response debug'+res);
            }    
        
        
    }
}