force-app/main/default/objects/Call_Log__c/Call_Log__c.object-meta.xml
<CustomObject>
    <label>Call Log</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Call Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account associated with this call.</description>
    <inlineHelpText>The account associated with this call.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/ANI__c.field-meta.xml
<CustomField>
    <fullName>ANI__c</fullName>
    <description>Caller ID Number</description>
    <inlineHelpText>Caller ID Number</inlineHelpText>
    <label>ANI</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <description>Formula to flag trigger to create billable inventory record when a call is forwarded to a company after activation or after hours.</description>
    <formula>AND( 
Answered_Duration__c &gt;= 0, 
OR(Record_Type__c = &quot;nuHome nuCard CPL&quot;,Record_Type__c = &quot;nuHome nuCard SUB&quot;,Record_Type__c = &quot;nuHome nuCard SPEC&quot;) 
, 
Account__c != NULL, 
Record_Type__c != NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula to flag trigger to create billable inventory record when a call is forwarded to a company after activation or after hours.</inlineHelpText>
    <label>Billable?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Call_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Call_Disposition__c</fullName>
    <description>The system or agent disposition for this call record.</description>
    <inlineHelpText>The system or agent disposition for this call record.</inlineHelpText>
    <label>Call Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Announcement</fullName>
            </value>
            <value>
                <fullName>Answering Machine</fullName>
            </value>
            <value>
                <fullName>Appointment Set</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Call Back Appointment</fullName>
            </value>
            <value>
                <fullName>Call Back Later</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
            <value>
                <fullName>Dropped while talking</fullName>
            </value>
            <value>
                <fullName>Fast busy</fullName>
            </value>
            <value>
                <fullName>Fax or modem</fullName>
            </value>
            <value>
                <fullName>Has Provider</fullName>
            </value>
            <value>
                <fullName>Invalid number</fullName>
            </value>
            <value>
                <fullName>Network announcement</fullName>
            </value>
            <value>
                <fullName>No answer</fullName>
            </value>
            <value>
                <fullName>No disposition</fullName>
            </value>
            <value>
                <fullName>No English</fullName>
            </value>
            <value>
                <fullName>No numbers left to call</fullName>
            </value>
            <value>
                <fullName>Not Answered</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Number matches DNC</fullName>
            </value>
            <value>
                <fullName>Other connection issue</fullName>
            </value>
            <value>
                <fullName>Persons Work Phone</fullName>
            </value>
            <value>
                <fullName>Person&apos;s Work Phone</fullName>
            </value>
            <value>
                <fullName>QC Call</fullName>
            </value>
            <value>
                <fullName>Silence</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>System failure</fullName>
            </value>
            <value>
                <fullName>Warm Transfer</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
            <value>
                <fullName>Wrong person</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Call_Notes__c.field-meta.xml
<CustomField>
    <fullName>Call_Notes__c</fullName>
    <description>Notes an agent enters in during a call.</description>
    <inlineHelpText>Notes an agent enters in during a call.</inlineHelpText>
    <label>Call Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/DID__c.field-meta.xml
<CustomField>
    <fullName>DID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Did record that is associated with this call.</description>
    <inlineHelpText>Did record that is associated with this call.</inlineHelpText>
    <label>DID</label>
    <referenceTo>DID__c</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Inventory_Created__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Once inventory is created this box should be updated to = True. 
This should prevent duplicate inventory being created.</description>
    <inlineHelpText>Once inventory is created this box should be updated to = True. 
This should prevent duplicate inventory being created.</inlineHelpText>
    <label>Inventory Created?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>DID__r.fOpportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DID__c/DID__c.object-meta.xml
<CustomObject>
    <label>DID</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}:{00}</displayFormat>
        <label>DID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DID__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>DIDs</relationshipLabel>
    <relationshipName>DIDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/ANI__c.field-meta.xml
<CustomField>
    <fullName>ANI__c</fullName>
    <label>ANI</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Call_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Call_Disposition__c</fullName>
    <label>Call Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Appointment Set</fullName>
            </value>
            <value>
                <fullName>Appt Set: IB</fullName>
            </value>
            <value>
                <fullName>Appt Set: OB</fullName>
            </value>
            <value>
                <fullName>Appt set: Project Yes</fullName>
            </value>
            <value>
                <fullName>Appt Set and Inventory Created</fullName>
            </value>
            <value>
                <fullName>Transfer: IB</fullName>
            </value>
            <value>
                <fullName>Transfer: OB</fullName>
            </value>
            <value>
                <fullName>Transfer: Project Yes</fullName>
            </value>
            <value>
                <fullName>Business No Answer</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Call Back Appointment</fullName>
            </value>
            <value>
                <fullName>Delivered to Wrong House</fullName>
            </value>
            <value>
                <fullName>Disposition</fullName>
            </value>
            <value>
                <fullName>Dropped while talking</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Failed Transfer</fullName>
            </value>
            <value>
                <fullName>Hang Up</fullName>
            </value>
            <value>
                <fullName>Lead Returned</fullName>
            </value>
            <value>
                <fullName>Left Message</fullName>
            </value>
            <value>
                <fullName>Manager Call</fullName>
            </value>
            <value>
                <fullName>Need a Pro</fullName>
            </value>
            <value>
                <fullName>No Answer</fullName>
            </value>
            <value>
                <fullName>No Email</fullName>
            </value>
            <value>
                <fullName>No Email/Activation</fullName>
            </value>
            <value>
                <fullName>No English</fullName>
            </value>
            <value>
                <fullName>No Gift Box Delivered</fullName>
            </value>
            <value>
                <fullName>No Good</fullName>
            </value>
            <value>
                <fullName>No Home owner</fullName>
            </value>
            <value>
                <fullName>No Network</fullName>
            </value>
            <value>
                <fullName>Not Homeowner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Call_Notes__c.field-meta.xml
<CustomField>
    <fullName>Call_Notes__c</fullName>
    <label>Call Notes</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/DID__c.field-meta.xml
<CustomField>
    <fullName>DID__c</fullName>
    <label>DID</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Sale_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Sale_Disposition__c</fullName>
    <label>Sale Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>No Good</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Pitch and miss</fullName>
            </value>
            <value>
                <fullName>1 Leg</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Reset</fullName>
            </value>
            <value>
                <fullName>Did not run</fullName>
            </value>
            <value>
                <fullName>Sale turn down</fullName>
            </value>
            <value>
                <fullName>Sale cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DID__c.field-meta.xml
<CustomField>
    <fullName>DID__c</fullName>
    <label>DID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Inventory_Created__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates that hot lead invetory record created or not for this user address</description>
    <label>Inventory Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CallLogTriggerHelper.cls
/*
    Developer Name : Ganesh
    Created Date : Dec 8th 2016
*/

public class CallLogTriggerHelper{

    private Static void ProcessInventoryfromCallLogs(map<id,Call_Log__c> newMap)
    {
        // COllecting All DID__c Id's
        set<ID> dIDRecSet = new set<ID>();
        List<Call_Log__c> updCallLogInvCreatedFlagColl = new List<Call_Log__c>();
        for(Call_Log__c callLogs : newMap.values()){
            dIDRecSet.add(callLogs.DID__c);
        }
        
        // Getting all Opportunity ids for DID__c records
        List<inventory__C> newInventoryList = new List<inventory__c>();
        map<id,DID__c> newMApWithDID = new map<id,DID__c>([select id,Opportunity__c 
                                                            from DID__c where id in : dIDRecSet and Opportunity__c != null]);
                                                            
        for(Call_Log__c callLogs : newMap.values()){
            if(callLogs.Billable__c && callLogs.Inventory_Created__c == false){
                
                id idCpl = (callLogs.DID__c == null ? null : newMApWithDID.get(callLogs.DID__c).Opportunity__c);                
                
                // Getting RecordType Name for Call_Log__c Record
                string nameRecType  = Schema.SObjectType.Call_Log__c.getRecordTypeInfosById().get(callLogs.RecordTypeId).getName(); 
                
                
                // Getting RecordType Id based on Call_Log__c record RecordTypeName
                Id recorcTyeId = Schema.SObjectType.inventory__c.getRecordTypeInfosByName().get(nameRecType).getRecordTypeId();
                
                // Forming New inventory__C
                newInventoryList.add(new inventory__C(recordtypeid = recorcTyeId ,
                    Sale_Disposition__c='Install',ANI__c = callLogs.ANI__c ,
                    Call_Disposition__c = callLogs.Call_Disposition__c ,
                    Call_Notes__c = callLogs.Call_Notes__c ,Account__c = callLogs.Account__c ,
                    User_Address__c = callLogs.User_Address__c ,Industry__c = callLogs.Industry__c,
                    Inventory_Type__c = callLogs.Record_Type__c, interactionStepId__c = callLogs.interactionStepId__c,
                    idCPL_Billing_Opportunity__c = idCpl,Call_Time__c = callLogs.Answered_Duration__c));  
                // update the inventory created flag after insertion of inventory records 
                updCallLogInvCreatedFlagColl.add(new Call_log__c(id=callLogs.id,Inventory_Created__c = true));
            }           
        }
        
        // Inserting New inventory__C Records
        if(newInventoryList.size() > 0){
            insert newInventoryList;
            update updCallLogInvCreatedFlagColl;
        }
    }
    public static void afterInsertHandler(map<id,Call_Log__c> newMap){
        CallLogTriggerHelper.ProcessInventoryfromCallLogs(newMap);           
    } 
    public static void afterUpdateHandler(map<id,Call_Log__c> newMap){        
        CallLogTriggerHelper.ProcessInventoryfromCallLogs(newMap);
    }    
}