force-app/main/default/objects/neverBounce__c/neverBounce__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>neverBounce</label>
</CustomObject>

force-app/main/default/objects/neverBounce__c/fields/ApiKey__c.field-meta.xml
<CustomField>
    <fullName>ApiKey__c</fullName>
    <label>ApiKey</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/Emails_per_page__c.field-meta.xml
<CustomField>
    <fullName>Emails_per_page__c</fullName>
    <label>Emails per page</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/First_Job__c.field-meta.xml
<CustomField>
    <fullName>First_Job__c</fullName>
    <label>First Job</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/Job_id__c.field-meta.xml
<CustomField>
    <fullName>Job_id__c</fullName>
    <label>Job id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/next_page__c.field-meta.xml
<CustomField>
    <fullName>next_page__c</fullName>
    <defaultValue>0</defaultValue>
    <label>next page</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/number_of_pages__c.field-meta.xml
<CustomField>
    <fullName>number_of_pages__c</fullName>
    <label>number of pages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/Second_Job__c.field-meta.xml
<CustomField>
    <fullName>Second_Job__c</fullName>
    <label>Second Job</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sms_Url__c/Sms_Url__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations to activate sms function.</description>
    <label>SMS Url</label>
</CustomObject>

force-app/main/default/objects/Sms_Url__c/fields/Activate_sms_function__c.field-meta.xml
<CustomField>
    <fullName>Activate_sms_function__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate sms function</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sms_Url__c/fields/Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Sender_Id__c</fullName>
    <label>Sender Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sms_Url__c/fields/Sms_Text__c.field-meta.xml
<CustomField>
    <fullName>Sms_Text__c</fullName>
    <label>Sms Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/diacoSmsHSTest.cls
@isTest
public class diacoSmsHSTest {
    @isTest static void testAll(){
        neverBounce__c nb = new neverBounce__c(
            Job_id__c = '277461',
            number_of_pages__c = 10,
            next_page__c = 1, 
            ApiKey__c = 'Apikey******', 
            First_Job__c = 3, 
            Second_Job__c =1, 
            Emails_per_page__c = 10 
        );
        upsert nb;
        //Config sms function
        Sms_Url__c sms = new Sms_Url__c(
            Activate_sms_function__c =true,
            Sender_Id__c = '1244',
            Function__c = 'Sweepstake',
            Sms_Text__c = 'Sms sweepstake'
        );
        upsert sms;
        //Create account
        Account acc = new Account(
            FirstName = 'Test acc',
            LastName = 'last test'
            //PersonEmail = 'test@test.com'
        );        
        
        test.startTest();
        test.setMock(HttpCalloutMock.class, new diacoValidateEmailHttpCallOutMock());
        insert acc;
        acc.PersonEmail = 'test@test.com';
        acc.Phone = '4803061365';
        System.debug(acc);
        diacoSmsHS.Sweepstake(acc, 0);
        List<String> paramList = new List<String>();
        paramList.add(acc.Id);
        diacoSmsHS.Sweepstake(paramList);
        test.stopTest();
    }

}