force-app/main/default/objects/Orientation__c/Orientation__c.object-meta.xml
<CustomObject>
    <label>Orientation</label>
    <nameField>
        <label>Orientation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orientations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Orientation__c/fields/Current_Orientation__c.field-meta.xml
<CustomField>
    <fullName>Current_Orientation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tranings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Orientation__c.field-meta.xml
<CustomField>
    <fullName>Orientation__c</fullName>
    <label>Orientation</label>
    <referenceTo>Orientation__c</referenceTo>
    <relationshipLabel>Tranings</relationshipLabel>
    <relationshipName>Tranings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Training_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Training_Start_Date__c</fullName>
    <label>Training Start Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DiacoOrientationStatusBatch.cls
global class DiacoOrientationStatusBatch implements  Database.Batchable<sObject> {
    
    global List<Orientation__c> start(Database.BatchableContext bc) {
        
        // DateTime now=System.now();
        //   'SELECT ID,(SELECT Name,Training_Start_Date__c  FROM Tranings__r WHERE Training_Start_Date__c>'+now+') FROM Orientation__c WHERE Current_Orientation__c = true'
        return [SELECT ID,(SELECT Name,Training_Start_Date__c  FROM Tranings__r)
                FROM Orientation__c 
                WHERE Current_Orientation__c = true Limit 50000];
        

    }
    
    global void execute(Database.BatchableContext bc, List<Orientation__c> scope){
        list<Orientation__c> listToUpdate = new list<Orientation__c>(); 
        
        for (Orientation__c orientation : scope) {
            Boolean needsToBeActive = false; 
            for(Training__c training : orientation.Tranings__r){
                if(training.Training_Start_Date__c > System.now()){ 
                    needsToBeActive = true;
                    break;
                } 
            }
            if(!needsToBeActive)listToUpdate.add(new Orientation__c(id = orientation.id, Current_Orientation__c = false)); 
        }
        System.debug('List to Update: ');
        System.debug(listToUpdate); 
        update listToUpdate;
        
    } 
    
    
    global void finish(Database.BatchableContext bc){
    } 
    
}