force-app/main/default/objects/CPL_Joins__c/CPL_Joins__c.object-meta.xml
<CustomObject>
    <label>CPL Joins</label>
    <nameField>
        <displayFormat>SC-{0}</displayFormat>
        <label>CPL Join Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPL Joins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CPL_Joins__c/fields/Active_CPL_Join__c.field-meta.xml
<CustomField>
    <fullName>Active_CPL_Join__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active CPL Join</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPL_Joins__c/fields/Billing_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Billing_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The destination CPL business opportunity.</description>
    <label>Billing Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>SPECCARD1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CPL_Joins__c/fields/Lead_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Lead_Distribution__c</fullName>
    <label>Lead Distribution</label>
    <referenceTo>Lead_Distribution__c</referenceTo>
    <relationshipLabel>CPL Joins</relationshipLabel>
    <relationshipName>CPL_Joins</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CPL_Joins__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Distribution__c/Lead_Distribution__c.object-meta.xml
<CustomObject>
    <label>Lead Distribution</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Lead Distribution ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Distribution__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lead Distributions</relationshipLabel>
    <relationshipName>Lead_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Distribution__c/fields/LastDialedNumber__c.field-meta.xml
<CustomField>
    <fullName>LastDialedNumber__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This box will be check by Bright Pattern as a call comes in or by a trigger when we see an inventory record show up with this as the dialed number on a forward to business call.</description>
    <label>Last Dialed Number</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead_Distribution__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Lead Distributions</relationshipLabel>
    <relationshipName>Lead_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forward_to_number__c.field-meta.xml
<CustomField>
    <fullName>Forward_to_number__c</fullName>
    <label>Forward To Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddAccountIDonLDTest.cls
/*
--------------------------
 * Modified By: Ganesh
 * Modified on:
 * Description: This test class covers the trigger AddAccountIDonLD & UpdateCPLJoinInfoHandler class.
				Updated the test class as per best practices. 
-----------------------------
*/
@isTest(seealldata = false)
private class AddAccountIDonLDTest {   
    @testsetup static void createtestdata(){
        Account newAcc = new Account(LastName = 'Test',Phone = '1234567897');
        insert newAcc;
        system.assertNotEquals(null, newAcc.id);
        
        Insert new Opportunity(Name = 'Test Opp',AccountId = newAcc.Id,Type = 'Trade',stageName = 'Needs Analysis',closeDate = system.Today(),Forward_to_number__c='8220708920');
        system.assertnotEquals(null,[select id from Opportunity where Type = 'Trade' limit 1]);
    }
    static testmethod void insertLead(){
        Test.startTest();
        Opportunity opp = [select id from Opportunity where Type='Trade' limit 1];
        Account acc = [select id from Account where LastName='Test' limit 1];
        
        Insert new Lead_Distribution__c(Opportunity__c = opp.id,Account__c = acc.id,LastDialedNumber__c = false);
        system.assertEquals(1,[select count() from Lead_Distribution__c]);
        
        Lead_Distribution__c testLeadDist = [select id,LastDialedNumber__c from Lead_Distribution__c limit 1];
        Insert new CPL_Joins__c(Billing_Opportunity__c = opp.Id,Lead_Distribution__c = testLeadDist.id,Active_CPL_Join__c  = true,Sort_Order__c = 0);
        system.assertEquals(1,[select count() from CPL_Joins__c]);
        
        testLeadDist.LastDialedNumber__c = true;
        update testLeadDist;
        Test.stopTest();
    }
}