force-app/main/default/objects/CallCenterCampaign__c/CallCenterCampaign__c.object-meta.xml
<CustomObject>
    <description>Call center application campaign and its details</description>
    <label>Call Center Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Center Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CallCenterCampaign__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry</label>
    <referenceTo>Industry__c</referenceTo>
    <relationshipLabel>Call Center Campaigns</relationshipLabel>
    <relationshipName>Call_Center_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CallCenterCampaign__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Call Center Campaigns</relationshipLabel>
    <relationshipName>Call_Center_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CallCenterPriority__c/CallCenterPriority__c.object-meta.xml
<CustomObject>
    <label>Call Center Priority</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Call Center Priroties Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Center Priorities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CallCenterPriority__c/fields/CallCenterCampaign__c.field-meta.xml
<CustomField>
    <fullName>CallCenterCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Call Center Campaign</label>
    <referenceTo>CallCenterCampaign__c</referenceTo>
    <relationshipLabel>Call Center Priorities</relationshipLabel>
    <relationshipName>Call_Center_Priorities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CallCenterPriority__c/fields/ConsiderSurveyResponseinUserAddress__c.field-meta.xml
<CustomField>
    <fullName>ConsiderSurveyResponseinUserAddress__c</fullName>
    <label>Consider Survey Response in UserAddress?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CallCenterPriority__c/fields/DailyCallCount__c.field-meta.xml
<CustomField>
    <fullName>DailyCallCount__c</fullName>
    <label>Daily Call Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CallCenterPriority__c/fields/OBCMMatchingInventories__c.field-meta.xml
<CustomField>
    <fullName>OBCMMatchingInventories__c</fullName>
    <label>OBCM Matching Inventories</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CallCenterPriority__c/fields/OBCMUnMatchingInventories__c.field-meta.xml
<CustomField>
    <fullName>OBCMUnMatchingInventories__c</fullName>
    <label>OBCM UnMatching Inventories</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CallCenterPriority__c/fields/Priorityforrecentresponddate__c.field-meta.xml
<CustomField>
    <fullName>Priorityforrecentresponddate__c</fullName>
    <label>Priority for recent respond date?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CallCenterPriority__c/fields/RespondDateMaximumRange__c.field-meta.xml
<CustomField>
    <fullName>RespondDateMaximumRange__c</fullName>
    <label>Respond Date Maximum Range</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CallCenterPriority__c/fields/RespondDateMinRange__c.field-meta.xml
<CustomField>
    <fullName>RespondDateMinRange__c</fullName>
    <label>Respond Date Minimum Range</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CallRecords__c/CallRecords__c.object-meta.xml
<CustomObject>
    <label>Call Record</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Records Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CallRecords__c/fields/CallCenterCampaign__c.field-meta.xml
<CustomField>
    <fullName>CallCenterCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Call Center Campaign</label>
    <referenceTo>CallCenterCampaign__c</referenceTo>
    <relationshipLabel>Call Records</relationshipLabel>
    <relationshipName>Call_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CallRecords__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Call Records</relationshipLabel>
    <relationshipName>Call_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CheckResultsJob__c/CheckResultsJob__c.object-meta.xml
<CustomObject>
    <label>Check Results Job</label>
    <nameField>
        <displayFormat>Job-{0000000}</displayFormat>
        <label>Check Results Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Results Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CheckResultsJob__c/fields/CallCenterPriority__c.field-meta.xml
<CustomField>
    <fullName>CallCenterPriority__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Call Center Priority</label>
    <referenceTo>CallCenterPriority__c</referenceTo>
    <relationshipLabel>Check Results Jobs</relationshipLabel>
    <relationshipName>Check_Results_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Door_Tag_Script__c/Door_Tag_Script__c.object-meta.xml
<CustomObject>
    <label>Door Tag Script</label>
    <nameField>
        <displayFormat>Survey-{0000000000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Door Tag Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Door_Tag_Script__c/fields/DailyCallCount__c.field-meta.xml
<CustomField>
    <fullName>DailyCallCount__c</fullName>
    <label>Daily Call Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Door_Tag_Script__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Door Tag Scripts</relationshipLabel>
    <relationshipName>Door_Tag_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>It will hold the industry value of the survey question and it would map to the Industry values custom settings.</description>
    <label>Industry</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/OB_Campaign_Member__c.field-meta.xml
<CustomField>
    <fullName>OB_Campaign_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OB Campaign Member</label>
    <referenceTo>OB_Campaign_Member__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OB_Campaign_Member__c/OB_Campaign_Member__c.object-meta.xml
<CustomObject>
    <label>OB Campaign Member</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>OB Campaign Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OB Campaign Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OB_Campaign_Member__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry</label>
    <referenceTo>Industry__c</referenceTo>
    <relationshipLabel>OB Campaign Members</relationshipLabel>
    <relationshipName>OB_Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OB_Campaign_Member__c/fields/SOQLRegion__c.field-meta.xml
<CustomField>
    <fullName>SOQLRegion__c</fullName>
    <formula>User_Address__r.Address__r.Branch__r.Region_MD__r.Id</formula>
    <label>SOQL Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OB_Campaign_Member__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>OB Campaign Members</relationshipLabel>
    <relationshipName>OB_Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <formula>PricebookEntry.Product2.Industry__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Available_ZipCodes__c.field-meta.xml
<CustomField>
    <fullName>Available_ZipCodes__c</fullName>
    <description>Zip Codes available for the branch</description>
    <label>Available ZipCodes</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry</label>
    <referenceTo>Industry__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <formula>IF( 
CONTAINS(Profile.Name,&quot;Solar&quot;),&quot;Solar&quot;, 
IF( 
CONTAINS(Profile.Name,&quot;Water&quot;),&quot;Water&quot;, 
IF( 
CONTAINS(Profile.Name,&quot;Window&quot;),&quot;Window&quot;, 
IF( 
CONTAINS(Profile.Name,&quot;Automation&quot;), &quot;Home Automation&quot;, 
IF( 
CONTAINS(Profile.Name,&quot;Pest&quot;), &quot;Pest Control&quot;,&quot;&quot;)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/fAddress_Branch__c.field-meta.xml
<CustomField>
    <fullName>fAddress_Branch__c</fullName>
    <formula>Address__r.Branch__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fAddress:Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/fzipCode__c.field-meta.xml
<CustomField>
    <fullName>fzipCode__c</fullName>
    <formula>Address__r.Zip_Code__c</formula>
    <label>fzipCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Respond_Date_Created_by__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date_Created_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It will holds the value of user who updated the respond date</description>
    <label>Respond Date Created by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/SOQLRegion__c.field-meta.xml
<CustomField>
    <fullName>SOQLRegion__c</fullName>
    <formula>Address__r.Branch__r.Region_MD__r.Id</formula>
    <label>SOQL Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/nuHome_Call_Center_Batch_AC.cls
/****************************************************************************
* Created By   : MSTSolutions
* Created Date : 25 December 2016
* Description  : Batch class to check result for the priorities and create call records for the priorities.
* **************************************************************************/
Global class nuHome_Call_Center_Batch_AC Implements Database.Batchable<sObject>{

    Public String priorityInsId;
    Public String batchId;
    Public List<CallCenterPriority__c> prioritiesList;
    Public String futureJobId;
    Public String jobType;
    Public String campaignCenterId;
    Public String campaignIndustry;

    Public nuHome_Call_Center_Batch_AC(String priorityId,String batchTrackerId,String batchJobType){
        prioritiesList  =   New List<CallCenterPriority__c>();
        priorityInsId   =   priorityId;
        futureJobId     =   batchTrackerId;
        jobType         =   batchJobType;
        prioritiesList  =   [SELECT Id,CallCenterCampaign__r.Industry__c,CallCenterCampaign__r.Industry__r.Name,CallCenterCampaign__r.Region__c,CallCenterCampaign__c,
                             ConsiderSurveyResponseinUserAddress__c,DailyCallCount__c,OBCMMatchingInventories__c,OBCMUnMatchingInventories__c,
                             Priorityforrecentresponddate__c,RespondDateMaximumRange__c,RespondDateMinRange__c FROM CallCenterPriority__c
                             WHERE Id = :priorityInsId];
        if(prioritiesList.size() > 0){
            campaignCenterId    =   prioritiesList[0].CallCenterCampaign__c;
            campaignIndustry    =   prioritiesList[0].CallCenterCampaign__r.Industry__c;
        }
        system.debug('priorityInsId value '+priorityInsId+' prioritiesList '+prioritiesList);
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        String doorTagScript   =   Schema.SObjectType.Inventory__c.getRecordTypeInfosByName().get('nuHome Door Tag Script').getRecordTypeId();
        String queryIndustry    =   '';
        String queryRegion      =   '';
        Set<Id> OBCMSet             =   New Set<Id>();
        Set<Id> userAddressSet      =   New Set<Id>();
        Set<Id> userAddressmat      =   New Set<Id>();
        Set<Id> userAddressUnmat    =   New Set<Id>();
        Set<Id> userAddressCall     =   New Set<Id>();
        Set<Id> userAddressRespond  =   New Set<Id>();

        if(prioritiesList.size() > 0){
            queryIndustry   =   prioritiesList[0].CallCenterCampaign__r.Industry__c;
            queryRegion     =   prioritiesList[0].CallCenterCampaign__r.Region__c;

            if(queryRegion.length() > 14)
                queryRegion     =   queryRegion.substring(0, 15);
            if(queryIndustry.length() > 14)
                queryIndustry   =   queryIndustry.substring(0, 15);

            system.debug('For region '+queryRegion+' and for industry '+queryIndustry);

            if((queryIndustry != '') && (queryRegion != '')){

                string query = 'SELECT Id,Name,User_Address__c,User_Address__r.fAddress_Branch__c,Industry__r.Name,User_Address__r.fzipCode__c FROM OB_Campaign_Member__c WHERE Industry__c = :queryIndustry AND SOQLRegion__c = :queryRegion';
                return Database.getQueryLocator(query);
            }
        }

        return Null;

    }

    global void execute(Database.BatchableContext BC, List<OB_Campaign_Member__c> scope) {
        String doorTagScript    =   Schema.SObjectType.Inventory__c.getRecordTypeInfosByName().get('nuHome Door Tag Script').getRecordTypeId();
        Id oppRecordTypeId      =   Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('nuHome OB Campaign').getRecordTypeId();
        String queryIndustry    =   '';
        String queryRegion      =   '';
        Set<Id> OBCMSet             =   New Set<Id>();
        Set<Id> userAddressSet      =   New Set<Id>();
        Set<Id> userAddressmat      =   New Set<Id>();
        Set<Id> userAddressUnmat    =   New Set<Id>();
        Set<Id> userAddressCall     =   New Set<Id>();
        Set<Id> userAddressRespond  =   New Set<Id>();

        Integer OBCMCount       =   0;
        Integer MatchingCount   =   0;
        Integer UnMatchingCount =   0;
        Integer CallCount       =   0;
        Integer RespondDate     =   0;
        Map<String,Id> selectedProductMap   =   New Map<String,Id>();
        Map<String,String> selectedZipCodeMap   =   New Map<String,String>();
        Set<ID> opportunityIDSet = New Set<ID>();

        for(OB_Campaign_Member__c OBC:scope){
            String productName  =   OBC.User_Address__r.fAddress_Branch__c+'-'+OBC.Industry__r.Name;
            if(!selectedProductMap.containsKey(productName)){
                selectedProductMap.put(productName,OBC.User_Address__c);
                selectedZipCodeMap.put(productName,OBC.User_Address__r.fzipCode__c);
                }
        }

        For(OpportunityLineItem oppLine:[SELECT product2.Name,opportunityId,product2.available_zipcodes__c FROM opportunityLineItem
                                         WHERE product2.Name IN:selectedProductMap.keySet() AND Opportunity.RecordTypeId = :oppRecordTypeId
                                         AND Opportunity.StageName = 'Closed Won']){
            system.debug(oppLine.product2.Name+'/'+oppLine.product2.available_zipcodes__c);
            Set<String> zipCodesSet = new Set<String>();

            if(oppLine.product2.available_zipcodes__c != Null && oppLine.product2.available_zipcodes__c != ''){
                for(String currZip : oppLine.product2.available_zipcodes__c.split(';')){
                    zipCodesSet.add(currZip);
                }
            }
            if(zipCodesSet.contains(selectedZipCodeMap.get(oppLine.product2.Name))){
                userAddressSet.add(selectedProductMap.get(oppLine.product2.Name));
            }
        }

        OBCMCount   =   userAddressSet.size();

        system.debug('**user address filter** '+userAddressSet.size());
        system.debug('**OBCMSet filter** '+OBCMSet.size());
        //AND Last_Disposition_Date_Time__c = Today
        if(prioritiesList[0].DailyCallCount__c != Null && userAddressSet.size() > 0){

            for(Door_Tag_Script__c DTS:[SELECT Id,User_Address__c,DailyCallCount__c FROM Door_Tag_Script__c WHERE User_Address__c IN :userAddressSet AND DailyCallCount__c <= :prioritiesList[0].DailyCallCount__c AND Last_Disposition_Date_Time__c = Today]){
                userAddressCall.add(DTS.User_Address__c);
            }
        }

        CallCount   =   userAddressCall.size();

        if(prioritiesList[0].OBCMMatchingInventories__c != Null){
            Date matchingDate = system.today().addDays(Integer.valueof('-'+prioritiesList[0].OBCMMatchingInventories__c));
            system.debug('matchingDate value '+matchingDate);
            for(Inventory__c inv:[SELECT Id,User_Address__c FROM Inventory__c WHERE UnMatching_Invetnory__c = False AND Survey_Response__c = 'Verified Lead' AND CreatedDate >= :matchingDate AND recordTypeId = :doorTagScript AND User_Address__c IN: userAddressCall]){
                userAddressmat.add(inv.User_Address__c);
            }
        }

        MatchingCount   =   userAddressmat.size();

        if(prioritiesList[0].OBCMUnMatchingInventories__c != Null){
            Date matchingDate2 = system.today().addDays(Integer.valueof('-'+prioritiesList[0].OBCMUnMatchingInventories__c));
            for(Inventory__c inv:[SELECT Id,User_Address__c FROM Inventory__c WHERE UnMatching_Invetnory__c = True AND Survey_Response__c = 'Verified Lead' AND CreatedDate >= :matchingDate2 AND recordTypeId = :doorTagScript AND User_Address__c IN: userAddressCall]){
                userAddressUnmat.add(inv.User_Address__c);
            }
        }

        UnMatchingCount =   userAddressUnmat.size();

        Set<Id> tempList = New Set<Id>();
        for(Id Ids:userAddressCall){
            if(!userAddressmat.contains(Ids))
                tempList.add(Ids);
        }
        if(tempList.size() > 0){
            userAddressCall.clear();
            userAddressCall.addAll(tempList);
            tempList.clear();
        }


        userAddressCall.addAll(userAddressUnmat);

        if(prioritiesList[0].RespondDateMinRange__c != Null && prioritiesList[0].RespondDateMaximumRange__c != Null && userAddressCall.size() > 0 && jobType != 'Rollover'){

            Date max = Date.today().addDays(-Integer.valueOf(prioritiesList[0].RespondDateMaximumRange__c));
            Date min = Date.today().addDays(-Integer.valueOf(prioritiesList[0].RespondDateMinRange__c));
            system.debug(max+'/'+min);
            for(Door_Tag_Script__c DTS:[SELECT Id,User_Address__c,DailyCallCount__c,User_Address__r.Respond_Date__c FROM Door_Tag_Script__c
                                        WHERE User_Address__c IN :userAddressCall AND User_Address__r.Respond_Date__c >= :max
                                        AND User_Address__r.Respond_Date__c <= :min]){
                                            userAddressRespond.add(DTS.User_Address__c);
                                        }
        }
        
        if(prioritiesList[0].RespondDateMinRange__c != Null && userAddressCall.size() > 0 && jobType == 'Rollover'){
            Date min = Date.today().addDays(-Integer.valueOf(prioritiesList[0].RespondDateMinRange__c));
            for(Door_Tag_Script__c DTS:[SELECT Id,User_Address__c,DailyCallCount__c,User_Address__r.Respond_Date__c FROM Door_Tag_Script__c
                                        WHERE User_Address__c IN :userAddressCall AND User_Address__r.Respond_Date__c = :min]){
                                            userAddressRespond.add(DTS.User_Address__c);
                                        }
        }

        RespondDate =   userAddressRespond.size();

        system.debug('**Respond date filter** '+userAddressRespond.size());
        system.debug('**Call count filter** '+userAddressCall.size());

        List<CallRecords__c> callLogList   =   New List<CallRecords__c>();
        Integer resultCount = 0;
        if(userAddressRespond.size() > 0)
            resultCount =   userAddressRespond.size();
        else if(userAddressCall.size() > 0)
            resultCount =   userAddressCall.size();
        else
            resultCount =   userAddressSet.size();

        
        set<Id> DNCusers = New set<Id>();
        
        if(jobType != 'Query'){
            for(CallRecords__c callRecords:[SELECT Id,User_Address__c FROM CallRecords__c WHERE (User_Address__c IN:userAddressRespond
                                           OR User_Address__c IN:userAddressCall OR User_Address__c IN:userAddressSet) AND (CallDisposition__c = 'DNC')]){
                DNCusers.add(callRecords.User_Address__c);
            }

            for(CallRecords__c callRecords:[SELECT Id,User_Address__c FROM CallRecords__c WHERE (CallCenterCampaign__r.Industry__c =:campaignIndustry) AND (User_Address__c IN:userAddressRespond
                                           OR User_Address__c IN:userAddressCall OR User_Address__c IN:userAddressSet) AND (CallDisposition__c  =  'Appointment set' OR CallDisposition__c = 'Not interested' OR CallDisposition__c = 'Wrong number' OR CallDisposition__c = 'Has provider' OR CallDisposition__c = 'Call back')]){
                DNCusers.add(callRecords.User_Address__c);
            }
        }
        
        if(jobType == 'Query'){

            CheckResultsJob__c futureJobIns =   [SELECT Id,Job_Result__c,OBCMUserAddress__c,MatchingInventory__c,UnmatchingInventory__c,
                                                 CallCountFiltered__c,RespondDateFiltered__c FROM CheckResultsJob__c WHERE Id = :futureJobId];

            CheckResultsJob__c futureJob    =   New CheckResultsJob__c();
            futureJob.Id                    =   futureJobId;

            if(futureJobIns.Job_Result__c != Null)
                futureJob.Job_Result__c         =   futureJobIns.Job_Result__c + resultCount;
            else
                futureJob.Job_Result__c         =   resultCount;

            if(futureJobIns.OBCMUserAddress__c != Null)
                futureJob.OBCMUserAddress__c         =   futureJobIns.OBCMUserAddress__c + OBCMCount;
            else
                futureJob.OBCMUserAddress__c    =   OBCMCount;

            if(futureJobIns.MatchingInventory__c != Null)
                futureJob.MatchingInventory__c         =   futureJobIns.MatchingInventory__c + MatchingCount;
            else
                futureJob.MatchingInventory__c  =   MatchingCount;

            if(futureJobIns.UnmatchingInventory__c != Null)
                futureJob.UnmatchingInventory__c         =   futureJobIns.UnmatchingInventory__c + UnMatchingCount;
            else
                futureJob.UnmatchingInventory__c=   UnMatchingCount;

            if(futureJobIns.CallCountFiltered__c != Null)
                futureJob.CallCountFiltered__c         =   futureJobIns.CallCountFiltered__c + CallCount;
            else
                futureJob.CallCountFiltered__c  =   CallCount;

            if(futureJobIns.RespondDateFiltered__c != Null)
                futureJob.RespondDateFiltered__c         =   futureJobIns.RespondDateFiltered__c + RespondDate;
            else
                futureJob.RespondDateFiltered__c=   RespondDate;
            Update futureJOb;

            system.debug('futureJOb updated '+futureJOb);
        }else if(jobType == 'Create'){

            if(userAddressRespond.size() > 0){
                for(Id userAddIns:userAddressRespond){
                    if(!DNCusers.contains(userAddIns)){
                        CallRecords__c callLog          =   New CallRecords__c();
                        callLog.User_Address__c         =   userAddIns;
                        callLog.CallCenterCampaign__c   =   campaignCenterId;
                        callLogList.add(callLog);
                    }
                }
            }else if(userAddressCall.size() > 0){
                for(Id userAddIns:userAddressCall){
                    if(!DNCusers.contains(userAddIns)){
                        CallRecords__c callLog          =   New CallRecords__c();
                        callLog.User_Address__c         =   userAddIns;
                        callLog.CallCenterCampaign__c   =   campaignCenterId;
                        callLogList.add(callLog);
                    }
                }
            }else{
                for(Id userAddIns:userAddressSet){
                    if(!DNCusers.contains(userAddIns)){
                        CallRecords__c callLog          =   New CallRecords__c();
                        callLog.User_Address__c         =   userAddIns;
                        callLog.CallCenterCampaign__c   =   campaignCenterId;
                        callLogList.add(callLog);
                    }
                }
            }

        }else if(jobType == 'Rollover'){
            
            if(prioritiesList[0].RespondDateMaximumRange__c != null){
                List<CallRecords__c> DeleteCallRecords = New List<CallRecords__c>();
                Date max = Date.today().addDays(-(Integer.valueOf(prioritiesList[0].RespondDateMaximumRange__c)+1)); 
                for(CallRecords__c callRecordsDelete:[SELECT Id FROM CallRecords__c WHERE User_Address__r.Respond_Date__c =: max AND CallCenterCampaign__c =: campaignCenterId AND IsProcessed__c = False AND CallDisposition__c != 'Call back']){
                    DeleteCallRecords.add(callRecordsDelete);
                }
                if(DeleteCallRecords.size() > 0)
                    Delete DeleteCallRecords;
            }
            
            for(Id userAddIns:userAddressRespond){
                if(!DNCusers.contains(userAddIns)){
                    CallRecords__c callLog          =   New CallRecords__c();
                    callLog.User_Address__c         =   userAddIns;
                    callLog.CallCenterCampaign__c   =   campaignCenterId;
                    callLogList.add(callLog);
                }
            }
        }

        if(callLogList.size() > 0){
            Insert callLogList;
            CheckResultsJob__c futureJobIns =   [SELECT Id,Job_Result__c FROM CheckResultsJob__c WHERE Id = :futureJobId];

            CheckResultsJob__c futureJob    =   New CheckResultsJob__c();
            futureJob.Id                    =   futureJobId;
            if(futureJobIns.Job_Result__c != Null)
                futureJob.Job_Result__c         =   futureJobIns.Job_Result__c + callLogList.size();
            else
                futureJob.Job_Result__c         =   callLogList.size();
            Update futureJOb;
        }


    }

    global void finish(Database.BatchableContext BC) {
        // Check batch status - IF COMPLETED then
        AsyncApexJob a = [Select Id, Status, NumberOfErrors, JobItemsProcessed,
                          TotalJobItems, CreatedBy.Email, ExtendedStatus
                          from AsyncApexJob where Id = :bc.getJobId()];

        CheckResultsJob__c futureJob    =   New CheckResultsJob__c();
        futureJob.Id                    =   futureJobId;
        futureJob.status__c             =   a.Status;
        Update futureJOb;
        
        if(a.Status == 'Completed')
            DELETE [SELECT Id FROM CallRecords__c WHERE CallCenterCampaign__c = :campaignCenterId AND IsProcessed__c = False AND CallBackUser__c = Null];

    }

}