force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Battery_Location_Garage__c.field-meta.xml
<CustomField>
    <fullName>Battery_Location_Garage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Garage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Battery_Location_Inside__c.field-meta.xml
<CustomField>
    <fullName>Battery_Location_Inside__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inside</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Battery_Location_Outside__c.field-meta.xml
<CustomField>
    <fullName>Battery_Location_Outside__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Outside</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Battery_Use_Backup_Power__c.field-meta.xml
<CustomField>
    <fullName>Battery_Use_Backup_Power__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Backup Power</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Battery_Use_Energy_Demand_Reduction__c.field-meta.xml
<CustomField>
    <fullName>Battery_Use_Energy_Demand_Reduction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Energy / Demand Reduction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Battery_Use_Solar_Self_consumption__c.field-meta.xml
<CustomField>
    <fullName>Battery_Use_Solar_Self_consumption__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solar Self-consumption</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Card_Expiration_Year__c.field-meta.xml
<CustomField>
    <fullName>Card_Expiration_Year__c</fullName>
    <label>Card Expiration Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Explain_SRP__c.field-meta.xml
<CustomField>
    <fullName>Explain_SRP__c</fullName>
    <label>Explain SRP</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Sales_Representative__c</fullName>
    <formula>Sales_Rep__r.FirstName + &quot; &quot; + Sales_Rep__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Representative Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Send_Utility_Solar__c.field-meta.xml
<CustomField>
    <fullName>Send_Utility_Solar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Utility - Solar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/way_restricted_or_impeded__c.field-meta.xml
<CustomField>
    <fullName>way_restricted_or_impeded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>way restricted or impeded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Line Items (HS)</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items (Product)</relationshipLabel>
    <relationshipName>Line_Items_Product</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/AccountNumberChecking__c.field-meta.xml
<CustomField>
    <fullName>AccountNumberChecking__c</fullName>
    <label>Account Number Checking</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/BankAccountType__c.field-meta.xml
<CustomField>
    <fullName>BankAccountType__c</fullName>
    <label>Bank Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BankAccountTypePick</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/CardExpirationMonth__c.field-meta.xml
<CustomField>
    <fullName>CardExpirationMonth__c</fullName>
    <label>Card Expiration Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/CardNumber__c.field-meta.xml
<CustomField>
    <fullName>CardNumber__c</fullName>
    <label>Card Number</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/CardType__c.field-meta.xml
<CustomField>
    <fullName>CardType__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CardTypePick</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/CSV__c.field-meta.xml
<CustomField>
    <fullName>CSV__c</fullName>
    <label>CSV</label>
    <length>4</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/FinanceCompany__c.field-meta.xml
<CustomField>
    <fullName>FinanceCompany__c</fullName>
    <label>Finance Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/FinancedAmount__c.field-meta.xml
<CustomField>
    <fullName>FinancedAmount__c</fullName>
    <label>Financed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/HomeService__c.field-meta.xml
<CustomField>
    <fullName>HomeService__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/NameOnCard__c.field-meta.xml
<CustomField>
    <fullName>NameOnCard__c</fullName>
    <label>Name On Card</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/Payment_Destination__c.field-meta.xml
<CustomField>
    <fullName>Payment_Destination__c</fullName>
    <label>Payment Destination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Once</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Biweekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bimonthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semiannual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Biennial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentMethodType__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodType__c</fullName>
    <label>Payment Method Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentMethodTypePick</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/RoutingNumber__c.field-meta.xml
<CustomField>
    <fullName>RoutingNumber__c</fullName>
    <label>Routing Number</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product HS</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products HS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Manufacture__c.field-meta.xml
<CustomField>
    <fullName>Manufacture__c</fullName>
    <label>Manufacture</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alarm.com</fullName>
            </value>
            <value>
                <fullName>Ameriflow</fullName>
            </value>
            <value>
                <fullName>CFA Cabinetry</fullName>
            </value>
            <value>
                <fullName>DSC</fullName>
            </value>
            <value>
                <fullName>Energy Shield</fullName>
            </value>
            <value>
                <fullName>Flowwall</fullName>
            </value>
            <value>
                <fullName>Hague</fullName>
            </value>
            <value>
                <fullName>Kwikset</fullName>
            </value>
            <value>
                <fullName>Mohawk</fullName>
            </value>
            <value>
                <fullName>MSI</fullName>
            </value>
            <value>
                <fullName>Premier Custom Coating</fullName>
            </value>
            <value>
                <fullName>Qolsys</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Sonos</fullName>
            </value>
            <value>
                <fullName>Stone Quarry</fullName>
            </value>
            <value>
                <fullName>Simon</fullName>
            </value>
            <value>
                <fullName>Ring</fullName>
            </value>
            <value>
                <fullName>Z-Wave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DiacoContractAPS.cls
/**
* Diaco
* @author 			Esnayder Morales href=<emorales@diaco.us>
* Project:			Contracts
* Description:		Manage information to contract ASP, SRP and ED3
*
* Changes (Version)
* -------------------------------------
*			No.		Date			Author					    Description
*			-----	----------		--------------------	    ---------------
* @version	1.0		15/06/2020		Esnayder Morales (EM)		Initial version.
**/
public class DiacoContractAPS {

    //Atribute
    private final Home_Services__c hs;
    public decimal totalModule {get; set;}
    public decimal totalInverter {get; set;}
    private final List<PaymentMethod__c> pm;
    public boolean cash {get; set;}
    public boolean finance {get; set;}
    public boolean lease {get; set;}
    public boolean other {get; set;}


    /**
     * This constructor the class
     * 
     * 
     * @param ApexPages.StandardController stdController
     * @return nothing
     **/
    public DiacoContractAPS(ApexPages.StandardController stdController){
       this.hs = (Home_Services__c)stdController.getRecord();
       this.pm = getPaymentMethods();
       setMethod();
    }

    /**
     * This method is responsible to get cash method value if exist
     * 
     * This method is used in:
     * ContractSolarAPS.page, NergiSolutions_LLC_SRP.page
     * 
     * @param nothing
     * @return Boolean
     **/
    public boolean getCash(){
        return cash;
    }

    /**
     * This method is responsible to get finance method value if exist
     * 
     * This method is used in:
     * ContractSolarAPS.page, NergiSolutions_LLC_SRP.page
     * 
     * @param nothing
     * @return Boolean
     **/
    public boolean getFinance(){
        return finance;
    }

    /**
     * This method is responsible to get lease method value if exist
     * 
     * This method is used in:
     * ContractSolarAPS.page, NergiSolutions_LLC_SRP.page
     * 
     * @param nothing
     * @return Boolean
     **/
    public boolean getLease(){
        return lease;
    }

    /**
     * This method is responsible to get other method value if exist
     * 
     * This method is used in:
     * ContractSolarAPS.page, NergiSolutions_LLC_SRP.page
     * 
     * @param nothing
     * @return Boolean
     **/
    public boolean getOther(){
        return other;
    }

    /**
     * This method is responsible to set the true or false value to payment method
     * 
     * This method is used in:
     * DiacoContractAPS method
     * 
     * @param nothing
     * @return nothing
     **/
    public void setMethod(){
        String look = '';
        for(PaymentMethod__c item : pm){
            if(!look.contains(item.PaymentMethodType__c)){
                look += item.PaymentMethodType__c;
                finance = look.contains('Finance');
                cash = look.contains('Cash');
                lease = look.contains('Lease');
                other = look.contains('ACH') || look.contains('Credit Card') || look.contains('Checking');
            }
        }
    }

    /**
     * This method is responsible to get the fields that doesn´t return standarcontroller
     * 
     * This method is used in:
     * ContractSolarAPS.page, NergiSolutions_LLC_SRP.page
     * 
     * @param nothing
     * @return Home_Services__c
     **/
    public Home_Services__c getHs(){
        return [select way_restricted_or_impeded__c, Explain_SRP__c,
        Sales_Representative__c,Send_Utility_Solar__c, Battery_Use_Backup_Power__c,
        Battery_Use_Energy_Demand_Reduction__c, Battery_Use_Solar_Self_consumption__c,
        Battery_Location_Garage__c, Battery_Location_Inside__c, Battery_Location_Outside__c
        from Home_Services__c where Id=:this.hs.Id];
    }

    /**
     * This method is responsible to get payments method
     * 
     * This method is used in:
     * ContractSolarAPS.page, NergiSolutions_LLC_SRP.page
     * 
     * @param nothing
     * @return List<PaymentMethod__c>
     **/
    public List<PaymentMethod__c> getPaymentMethods(){
        List<PaymentMethod__c> PaymentMethods = new List<PaymentMethod__c>();
        System.debug(hs.Id);
        if(hs.Id!=null){
            PaymentMethods = [select Id, Name, AccountNumberChecking__c, Amount__c, Bank_Account_Name__c,
            BankAccountNumber__c, BankName__c, BankAccountType__c, CardExpirationMonth__c,  
            Card_Expiration_Year__c, CardNumber__c, CardType__c, CSV__c, 
            FinanceCompany__c, FinancedAmount__c, NameOnCard__c, Payment_Destination__c, 
            Payment_Frequency__c, PaymentMethodType__c, RoutingNumber__c from PaymentMethod__c where HomeService__c =:this.hs.Id];
            System.debug(PaymentMethods);
        }
        return PaymentMethods;
    }

    /**
     * This method is responsible to get products
     * 
     * This method is used in:
     * ContractSolarAPS.page, NergiSolutions_LLC_SRP.page
     * 
     * @param nothing
     * @return List<Line_Item__c>
     **/
    public List<Line_Item__c> getProducts(){
        List<Line_Item__c> listItems = new List<Line_Item__c>();
        if(hs.Id!=null){
            listItems = [select Product__r.Name, Product__r.Manufacture__c
            from Line_Item__c where Home_Service__c =:this.hs.Id];
        }
        return listItems;
    }

    /**
     * This method is responsible to get inverte products 
     * 
     * This method is used in:
     * ContractSolarAPS.page, NergiSolutions_LLC_SRP.page
     * 
     * @param nothing
     * @return List<Line_Item__c>
     **/
    public List<Line_Item__c> getProductsInverter(){
        List<Line_Item__c> listItems = new List<Line_Item__c>();
        if(hs.Id!=null){
            listItems = [select Product__r.Name, Product__r.Manufacture__c,
            Product__r.Product_Type__c, Product__r.Part_Number__c, Quantity__c,
            Product__r.Nameplate_rating_kW_AC__c, Product__r.Max_power_rating_watts__c
            from Line_Item__c where Home_Service__c =:this.hs.Id and Product__r.Remodel_Category__c='Inverter'];
        }
        return listItems;
    }

    /**
     * This method is responsible to get modules products
     * 
     * This method is used in:
     * ContractSolarAPS.page, NergiSolutions_LLC_SRP.page
     * 
     * @param nothing
     * @return List<Line_Item__c>
     **/
    public List<Line_Item__c> getProductsModules(){
        List<Line_Item__c> listItems = new List<Line_Item__c>();
        if(hs.Id!=null){
            listItems = [select Product__r.Name, Product__r.Manufacture__c,
            Product__r.Product_Type__c, Product__r.Part_Number__c, Quantity__c,
            Product__r.Nameplate_rating_kW_AC__c, Product__r.Tilt__c, 
            Product__r.Azimuth__c, Product__r.Max_power_rating_watts__c
            from Line_Item__c where Home_Service__c =:this.hs.Id and Product__r.Remodel_Category__c='Module'];
        }
        return listItems;
    }

    /**
     * This method is responsible to get demands products
     * 
     * This method is used in:
     * ContractSolarAPS.page, NergiSolutions_LLC_SRP.page
     * 
     * @param nothing
     * @return List<Line_Item__c>
     **/
    public List<Line_Item__c> getProductsDemands(){
        List<Line_Item__c> listItems = new List<Line_Item__c>();
        if(hs.Id!=null){
            listItems = [select Product__r.Name, Product__r.Manufacture__c,
            Product__r.Product_Type__c, Product__r.Part_Number__c, Quantity__c,
            Product__r.Nameplate_rating_kW_AC__c, Product__r.Tilt__c, 
            Product__r.Azimuth__c, Product__r.Max_power_rating_watts__c
            from Line_Item__c where Home_Service__c =:this.hs.Id and Product__r.Remodel_Category__c='Demand Management System'];
        }
        return listItems;
    }

    /**
     * This method is responsible to get battery storage
     * 
     * This method is used in:
     * ContractSolarAPS.page, NergiSolutions_LLC_SRP.page
     * 
     * @param nothing
     * @return List<Line_Item__c>
     **/
    public List<Line_Item__c> getProductsBatteryStorage(){
        List<Line_Item__c> listItems = new List<Line_Item__c>();
        if(hs.Id!=null){
            listItems = [select Product__r.Name, Product__r.Manufacture__c,
            Product__r.Product_Type__c, Product__r.Part_Number__c, Quantity__c,
            Product__r.Nameplate_rating_kW_AC__c, Product__r.Tilt__c, 
            Product__r.Power_kW_DC__c, Product__r.Energy_kWh_DC__c
            from Line_Item__c where Home_Service__c =:this.hs.Id and Product__r.Remodel_Category__c='Battery Storage'];
        }
        return listItems;
    }

    public List<Line_Item__c> getProductsBatteryInverter(){
        List<Line_Item__c> listItems = new List<Line_Item__c>();
        if(hs.Id!=null){
            listItems = [select Product__r.Name, Product__r.Manufacture__c,
            Product__r.Product_Type__c, Product__r.Part_Number__c, Quantity__c,
            Product__r.Nameplate_rating_kW_AC__c, Product__r.Tilt__c, 
            Product__r.Power_kW_DC__c
            from Line_Item__c where Home_Service__c =:this.hs.Id and Product__r.Remodel_Category__c='Battery Inverter'];
        }
        return listItems;
    }


    /**
     * This method is responsible to get total product inverter
     * 
     * This method is used in:
     * ContractSolarAPS.page, NergiSolutions_LLC_SRP.page
     * 
     * @param nothing
     * @return decimal
     **/
    public decimal getTotalProductInverter(){
        List<Line_Item__c> listItems = getProductsInverter();
        decimal response = 0.0;
        if(listItems.size()>0){
            for(Line_Item__c li : listItems){
                if( li.Product__r.Nameplate_rating_kW_AC__c != null &&
                li.Quantity__c != null){
                    System.debug('NamePlate');
                    System.debug(li.Product__r.Nameplate_rating_kW_AC__c);
                    System.debug(li.Quantity__c);
                    response += li.Product__r.Nameplate_rating_kW_AC__c * li.Quantity__c;
                }
                
            }
        }
        System.debug(response);
        totalInverter = response;
        return response;
    }

    /**
     * This method is responsible to get total product modules
     * 
     * This method is used in:
     * ContractSolarAPS.page, NergiSolutions_LLC_SRP.page
     * 
     * @param nothing
     * @return decimal
     **/
    public decimal getTotalProductModules(){
        List<Line_Item__c> listItems = getProductsModules();
        decimal response = 0.0;
        if(listItems.size()>0){
            for(Line_Item__c li : listItems){
                if( li.Product__r.Max_power_rating_watts__c != null &&
                li.Quantity__c != null){
                    response += li.Product__r.Max_power_rating_watts__c * li.Quantity__c;
                }
            }
        }
        System.debug(response);
        totalModule = response;
        return response;
    }

}