force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Communication_By__c.field-meta.xml
<CustomField>
    <fullName>Communication_By__c</fullName>
    <label>Communication By</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POTS</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>VoIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Hardness_gpg__c.field-meta.xml
<CustomField>
    <fullName>Hardness_gpg__c</fullName>
    <label>Hardness gpg</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Hyd_Supl_ppm__c.field-meta.xml
<CustomField>
    <fullName>Hyd_Supl_ppm__c</fullName>
    <label>Hyd.Supl. ppm</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Iron_Algae__c.field-meta.xml
<CustomField>
    <fullName>Iron_Algae__c</fullName>
    <label>Iron Algae</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Iron_ppm__c.field-meta.xml
<CustomField>
    <fullName>Iron_ppm__c</fullName>
    <label>Iron ppm</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Monthly_Security_Services__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Security_Services__c</fullName>
    <label>Monthly Security Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Alarm Signal Verification</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/No_Reg__c.field-meta.xml
<CustomField>
    <fullName>No_Reg__c</fullName>
    <label>No Reg.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Other__c.field-meta.xml
<CustomField>
    <fullName>Other__c</fullName>
    <label>Other</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Ph__c.field-meta.xml
<CustomField>
    <fullName>Ph__c</fullName>
    <label>pH</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/diacoContractHAServicePackageController.cls
public class diacoContractHAServicePackageController {
    
    @AuraEnabled
    public static Home_Services__c getDataHomeService(String RecordId){
        Home_Services__c home =  [select Id, Account__c,Communication_By__c,Monthly_Security_Services__c, Hardness_gpg__c, Ph__c, Iron_Algae__c, Iron_ppm__c, Hyd_Supl_ppm__c, No_Reg__c, Other__c, Special_Instructions__c 
                                  from Home_Services__c where id = :RecordId];
        return home;
    }
    
        @AuraEnabled
    public static Home_Services__c saveHomeService(Home_Services__c Home_Services){
        upsert Home_Services;
        return Home_Services;
    }
}