force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Dealer_Number__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Number__c</fullName>
    <defaultValue>0.00000</defaultValue>
    <label>Dealer Number</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Industry_Formula__c.field-meta.xml
<CustomField>
    <fullName>Industry_Formula__c</fullName>
    <formula>IF(
CONTAINS( RecordType.Name , &quot;Home Automation&quot; ), &quot;Home Automation&quot;, 
IF(
CONTAINS(RecordType.Name, &quot;Solar&quot; ), &quot;Solar&quot;,
IF(
CONTAINS(RecordType.Name, &quot;Water&quot; ), &quot;Water Treatment&quot;,
IF(
CONTAINS(RecordType.Name, &quot;Remodel&quot; ), &quot;Remodel&quot;,
IF(
CONTAINS(RecordType.Name, &quot;Pest Control&quot; ), &quot;Pest Control&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Carpet &amp; Tile Cleaning&quot; ), &quot;Carpet &amp; Tile Cleaning&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Flooring&quot; ), &quot;Flooring&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Garage Doors&quot; ), &quot;Garage Doors&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Garage Floor Coating&quot; ), &quot;Garage Floor Coating&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Handy Man&quot; ), &quot;Handy Man&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Internet-Cable-Satellite&quot; ), &quot;Internet-Cable-Satelite&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Kitchen &amp; Bath&quot; ), &quot;Kitchen &amp; Bath&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Lock Smith&quot; ), &quot;Lock Smith&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Maid Service&quot; ), &quot;Maid Service&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Painting&quot; ), &quot;Painting&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Pool Maintenance&quot; ), &quot;Pool Maintenance&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;HVAC&quot; ), &quot;HVAC&quot;, 
&quot;&quot;)))))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry:</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Retail_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Retail_Multiplier__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Retail Multiplier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Home Services</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Costing_Settings__c/Job_Costing_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Job Costing Settings</label>
</CustomObject>

force-app/main/default/objects/Job_Costing_Settings__c/fields/Dealer_Number__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Number__c</fullName>
    <defaultValue>0.03</defaultValue>
    <label>Dealer Number</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Costing_Settings__c/fields/Retail_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Retail_Multiplier__c</fullName>
    <defaultValue>2.0</defaultValue>
    <label>Retail Multiplier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Line Items (HS)</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Latch_Suggested_Retail_w_Install__c.field-meta.xml
<CustomField>
    <fullName>Latch_Suggested_Retail_w_Install__c</fullName>
    <formula>Unit_Price__c *  Quantity__c  * Home_Service__r.Retail_Multiplier__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Latch Suggested Retail w/Install</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Latch_Suggested_Retail_w_Install_Fee__c.field-meta.xml
<CustomField>
    <fullName>Latch_Suggested_Retail_w_Install_Fee__c</fullName>
    <formula>Latch_Suggested_Retail_w_Install__c * ( 1 + Home_Service__r.Dealer_Number__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Latch Suggested Retail w/Install &amp; Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Latch_UOM__c.field-meta.xml
<CustomField>
    <fullName>Latch_UOM__c</fullName>
    <formula>Product__r.UOM__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Latch UOM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items (Product)</relationshipLabel>
    <relationshipName>Line_Items_Product</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <formula>Quantity__c *  Product__r.Sales_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Total_Sales_Price_p__c.field-meta.xml
<CustomField>
    <fullName>Total_Sales_Price_p__c</fullName>
    <label>Total Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product HS</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products HS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Remodel_Category__c.field-meta.xml
<CustomField>
    <fullName>Remodel_Category__c</fullName>
    <label>Remodel Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DESIGN,PLANS, &amp; PERMITS</fullName>
            </value>
            <value>
                <fullName>TEAR-OUT</fullName>
            </value>
            <value>
                <fullName>EXCAVATION</fullName>
            </value>
            <value>
                <fullName>CONCRETE</fullName>
            </value>
            <value>
                <fullName>MASONRY</fullName>
            </value>
            <value>
                <fullName>FLOOR FRAMING</fullName>
            </value>
            <value>
                <fullName>WALL FRAMING</fullName>
            </value>
            <value>
                <fullName>ROOF FRAMING</fullName>
            </value>
            <value>
                <fullName>ROOFING &amp; FLASHING</fullName>
            </value>
            <value>
                <fullName>CARPET</fullName>
            </value>
            <value>
                <fullName>BATHROOMS</fullName>
            </value>
            <value>
                <fullName>EXT. DOORS, &amp; WINDOWS</fullName>
            </value>
            <value>
                <fullName>PLUMBING &amp; WATER FILTRATION</fullName>
            </value>
            <value>
                <fullName>HEATING &amp; COOLING</fullName>
            </value>
            <value>
                <fullName>ELECTRICAL</fullName>
            </value>
            <value>
                <fullName>INSULATION &amp; SOLAR</fullName>
            </value>
            <value>
                <fullName>DRYWALL</fullName>
            </value>
            <value>
                <fullName>HARDSCAPES</fullName>
            </value>
            <value>
                <fullName>INT. DOORS &amp; TRIM</fullName>
            </value>
            <value>
                <fullName>KITCHEN CABINETS</fullName>
            </value>
            <value>
                <fullName>GARAGE CABINETS &amp; EPOXY</fullName>
            </value>
            <value>
                <fullName>FLOORING &amp; BACKSPLASH</fullName>
            </value>
            <value>
                <fullName>PAINTING</fullName>
            </value>
            <value>
                <fullName>COUNTERTOPS</fullName>
            </value>
            <value>
                <fullName>WINDOW COVERINGS</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Inverter</fullName>
            </value>
            <value>
                <fullName>Demand Management System</fullName>
            </value>
            <value>
                <fullName>Battery Storage</fullName>
            </value>
            <value>
                <fullName>Battery Inverter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Suggested Retail</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Unit_Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Total_Cost__c</fullName>
    <formula>Cost__c +  Installation_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Home_Service_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DiacoWindowLineItemController.cls
/*
* Diaco
* @author 			Álvaro Ortega href=<aovargas05@gmail.com>
* Project:			To Windows
* Description:		Component to manage Products and Line Item on Window Industry
*
* Changes (Version)
* ___________________________________
*			No.		Date			Author					Description
*			_____	__________		____________________	____________________________________
* @version	1.0		20/12/2019		Alvaro Ortega (AO)		Component.
*/

public class DiacoWindowLineItemController {
    /*@AuraEnabled
public static List<Decimal> getCustomSetting(){
Job_Costing_Settings__c jc = Job_Costing_Settings__c.getOrgDefaults();
List<Decimal> rt = new List<Decimal>();
rt.add(jc.Dealer_Number__c);
rt.add(jc.Retail_Multiplier__c);

return rt;
}*/
    @AuraEnabled
    public static List<String> getPicklistProductType(){
        /*List<String> ignored = new List<String>();
ignored.add('Carpet & Tile Cleaning');
ignored.add('Electric');
ignored.add('Garage Door');
ignored.add('Internet-Cable-Satellite');
ignored.add('Landscape Maintenance');
ignored.add('Lock Smith');
ignored.add('Maid Service');
ignored.add('Misc');
ignored.add('Pool Install');
ignored.add('Pool Maintenance');
ignored.add('Security Doors');
ignored.add('Weed Removal');
ignored.add('Window');*/
        
        List<String> pickListValuesList = new List<String>();
        Schema.DescribeFieldResult fieldResult = Product__c.Remodel_Category__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        } 
        
        /*for( Schema.PicklistEntry pickListVal : ple){
boolean aux = false;
for(String ing: ignored){
if(ing == pickListVal.getLabel()){
aux = true;
break;
}
}
if(!aux){
pickListValuesList.add(pickListVal.getLabel());
}
}  */   
        return pickListValuesList;
    }
    
    @AuraEnabled
    public static List<Decimal> getInfoFromHS(string recordId){
        Home_Services__c hs = [SELECT Id,Dealer_Number__c, Retail_Multiplier__c FROM Home_Services__c where Id=:recordId];
        List<Decimal> rt = new List<Decimal>();
        rt.add(hs.Dealer_Number__c);
        rt.add(hs.Retail_Multiplier__c);
        
        if(hs.Dealer_Number__c == null || hs.Retail_Multiplier__c == null){
            hs.Dealer_Number__c = hs.Dealer_Number__c == null ? 0.0 : hs.Dealer_Number__c ;
            hs.Retail_Multiplier__c = hs.Retail_Multiplier__c == null ? 1 : hs.Retail_Multiplier__c;
            
            update hs;
        }
        
        /*system.debug('------------------------------------------------------@@@@---------------------------------------------------');
system.debug(hs.Dealer_Number__c);
system.debug(hs.Retail_Multiplier__c);
system.debug('------------------------------------------------------@@@@---------------------------------------------------');*/
        
        return rt;
    }
    
    @AuraEnabled
    public static List<Line_Item__c> updateHSLineItem(String recordId){
        List<Line_Item__c> lis = [select Id, Quantity__c, Unit_Price__c, Total_Sales_Price_p__c, Home_Service__r.Retail_Multiplier__c
                                  from Line_Item__c 
                                  where Home_Service__c=:recordId];
        for(integer i = 0; i < lis.size(); i++){
            //aux.Total_Sales_Price_p__c = aux.Quantity__c * aux.Unit_Price__c * multiplier
            lis[i].Total_Sales_Price_p__c = lis[i].Quantity__c * lis[i].Unit_Price__c * lis[i].Home_Service__r.Retail_Multiplier__c;
        }
        update lis;
        return lis;
    }
    
    @AuraEnabled
    public static List<Line_Item__c> updateLineItem(List<Line_Item__c> recordToUpdate){
        update recordToUpdate;
        return recordToUpdate;
    }
    
    @AuraEnabled
    public static List<Line_Item__c> getWindowsLineItems(String recordId){
        List<Line_Item__c> lis = [select Product__r.Remodel_Category__c, Latch_Suggested_Retail_w_Install__c , Latch_Suggested_Retail_w_Install_Fee__c 
                                  from Line_Item__c 
                                  where Home_Service__c=:recordId and Product__c!=null];
        return lis;
    }
    
    @AuraEnabled
    public static List<Line_Item__c> getWindowsLineItemsCategory(String recordId, String category){
        List<Line_Item__c> lis = [select Name, Latch_UOM__c, Quantity__c, Latch_Suggested_Retail_w_Install__c, Latch_Suggested_Retail_w_Install_Fee__c, Unit_Price__c, Product__r.Unit_Total_Cost__c
                                  from Line_Item__c 
                                  where Home_Service__c =:recordId and Product__r.Remodel_Category__c =:category
                                  order by CreatedDate desc ];
        return lis;
    }
    
    public static List<SObject> slice(List<SObject> input, Integer ge, Integer l){
        List<Product__c> output = input.clone();
        for (Integer i = 0; i < ge; i++) output.remove(0);
        Integer elements = l - ge;
        while (output.size() > elements) output.remove(elements);
        return output;
    }
    
    @AuraEnabled
    public static List<Product__c> getProducts(String recordId, String category){
        Home_Services__c hs = [SELECT Industry_Formula__c 
                               FROM Home_Services__c 
                               where Id=:recordId];
        List<Product__c> ps1 = [select Id, Name, Sales_Price__c, Service__c,Unit_Total_Cost__c
                                from Product__c 
                                where active__c=true and Service__c=false and Remodel_Category__c=:category
                                and (Name like '0%' or Name like '1%' or Name like '2%' or Name like '3%' or Name like '4%' or Name like '5%'
                                     or Name like '6%' or Name like '7%' or Name like '8%' or Name like '9%')
                                order by Name];
        
        List<Product__c> ps2 = [select Id, Name, Sales_Price__c, Service__c,Unit_Total_Cost__c
                                from Product__c 
                                where active__c=true and Service__c=false and Remodel_Category__c=:category
                                and (NOT Name like '0%') and (NOT Name like '1%') and (NOT Name like '2%') and (NOT Name like '3%') and (NOT Name like '4%') 
                                and (NOT Name like '5%') and (NOT Name like '6%') and (NOT Name like '7%') and (NOT Name like '8%') and (NOT Name like '9%')
                                order by Name];
        List<Product__c> ps = new List<Product__c>();
        ps.addAll(ps2);
        ps.addAll(ps1);
        
        return ps;
    }
    
    @AuraEnabled
    public static List<Line_Item__c> addProductsToHS(String recordId, List<SObject> selectedOptions, String category, Decimal multiplier){
        try {
            //system.debug('___________________________________________________________________');
            //system.debug('Entra para agregar: '+selectedOptions);
            List<Product__c> options = getProducts(recordId, category);
            List<Line_Item__c> ois = new List<Line_Item__c>();
            
            for(integer i = 0; i < selectedOptions.size(); i++){
                //system.debug('Primer for: '+selectedOptions[i].Id);
                for(integer j = 0; i < options.size(); j++){
                    //system.debug('Segundo for: '+options[j].Id);
                    if(selectedOptions[i].Id == options[j].Id){
                        system.debug('Entra al IF');
                        Line_Item__c aux = new Line_Item__c();
                        aux.Name =  options[j].Name;
                        aux.Home_Service__c = recordId;
                        aux.Product__c = options[j].Id;
                        aux.Unit_Price__c = options[j].Sales_Price__c != null && options[j].Sales_Price__c != 0? options[j].Sales_Price__c : options[j].Unit_Total_Cost__c;
                        //aux.Price__c = options[j].Sales_Price__c != null ? options[j].Sales_Price__c : 0;
                        aux.Quantity__c = 1;
                        //ois[i].Quantity__c * (ois[i].Unit_Price__c)
                        aux.Total_Sales_Price_p__c = aux.Quantity__c * aux.Unit_Price__c * multiplier;
                        //aux.Latch_Category__c = category;
                        ois.add(aux);
                        system.debug('Todo bien despues de entrar al IF');
                        break;
                    } 
                }
            }
            insert ois;
            System.debug('Todo bien al crear');
            system.debug('___________________________________________________________________');
            return ois;
        } catch(Exception e) {
            System.debug('@--->' + e);
            return null;
        }
        
    }
    
    @AuraEnabled
    public static String deleteLineItem(String recordId){
        Line_Item__c oi = new Line_Item__c();
        oi.Id = recordId;
        delete oi;
        return recordId;
    }
}