force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/SMS_Notification_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SMS Notification Status</description>
    <label>SMS Notification Status</label>
</CustomObject>

force-app/main/default/objects/SMS_Notification_Status__c/fields/conditions__c.field-meta.xml
<CustomField>
    <fullName>conditions__c</fullName>
    <description>possible values OR, AND,CUSTOM_lOGIC</description>
    <inlineHelpText>possible values OR, AND,CUSTOM_lOGIC</inlineHelpText>
    <label>conditions</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Customize_Logic__c.field-meta.xml
<CustomField>
    <fullName>Customize_Logic__c</fullName>
    <description>Customize the logic for the filter conditions that you specified. For example: 1 &amp;&amp;  (2 || 3)</description>
    <inlineHelpText>Customize the logic for the filter conditions that you specified. For example: 1 &amp;&amp; (2 || 3)</inlineHelpText>
    <label>Customize Logic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Diaco_SenderId__c.field-meta.xml
<CustomField>
    <fullName>Diaco_SenderId__c</fullName>
    <label>Diaco SenderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Diaco_TemplateId__c.field-meta.xml
<CustomField>
    <fullName>Diaco_TemplateId__c</fullName>
    <label>Diaco TemplateId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_SenderId__c.field-meta.xml
<CustomField>
    <fullName>Magic_SenderId__c</fullName>
    <label>Magic SenderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_Source__c.field-meta.xml
<CustomField>
    <fullName>Magic_Source__c</fullName>
    <label>Magic Source</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_TemplateId__c.field-meta.xml
<CustomField>
    <fullName>Magic_TemplateId__c</fullName>
    <label>Magic TemplateId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Object_ApiName__c.field-meta.xml
<CustomField>
    <fullName>Object_ApiName__c</fullName>
    <label>Object ApiName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/ParentId_ApiName__c.field-meta.xml
<CustomField>
    <fullName>ParentId_ApiName__c</fullName>
    <label>ParentId ApiName</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/PhoneNumber_ApiName__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber_ApiName__c</fullName>
    <label>PhoneNumber ApiName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/SMSText__c.field-meta.xml
<CustomField>
    <fullName>SMSText__c</fullName>
    <description>Text Message</description>
    <inlineHelpText>You&apos;ll ignore the Template Id when If this field is populated</inlineHelpText>
    <label>SMSText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/SMS_Send_Condition__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SMS Send Condition</description>
    <label>SMS Send Condition</label>
</CustomObject>

force-app/main/default/objects/SMS_Send_Condition__c/fields/Compare_Static_Operation__c.field-meta.xml
<CustomField>
    <fullName>Compare_Static_Operation__c</fullName>
    <description>COMPAREC possible values ==, !=, &lt;, &lt;=, &gt;, &gt;=
FIND_BY_RECORDTYPE possible values Field Apiname&gt; Example: Id, Account.</description>
    <inlineHelpText>https://github.com/jdcrensh/apex-evalex</inlineHelpText>
    <label>Compare Static Operation / Field ApiName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/fields/Compare_Static_Value__c.field-meta.xml
<CustomField>
    <fullName>Compare_Static_Value__c</fullName>
    <label>Compare Static Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/fields/Condition_Type__c.field-meta.xml
<CustomField>
    <fullName>Condition_Type__c</fullName>
    <description>possible values CHANGEC, COMPAREC,FIND_BY_RECORDTYPE,CONTAINS,ISNULL,ISNOTNULL</description>
    <inlineHelpText>possible values CHANGEC, COMPAREC,FIND_BY_RECORDTYPE,CONTAINS,ISNULL,ISNOTNULL</inlineHelpText>
    <label>Condition Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <label>FieldApiName</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/fields/IsInsert__c.field-meta.xml
<CustomField>
    <fullName>IsInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsInsert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/fields/Notification_Id__c.field-meta.xml
<CustomField>
    <fullName>Notification_Id__c</fullName>
    <description>Notification Id</description>
    <label>Notification Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <description>When Notification condition equals Custom Logic</description>
    <inlineHelpText>1</inlineHelpText>
    <label>Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <label>ObjectApiName</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiacoSMSettings.cls
/*
 * Diaco
 * @author             Jull Quintero D
 * Project:            SMS
 * TestClass:          DiacoSMSettingsTest
 * Description:        Diaco SMS Settings
 *
 * Changes (Version)
 * _________________________________________
 *            No.        Date            Author                    Description
 *            ____    __________        __________________      _____________________________________
 * @version   1.0    10/12/2020         Jull Quintero D          Initial implementation of the class.
 * @version   2.0    19/12/2020         Jull Quintero D          SMS Trigger Condition 
 **/

public virtual class DiacoSMSettings {

    // Condition Types
    private static String CHANGE_CONDITION = 'CHANGEC'; 
    private static String COMPARE_STATIC_CONDITION = 'COMPAREC'; 
    private static String CONTAINS_RECORDTYPE = 'FIND_BY_RECORDTYPE'; 
    private static String CONTAINS = 'CONTAINS'; 
    private static String ISNULL = 'ISNULL'; 
    private static String ISNOTNULL = 'ISNOTNULL'; 


    // Logic
    private static String OR_LOGIC = 'OR';
    private static String AND_LOGIC = 'AND'; 
    private static String CUSTOM_lOGIC = 'CUSTOM_lOGIC'; 

    private static Boolean isUpdateOld;
    private static Boolean isInsertOld;
    private static String objectApiNameOld;
    private static NotCondData conditionsToEvaluate;

    private static Map<String,String> diacoSenderName;

    /*
    *@Author: Jull Q Daza - 19/12/2020
     * This method is responsible to get SMS Trigger Notifications
     * 
     * This method is used in:
     * CreateSMS.cls
     * 
     * @param String (Object ApiName)
     * @param Boolean (Update)
     */
    public static NotCondData getConditionsToEvaluate(String objectApiName,Boolean isInsert, Boolean isUpdate) {
        if( objectApiNameOld != objectApiName || isUpdateOld != isUpdate || isInsertOld != isInsert) {

            List<SMS_Send_Condition__c> conditionFromObject = [SELECT Id,ObjectApiName__c,Notification_Id__c,IsInsert__c,IsUpdate__c,Number__c,
                                                                    FieldApiName__c,Condition_Type__c,Compare_Static_Value__c,
                                                                    Compare_Static_Operation__c
                                                                FROM SMS_Send_Condition__c 
                                                                WHERE ObjectApiName__c = :objectApiName AND 
                                                                (IsInsert__c = :isInsert OR IsUpdate__c = :isUpdate) ];

            List<SMS_Notification_Status__c> activeNots = [SELECT Id,ParentId_ApiName__c,Active__c,Category__c,Diaco_SenderId__c,Diaco_TemplateId__c,SMSText__c,
                                                                Magic_SenderId__c,Magic_Source__c,Magic_TemplateId__c,conditions__c,Customize_Logic__c,
                                                                Object_ApiName__c,PhoneNumber_ApiName__c,Provider__c,Type__c
                                                            FROM SMS_Notification_Status__c
                                                            WHERE Object_ApiName__c = :objectApiName AND Active__c = true];

            Map<Id, SMS_Notification_Status__c> activeNotsMap = new Map<Id, SMS_Notification_Status__c>(activeNots);
            Map<Id, List<SMS_Send_Condition__c>> conditionsByNot = new Map<Id, List<SMS_Send_Condition__c>>();
    
            Integer conditionFromObjectSize = conditionFromObject.size();
            for (Integer i = 0; i < conditionFromObjectSize; i++) {
                SMS_Send_Condition__c contoeval = conditionFromObject[i];
                if( activeNotsMap.get(contoeval.Notification_Id__c) != null && activeNotsMap.get(contoeval.Notification_Id__c).Active__c ) {
                    Id notId = activeNotsMap.get(contoeval.Notification_Id__c).Id;
                    if( conditionsByNot.get(notId) == null ) {
                        conditionsByNot.put(notId, new List<SMS_Send_Condition__c>());
                    }
                    conditionsByNot.get(notId).add(contoeval);
                }
            }

            NotCondData returnValue = new NotCondData();
            returnValue.notifications = activeNotsMap;
            returnValue.conditionsByNot = conditionsByNot;

            conditionsToEvaluate = returnValue;
            objectApiNameOld = objectApiName;
            isInsertOld = isInsert;
            isUpdateOld = isUpdate;
        }
        return conditionsToEvaluate;
    }

    /*
    *@Author: Jull Q Daza - 21/12/2020
     * This method is responsible to evaluate Conditions By Notification Id
     * 
     * This method is used in:
     * CreateSMS.cls
     * 
     * @param List SMS_Send_Condition__c (Custom Setting)
     * @param SObject (newObject)
     * @param SObject (oldObject)
     * @param Boolean (isUpdate)
     */
    public static Boolean evaluateConditions(SMS_Notification_Status__c notification,List<SMS_Send_Condition__c> tgrConditions,SObject newObject,SObject oldObject,Boolean isUpdate) {
        Map<String,Boolean> meetCond = new Map<String,Boolean>();
        Integer tgrConditionsLgth = tgrConditions.size();
        for (Integer i = 0; i < tgrConditionsLgth; i++) {
            SMS_Send_Condition__c condition = tgrConditions[i];
            Boolean value = false;
            if( condition.Condition_Type__c == CONTAINS_RECORDTYPE ) {
                if( String.isNotBlank(condition.Compare_Static_Value__c) && String.isNotBlank(condition.Compare_Static_Operation__c) ) {

                    Id objRecordId = (Id)newObject.get(condition.Compare_Static_Operation__c);
                    Id recordTypeId = (Id)newObject.get(condition.FieldApiName__c);
                    value = containsRecordtype(objRecordId,recordTypeId,condition.Compare_Static_Value__c);
                }

            } else if( condition.Condition_Type__c == CONTAINS ) {
                if( condition.Compare_Static_Value__c != null ) {
                    
                    value = String.valueOf(newObject.get(condition.FieldApiName__c)).contains(condition.Compare_Static_Value__c);
                }

            } else if( condition.Condition_Type__c == CHANGE_CONDITION ) {
                if( isUpdate && oldObject != null ) {
                    
                    value = newObject.get(condition.FieldApiName__c) != oldObject.get(condition.FieldApiName__c);
                }else { value = true;}

            } else if( condition.Condition_Type__c == COMPARE_STATIC_CONDITION ) {
                if( String.isNotBlank(condition.Compare_Static_Operation__c) && String.isNotBlank(condition.Compare_Static_Value__c) ) {
                    String evalExpression =  '"' + newObject.get(condition.FieldApiName__c) + '"' + condition.Compare_Static_Operation__c + '"'+ condition.Compare_Static_Value__c + '"';
                    System.debug('>> evalExpression: ' + evalExpression);
                    value = new RT_Expression(evalExpression).evalBool();
                }
            } else if( condition.Condition_Type__c  == ISNULL ) {
                value = newObject.get(condition.FieldApiName__c) == null;
            
            } else if( condition.Condition_Type__c  == ISNOTNULL ) {
                value = newObject.get(condition.FieldApiName__c) != null;

            } else { return false; }

            if ( notification.conditions__c == CUSTOM_lOGIC ) {
                if( condition.Condition_Type__c == null ) return false;
                meetCond.put(String.valueOf(condition.Number__c), value);
            }else {
                meetCond.put(String.valueOf(i), value);
            }
        }

        Boolean value = false;
        // OR
        if ( notification.conditions__c == OR_LOGIC ) {
            list<Boolean> values = meetCond.values();
            if( values.contains(true) ) value = true;
            
        } // AND 
        else if ( notification.conditions__c == AND_LOGIC ) {
            list<Boolean> values = meetCond.values();
            if( !values.contains(false) ) value = true;
            
        }
        // Custom Logic
        else if( notification.conditions__c ==  CUSTOM_lOGIC ) {
            if( notification.Customize_Logic__c != null ) {
                String customLogic =  notification.Customize_Logic__c; //'( 1 || 2 ) && 3';
                List<String> logicHar = customLogic.split('');
                Integer logicHarSize = logicHar.size();
                string logical= '';
                for (Integer i = 0; i < logicHarSize; i++) {
                    String str = logicHar[i];
                    String val = string.valueOf(meetCond.get(str)); 
                    logical += val != null ? val: str;
                }    
                System.debug('>> logical: ' + logical);
                if( string.isNotBlank(logical) ) {
                    value = new RT_Expression(logical).evalBool();
                    System.debug('>> value: ' + value);
                }
            }
        }
        return value;
    }

    /*
    *@Author: Jull Q Daza - 10/12/2020
     * This method is responsible to return true if string name is contained in record type
     * 
     * @param SObject (newObject)
     * @param String (nameStr) 
     */
    @TestVisible
    private static Boolean containsRecordtype(Id objRecordId,Id recordTypeId,String nameStr) {
        if( objRecordId != null && recordTypeId != null ) {
            String objectName = objRecordId.getSObjectType().getDescribe().getName();        
            string recordtypeName = Schema.getGlobalDescribe().get(objectName).getDescribe().getRecordTypeInfosById().get(recordTypeId).getName();
            if( recordtypeName.contains(nameStr) ) {
                return true;
            }   
        }
        return false;
    }
    

    /*
    *@Author: Jull Q Daza - 10/12/2020
     * This method is responsible to get Slack Channel
     * 
     * This method is used in:
     * DsmsMessageTriggerHelper.cls
     * 
     * @param List String Phone Number
     */
    public static Map<String,String> getDiacoSMSenderSlackChannel(Set<String> phones) {
        if( diacoSenderName == null ) {
            diacoSenderName = new Map<String,String>();
            List<dsms__Phone_Number__c> senderIds = [SELECT Id,Name,dsms__Phone_Number__c,dsms__Active__c,Slack_Channel__c 
                                                    FROM dsms__Phone_Number__c 
                                                    WHERE dsms__Phone_Number__c IN :phones AND dsms__Active__c=true];
            Integer senderIdLength = senderIds.size();
            for (Integer i = 0; i < senderIdLength; i++) {
                diacoSenderName.put(senderIds[i].dsms__Phone_Number__c, senderIds[i].Slack_Channel__c);
            }
            return diacoSenderName;
        }
        return diacoSenderName;
    }


    /*
    *@Author: Jull Q Daza - 11/12/2020
     * This method is responsible to get Account name by Parent Id
     * 
     * This method is used in:
     * DsmsMessageTriggerHelper.cls
     * 
     * @param Set Ids
     */
    public static Map<Id,String> getParentNames (Set<Id> parentIds) {
        List<Account> accts = new List<Account>();
        List<Home_services__c> hServices = new List<Home_services__c>();
        Map<Id,String> parentName = new Map<Id,String>();
        Set<String> hsIds = new Set<String>();
        Set<String> acctIds = new Set<String>();

        for (String parentId : parentIds) {
            String sObjName = id.valueOf(parentId).getSObjectType().getDescribe().getName();
            if( sObjName == 'Account' ){
                acctIds.add(parentId);
            }else if( sObjName == 'Home_services__c' ){
                hsIds.add(parentId);
            }
        }

        if( !hsIds.isEmpty() ) {
            hServices =  [SELECT Id,Account__c,Account__r.Name FROM Home_services__c WHERE Id IN :hsIds];
        }

        if( !acctIds.isEmpty() ) {
            accts = [SELECT Id, Name FROM Account WHERE Id IN :acctIds];
        }
        if( !accts.isEmpty() || !hServices.isEmpty() ) {
            Integer acctsLgth = accts.size(); Integer hServicesLgth = hServices.size(); 
            for (Integer i = 0; i < acctsLgth; i++) {
                parentName.put(accts[i].id, accts[i].name);
            }

            for (Integer j = 0; j < hServicesLgth; j++) {
                Home_services__c  hs = hServices[j];
                if( hs.Account__c != null )
                    parentName.put(hs.id, hs.Account__r.Name);
            }
        }
        return parentName;
    }

    public class NotCondData{
        public Map<Id, SMS_Notification_Status__c> notifications;
        // conditions by notification id
        public Map<Id, List<SMS_Send_Condition__c>> conditionsByNot;
    }
}