force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/ApptSetter__c.field-meta.xml
<CustomField>
    <fullName>ApptSetter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appointment Setter</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Personnel__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Personnel__c.Appt_Setter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Home Services (Appointment Setter)</relationshipLabel>
    <relationshipName>Home_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.FirstName),&apos;&apos;,Account__r.FirstName)</formula>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/diacoEventCurrentTest.cls
@isTest
public class diacoEventCurrentTest {
    @isTest static void testAll(){
        Personnel__c person = new Personnel__c (
            First_Name__c = 'Test Personnel'
        );
        insert person;
        Account acc = new Account(
        	FirstName = 'Test acc',
            LastName = 'last test'
        );
        insert acc;
        Home_Services__c hs = new Home_Services__c(
        	Name = 'test',
            Account__c = acc.Id,
            ApptSetter__c = person.Id
        );
        insert hs;
        Event event = new Event(
            Home_Service__c = hs.Id,
            RecordTypeId = '012410000013G9CAAU',
            DurationInMinutes=1,
            ActivityDateTime= Date.Today()
        );
        insert event;
        test.startTest();
        String param = event.Id+','+event.RecordTypeId+','+event.Home_Service__c;
        List<String> params = new List<String>();
        params.add(param);
		diacoEventCurrent.CurrentEvent(params);		
        test.stopTest();
    }
}