force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentMethodType__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodType__c</fullName>
    <label>Payment Method Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentMethodTypePick</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/DiacoAccountPaymentMethodTest.cls
@isTest
public class DiacoAccountPaymentMethodTest {
	@testSetup
    static void setup(){
        Account a = new Account(Name='test');
        insert a;
        PaymentMethod__c pay = new PaymentMethod__c(Name='Test pay',Account__c=a.Id,PaymentMethodType__c='ACH');
        insert pay;
    }
    @isTest
    static void testAll(){
        Account act = [select id from Account where Name='test'];
        Test.startTest();
        List<PaymentMethod__c> pays = DiacoAccountPaymentMethod.getPayMethods(act.Id);
        DiacoAccountPaymentMethod.deletePayMethod(pays[0].Id);
        Test.stopTest();
    }
}