force-app/main/default/objects/Attention__c/Attention__c.object-meta.xml
<CustomObject>
    <label>Attention</label>
    <nameField>
        <label>Attention Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attentions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attention__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Personnel</label>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Attentions</relationshipLabel>
    <relationshipName>Attentions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attention__c/fields/This_Closed_Ticket__c.field-meta.xml
<CustomField>
    <fullName>This_Closed_Ticket__c</fullName>
    <defaultValue>false</defaultValue>
    <label>This Closed Ticket</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attention__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Attentions</relationshipLabel>
    <relationshipName>Attentions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Arrow_To_Show__c.field-meta.xml
<CustomField>
    <fullName>Arrow_To_Show__c</fullName>
    <formula>If(ISPICKVAL( Priority__c  , &apos;Very Low&apos;), &apos;arrow down lowGreen&apos;, If(ISPICKVAL( Priority__c  , &apos;Low&apos;), &apos;arrow down green&apos;, If(ISPICKVAL( Priority__c  , &apos;Medium&apos;), &apos;arrow up yellow&apos;, If(ISPICKVAL( Priority__c  , &apos;High&apos;), &apos;arrow up orange&apos;, &apos;arrow up red&apos; ) )) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Arrow To Show</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <displayFormat>TP{0000}</displayFormat>
    <label>Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Name_Assign_To__c.field-meta.xml
<CustomField>
    <fullName>Name_Assign_To__c</fullName>
    <formula>IF(ISBLANK(Assign_to__c),&apos;Not Assigned&apos;,Assign_to__r.Full_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name Assign To</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>&apos;Medium&apos;</defaultValue>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Very Low</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Very High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ticket Type</label>
    <referenceTo>Ticket_Type__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket_Type__c/Ticket_Type__c.object-meta.xml
<CustomObject>
    <label>Ticket Type</label>
    <nameField>
        <label>Ticket Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket_Type__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <displayFormat>TT{0000}</displayFormat>
    <label>Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/DiacoTicketComponentController.cls
public class DiacoTicketComponentController {
    @AuraEnabled
    public static List<Ticket__c> getAllTickets(){
        List<Ticket__c> ts = [select Id, Code__c, Name, Status__c, Name_Assign_To__c, Priority__c, Arrow_To_Show__c, Description__c
                             from Ticket__c
                             order by CreatedDate desc];
        
        return ts;
    }
    
    @AuraEnabled
    public static List<Ticket_Type__c> getAllTicketTypes(){
        List<Ticket_Type__c> ts = [select Id, Name
                                   from Ticket_Type__c
                                   where Active__c = True
                                   order by CreatedDate desc];
        
        return ts;
    }
    
    @AuraEnabled
    public static void deleteAttention(String recordId){
        Attention__c at = new Attention__c();
        at.Id = recordId;
        delete at;
        
    }

    @AuraEnabled
    public static List<Attention__c> getAttentions(String recordId){
        List<Attention__c> ass = [select Id, Name, Description__c, Personnel__r.Name, This_Closed_Ticket__c, Ticket__c
                                 from Attention__c
                                 where Ticket__c =:recordId
                                 order by CreatedDate desc];
        
        return ass;
    }
    
    @AuraEnabled
    public static List<Ticket__c> getAllFilterTickets(List<String> data){
        system.debug(data);
        
        List<Ticket__c> ts;
        
        if(data[4] == ''){
            ts = [select id, Code__c, Name, Status__c, Name_Assign_To__c, Priority__c, Arrow_To_Show__c, Description__c
                  from Ticket__c
                  where Code__c like :data[0] and Name like :data[1] and Name_Assign_To__c like :data[2] and Status__c like :data[3]
                  order by CreatedDate desc];
        }else{
            ts = [select id, Code__c, Name, Status__c, Name_Assign_To__c, Priority__c, Arrow_To_Show__c, Description__c
                  from Ticket__c
                  where Code__c like :data[0] and Name like :data[1] and Name_Assign_To__c like :data[2] and Status__c like :data[3] and Priority__c =:data[4]
                  order by CreatedDate desc];
        }

        return ts;
    }

}