force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>To keep the county name. It is not unique. The same county name can exist for different states.</description>
    <label>County</label>
    <nameField>
        <displayFormat>CN-{000}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/County_state__c.field-meta.xml
<CustomField>
    <fullName>County_state__c</fullName>
    <description>Combination of County+&quot;:&quot;+state.</description>
    <externalId>true</externalId>
    <label>CountyState</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SchedulableInsertAuditingRecords.cls
/********************************************************************************************
* Class Name : SchedulableInsertAuditingRecords
* Created By : Sankar Marappan
* Created Date : 2/10/2016
* Author : MST
* Description: Every day at 12 a.m PST the job runs to invoke InsertAuditingRecords class logic to insert PA_Import_Auditing Records
**********************************************************************************************/

global class SchedulableInsertAuditingRecords implements Schedulable {
    Set<String> countyWithStateSet = new Set<String>();
    
   global void execute(SchedulableContext sc) {  
       String query = 'SELECT County_State__c FROM County__c';    
            database.executebatch(new InsertAuditingRecords(query),200);
   }
}