force-app/main/default/objects/docuSignConf__c/docuSignConf__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Docusign Configuration</label>
</CustomObject>

force-app/main/default/objects/docuSignConf__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <label>Account</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/docuSignConf__c/fields/accountId__c.field-meta.xml
<CustomField>
    <fullName>accountId__c</fullName>
    <label>Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/docuSignConf__c/fields/integratorsKey__c.field-meta.xml
<CustomField>
    <fullName>integratorsKey__c</fullName>
    <label>Integrators Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/docuSignConf__c/fields/PassWord_Pest_Control__c.field-meta.xml
<CustomField>
    <fullName>PassWord_Pest_Control__c</fullName>
    <label>PassWord Pest Control</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/docuSignConf__c/fields/passwordSolar__c.field-meta.xml
<CustomField>
    <fullName>passwordSolar__c</fullName>
    <label>Password Solar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/docuSignConf__c/fields/User_Id_Pest_Control__c.field-meta.xml
<CustomField>
    <fullName>User_Id_Pest_Control__c</fullName>
    <label>User Id Pest Control</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/docuSignConf__c/fields/userIdSolar__c.field-meta.xml
<CustomField>
    <fullName>userIdSolar__c</fullName>
    <label>User Id Solar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/diacoDocusignSetup.cls
public class diacoDocusignSetup {
    public List<docuSignConf__c> docusignconf{get;set;}
    public docuSignConf__c conf{get;set;}
    public String pass{get;set;}
    public diacoDocusignSetup(){
        conf = new docuSignConf__c();
        docusignconf = [select accountId__c, integratorsKey__c, password__c, userId__c, User_Id_Pest_Control__c,
                        userIdSolar__c, account__c, passwordSolar__c, PassWord_Pest_Control__c
                                              from docuSignConf__c];
        conf = docusignconf[0];
        pass = conf.password__c;
    }
    
    public void save(){
        if( conf.password__c == '' || conf.password__c == null ){
            conf.password__c = pass;
        }
        upsert conf;
    }
}