force-app/main/default/objects/docuSignConf__c/docuSignConf__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Docusign Configuration</label>
</CustomObject>

force-app/main/default/objects/docuSignConf__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <label>Account</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/docuSignConf__c/fields/integratorsKey__c.field-meta.xml
<CustomField>
    <fullName>integratorsKey__c</fullName>
    <label>Integrators Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/docuSignConf__c/fields/tokenPart1__c.field-meta.xml
<CustomField>
    <fullName>tokenPart1__c</fullName>
    <label>Token Part 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/docuSignConf__c/fields/tokenPart2__c.field-meta.xml
<CustomField>
    <fullName>tokenPart2__c</fullName>
    <label>Token Part 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/docuSignConf__c/fields/tokenPart3__c.field-meta.xml
<CustomField>
    <fullName>tokenPart3__c</fullName>
    <label>Token Part 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/ApptSetter__c.field-meta.xml
<CustomField>
    <fullName>ApptSetter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appointment Setter</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Personnel__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Personnel__c.Appt_Setter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Home Services (Appointment Setter)</relationshipLabel>
    <relationshipName>Home_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Contract_Status_Product__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status_Product__c</fullName>
    <label>Contract Status Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Contract_Status_Service__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status_Service__c</fullName>
    <label>Contract Status Service</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/contractDocument__c.field-meta.xml
<CustomField>
    <fullName>contractDocument__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contract Document</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/envelopeId__c.field-meta.xml
<CustomField>
    <fullName>envelopeId__c</fullName>
    <label>EnvelopeId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>Exp_Date__c</fullName>
    <label>Exp Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.FirstName),&apos;&apos;,Account__r.FirstName)</formula>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.LastName),&apos;&apos;,Account__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Method_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Method_Of_Payment__c</fullName>
    <label>Method Of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/sendDate__c.field-meta.xml
<CustomField>
    <fullName>sendDate__c</fullName>
    <label>Send Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/fields/Kunnect_ID__c.field-meta.xml
<CustomField>
    <fullName>Kunnect_ID__c</fullName>
    <inlineHelpText>This is a Required field.  If this person does not have a Kunnect account please put &quot;none&quot;</inlineHelpText>
    <label>Kunnect ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiacoDocusignBatchTest.cls
@isTest
public class DiacoDocusignBatchTest {
    static testmethod void test() {
        Account Acc = new Account();
        Acc.FirstName = 'Account';
        Acc.LastName = 'Test';
        Acc.RecordTypeId ='012410000012NOKAA2';
        insert Acc;
        
        Personnel__c per = new Personnel__c();
        per.Name = 'test';
        per.First_Name__c = 'test';
        per.Last_Name__c = 'test';
        per.Kunnect_ID__c = 'none';
        insert per;
        
        Home_Services__c hs1 = new  Home_Services__c();
        hs1.Name = 'test test - Water Treatment Sales';
        hs1.Account__c = Acc.Id;
        hs1.RecordTypeId = '012410000013G9NAAU';
        hs1.Method_Of_Payment__c = 'Credit Card';		 
        hs1.ApptSetter__c = per.Id;
        hs1.Exp_Date__c = '7/24';
        hs1.sendDate__c = Date.today();
        hs1.envelopeId__c = '7d65ea43-8d7e-4ce4-a6d3-a523dbd7e155';
        hs1.contractDocument__c = false;
        insert hs1;
        
        Home_Services__c hs2 = new  Home_Services__c();
        hs2.Name = 'test test - Water Treatment Sales';
        hs2.Account__c = Acc.Id;
        hs2.RecordTypeId = '012410000013G9NAAU';
        hs2.Method_Of_Payment__c = 'Credit Card';		 
        hs2.ApptSetter__c = per.Id;
        hs2.Exp_Date__c = '7/24';
        hs2.sendDate__c = Date.today();
        hs2.Contract_Status_Product__c = 'Waiting';
        hs2.envelopeId__c = '7d65ea43-8d7e-4ce4-a6d3-a523dbd7e155';
        hs2.contractDocument__c = false;
        insert hs2;
        
        Home_Services__c hs3 = new  Home_Services__c();
        hs3.Name = 'test test - Water Treatment Sales';
        hs3.Account__c = Acc.Id;
        hs3.RecordTypeId = '012410000013G9NAAU';
        hs3.Method_Of_Payment__c = 'Credit Card';		 
        hs3.ApptSetter__c = per.Id;
        hs3.Contract_Status_Service__c = 'Waiting';
        hs3.Exp_Date__c = '7/24';
        hs3.sendDate__c = Date.today();
        hs3.envelopeId__c = '7d65ea43-8d7e-4ce4-a6d3-a523dbd7e155';
        hs3.contractDocument__c = false;
        insert hs3;
        docuSignConf__c doc = new docuSignConf__c(
            account__c = '1234567', 
            integratorsKey__c = 'TestintegratorsKey', 
            password__c = 'testapassword', 
            userId__c = 'TestuserId',
            tokenPart1__c = '123', tokenPart2__c= '123', tokenPart3__c= '123'
        ); 
        upsert doc;
        
        List<Home_Services__c> lsths = [select envelopeId__c, contractDocument__c, id, Name, sendDate__c, Account__c, RecordTypeId, Contract_Status_Product__c, Contract_Status_Service__c
                                          from Home_Services__c 
                                          where (envelopeId__c != null or envelopeId__c != '') and contractDocument__c = false];
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DiacoDocuSignCalloutMock());
        diacoDocusignBatcheableGetDocu dbstsroua = new diacoDocusignBatcheableGetDocu();
        dbstsroua.execute(null, lsths);
        dbstsroua.finish(null);
        dbstsroua.start(null);
        Test.stopTest();
    }
    
    static testmethod void test1() {
        Account Acc = new Account();
        Acc.FirstName = 'Account';
        Acc.LastName = 'Test';
        Acc.RecordTypeId ='012410000012NOKAA2';
        insert Acc;
        
        Personnel__c per = new Personnel__c();
        per.Name = 'test';
        per.First_Name__c = 'test';
        per.Last_Name__c = 'test';
        per.Kunnect_ID__c = 'none';
        insert per;
        
        Home_Services__c hs1 = new  Home_Services__c();
        hs1.Name = 'test test - Water Treatment Sales';
        hs1.Account__c = Acc.Id;
        hs1.RecordTypeId = '012410000013G9NAAU';
        hs1.Method_Of_Payment__c = 'Credit Card';		 
        hs1.ApptSetter__c = per.Id;
        hs1.Exp_Date__c = '7/24';
        hs1.sendDate__c = Date.today();
        hs1.envelopeId__c = '7d65ea43-8d7e-4ce4-a6d3-a523dbd7e155';
        hs1.contractDocument__c = false;
        insert hs1;
        
        Home_Services__c hs2 = new  Home_Services__c();
        hs2.Name = 'test test - Water Treatment Sales';
        hs2.Account__c = Acc.Id;
        hs2.RecordTypeId = '012410000013G9NAAU';
        hs2.Method_Of_Payment__c = 'Credit Card';		 
        hs2.ApptSetter__c = per.Id;
        hs2.Exp_Date__c = '7/24';
        hs2.sendDate__c = Date.today();
        hs2.envelopeId__c = '7d65ea43-8d7e-4ce4-a6d3-a523dbd7e155';
        hs2.contractDocument__c = false;
        insert hs2;
        
        Home_Services__c hs3 = new  Home_Services__c();
        hs3.Name = 'test test - Water Treatment Sales';
        hs3.Account__c = Acc.Id;
        hs3.RecordTypeId = '012410000013G9NAAU';
        hs3.Method_Of_Payment__c = 'Credit Card';		 
        hs3.ApptSetter__c = per.Id;
        hs3.Exp_Date__c = '7/24';
        hs3.sendDate__c = Date.today();
        hs3.envelopeId__c = '7d65ea43-8d7e-4ce4-a6d3-a523dbd7e155';
        hs3.contractDocument__c = false;
        insert hs3;
        docuSignConf__c doc = new docuSignConf__c(
            account__c = '1234567', 
            integratorsKey__c = 'TestintegratorsKey', 
            password__c = 'testapassword', 
            userId__c = 'TestuserId',
            tokenPart1__c = '123', tokenPart2__c= '123', tokenPart3__c= '123'
        ); 
        upsert doc;
        
        List<Home_Services__c> lsths = [select envelopeId__c, contractDocument__c, id, Name, sendDate__c, Account__c, RecordTypeId
                                          from Home_Services__c 
                                          where (envelopeId__c != null or envelopeId__c != '') and contractDocument__c = false];
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DiacoDocuSignCalloutMock());
        DateTime myDateTime = System.now().addMinutes(1);
        diacoDocusignScheduleClass request = new diacoDocusignScheduleClass();
        String title = 'Docusign job xx';
        String sch = '0 '+myDateTime.minute()+' '+myDateTime.hour()+' '+myDateTime.day()+' '+myDateTime.month()+' ?';
        String jobID = system.schedule(title, sch, request);
        Test.stopTest();
    }
}