force-app/main/default/objects/docuSignConf__c/docuSignConf__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Docusign Configuration</label>
</CustomObject>

force-app/main/default/objects/docuSignConf__c/fields/accountId__c.field-meta.xml
<CustomField>
    <fullName>accountId__c</fullName>
    <label>Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/docuSignConf__c/fields/integratorsKey__c.field-meta.xml
<CustomField>
    <fullName>integratorsKey__c</fullName>
    <label>Integrators Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/diacoDocusignSetupTest.cls
@isTest
public class diacoDocusignSetupTest {
    static testMethod void test(){
        docuSignConf__c doc = new docuSignConf__c(
            accountId__c = 'testaccouont', 
            integratorsKey__c = 'TestintegratorsKey', 
            password__c = 'testapassword', 
            userId__c = 'TestuserId'
        ); 
        upsert doc;
        Test.startTest();
        diacoDocusignSetup setup = new diacoDocusignSetup();
        setup.conf.password__c = '';
        setup.save();
        Test.stopTest();
        
    }

}