force-app/main/default/objects/Install_Item__c/Install_Item__c.object-meta.xml
<CustomObject>
    <label>Install Item</label>
    <nameField>
        <label>Install Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Install_Item__c/fields/Install_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>Install_Item_Status__c</fullName>
    <defaultValue>&quot;In Process&quot;</defaultValue>
    <label>Install Item Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Install_Item__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Install Items</relationshipLabel>
    <relationshipName>Install_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Install_Item__c/fields/Invoiced_Amounts__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_Amounts__c</fullName>
    <label>Invoiced Amounts</label>
    <summarizedField>Invoice__c.Invoiced_Amount__c</summarizedField>
    <summaryForeignKey>Invoice__c.Install_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <label>Installation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Install_Item__c.field-meta.xml
<CustomField>
    <fullName>Install_Item__c</fullName>
    <label>Install Item</label>
    <referenceTo>Install_Item__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <defaultValue>&quot;In Process&quot;</defaultValue>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
                <default>true</default>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoiced_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_Amount__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Invoiced Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DiacoInstallItemController.cls
/**
* Diaco
* @author 			Álvaro Ortega href=<aovargas05@gmail.com>
* Project:			Change Order
* Description:		Component to create Change Order Objects and Order Item Objects
*
* Changes (Version)
* ___________________________________
*			No.		Date			Author					Description
*			_____	__________		____________________	____________________________________
* @version	1.0		14/11/2019		Alvaro Ortega (AO)		Component.
**/
public class DiacoInstallItemController {
    @AuraEnabled
    public static List<Install_Item__c> getInstallItems(String recordId){
        List<Install_Item__c> ii = [select Id, Name, Bid_Amount__c, Invoiced_Amounts__c, Install_Item_Status__c, CreatedDate from Install_Item__c where Installation__c=:recordId order by CreatedDate desc];
        return ii;
    }
    
    @AuraEnabled
    public static String deleteInstallItem(String recordId){
        Install_Item__c co = new Install_Item__c();
        co.Id = recordId;
        delete co;
        return recordId;
    }
    
    @AuraEnabled
    public static List<Invoice__c> getInvoices(String recordId){
        List<Invoice__c> i = [select Id, Name, Bid_Amount__c, Invoiced_Amount__c,Invoice_Status__c, CreatedDate from Invoice__c where Install_Item__c=:recordId order by CreatedDate desc];
        return i;
    }
    
    @AuraEnabled
    public static String deleteInvoices(String recordId){
        Invoice__c co = new Invoice__c();
        co.Id = recordId;
        delete co;
        return recordId;
    }
    
    @AuraEnabled
    public static List<Invoice__c> updateInvoices(List<Invoice__c> recordToUpdate){
        update recordToUpdate;
        return recordToUpdate;
    }

}