force-app/main/default/objects/Account/fields/Assessed_Value__c.field-meta.xml
<CustomField>
    <fullName>Assessed_Value__c</fullName>
    <label>Assessed Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Home_Type__c.field-meta.xml
<CustomField>
    <fullName>Home_Type__c</fullName>
    <label>Home Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>MF</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>SF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Recording_Date__c.field-meta.xml
<CustomField>
    <fullName>Recording_Date__c</fullName>
    <description>The date that the house sale was recorded.</description>
    <label>Recording Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sale_Date__c.field-meta.xml
<CustomField>
    <fullName>Sale_Date__c</fullName>
    <label>Sale Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field holds the branch details</description>
    <inlineHelpText>Select the branch where the address resides in.</inlineHelpText>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Home_Type__c.field-meta.xml
<CustomField>
    <fullName>Home_Type__c</fullName>
    <description>Describes the type of home that the person needs.</description>
    <inlineHelpText>Specify the type of home.</inlineHelpText>
    <label>Home Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>MF</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>SF</fullName>
            </value>
            <value>
                <fullName>User Created</fullName>
                <default>true</default>
                <label>User Created</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Used to store 5 digit zipCode.</description>
    <label>Primary Shipping Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Assessed_Value__c.field-meta.xml
<CustomField>
    <fullName>Assessed_Value__c</fullName>
    <label>Assessed Value</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Home_Type__c.field-meta.xml
<CustomField>
    <fullName>Home_Type__c</fullName>
    <formula>TEXT( Address__r.Home_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Home Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/User_Address_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Address_Type__c</fullName>
    <description>holds the type of address</description>
    <label>User Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Owner</fullName>
            </value>
            <value>
                <fullName>Secondary Owner</fullName>
            </value>
            <value>
                <fullName>Mailing Address</fullName>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Renter</fullName>
            </value>
            <value>
                <fullName>Un-validated Homeowner</fullName>
            </value>
            <value>
                <fullName>Family of Renter</fullName>
            </value>
            <value>
                <fullName>Family of Un-validated Homeowner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CreateDeliveryOneRecordsForPA_Test.cls
/************************************************************************************************************************************************************************
* Class Name : CreateDeliveryOneRecordsForPA_Test
* Created By : Priyanka Shanmugam  
* Created Date : 2/23/2016
* Author : MST
* Description : This is code coverage class for CreateDeliveryOneRecordsForPA , CreateDeliveryTwoRecordsForPA ,SchedulableCreateDeliveryOneRecordsForPA and SchedulableCreateDeliveryTwoRecordsForPA.
*************************************************************************************************************************************************************************/
@isTest
private class CreateDeliveryOneRecordsForPA_Test {
    // This test runs a scheduled job at every week at 12 AM
    private static String CRON_EXP = '0 0 5 * * ? *';
    
    @testSetup static void setup() {
        TestClassUtil.createZipcodeForBranch();
        TestClassUtil.createDriver();
        TestClassUtil.createCheetahGiftCardOrder();
        TestClassUtil.createBranch();
        TestClassUtil.createAccount(2);
        TestClassUtil.createAddress(2);
        TestClassUtil.createUserAddress(2);  
        TestClassUtil.createDeliveryProducts();    
        TestClassUtil.createDeliveryParameter(1);
        TestClassUtil.createDeliveryParameter(2);
    }
    
    // Schedule the batch class for the the delivery one record
    @isTest static void testSchedulableCreateDeliveryOneRecord() {
        Test.startTest();
        
        // Schedule the test job        
        String jobId = System.schedule('testScheduleLastSession',CRON_EXP, new SchedulableDeliveryOneRecordCreation());
        
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        
        // Verify the expressions are the same
        System.assertEquals(CRON_EXP, ct.CronExpression);
        
        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);
        
        // Verify the next time the job will run
        // System.assertEquals('2015-09-03 00:00:00',String.valueOf(ct.NextFireTime));
        
        Test.stopTest();
        
    }    
    // Execute the batch job for the delivery one record
    @isTest static void testCreateDeliveryOneRecord(){
        Test.startTest();
        String query = 'SELECT Id,Address__r.Branch__c,Address__r.Zip_code__c,CreatedDate,UserAccount__r.CreatedDate,Sales_Price__c,Recording_Date__c,Sale_Date__c,Assessed_Value__c FROM User_Address__c WHERE User_Address_Type__c = \'Primary Owner\' AND Active__c = true AND UserAccount__r.IsPersonAccount = true AND Address__r.Branch__c != null AND (Sale_Date__c != null OR Recording_Date__c != null) AND(Address__r.Home_Type__c = \'SF\' OR Address__r.Home_Type__c = \'Sfr\') AND id NOT IN (SELECT User_Address__c FROM Delivery_object__c)';
        List<User_Address__c> userAddress = Database.query(query);
        system.debug('***************************'+userAddress.size());
        Database.Executebatch(new CreateDeliveryOneRecordsForPA(query),200);
        Test.stopTest();
        
        //Check the delivery one record is created after executing the batch class of the delivery one record.
        List<Delivery_Object__c> deliveryOneRecords = [SELECT Id FROM Delivery_Object__c WHERE Name = '1'];
        System.assert(deliveryOneRecords.size() > 0);       
    }
    // Execute the batch job for the delivery one record
    @isTest static void testCreateDeliveryWithSaleDate(){
        List<User_Address__c> userAddressList = [SELECT id,Sale_Date__c,Recording_Date__c FROM User_Address__c];
        userAddressList[0].Sale_Date__c = userAddressList[0].Recording_Date__c.addDays(-7);
        
        userAddressList[1].Sale_Date__c = userAddressList[1].Recording_Date__c;
        userAddressList[1].Recording_Date__c = userAddressList[1].Recording_Date__c.addDays(-7);
        update userAddressList;
        Test.startTest();
        String query = 'SELECT Id,Address__r.Branch__c,Address__r.Zip_code__c,CreatedDate,UserAccount__r.CreatedDate,Sales_Price__c,Recording_Date__c,Sale_Date__c,Assessed_Value__c FROM User_Address__c WHERE User_Address_Type__c = \'Primary Owner\' AND Active__c = true AND UserAccount__r.IsPersonAccount = true AND Address__r.Branch__c != null AND (Sale_Date__c != null OR Recording_Date__c != null) AND(Address__r.Home_Type__c = \'SF\' OR Address__r.Home_Type__c = \'Sfr\') AND id NOT IN (SELECT User_Address__c FROM Delivery_object__c)';
        Database.Executebatch(new CreateDeliveryOneRecordsForPA(query),200);
        Test.stopTest();
        
        //Check the delivery one record is created after executing the batch class of the delivery one record.
        List<Delivery_Object__c> deliveryOneRecords = [SELECT Id FROM Delivery_Object__c WHERE Name = '1'];
        System.assert(deliveryOneRecords.size() > 0);       
    }
}