force-app/main/default/objects/Account/fields/Assessed_Value__c.field-meta.xml
<CustomField>
    <fullName>Assessed_Value__c</fullName>
    <label>Assessed Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Captures the date at which the package was dropped and delivered to the customer.</description>
    <inlineHelpText>Captures the date at which the package was dropped and delivered to the customer.</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recording_Date__c.field-meta.xml
<CustomField>
    <fullName>Recording_Date__c</fullName>
    <description>The date that the house sale was recorded.</description>
    <label>Recording Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sale_Date__c.field-meta.xml
<CustomField>
    <fullName>Sale_Date__c</fullName>
    <label>Sale Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field holds the branch details</description>
    <inlineHelpText>Select the branch where the address resides in.</inlineHelpText>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Used to store 5 digit zipCode.</description>
    <label>Primary Shipping Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Branch_Object__c.field-meta.xml
<CustomField>
    <fullName>Branch_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Object</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Delivery_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Parameter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to identify current delivery parameter for the delivery.</description>
    <label>Delivery Parameter</label>
    <referenceTo>Delivery_Parameter__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/fBranch__c.field-meta.xml
<CustomField>
    <fullName>fBranch__c</fullName>
    <formula>User_Address__r.Address__r.Branch__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fBranch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Hung_Status__c.field-meta.xml
<CustomField>
    <fullName>Hung_Status__c</fullName>
    <label>Hung Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrived</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hung</fullName>
            </value>
            <value>
                <fullName>COMPLETED GATED</fullName>
            </value>
            <value>
                <fullName>Gated</fullName>
            </value>
            <value>
                <fullName>Cant Find</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Invld</fullName>
            </value>
            <value>
                <fullName>Remove: Management</fullName>
            </value>
            <value>
                <fullName>Too Far</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Wrong House Number</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Remove: Gated</fullName>
            </value>
            <value>
                <fullName>Remove: Aging</fullName>
            </value>
            <value>
                <fullName>Sent To Cheetah</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Gio - In Process</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Access Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Parameter__c/Delivery_Parameter__c.object-meta.xml
<CustomObject>
    <description>Used to hold delivery parameters.</description>
    <label>Delivery Parameter</label>
    <nameField>
        <displayFormat>DP-{0}</displayFormat>
        <label>Delivery Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Parameter__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Delivery Parameters</relationshipLabel>
    <relationshipName>Delivery_Parameters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Delivery_Parameter__c/fields/Days_Until_Next_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Days_Until_Next_Delivery__c</fullName>
    <description>Used to send next delivery to the customers, if he doesn&apos;t respond for delivery 1 with status Hung.</description>
    <inlineHelpText>Days between this delivery and next if this delivery is completed (Status = Hung). Organizational default value is 7 days.</inlineHelpText>
    <label>Days Until Next Delivery</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Assessed_Value__c.field-meta.xml
<CustomField>
    <fullName>Assessed_Value__c</fullName>
    <label>Assessed Value</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SchedulableDeliveryTwoRecordCreation.cls
/*********************************************************************************************
Author : Priyanka S
CreatedDate : 02-22-2016 
Description:Every day at 12 a.m PST the job runs to invoke CreateDeliveryTwoRecordsForPA 
            class logic to insert the delivery two records.           
**********************************************************************************************/

global class SchedulableDeliveryTwoRecordCreation implements Schedulable {
   global void execute(SchedulableContext sc) {
      String query = 'SELECT Id,Name,fbranch__c,Hung_Status__c,Branch_Object__c,User_address__r.createddate,User_Address__r.Address__r.Branch__c,Delivery_Parameter__r.Days_Until_Next_Delivery__c,Delivery_Date__c,Person_Account__c,User_Address__r.Sales_Price__c,User_Address__r.Assessed_Value__c,User_Address__r.Address__r.Zip_Code__c,User_Address__r.Sale_Date__c,User_Address__r.Recording_Date__c,Person_Account__r.createddate,lastmodifieddate,User_Address__r.Respond_Date__c FROM Delivery_Object__c WHERE Hung_Status__c = \'Hung\' AND Delivery_Date__c != null AND Person_Account__r.isPersonAccount = true AND User_Address__r.Address__r.Branch__c != null AND (User_Address__r.Sale_Date__c != null OR User_Address__r.Recording_Date__c != null) AND User_Address__r.Respond_Date__c = null AND IsRecent__c = true';
      database.executebatch(new CreateDeliveryTwoRecordsForPA(query),200); //Maximum batch size is 200.
   }
}