force-app/main/default/objects/Account/fields/AZROC_License__c.field-meta.xml
<CustomField>
    <fullName>AZROC_License__c</fullName>
    <label>AZROC License</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Doing_Business_As__c.field-meta.xml
<CustomField>
    <fullName>Doing_Business_As__c</fullName>
    <description>&quot;DBA&quot;</description>
    <label>Doing Business As</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Installation_Company__c.field-meta.xml
<CustomField>
    <fullName>Installation_Company__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation Company</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/Finance_Package__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Finance Package</label>
</CustomObject>

force-app/main/default/objects/Finance_Package__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Card_Expiration_Year__c.field-meta.xml
<CustomField>
    <fullName>Card_Expiration_Year__c</fullName>
    <label>Card Expiration Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Installation_Company__c.field-meta.xml
<CustomField>
    <fullName>Installation_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Company</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The lookup Account must be  checked with &apos;Installation Company&apos; field.</errorMessage>
        <filterItems>
            <field>Account.Installation_Company__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Installation Company)</relationshipLabel>
    <relationshipName>Home_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Home Services</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT( Account__r.State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <formula>Account__r.Street__c</formula>
    <label>Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <formula>Account__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Line Items (HS)</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <formula>Product__r.Part_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <formula>Quantity__c *  Product__r.Sales_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Total_Sales_Price_p__c.field-meta.xml
<CustomField>
    <fullName>Total_Sales_Price_p__c</fullName>
    <label>Total Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/AccountNumberChecking__c.field-meta.xml
<CustomField>
    <fullName>AccountNumberChecking__c</fullName>
    <label>Account Number Checking</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/BankAccountType__c.field-meta.xml
<CustomField>
    <fullName>BankAccountType__c</fullName>
    <label>Bank Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BankAccountTypePick</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/CardExpirationMonth__c.field-meta.xml
<CustomField>
    <fullName>CardExpirationMonth__c</fullName>
    <label>Card Expiration Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/CardNumber__c.field-meta.xml
<CustomField>
    <fullName>CardNumber__c</fullName>
    <label>Card Number</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/CardType__c.field-meta.xml
<CustomField>
    <fullName>CardType__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CardTypePick</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/CSV__c.field-meta.xml
<CustomField>
    <fullName>CSV__c</fullName>
    <label>CSV</label>
    <length>4</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/FinanceCompany__c.field-meta.xml
<CustomField>
    <fullName>FinanceCompany__c</fullName>
    <label>Finance Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/FinancedAmount__c.field-meta.xml
<CustomField>
    <fullName>FinancedAmount__c</fullName>
    <label>Financed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/HomeService__c.field-meta.xml
<CustomField>
    <fullName>HomeService__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/NameOnCard__c.field-meta.xml
<CustomField>
    <fullName>NameOnCard__c</fullName>
    <label>Name On Card</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/Payment_Destination__c.field-meta.xml
<CustomField>
    <fullName>Payment_Destination__c</fullName>
    <label>Payment Destination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Once</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Biweekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bimonthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semiannual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Biennial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentMethodType__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodType__c</fullName>
    <label>Payment Method Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentMethodTypePick</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/RoutingNumber__c.field-meta.xml
<CustomField>
    <fullName>RoutingNumber__c</fullName>
    <label>Routing Number</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product HS</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products HS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Suggested Retail</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Home_Service_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RenderContractController.cls
/**
 * @File Name          : RenderContractController.cls
 * @Description        : 
 * @Author             : William Aldana
 * @Group              : 
 * @Last Modified By   : William Aldana
 * @Last Modified On   : 07-22-2020
 * @Modification Log   : 
 * @test Class: diacoRenderContractControllerTest(John Hernandez)
 * Ver       Date            Author      		    Modification
 * 1.0       5/19/2020       William Aldana         Initial Version
 * 1.1		 7/01/2020		 Fabian Pineda			Added support for fetching the Nergy account's data and Home Service's Installation Company's Application and Design Contacts.
 * 1.2       21/07/2020      William Aldana         added amount to the payment method querys/
**/
public class RenderContractController {
    public Home_Services__c homeService{get; set;}
    public List<Line_Item__c> toLineItems{get; set;}
    public List<Line_Item__c> toLineItems2{get; set;}
    public List<PaymentMethod__c> paymentMethodsProd{get; set;}
    public List<PaymentMethod__c> paymentMethodsServ{get; set;}
    List<PaymentMethod__c> PaymentMethods {get; set;}
    public Boolean trueVal {get; set;}
    public Account installationCompany{get; set;}
    public Contact installationCompanyApplicationContact{get; set;}
    public Contact installationCompanyDesignContact{get; set;}
    public Account nergy{get; set;}
    public Contact nergyApplicationContact{get; set;}
    public String signatureTitle{get; set;}
    public String signatureName{get; set;}
    public String dealerSignatureTitle{get; set;}
    public String dealerSignatureName{get; set;}
    
    public RenderContractController(ApexPages.StandardController controller){
        this.homeService = (Home_Services__c)controller.getRecord();
        toLineItems = new List<Line_Item__c>();
        paymentMethodsProd = new List<PaymentMethod__c>();
        paymentMethodsServ = new List<PaymentMethod__c>();
        PaymentMethods = new List<PaymentMethod__c>();
        List<Line_Item__c> tlines = ListLI(1);
        if(!tlines.isEmpty()){
            toLineItems = tlines;
            for(Line_Item__c li : toLineItems){
                if(li.Total_Sales_Price_p__c == null){
                    li.Total_Sales_Price_p__c = li.Sales_Price__c;
                }
            }
        }
        List<Line_Item__c> tlines2 = ListLI(2);
        if(!tlines2.isEmpty()){
            toLineItems2 = tlines2;
            for(Line_Item__c li : toLineItems2){
                if(li.Total_Sales_Price_p__c == null){
                    li.Total_Sales_Price_p__c = li.Sales_Price__c;
                }
            }
        } 

        paymentMethodsProd = [SELECT AccountNumberChecking__c,BankAccountNumber__c,BankAccountType__c,BankName__c,CardExpirationMonth__c,CardNumber__c,CardType__c,Card_Expiration_Year__c,CSV__c,FinanceCompany__c,FinancedAmount__c,Id,NameOnCard__c,PaymentMethodType__c,RoutingNumber__c,Bank_Account_Name__c, Amount__c FROM PaymentMethod__c where HomeService__c =: this.homeService.id and Payment_Destination__c = 'Products'];
        paymentMethodsServ = [SELECT AccountNumberChecking__c,BankAccountNumber__c,BankAccountType__c,BankName__c,CardExpirationMonth__c,CardNumber__c,CardType__c,Card_Expiration_Year__c,CSV__c,FinanceCompany__c,FinancedAmount__c,Id,NameOnCard__c,PaymentMethodType__c,RoutingNumber__c,Bank_Account_Name__c, Amount__c FROM PaymentMethod__c where HomeService__c =: this.homeService.id and Payment_Destination__c = 'Services'];
        PaymentMethods = [select Id, Name, AccountNumberChecking__c, Amount__c, Bank_Account_Name__c,
        BankAccountNumber__c, BankName__c, BankAccountType__c, CardExpirationMonth__c,  
        Card_Expiration_Year__c, CardNumber__c, CardType__c, CSV__c, 
        FinanceCompany__c, FinancedAmount__c, NameOnCard__c, Payment_Destination__c, 
        Payment_Frequency__c, PaymentMethodType__c, RoutingNumber__c from PaymentMethod__c where HomeService__c =:this.homeService.id and Payment_Destination__c='Products'];
        trueVal = true;
        
        // installationCompany, installationCompanyApplicationContact
        // and installationCompanyDesignContact section
        // Do note that this section assumes only one Application and one Design contact exists at most.

        Home_Services__c hs = [SELECT Installation_Company__c FROM Home_Services__c WHERE Id = :this.homeService.Id LIMIT 1];
        List<Account> installationCompany = null;
        List<Contact> installationCompanyApplicationContact = null;
        List<Contact> installationCompanyDesignContact = null; 
        
        if (hs != null && hs.Installation_Company__c != null) {
			installationCompany = [
                SELECT
                Name,
                AZROC_License__c,
                Doing_Business_As__c,
                Street__c,
                City__c,
                State__c,
                Zip__c
                FROM
                Account
                WHERE
                (
                    Id = :hs.Installation_Company__c
                )
                LIMIT 1
            ];
            
            if (installationCompany != null && installationCompany.size() > 0) {
				installationCompanyApplicationContact = [SELECT Name, Phone, Email FROM Contact WHERE (AccountId = :installationCompany[0].Id AND type__c = 'Application') LIMIT 1];
                installationCompanyDesignContact = [SELECT Name, Phone, Email FROM Contact WHERE (AccountId = :installationCompany[0].Id AND type__c = 'Design') LIMIT 1];
            }
        }
        
        this.installationCompany = (installationCompany != null && installationCompany.size() > 0) ? installationCompany[0] : null;
        this.installationCompanyApplicationContact = (installationCompanyApplicationContact != null && installationCompanyApplicationContact.size() > 0) ? installationCompanyApplicationContact[0] : null;
        this.installationCompanyDesignContact = (installationCompanyDesignContact != null && installationCompanyDesignContact.size() > 0) ? installationCompanyDesignContact[0] : null;
        
        // Fetching the special "Nergy" (Installation-Company) Account and its Application Contact
        
        List<Contact> nergyApplicationContact = null;
        List<Account> nergy = [
            SELECT 
            Name,
            AZROC_License__c,
            Doing_Business_As__c,
            Street__c,
            City__c,
            State__c,
            Zip__c
            FROM
            Account
            WHERE
            (
                Name = 'NERGY LLC'
                AND
                Installation_Company__c= true
            )
            LIMIT 1
        ];
        
        if (nergy != null && nergy.size() > 0) {
            nergyApplicationContact = [SELECT Name, Phone, Email FROM Contact WHERE (AccountId = :nergy[0].Id AND type__c = 'Application') LIMIT 1];
        }
        
        this.nergy = (nergy != null && nergy.size() > 0) ? nergy[0] : null;
        this.nergyApplicationContact = (nergyApplicationContact != null && nergyApplicationContact.size() > 0) ? nergyApplicationContact[0] : null;
    }
    
    public List<Line_Item__c> ListLI(Integer opt){
        if(opt == 1){
            return [select Id, Name,  Home_Service__c, Part_Number__c, Product__c, Product__r.Service__c,Quantity__c, Sales_Price__c, 
                    Total_Cost__c, Total_Sales_Price_p__c, Bill_Start_Date__c, Billing_Frequency__c, Monthly_Investment__c, Bill_SD__c, Service_Check__c
                    from Line_Item__c 
                    where Product__r.Service__c = false and Home_Service__c = :this.homeService.Id];
        }else{
            return [select Id,  Name, Home_Service__c,  Part_Number__c, Product__c,Product__r.Service__c,Quantity__c, Sales_Price__c, Total_Cost__c, 
                    Total_Sales_Price_p__c,Bill_Start_Date__c,Billing_Frequency__c,Monthly_Investment__c,Bill_SD__c, Service_Check__c
                    from Line_Item__c 
                    where Product__r.Service__c = true and Home_Service__c = :this.homeService.Id];
        }
    }
    


   public  String getSignatureLink() {
       
       String link='Not found'; //Default value
       String recordId;
       try{
           recordId=this.installationCompany.Id;
       }catch(Exception e){
           recordId=null;
       }
              
        Map<String, sObject> ret = new Map<String, sObject>();
        ret.put('ContentDocumentLink', null);
        ret.put('ContentDocument', null);
        ret.put('ContentVersion', null);
        
        List<ContentDocumentLink> cdl;
        List<Id> cdlIds = new List<Id>();
        
        List<ContentDocument> cd;
        List<ContentVersion> cv;
        
        if (recordId != null && recordId.trim().length() > 0) {
            cdl = [SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE (LinkedEntityId = :recordId AND IsDeleted = false)];
            
            if (cdl != null && cdl.size() > 0) {
                for (Integer i = 0; i < cdl.size(); i++) {
                    cdlIds.add(cdl[i].ContentDocumentId);
                }
                
                cd = [SELECT LatestPublishedVersionId FROM ContentDocument WHERE (Id IN :cdlIds AND IsDeleted = false AND Title = 'Account Signature') LIMIT 1];
                
                if (cd != null && cd.size() > 0) {
                    for (Integer i = 0; i < cdl.size(); i++) {
                        if (cdl[i].ContentDocumentId == cd[0].Id) {
                            ret.put('ContentDocumentLink', cdl[i]);
                            break;
                        }
                    }
                    
                    ret.put('ContentDocument', cd[0]);
                    
                    cv = [SELECT Dealer_Certification_Title__c, Dealer_Certification_Name__c FROM ContentVersion WHERE (Id = :cd[0].LatestPublishedVersionId AND IsDeleted = false AND IsLatest = true) LIMIT 1];
                    
                    if (cv != null && cv.size() > 0) {
                        ret.put('ContentVersion', cv[0]);
                    }
                }
                signatureName = cv[0].Dealer_Certification_Title__c;
                signatureTitle = cv[0].Dealer_Certification_Name__c;
                link=ret.get('ContentVersion').Id==null?'Not found': '/sfc/servlet.shepherd/version/download/' + ret.get('ContentVersion').Id;
                return link;
            }
        }
        return link;
    }  
    
    
    public String getDealerSignatureLink() {
        String ret = 'Not found';
        
        List<ContentDocumentLink> cdl = [SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE (LinkedEntityId = :this.nergy.Id AND IsDeleted = false)];
        List<Id> cdlIds = new List<Id>();
        
        List<ContentDocument> cd;
        List<ContentVersion> cv;
        
        if (cdl != null && cdl.size() > 0) {
            for (Integer i = 0; i < cdl.size(); i++) {
                cdlIds.add(cdl[i].ContentDocumentId);
            }
            
            cd = [SELECT LatestPublishedVersionId FROM ContentDocument WHERE (Id IN :cdlIds AND IsDeleted = false AND Title = 'Account Signature') LIMIT 1];
            
            if (cd != null && cd.size() > 0) {
                cv = [SELECT Dealer_Certification_Title__c, Dealer_Certification_Name__c FROM ContentVersion WHERE (Id = :cd[0].LatestPublishedVersionId AND IsDeleted = false AND IsLatest = true) LIMIT 1];
                
                if (cv != null && cv.size() > 0) {
                    ret = cv[0].Id == null ? 'Not found' : '/sfc/servlet.shepherd/version/download/' + cv[0].Id;
                    this.dealerSignatureTitle = cv[0].Dealer_Certification_Title__c;
                    this.dealerSignatureName = cv[0].Dealer_Certification_Name__c;
                }
            }
        }
        
        return ret;
    }
    
    public dpcle__Loan_Aplication__c getLoanInfo(){
        List<dpcle__RelatedObject__c> ro=[select Id,dpcle__Loan_Application__c from dpcle__RelatedObject__c where dpcle__Source_Object_Id__c =:this.homeService.Id and dpcle__Loan_Application__c!=null order by createdDate desc limit 1];
        system.debug(ro);
        dpcle__Loan_Aplication__c loanInfo = new dpcle__Loan_Aplication__c();
        if(ro.size()>0){
            loanInfo = [select dpcle__First_Payment_Date__c, dpcle__LA_SaleAmount__c from dpcle__Loan_Aplication__c where Id =:ro[0].dpcle__Loan_Application__c];
        }
        system.debug('LA: '+loanInfo);
        return loanInfo;
    }
    
    public Date getContractEnd(){
        Date todays = Date.today();
        todays = todays.addYears(1);
        
        return todays.addDays(-1);
    }
    
    public List<Finance_Package__c> getFinanceInfo(){
        return [select Monthly_Renewal_PURCHASE__c                                             
                                             from Finance_Package__c where Name=:this.homeService.Id];
    }
}