force-app/main/default/objects/Account/fields/Billing_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_First_Name__c</fullName>
    <label>Billing First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Last_Name__c</fullName>
    <label>Billing Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Phone__c.field-meta.xml
<CustomField>
    <fullName>Billing_Phone__c</fullName>
    <label>Billing Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_City__c</fullName>
    <label>Primary Billing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Street__c</fullName>
    <label>Primary Billing Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Alarm_com_Additional_Services__c.field-meta.xml
<CustomField>
    <fullName>Alarm_com_Additional_Services__c</fullName>
    <label>Alarm.com Additional Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weather to Panel</fullName>
            </value>
            <value>
                <fullName>Severe Weather Alerts</fullName>
            </value>
            <value>
                <fullName>Lock Service</fullName>
            </value>
            <value>
                <fullName>Thermostat Service</fullName>
            </value>
            <value>
                <fullName>Lights Service</fullName>
            </value>
            <value>
                <fullName>Doorbell Camera</fullName>
            </value>
            <value>
                <fullName>Garage Door Control</fullName>
            </value>
            <value>
                <fullName>Lift Master Integration</fullName>
            </value>
            <value>
                <fullName>Two-Way Voice</fullName>
            </value>
            <value>
                <fullName>Pro Video 3-4 Cameras</fullName>
            </value>
            <value>
                <fullName>Pro Video Plus 5-8 Cameras</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Card_Expiration_Year__c.field-meta.xml
<CustomField>
    <fullName>Card_Expiration_Year__c</fullName>
    <label>Card Expiration Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Communication_By__c.field-meta.xml
<CustomField>
    <fullName>Communication_By__c</fullName>
    <label>Communication By</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POTS</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>VoIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Customer_Alarm__c.field-meta.xml
<CustomField>
    <fullName>Customer_Alarm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Alarm</label>
    <referenceTo>DiacoAlarm__Diaco_Customer_Alarm__c</referenceTo>
    <relationshipLabel>Home Services</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Monthly_Security_Services__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Security_Services__c</fullName>
    <label>Monthly Security Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Alarm Signal Verification</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Home Services</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/X2_Story__c.field-meta.xml
<CustomField>
    <fullName>X2_Story__c</fullName>
    <defaultValue>false</defaultValue>
    <label>2 Story</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Line Items (HS)</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Monthly_Investment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Investment__c</fullName>
    <label>Monthly Investment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/AccountNumberChecking__c.field-meta.xml
<CustomField>
    <fullName>AccountNumberChecking__c</fullName>
    <label>Account Number Checking</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/BankAccountType__c.field-meta.xml
<CustomField>
    <fullName>BankAccountType__c</fullName>
    <label>Bank Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BankAccountTypePick</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/CardExpirationMonth__c.field-meta.xml
<CustomField>
    <fullName>CardExpirationMonth__c</fullName>
    <label>Card Expiration Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/CardNumber__c.field-meta.xml
<CustomField>
    <fullName>CardNumber__c</fullName>
    <label>Card Number</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/CardType__c.field-meta.xml
<CustomField>
    <fullName>CardType__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CardTypePick</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/CSV__c.field-meta.xml
<CustomField>
    <fullName>CSV__c</fullName>
    <label>CSV</label>
    <length>4</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/FinanceCompany__c.field-meta.xml
<CustomField>
    <fullName>FinanceCompany__c</fullName>
    <label>Finance Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/FinancedAmount__c.field-meta.xml
<CustomField>
    <fullName>FinancedAmount__c</fullName>
    <label>Financed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/HomeService__c.field-meta.xml
<CustomField>
    <fullName>HomeService__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/NameOnCard__c.field-meta.xml
<CustomField>
    <fullName>NameOnCard__c</fullName>
    <label>Name On Card</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/Payment_Destination__c.field-meta.xml
<CustomField>
    <fullName>Payment_Destination__c</fullName>
    <label>Payment Destination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentMethodType__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodType__c</fullName>
    <label>Payment Method Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentMethodTypePick</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/RoutingNumber__c.field-meta.xml
<CustomField>
    <fullName>RoutingNumber__c</fullName>
    <label>Routing Number</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product HS</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products HS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Home_Service_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/diacoRenderContractController.cls
public class diacoRenderContractController {
    private final Home_Services__c hs;
    public List<PaymentMethod__c> paymentMethodsProd{get; set;}
    public List<PaymentMethod__c> paymentMethodsServ{get; set;}
    public list<String> communicationByList{get;set;}
    public list<String> eventGroupsToForwardList{get;set;}
    public list<String> monthlySecurityServicesList {get;set;}
    public list<String> alarmcomAdditionalServicesList {get;set;}
    public List<Line_Item__c> productList {get;set;}
    public List<Line_Item__c> ServiceList {get;set;}
    public boolean existWarranty {get;set;}
    public decimal monitoring {get;set;}
    public Date notLaterThanMidnightOf {get; set;}
    public boolean isService {get; set;}
    public String CSIDNumber {get; set;}
    public Map<String, String> AddOnFeatures {get; set;}

    
    public diacoRenderContractController(ApexPages.StandardController stdController){
        
        this.hs = (Home_Services__c)stdController.getRecord();
        
        if(this.hs.Id !=null){
            notLaterThanMidnightOf =AddBusinessDays(system.today(),3);
            paymentMethodsProd = paymentMethodList(this.hs.Id,'Products');
            paymentMethodsServ = paymentMethodList(this.hs.Id,'Services');
            productList = getLineItems(this.hs.Id,false);
            ServiceList = getLineItems(this.hs.Id,true);
            monitoring = getMonitoringInvestment(ServiceList);
            existWarranty = verifyWarranty(ServiceList);
            Home_Services__c homeService = [select Customer_Alarm__c from Home_Services__c where id = :hs.Id];
            if (String.isNotblank(homeService.Customer_Alarm__c)) {
                List<DiacoAlarm__DiacoSiteAvantguard__c>  diacoSitesAvantguard =
                [select id, DiacoAlarm__DiacoTransmitterCode__c, DiacoAlarm__Diaco_Customer_Alarm__r.DiacoAlarm__DiacoAddOnFeatures__c from DiacoAlarm__DiacoSiteAvantguard__c where
                        DiacoAlarm__Diaco_Customer_Alarm__c =:homeService.Customer_Alarm__c];
                if (!diacoSitesAvantguard.isEmpty()) {
                    CSIDNumber = diacoSitesAvantguard.get(0).DiacoAlarm__DiacoTransmitterCode__c;
                    AddOnFeatures = getValuesAndLabels(DiacoAlarm__Diaco_Customer_Alarm__c.DiacoAlarm__DiacoAddOnFeatures__c,
                            diacoSitesAvantguard.get(0).DiacoAlarm__Diaco_Customer_Alarm__r.DiacoAlarm__DiacoAddOnFeatures__c.split(';'));
                }
            }
            getHomeServiceInfo(this.hs.Id);     
        }



    }

   

    public List<PaymentMethod__c> paymentMethodList(Id homeServiceId,String paymentDestination){

        List<PaymentMethod__c> paymentMethods = [SELECT AccountNumberChecking__c,BankAccountNumber__c,
        BankAccountType__c,BankName__c,CardExpirationMonth__c,
        CardNumber__c,CardType__c,Card_Expiration_Year__c,
        CSV__c,FinanceCompany__c,FinancedAmount__c,Id,NameOnCard__c,
        PaymentMethodType__c,RoutingNumber__c,Bank_Account_Name__c 
        FROM PaymentMethod__c where HomeService__c =: homeServiceId and Payment_Destination__c =: paymentDestination];

        //return paymentMethodsProd;
        return paymentMethods;

    }

    public Decimal getMonitoringInvestment(List<Line_Item__c> ServiceList){

        decimal monitoringInvestment = 0.0;
        for (Line_Item__c service : ServiceList) {
            if (service.Name == 'Alarm Monitoring') {
                monitoringInvestment = service.Monthly_Investment__c;
                break;
            }       
        }

        return monitoringInvestment;
    }

    public boolean verifyWarranty(List<Line_Item__c> ServiceList){
    
        boolean existWarranty = false;
        for (Line_Item__c service : ServiceList) {
            if (service.Name == 'Warranty') {
                existWarranty = true;
                break;
            }       
        }

        return existWarranty;
    }

    public List<PaymentMethod__c> getPMChecking(){
        List<PaymentMethod__c> pm  = new List<PaymentMethod__c>();
        System.debug('Payment Services');
        System.debug(this.hs.Id);
        for(PaymentMethod__c item: paymentMethodsProd){
            if(item.PaymentMethodType__c =='Checking'){
                pm.add(item);
                break;
            }
        }
        return pm;
    }

    public list<DiacoAlarm__DiacoSiteContact__c> getContacts() {
        return [SELECT id,
                DiacoAlarm__DiacoFirstName__c,
                DiacoAlarm__DiacoLastName__c,
                DiacoAlarm__DiacoPhone__c 
                FROM DiacoAlarm__DiacoSiteContact__c 
                WHERE  DiacoAlarm__DiacoCustomerAlarm__r.Home_Service__c =:this.hs.Id LIMIT 4];        
    }

    public void getHomeServiceInfo(Id homeServiceId){
        
        Home_Services__c hsElement = [select Id,X2_Story__c,
                                      Customer_Alarm__c, Communication_By__c, 
                                      Monthly_Security_Services__c, Alarm_com_Additional_Services__c,
                                      Customer_Alarm__r.DiacoAlarm__DiacoCsEventGroupsToForward__c
                                      from Home_Services__c where Id=:this.hs.Id];
        
        list<String> communicationValue = new list<String>();
        
        if(hsElement.Communication_By__c != null){
            communicationByList = hsElement.Communication_By__c.split(';');
        }
        
        if(hsElement.Monthly_Security_Services__c != null){
            monthlySecurityServicesList = hsElement.Monthly_Security_Services__c.split(';');
            isService = hsElement.Monthly_Security_Services__c.contains('Service');

        }
        
        if(AddOnFeatures != null && !AddOnFeatures.isEmpty()){

            alarmcomAdditionalServicesList = new List<String> (getSelectedAddons()); //hsElement.Alarm_com_Additional_Services__c.split(';');
        }
        
        if(hsElement.Customer_Alarm__r.DiacoAlarm__DiacoCsEventGroupsToForward__c != null){
            eventGroupsToForwardList = hsElement.Customer_Alarm__r.DiacoAlarm__DiacoCsEventGroupsToForward__c.split(';');
        }  
    }

    public Set<String> getSelectedAddons() {
        Set<String> selectedAddons = new Set<String>();

        Map<String, String> posiblesValues = getValuesAndLabels(Home_Services__c.Alarm_com_Additional_Services__c, null);
        if (this.AddOnFeatures != null) {
            for (String addon: this.AddOnFeatures.keySet()) {
                if (posiblesValues.containsKey(addon)) {
                    selectedAddons.add(addon);
                }
                else if ('Locks' == addon) {
                    selectedAddons.add('Lock Service');
                }
                else if (addon.contains('Thermostat')) {
                    selectedAddons.add('Thermostat Service');
                }
                else if (addon.contains('Lights')) {
                    selectedAddons.add('Lights Service');
                }
                else if (addon.contains('Doorbell Camera')) {
                    selectedAddons.add('Doorbell Camera');
                }

                else if (addon.contains('Two-Way Voice')) {
                    selectedAddons.add('Two-Way Voice');
                }

                else if (addon == 'Pro Video') {
                    selectedAddons.add('Pro Video 3-4 Cameras');
                }

                else if (addon == 'Pro Video Plus') {
                    selectedAddons.add('Pro Video Plus 5-8 Cameras');
                }
            }
        }
        return selectedAddons;
    }

    /**
    * Method responsible to get the values for a picklist.
    *
    * @param picklistToGet schema the picklist that wish to get.
    *
    * @return values for the picklist.
    */
    public static Map<String, String> getValuesAndLabels(SObjectField picklistToGet, List<String> selectedAddons1) {
        Map<String,String> optionsValues = new Map<String, String>();
        Set<String> selectedAddons = null;
        if (selectedAddons1 != null) {
            selectedAddons = new Set<String> (selectedAddons1);
        }
        for( Schema.PicklistEntry f :  picklistToGet.getDescribe().getPicklistValues())
        {
            if (selectedAddons != null) {
                if (selectedAddons.contains(f.getValue())) {
                    optionsValues.put(f.getLabel(), f.getValue());
                }
            }
            else {
                optionsValues.put(f.getLabel(), f.getValue());
            }
        }
        return optionsValues;
    }
    public Home_Services__c getHs(){
        return [select Account__r.Billing_First_Name__c, Account__r.Billing_Last_Name__c,
        Account__r.Primary_Billing_Street__c, Account__r.Billing_Phone__c,
        Account__r.Primary_Billing_City__c, Account__r.Primary_Billing_State__c,
        Account__r.Primary_Billing_Zip_Code__c, Account__r.Billing_Email__c, Account__r.Number_of_Stories__c
        from Home_Services__c where Id=:this.hs.Id];
    }

    public List<Line_Item__c> getLineItems(Id homeServiceId,boolean areServices){
        
        List<Line_Item__c> LineItemList = new List<Line_Item__c>();
        
        if(homeServiceId != null){
            
            LineItemList = [select Id,Name,Quantity__c,Sales_Price__c,Part_Number__c,
                        Total_Price__c,Home_Service__c,Billing_Frequency__c, Monthly_Investment__c 
                        from Line_Item__c where Home_Service__c =:homeServiceId and Product__r.Service__c =: areServices];
            
            if(!areServices){
                Integer element = 10 - LineItemList.size();
                System.debug(element);
                if(LineItemList.size() < 10){
                    for (Integer i = 0, j = 0; i < element; i++) {
                        LineItemList.add(new Line_Item__c());
                    }
                }  
            }
        }
        System.debug('--------------');
        System.debug(LineItemList.size());
        System.debug('--------------');
        return LineItemList;
    }
    
   public static Boolean IsWeekendDay(Date dateParam)
   {
      boolean result = false;
      system.debug('dateParam = '+dateParam); 
      //Recover the day of the week
      Date startOfWeek   = dateParam.toStartOfWeek();
      system.debug('startOfWeek = '+startOfWeek);
      Integer dayOfWeek  = dateParam.day() - startOfWeek.day();
      system.debug('dayOfWeek = '+dayOfWeek);   
      result = dayOfWeek == 0 || dayOfWeek == 6 ? true : false;
      system.debug('result = '+result); 
      return result;
   } 
   
   
   public static Date AddBusinessDays(Date StartDate, integer BusinessDaysToAdd )
   {
      //Add or decrease in BusinessDaysToAdd days 
      Date finalDate = StartDate;
      system.debug('finaldate = '+finalDate);
      integer direction = BusinessDaysToAdd < 0 ? -1 : 1;
      system.debug('direction = '+direction);
       while(BusinessDaysToAdd != 0)
       {
           finalDate = finalDate.AddDays(direction);
           system.debug('BusinessDaysToAdd = '+BusinessDaysToAdd);            
           system.debug('finaldate = '+finalDate);
           if (!isWeekendDay(finalDate))
           {
               BusinessDaysToAdd -= direction;
               
           }
       }

       return finalDate;
   }
 
    public Date getExpirationDate(){
        Date today=Date.today();
        Date expirationDate=today.addYears(1);
        return expirationDate.addDays(-1);
    }
    
     public List<String> getPickListValuesIntoList(){
       List<String> pickListValuesList= new List<String>();

		Schema.DescribeFieldResult fieldResult = DiacoAlarm__Diaco_Customer_Alarm__c.DiacoAlarm__DiacoPackageId__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}     
		return pickListValuesList;
    }
    
     public List<String> getPickListValuesIntoListCommunication(){
       List<String> pickListValuesList= new List<String>();

		Schema.DescribeFieldResult fieldResult = Home_Services__c.Communication_By__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}     
		return pickListValuesList;
    }
    
    public list<String> getPickListValuesMonthlySecurity(){
        
        List<String> pickListValuesList= new List<String>();
        
        Schema.DescribeFieldResult fieldResult = Home_Services__c.Monthly_Security_Services__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }     
        return pickListValuesList;
    }
    
       public list<String> getPickListValueAlarmcomAdditionalServices(){
        
        List<String> pickListValuesList= new List<String>();
        
        Schema.DescribeFieldResult fieldResult = Home_Services__c.Alarm_com_Additional_Services__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }     
        return pickListValuesList;
    }
    
     public list<String> getPickListValueAlarmCommunication(){
        
        List<String> pickListValuesList= new List<String>();
        
        Schema.DescribeFieldResult fieldResult = DiacoAlarm__Diaco_Customer_Alarm__c.DiacoAlarm__DiacoCsEventGroupsToForward__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }     
        return pickListValuesList;
    }   
    
    public Decimal getWarrantyAmount(){
        Integer size = ServiceList.size();
        Decimal response = 0;
        for(Integer i = 0; i<size; i++){
            if(ServiceList[i].Name == 'Warranty'){
                response+=ServiceList[i].Monthly_Investment__c;
            }
        }
        System.debug('####RESPONSE####');
        System.debug(response);
        return response;
    }
}