force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Recording_Date__c.field-meta.xml
<CustomField>
    <fullName>Recording_Date__c</fullName>
    <description>The date that the house sale was recorded.</description>
    <label>Recording Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sale_Date__c.field-meta.xml
<CustomField>
    <fullName>Sale_Date__c</fullName>
    <label>Sale Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Hung_Status__c.field-meta.xml
<CustomField>
    <fullName>Hung_Status__c</fullName>
    <label>Hung Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrived</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hung</fullName>
            </value>
            <value>
                <fullName>COMPLETED GATED</fullName>
            </value>
            <value>
                <fullName>Gated</fullName>
            </value>
            <value>
                <fullName>Cant Find</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Invld</fullName>
            </value>
            <value>
                <fullName>Remove: Management</fullName>
            </value>
            <value>
                <fullName>Too Far</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Wrong House Number</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Remove: Gated</fullName>
            </value>
            <value>
                <fullName>Remove: Aging</fullName>
            </value>
            <value>
                <fullName>Sent To Cheetah</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Gio - In Process</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Access Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/IsRecent__c.field-meta.xml
<CustomField>
    <fullName>IsRecent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This filed used to identify the recently created Delivery Object record.</description>
    <label>IsRecent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hung_Status__c/Hung_Status__c.object-meta.xml
<CustomObject>
    <description>This object will different Hung Status details for the Products</description>
    <label>Hung Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Hung Status No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hung Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateDevliveryobject.cls
global class UpdateDevliveryobject implements Database.Batchable<sObject> {    
/*************************************************************************************************************************************************************************************************************************************************************************************
* Class Name : UpdateDevliveryobject
* Created By : Priyanka Shanmugam
* Created Date : 3/25/2016
* Description : This Batch class will get executed daily and create a Delivery Object record, if the account don't have delivery already and meet specified values in the delivery parameter.
***************************************************************************************************************************************************************************************************************************************************************************************/
    global string query;    
    public UpdateDevliveryobject(){
        query = 'SELECT Id FROM Account WHERE isPersonAccount = true AND Branch__c != null AND (Sale_Date__c != null OR Recording_Date__c != null) AND Respond_Date__c = null AND createddate >= 2016-02-01T00:00:00.000Z';
    }
    
    // Get the list of accounts that has no delivery records associated to it.
    global Database.QueryLocator start(Database.BatchableContext BC) {               
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> accountList) {
        Map<Id,List<Delivery_Object__c>> accountDeliveryObjectCount = new Map<Id,List<Delivery_Object__c>>();
        List<Delivery_Object__c> deliveriesObjects = new List<Delivery_Object__c>();
        deliveriesObjects = [SELECT ID, Person_Account__c,name FROM Delivery_Object__c WHERE isRecent__c = false AND  hung_status__c != 'Send to Cheetah' AND hung_status__c != 'Canceled' AND Person_Account__c IN : accountList];
        for(Delivery_Object__c deliverObject : deliveriesObjects){
            if(accountDeliveryObjectCount.containsKey(deliverObject.Person_Account__c)){
                List<Delivery_Object__c> tempDeliverObject = accountDeliveryObjectCount.get(deliverObject.Person_Account__c);
                tempDeliverObject.add(deliverObject);
                accountDeliveryObjectCount.put(deliverObject.Person_Account__c,tempDeliverObject);
            }
            else{
                accountDeliveryObjectCount.put(deliverObject.Person_Account__c, new List<Delivery_Object__c>{deliverObject} );
            }  
        }
        for(Delivery_Object__c deliverObject : deliveriesObjects){
            
            if(deliverObject.name == '1' && accountDeliveryObjectCount.containskey(deliverObject.Person_Account__c) && accountDeliveryObjectCount.get(deliverObject.Person_Account__c).size() == 1){
            	deliverObject.IsRecent__c = true;    
            }
            if(deliverObject.name == '2' && accountDeliveryObjectCount.containskey(deliverObject.Person_Account__c) && accountDeliveryObjectCount.get(deliverObject.Person_Account__c).size() == 2){
            	deliverObject.IsRecent__c = true;    
            }
        
        }
        if(deliveriesObjects.size() > 0){
            try{
                update deliveriesObjects;
                
            }Catch(Exception ex){
                
            }
        }    
    }
    global void finish(Database.BatchableContext BC){
       
    }
}