force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DID__c/DID__c.object-meta.xml
<CustomObject>
    <label>DID</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}:{00}</displayFormat>
        <label>DID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DID__c/fields/Destination_Number__c.field-meta.xml
<CustomField>
    <fullName>Destination_Number__c</fullName>
    <description>10 digit phone number without the country code to where the phone calls will be routed to.</description>
    <inlineHelpText>10 digit phone number without the country code to where the phone calls will be routed to.</inlineHelpText>
    <label>Destination Number</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DID__c/fields/DID_Type__c.field-meta.xml
<CustomField>
    <fullName>DID_Type__c</fullName>
    <label>DID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>nuHome Door Tag Script</fullName>
            </value>
            <value>
                <fullName>nuHome nuCard SUB</fullName>
            </value>
            <value>
                <fullName>nuHome SPEC CPL</fullName>
            </value>
            <value>
                <fullName>Special Routing</fullName>
            </value>
            <value>
                <fullName>nuHome nuCard SPEC</fullName>
            </value>
            <value>
                <fullName>nuHome OB Campaign</fullName>
            </value>
            <value>
                <fullName>nuHome nuCard CPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DID__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>DIDs</relationshipLabel>
    <relationshipName>DIDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DID__c/fields/POC__c.field-meta.xml
<CustomField>
    <fullName>POC__c</fullName>
    <description>10 digit DID or ANI without the country code</description>
    <inlineHelpText>10 digit DID or ANI without the country code</inlineHelpText>
    <label>POC</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>TEXT ( Opportunity__r.Branch__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Destination_Number__c.field-meta.xml
<CustomField>
    <fullName>Destination_Number__c</fullName>
    <label>Destination Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/DID__c.field-meta.xml
<CustomField>
    <fullName>DID__c</fullName>
    <label>DID</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/NuCard_Industry__c.field-meta.xml
<CustomField>
    <fullName>NuCard_Industry__c</fullName>
    <formula>TEXT ( Opportunity__r.NuCard_Industry__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NuCard Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
            <value>
                <fullName>CO-Colorado_Springs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DID__c.field-meta.xml
<CustomField>
    <fullName>DID__c</fullName>
    <label>DID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NuCard_Industry__c.field-meta.xml
<CustomField>
    <fullName>NuCard_Industry__c</fullName>
    <label>NuCard Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>Air Duct Cleaning</fullName>
            </value>
            <value>
                <fullName>Appliance Repair</fullName>
            </value>
            <value>
                <fullName>Appliance Store</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Auto Detailing</fullName>
            </value>
            <value>
                <fullName>Auto Glass</fullName>
            </value>
            <value>
                <fullName>Auto Repair</fullName>
            </value>
            <value>
                <fullName>Awnings</fullName>
            </value>
            <value>
                <fullName>Bathroom Remodeling</fullName>
            </value>
            <value>
                <fullName>Bedding/Linens/Drapes</fullName>
            </value>
            <value>
                <fullName>Billiard</fullName>
            </value>
            <value>
                <fullName>Blinds/Shutters</fullName>
            </value>
            <value>
                <fullName>Cabinetry / Carpentry</fullName>
            </value>
            <value>
                <fullName>Cable/Satellite TV/Internet</fullName>
            </value>
            <value>
                <fullName>Carpet/Tile Cleaning</fullName>
            </value>
            <value>
                <fullName>Chimney Sweep</fullName>
            </value>
            <value>
                <fullName>Chiropractor</fullName>
            </value>
            <value>
                <fullName>Closet Organization</fullName>
            </value>
            <value>
                <fullName>Closet Remodel</fullName>
            </value>
            <value>
                <fullName>Computer Repair</fullName>
            </value>
            <value>
                <fullName>Computer Setup</fullName>
            </value>
            <value>
                <fullName>Custom BBQ</fullName>
            </value>
            <value>
                <fullName>Day/Med Spas</fullName>
            </value>
            <value>
                <fullName>Day Care Provider/Pre School</fullName>
            </value>
            <value>
                <fullName>Deck/Patio - Build</fullName>
            </value>
            <value>
                <fullName>Dentist</fullName>
            </value>
            <value>
                <fullName>Disaster Recovery</fullName>
            </value>
            <value>
                <fullName>Dog Grooming/Boarding</fullName>
            </value>
            <value>
                <fullName>Driveways/Repaving</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/updateDIDName_Test.cls
@isTest
public class updateDIDName_Test{
    
    public static Account createAccount()
    {
        Account testAccount = new Account();
        testAccount.Name = 'Test Account';
        testAccount.Type = 'Customer';
        testAccount.Branch__c = 'AZ-Tucson';
        testAccount.Industry = 'Awnings';
        testAccount.phone = '9090909090';
        
        return testAccount;
    }
    
    public static Opportunity createOpportunity()
    {
        Account testAccount = createAccount();
        insert testAccount;
        
        opportunity testOpportunity = new opportunity();
        testOpportunity.Name = 'Test Opportunity';
        testOpportunity.AccountId = testAccount.Id;
        testOpportunity.Type = 'Trade';
        testOpportunity.StageName = 'Leagal Review';
        testOpportunity.CloseDate = system.today().addDays(10);
        testOpportunity.NuCard_Industry__c = 'Awnings';
        testOpportunity.Branch__c = 'AZ-Tucson';
        
        return testOpportunity;
    }
    
   public static DID__c createDID()
    {
        opportunity testOpp = createOpportunity();
        insert testOpp;
        
        DID__c testDID = new DID__c();
        testDID.POC__c = '9898989898';
        testDID.Destination_Number__c = '9090898978';
        testDID.Opportunity__c = testOpp.Id;
        testDID.DID_Type__c = 'Gift Card';
        
        return testDID;
    }
    
    public static testMethod void insertInventoryWithDID(){
        DID__c testDID = createDID();
        insert testDID;
        
        Inventory__c testInventory = new Inventory__c();
        testInventory.DID__c = '9898989898';
        insert testInventory;
    }
    
     public static testMethod void insertInventoryWithoutDID(){
        DID__c testDID = createDID();
        insert testDID;
        
        Inventory__c testInventory = new Inventory__c();
        testInventory.DID__c = '';
        insert testInventory;
    }
    
     public static testMethod void coverCheckInventoryforNewRecord(){
        
        Inventory__c testInventory = new Inventory__c();
        testInventory.DID__c = '(111) 111-1111';
        insert testInventory;
         System.debug('##testInventory'+testInventory);
        
        DID__c testDID = createDID();
         insert testDID;
        
        testDID.POC__c ='1111111111';
        update testDID;
    }

 /*   public static testMethod void coverCheckInventoryforExistingRecord(){
        
        DID__c testDID = createDID();
        insert testDID;
        
        Inventory__c testInventory = new Inventory__c();
        testInventory.DID__c = '(989) 898-9898'; 
        insert testInventory;
        
        testDID.POC__c ='1111111111';
        update testDID;
    }*/

}