force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Web_Form__c.field-meta.xml
<CustomField>
    <fullName>Web_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Web Form</label>
    <referenceTo>webForm__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Carrier_ID__c.field-meta.xml
<CustomField>
    <fullName>Carrier_ID__c</fullName>
    <description>It holds the career code for the branch.This code will be used to send to the outbound call of the delivery object</description>
    <label>Carrier ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Region_MD__c.field-meta.xml
<CustomField>
    <fullName>Region_MD__c</fullName>
    <label>Region MD</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>To keep the county name. It is not unique. The same county name can exist for different states.</description>
    <label>County</label>
    <nameField>
        <displayFormat>CN-{000}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/County_Name__c.field-meta.xml
<CustomField>
    <fullName>County_Name__c</fullName>
    <description>It holds counties name.</description>
    <label>County Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/webForm__c/webForm__c.object-meta.xml
<CustomObject>
    <label>Web Form</label>
    <nameField>
        <label>webForm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipCode__c/ZipCode__c.object-meta.xml
<CustomObject>
    <description>It contains all zip codes for the corresponding branches.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipCode__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Zip Codes</relationshipLabel>
    <relationshipName>Zip_code</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Zip Codes</relationshipLabel>
    <relationshipName>Zip_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>Zip Codes</relationshipLabel>
    <relationshipName>Zip_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Zip Codes</relationshipLabel>
    <relationshipName>Zip_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZipCode</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiacoAccountCountyTest.cls
/**
 * Diaco LLC
 * @author 			Giovanni Ulloque Olivares href = <Gulloque@diaco.us>
 * Project:			County on Account
 * Class            DiacoAccountCounty        
 * Test:            DiacoAccountCountyTest
 * Description:		Relate a County record with the Account.
 * Changes (Version)
 * ______________________________________________________________________________________________
 *			No.		Date			Author					Description
 *			____	__________		__________________  	_____________________________________
 * @version	1.0		24/06/2020		Giovanni Ulloque (GU)	Initial implementation of the class.
 **/

@IsTest
public class DiacoAccountCountyTest {
 
        @istest static void testAll(){

            List<Route__c> route = new List<Route__c>();
            route.add(new Route__c(
                Name = 'Route 1'
            ));
            route.add(new Route__c(
                Name = 'unknown'
            ));
            insert route;

            Region__c region = new Region__c();
            region.Name      = 'Test';
            insert region;

            Branch__c branch     = new Branch__c();
            branch.Name          = 'Test';
            branch.Region_MD__c  = region.Id;
            branch.Carrier_ID__c = 'test';
            insert branch;

            List<ZipCode__c> zips = new List<ZipCode__c>();
            zips.add( new ZipCode__c(
                name      = '1111',
                Route__c  = route[0].Id,
                Branch__c = branch.Id
            ));

            zips.add( new ZipCode__c(
                name      = 'unknown',
                Route__c  = route[1].Id,
                Branch__c = branch.Id
            ));

            insert zips;

            City__c ci = new City__c();
                ci.Name       = 'City';
                insert ci;
            
            City__c ci2 = new City__c();
                ci2.Name       = 'Unknown';
                insert ci2;

            County__c c = new County__c();
                c.County_Name__c = 'City';
                insert c;
            
            County__c c2 = new County__c();
                c2.County_Name__c = 'Unknown';
                insert c2;

            webForm__c w = new webForm__c();
                w.Name = 'Unknown';
                insert w;
       
            Account acc = new Account();
                acc.FirstName = 'Test acc';
                acc.LastName  = 'last test';
                acc.City__c   =  'City';
                acc.County__c = 'test';
                acc.Web_Form__c = w.id;
                acc.Route__c = route[0].id;
                insert acc;
            
            Account acc2 = new Account();
                acc2.FirstName = 'Test acc';
                acc2.LastName  = 'last test';
                acc2.City__c   =  'Test';
                acc2.County__c = 'test';
                acc.Web_Form__c = w.id;
               acc.Route__c = route[0].id;
                insert acc2;
            
            Account acc3 = new Account();
                acc3.FirstName = 'Test acc';
                acc3.LastName  = 'last test';
                acc3.City__c   =  'Test2';
                acc3.County__c = 'test';
                acc.Web_Form__c = w.id;
                acc.Route__c = route[0].id;
                insert acc3;
            
            Account acc5 = new Account();
                acc5.FirstName = 'Test acc';
                acc5.LastName  = 'last test';
                acc5.City__c   = 'test3';
                acc5.County__c = 'test';
                acc.Web_Form__c = w.id;
                acc.Route__c = route[0].id;
                insert acc5;
            
       

            test.startTest();
            
        /*  List<String> params = new List<String> ();
            params.add(acc.Id);
            params.add(acc2.Id);
            params.add(acc3.Id);
            params.add(acc5.Id);
                
            DiacoAccountCounty.accountWithCounty(params); 
        */
            DiacoAccountCounty.param param = new DiacoAccountCounty.param();
            param.countyId  = acc.County__c;
            param.accountId = acc.id;


            DiacoAccountCounty.paramList(new List<DiacoAccountCounty.param> {param});

            List<Account> accs = new List<Account> ();
            accs.add(acc);
            accs.add(acc2);
            accs.add(acc3);
            accs.add(acc5);
            
            List<County__c> counties = new List<County__c> ();
            counties.add(c);
            counties.add(c2);
            
            DiacoAccountCounty.currentAccount(accs, counties, c2.Id);
        
            test.stopTest();


        }
   	   
}