force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MSA__c.field-meta.xml
<CustomField>
    <fullName>MSA__c</fullName>
    <label>MSA</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Austin-Round Rock-San Marcos  TX</fullName>
            </value>
            <value>
                <fullName>Bakersfield  Ca</fullName>
            </value>
            <value>
                <fullName>Dallas-Fort Worth-Arlington TX</fullName>
            </value>
            <value>
                <fullName>Houston-Sugar Land-Baytown  TX</fullName>
            </value>
            <value>
                <fullName>Killeen-Temple TX</fullName>
            </value>
            <value>
                <fullName>Los Angeles--Riverside--Orange County  Ca</fullName>
            </value>
            <value>
                <fullName>Phoenix-Mesa-Glendale AZ</fullName>
            </value>
            <value>
                <fullName>Provo-Orem Ut</fullName>
            </value>
            <value>
                <fullName>Salt Lake City-Ogden  Ut</fullName>
            </value>
            <value>
                <fullName>San Antonio-New Braunfels  TX</fullName>
            </value>
            <value>
                <fullName>San Diego-Carlsbad-San Marcos  Ca</fullName>
            </value>
            <value>
                <fullName>Tucson  AZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Shipping_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_Zip_Code__c</fullName>
    <label>Primary Shipping Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <label>Region Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/MSA__c.field-meta.xml
<CustomField>
    <fullName>MSA__c</fullName>
    <label>MSA</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
            <value>
                <fullName>CO-Colorado_Springs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Driver_City__c.field-meta.xml
<CustomField>
    <fullName>Driver_City__c</fullName>
    <label>Driver City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Driver_Street__c.field-meta.xml
<CustomField>
    <fullName>Driver_Street__c</fullName>
    <label>Driver Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <label>ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OB_Campaign_Member__c/OB_Campaign_Member__c.object-meta.xml
<CustomObject>
    <label>OB Campaign Member</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>OB Campaign Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OB Campaign Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OB_Campaign_Member__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>User_Address__r.Address__r.Branch__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fBranch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OB_Campaign_Member__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>AccountName__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fFirst Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OB_Campaign_Member__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <formula>Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OB_Campaign_Member__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>AccountName__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fLast Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OB_Campaign_Member__c/fields/MSA__c.field-meta.xml
<CustomField>
    <fullName>MSA__c</fullName>
    <formula>Text(User_Address__r.Address__r.MSA__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fMSA</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OB_Campaign_Member__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>BLANKVALUE(AccountName__r.Phone, AccountName__r.PersonContact.MobilePhone)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fPhone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCodeMatch__c/ZipCodeMatch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>On person account when Zip code is selected auto populate the Carrier code, region code and MSA.</description>
    <label>Zip Code Match</label>
</CustomObject>

force-app/main/default/objects/ZipCodeMatch__c/fields/Carrier_Code__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Code__c</fullName>
    <label>Carrier Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCodeMatch__c/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <label>Region Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GlobalTest.cls
@isTest
private  class GlobalTest {
    static testMethod void testMethod1(){
        ZipCodeMatch__c cs = new ZipCodeMatch__c();
        cs.Carrier_Code__c = 'San Antonio-TX';
        cs.name = '72832';
        cs.MSA__c = 'San Antonio-New Braunfels TX';
        cs.Region_Code__c = 'sc1';
        cs.Zip_Code__c = '72832';
        try{
            insert cs;
        }
        catch(exception e){
            system.assert(false,'Failed to insert the custom setting record. '+e.getMessage());
        }
        //
        String recTypeId = [Select id from recordType where developerName='PersonAccount' limit 1].Id;
        Account acc = new Account();
        acc.lastname = 'TestAccount';
        acc.recordTypeId = recTypeId;
        acc.Phone = '1222222211';
        acc.Primary_Shipping_Zip_Code__c = '72832';
        try{
            insert acc;
        }
        catch(exception e){
            system.assert(false,'Failed to insert the Account record. '+e.getMessage());
        }
        accountZipCodeMapper_Batch obj = new accountZipCodeMapper_Batch();
        database.executeBatch(obj);
    } 
    static testMethod void testMethod2(){
        GlobalTriggerController.DeliveryObjectTriggerVariable = true;
        Driver__c dr = new Driver__c();
        dr.name = 'Invalid Driver';
        dr.First_Name__c = 'Test';
        dr.Last_Name__c = 'Test';
        dr.ID__c = 'Invalid Driver';
        dr.Phone__c = '8188003959';
        dr.Branch__c = 'Austin';
        dr.Driver_Street__c = 'TesteStreet';
        dr.Driver_City__c = 'testCity';
        dr.Driver_State__c = 'CA';
        dr.Driver_Country__c = 'US';
        dr.Driver_Zip_Code__c = '99999';
        try{
            insert dr;
        }
        catch(exception e){
            system.assert(false,'failed to insert the test driver.');
        }
        String recTypeId = [Select id from recordType where developerName='PersonAccount' limit 1].Id;
        Account acc = new Account();
        acc.lastname = 'TestAccount';
        acc.recordTypeId = recTypeId;
        acc.Phone = '1234567892';
        acc.Primary_Shipping_Zip_Code__c = '72832';
        try{
            insert acc;
        }
        catch(exception e){
            system.assert(false,'Failed to insert the Account record. '+e.getMessage());
        }
        Gift_Card_Orders__c gc = new Gift_Card_Orders__c();
        gc.name = '222222222';
        try{
            insert gc;
        }
        catch(exception e){
            system.assert(false,'Failed to insert the gift card record. '+e.getMessage());
        }
        Driver__c driver = new Driver__c();
        driver.name = 'testDriver';
        driver.First_Name__c = 'testFirstName';
        driver.Last_Name__c = 'testLastName';
        driver.Phone__c = '8888888888';
        driver.ID__c = 'abc12345';
        driver.Driver_Street__c = 'testStreet';
        driver.Driver_City__c = 'SanJose';
        driver.Driver_State__c = 'CA';
        driver.Driver_Country__c = 'US';
        driver.Driver_Zip_Code__c = '94087';
        try{
            insert driver;
        }
        catch(exception e){
            system.assert(false,'Failed to insert the  driver record. '+e.getMessage());
        }
        Delivery_Object__c delObj = new Delivery_Object__c();
        delObj.name='testDO';
        delObj.Parent_Gift_Card_Order__c = gc.Id;
        delObj.Driver__c = driver.Id;
        delObj.Person_Account__c = acc.Id;
        delObj.Scan_Code__c = '2222222222';
        try{
            insert delObj;
        }
        catch(exception e){
            system.assert(false,'Failed to insert the delivery object record. '+e.getMessage());
        }
        acc.phone = '8188003000';
        acc.personmobilephone = '8188003001';
        try{
            update acc;
        }
        catch(exception e){
            system.assert(false,'Failed to insert the Account record. '+e.getMessage());
        }
    }
    
   /* static testMethod void testMethod3(){
        OB_Campaign_Member__c obcm = new OB_Campaign_Member__c();
        obcm.AccountName__c = '00121000003wXde';
        obcm.OB_Campaign__c = 'a2a210000004LII';
    try{
            insert obcm;
        }
        catch(exception e){
            system.assert(false,'Failed to insert the OB Campaign Member record. '+e.getMessage());
        }
        } */
}