force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_City__c</fullName>
    <label>Primary Billing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Country__c</fullName>
    <label>Primary Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
                <default>true</default>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_State__c</fullName>
    <label>Primary Billing State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Street__c</fullName>
    <label>Primary Billing Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Zip_Code__c</fullName>
    <label>Primary Billing Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocusignCredentials__c/DocusignCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>DocusignCredentials</label>
</CustomObject>

force-app/main/default/objects/DocusignCredentials__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocusignCredentials__c/fields/IntegratorKey__c.field-meta.xml
<CustomField>
    <fullName>IntegratorKey__c</fullName>
    <label>IntegratorKey</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocusignCredentials__c/fields/TemplateID__c.field-meta.xml
<CustomField>
    <fullName>TemplateID__c</fullName>
    <label>TemplateID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocusignCredentials__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <label>UserName</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_JSON2Apex.cls
/*********************************************************
Description : This test class created for JSON2Apex and docusign envelop sending class.
**********************************************************/
@isTest
Private class Test_JSON2Apex
{
  //Creating Dummy response method by creating instance for a class.
  static testmethod void callJson2Apex()
  {
    JSON2Apex newJson = new JSON2Apex();
    JSON2Apex.parse('{"envelopeId": "ffeb728c-4c49-4281-8427-39ca2fccedd4"}');
                        
  }
  //Test method for docusign authorization and envelope sending.
  static testmethod void AuthCalloutvf()
  {

                Account acc = new Account();
                acc.name = 'testAccount';  
                acc.Primary_Billing_City__c='Sunnyvale';    
                acc.Primary_Billing_Country__c='US';
                acc.Primary_Billing_State__c='CA';
                acc.Primary_Billing_Street__c='260 N Mathilda Ave';
                acc.Primary_Billing_Zip_Code__c='94086'; 
                acc.branch__c = 'CA-San_Jose';   
                acc.Phone = '1234567891';
                insert acc;
           
                Contact con = new Contact();
                con.LastName = 'test';
                con.email = 'test@gmail.com';
                con.accountId = acc.id;
                insert con;
                
                List<Contact> conList = new List<Contact>();
                conList.add(con);
         
                DocusignCredentials__c doccredentials = new DocusignCredentials__c();
                doccredentials.Name = 'DousignCredential1';
                doccredentials.AccountId__c = '74b3rf20-0b4d-409a-a253-f1ecd0b9d57f';
                doccredentials.IntegratorKey__c = 'MSTS-c136b3a7-7d95-4e6c-b7f5-0e00759b0756';
                doccredentials.TemplateID__c = 'DE066A64-5B0F-4EE7-9FB6-D36E17046494';
                doccredentials.UserName__c = '52893f7f-481b-404c-99b0-ad5cb336e01d';
                insert doccredentials;
                
                ApexPages.StandardController ctrl = new ApexPages.StandardController(acc);
                AuthCalloutvf authCtrl = new AuthCalloutvf(ctrl);
                authCtrl.senddoc();
                
                AuthCallout authcallctrl = new AuthCallout();
                Test.startTest();
                authcallctrl.basicAuthCallout(conList);
                  RestRequest req = new RestRequest();

                  RestResponse res = new RestResponse();
                
                  req.requestURI = '/services/apexrest/Customer/';  //Request URL
                
                  req.httpMethod = 'POST';
                
                  RestContext.request = req;
                  RestContext.response= res;
                Test_JSON2Apex.callJson2Apex();
                Test.stopTest();
  
  }
  
}