force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OB_Campaign__c/OB_Campaign__c.object-meta.xml
<CustomObject>
    <label>OB Campaign</label>
    <nameField>
        <displayFormat>OB Campaign-{0000}</displayFormat>
        <label>OB Campaign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OB Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OB_Campaign__c/fields/OB_Campaign_Active__c.field-meta.xml
<CustomField>
    <fullName>OB_Campaign_Active__c</fullName>
    <description>Pulled from the Opportunities Object as a formula.  Used a trigger to create OB Campaign Members under the active campaign.</description>
    <formula>Opportunity__r.OB_Campaign_Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OB Campaign Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OB_Campaign__c/fields/OB_Campaign_Branch__c.field-meta.xml
<CustomField>
    <fullName>OB_Campaign_Branch__c</fullName>
    <description>Branches that are assigned to the OB Campaign.</description>
    <inlineHelpText>Branches that are assigned to the OB Campaign.</inlineHelpText>
    <label>OB Campaign Branch</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Stockton</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Vallejo</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OB_Campaign__c/fields/OB_Campaign_Call_Center__c.field-meta.xml
<CustomField>
    <fullName>OB_Campaign_Call_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OB Campaign Call Center</label>
    <referenceTo>OB_Campaign_Call_Center__c</referenceTo>
    <relationshipLabel>OB Campaigns</relationshipLabel>
    <relationshipName>OB_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OB_Campaign__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OB Campaigns</relationshipLabel>
    <relationshipName>OB_Campaigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
            <value>
                <fullName>CO-Colorado_Springs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OB_Campaign_Active__c.field-meta.xml
<CustomField>
    <fullName>OB_Campaign_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Becomes active once the operational state is set to OB Campaign.</description>
    <label>OB Campaign Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OB_Campaign_Call_Center__c.field-meta.xml
<CustomField>
    <fullName>OB_Campaign_Call_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for the OB Campaigns.</description>
    <inlineHelpText>Used for the OB Campaigns.</inlineHelpText>
    <label>Call Center</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OB_Campaign_Call_Center__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OB_Campaign_Call_Center__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddOBCMTest.cls
/*
--------------------------
 * Modified By: Ganesh
 * Modified on:
 * Description: Updated the test class as per best practices. 
-----------------------------
*/
@isTest(seealldata = false)
private class AddOBCMTest {   
    @Testsetup static void createtestdata(){
        Account newAcc = new Account(LastName = 'Test',Phone = '1234567897',Branch__c = 'AZ-Phoenix_North',respond_date__c=system.today());
        insert newAcc;
        system.assertNotEquals(null, newAcc.id);
        
        Insert new Opportunity(Name = 'Test Opp',AccountId = newAcc.Id,Type = 'Trade',stageName = 'Needs Analysis',closeDate = system.Today(),OB_Campaign_Active__c = true);
        system.assertnotEquals(null,[select id from Opportunity where Type = 'Trade' limit 1]);
        
        Opportunity opp = [select id,OB_Campaign_Call_Center__c, OB_Campaign_Active__c from Opportunity where Type='Trade' limit 1];
		Insert new OB_Campaign__c(Opportunity__c = Opp.id,OB_Campaign_Call_Center__c = Opp.OB_Campaign_Call_Center__c,OB_Campaign_Branch__c='AZ-Phoenix_North');
		System.assertEquals(1,[select count() from OB_Campaign__c]);
    }
    static testmethod void insertOBC(){
	    Test.startTest();
		Account Acc = [select id,phone from Account where lastname='Test' limit 1];
        acc.phone = '9876543210';
        update acc;
		Test.stopTest();
    }
}