force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Gift_Card_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BranchLocation_Mapper__c/BranchLocation_Mapper__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>BranchLocation Mapper</label>
</CustomObject>

force-app/main/default/objects/BranchLocation_Mapper__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <label>Branch Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BranchLocation_Mapper__c/fields/Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Location_Name__c</fullName>
    <label>Location Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Gift_Card__c/Gift_Card__c.object-meta.xml
<CustomObject>
    <label>Gift Card</label>
    <nameField>
        <label>Gift Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Card__c/fields/Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Gift_Card_Order__c</fullName>
    <label>Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Gift Cards</relationshipLabel>
    <relationshipName>Gift_Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Gift_Card__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Gift Cards</relationshipLabel>
    <relationshipName>Gift_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift_Card_Orders__c/Gift_Card_Orders__c.object-meta.xml
<CustomObject>
    <label>Gift Card Order</label>
    <nameField>
        <label>Gift Card Orders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Card Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Card_Orders__c/fields/Branch_Location__c.field-meta.xml
<CustomField>
    <fullName>Branch_Location__c</fullName>
    <label>Branch Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
            <value>
                <fullName>CO-Colorado_Springs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gift_Card_Orders__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Gift Card Orders</relationshipLabel>
    <relationshipName>Gift_Card_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
            <value>
                <fullName>CO-Colorado_Springs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Operational_Stages__c.field-meta.xml
<CustomField>
    <fullName>Operational_Stages__c</fullName>
    <label>Operations Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage_Types__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Docusign Received</fullName>
            </value>
            <value>
                <fullName>Billing Setup</fullName>
            </value>
            <value>
                <fullName>DID Setup</fullName>
            </value>
            <value>
                <fullName>Gift Card Awaiting Artwork</fullName>
            </value>
            <value>
                <fullName>Gift Card Graphic Design</fullName>
            </value>
            <value>
                <fullName>Gift Card Proof Sent to Client</fullName>
            </value>
            <value>
                <fullName>Gift Card Pending</fullName>
            </value>
            <value>
                <fullName>Gift Card Client Approved</fullName>
            </value>
            <value>
                <fullName>Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Gift Card Proof Approved</fullName>
            </value>
            <value>
                <fullName>Gift Card Ordered</fullName>
            </value>
            <value>
                <fullName>Gift Card Received &amp; in Fulfillment</fullName>
            </value>
            <value>
                <fullName>Gift Card Active Customer</fullName>
            </value>
            <value>
                <fullName>Deactivated Customer</fullName>
            </value>
            <value>
                <fullName>Call Center DID</fullName>
            </value>
            <value>
                <fullName>Cancel Pending</fullName>
            </value>
            <value>
                <fullName>Gift Card Docusign Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Prime_Front__c.field-meta.xml
<CustomField>
    <fullName>Prime_Front__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prime Front Cards Included?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GiftCardCreator_Ctrl.cls
public with sharing class GiftCardCreator_Ctrl {
    public list<selectOption> branchOptions {get;set;}
    public String selectedBranch {get;set;}
    public boolean showOptions {get;set;}
    public String batchNumber {get;set;}
    public String location {get;set;}
    public Integer qnty {get;set;}
    public list<Opportunity> oppList {get;set;}
    public map<String,String> csMap;
    public Boolean showButton {get;set;}
    
    //
    public boolean getStatus{get; private set;}
    public boolean enabled {get; private set;}
    public String JobStatus {get; private set;}
    private Id AsyncDeleteJobId;
    private Id AsyncAddJobId;
    public Integer percentComplete {get; private set;}
    //
    
    public GiftCardCreator_Ctrl(){
        branchOptions = new list<Selectoption>();
        selectedBranch = '';
        enabled = false;
        location = '';
        batchNumber = '0300';
        JobStatus = 'Job Started';
        qnty = 0;
        showOptions = false;
        showButton = true;
        csMap = new map<String,String>();
        for(BranchLocation_Mapper__c each : BranchLocation_Mapper__c.getAll().values()){
            csMap.put(each.Branch_Name__c,each.Location_Name__c);
        }
        Schema.DescribeFieldResult dfr = Opportunity.Branch__c.getDescribe();
        List<Schema.PicklistEntry> P = dfr.getPicklistValues();
        branchOptions.add(new selectOption('--Select--','--Select--'));
        for(Schema.PicklistEntry each : p){
            branchOptions.add(new selectOption(each.getValue(),each.getLabel()));
        }
    }
    public void processSelection(){
        showOptions = true;
        showButton = true;
        oppList = new list<Opportunity>();
        String selBranch = apexpages.currentpage().getParameters().get('selBranch');
        if(csMap.containsKey(selBranch)){
            location = csMap.get(selBranch);
            oppList = [Select id,name,account.name,Prime_Front__c,Operational_Stages__c from opportunity 
                            where Branch__c=:selBranch and Operational_Stages__c in ('Gift Card Proof Approved','Gift Card Ordered','Gift Card Received & in Fulfillment','Gift Card Active Customer') 
                             order by Prime_Front__c desc, closedate asc];
             if(oppList.size()==0)showButton = false;
            Integer c = [Select count() from Gift_Card_Orders__c where Parent_Gift_Card_Order__c = null and Branch_Location__c=:selBranch limit 1000];
            if(c != 0){
                batchNumber = String.valueOf(0300+integer.valueOf(c));
                if(batchNumber.length()==3)
                batchNumber = '0'+batchNumber;
            }
            else
            batchNumber = '0300';
        }
        else
        location = 'Location can\'t be found, please contact your admin';
        
    }
    public pagereference saveOrder(){
        if(qnty == 0){
             Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.error,'required field missing: Quantity'));
             return null;
        }
        String oppIds = apexpages.currentpage().getParameters().get('oppIds');
        list<String> oppList = oppIds.split(',');
        /*if(qnty*oppList.size()>9500){
           Integer newQnty = 9500/oppList.size();
             Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.error,'Transaction size exceeded 9999,please reduce your quanity to '+String.valueOf(newQnty)+' orders or less'));
             return null;
        }*/
        list<Gift_Card_Orders__c> gcoList = new list<Gift_Card_Orders__c>();
        Gift_Card_Orders__c gco = new Gift_Card_Orders__c();
        gco.Date_Ordered__c = date.today();
        gco.Branch_Location__c = selectedBranch;
        gco.Quantity_Ordered__c = qnty;
        gco.name = csMap.get(selectedBranch)+' '+batchNumber+' '+'0000'+' '+'0000';
        try{
            insert gco;
        }
        catch(exception e){
             Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.error,e.getmessage()));
             return null;
        }
        for(integer i=1;i<=qnty;i++){
            Gift_Card_Orders__c gc = new Gift_Card_Orders__c();
            String nth = String.valueOf(i);
            if(nth.length() == 1)nth='000'+nth;
             if(nth.length() == 2)nth='00'+nth;
              if(nth.length() == 3)nth='0'+nth;
            gc.name =  csMap.get(selectedBranch)+' '+batchNumber+' '+'0000'+' '+nth;
            gc.Date_Ordered__c = date.today();
            gc.Parent_Gift_Card_Order__c = gco.Id;
            gc.Branch_Location__c = selectedBranch;
           /*gc.Quantity_Ordered__c = qnty;*/
            gcoList.add(gc);
        }
        try{
            insert gcoList;
            if((gcoList.size()*oppList.size())<=9500){
                list<Gift_Card__c> giftCardList = new list<Gift_Card__c>();
                integer i=1;
                for(Gift_Card_Orders__c each :  gcoList){
                     for(String eachOpp : oppList){
                        String nnth = String.valueOf(i);
                        if(nnth.length() == 1)nnth='000'+nnth;
                         if(nnth.length() == 2)nnth='00'+nnth;
                          if(nnth.length() == 3)nnth='0'+nnth;
                        Gift_Card__c giftCard = new Gift_Card__c();
                        giftCard.Opportunity__c = eachOpp;
                        giftCard.Gift_Card_Order__c = each.Id;
                        system.debug('@@@@'+each.name);
                        giftCard.name = csMap.get(selectedBranch)+' '+batchNumber+' '+nnth+' '+each.name.substring(each.name.length()-4,each.name.length());
                        giftCardList.add(giftCard);
                        i++;
                        if(i>oppList.size())i=1;
                     }
                }
                insert giftCardList;
                pagereference pg = new pagereference('/'+gco.Id);
              pg.setRedirect(true);
              return pg;
            }
            else{
              list<String> gcoIds = new list<String>();
              for(Gift_Card_Orders__c each :  gcoList){
                 gcoIds.add(each.Id);
              }
              system.debug('-----------selectedBranch'+selectedBranch);
              system.debug('----------batchNumber'+batchNumber);
              system.debug('-----------gcoIds'+gcoIds);
              system.debug('----------csMap'+csMap);
              system.debug('----------oppList'+oppList);
              GiftCardCreator_Batch obj = new GiftCardCreator_Batch(selectedBranch,batchNumber,gcoIds,csMap,oppList);
              database.executeBatch(obj,30);
              pagereference pg = new pagereference('/apex/GiftCardCreator_Status?gcId='+gco.Id);
              pg.setRedirect(true);
              return pg;
            }
           return null;
        }
       catch(exception e){
             Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.error,e.getmessage()));
             return null;
        }
        return null;
    }
    public Integer count = 0;
      
   public PageReference incrementCounter() {
      /*String queryString1 ='select id, name from apexclass where name ='+'\'GiftCardCreator_Batch\'';
      List <ApexClass> batchClass1 = new List <ApexClass>();    
      batchClass1 = database.query(queryString1);
      String batchId1 =batchClass1[0].Id;
      String queryString2='Select id, TotalJobItems, Numberoferrors, JobItemsProcessed from AsyncApexJob where (ApexClassId =\''+batchId1+'\') And (Status = \'Queued\' OR Status = \'Preparing\' OR Status = \'Processing\')';
      List<AsyncApexjob> Async_Addjob = new List<AsyncApexjob>();  
      Async_Addjob = database.query(queryString2); 
       if(Async_Addjob.size()>0){ 
           Double itemsProcessed ;
        Double totalItems; 
       this.JobStatus='Adding Entities';
       itemsProcessed = Async_Addjob[0].JobItemsProcessed;
       totalItems = Async_Addjob[0].TotalJobItems;
          if(totalItems == 0){
                  this.percentComplete = 0;
            }else{
                this.percentComplete = ((itemsProcessed  / totalItems) * 100.0).intValue();
           }
       } */
        return null;
    }
  public void incrementCounter1(){
    enabled = true;
  }  
    public Integer getCount() {
        return count;
    }
}