force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Scan_Code__c.field-meta.xml
<CustomField>
    <fullName>Scan_Code__c</fullName>
    <description>The scan code of the card</description>
    <inlineHelpText>Identifies Batch / Order / Card / Box</inlineHelpText>
    <label>Scan Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field holds the branch details</description>
    <inlineHelpText>Select the branch where the address resides in.</inlineHelpText>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Holds the City Name</description>
    <inlineHelpText>Enter the City Name</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/CreatedFromBP__c.field-meta.xml
<CustomField>
    <fullName>CreatedFromBP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field to indicate that record is created from Bright pattern or not.</description>
    <label>CreatedFromBP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Full_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Full_Zip_Code__c</fullName>
    <description>Used to store 10 digit zipcode.</description>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Invalid__c.field-meta.xml
<CustomField>
    <fullName>Invalid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It holds true or false value</description>
    <label>Invalid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Holds the state information</description>
    <inlineHelpText>Enter the state</inlineHelpText>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Holds the street information</description>
    <inlineHelpText>Enter the street information</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Used to store 5 digit zipCode.</description>
    <label>Primary Shipping Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/CreatedfromBP__c.field-meta.xml
<CustomField>
    <fullName>CreatedfromBP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will indicate that field is created from BP or not.</description>
    <label>CreatedfromBP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field will store the person Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Scan_code__c.field-meta.xml
<CustomField>
    <fullName>Scan_code__c</fullName>
    <description>The scan code of the card</description>
    <inlineHelpText>Identifies Batch / Order / Card / Box</inlineHelpText>
    <label>Scan code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/User_Address_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Address_Type__c</fullName>
    <description>holds the type of address</description>
    <label>User Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Owner</fullName>
            </value>
            <value>
                <fullName>Secondary Owner</fullName>
            </value>
            <value>
                <fullName>Mailing Address</fullName>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Renter</fullName>
            </value>
            <value>
                <fullName>Un-validated Homeowner</fullName>
            </value>
            <value>
                <fullName>Family of Renter</fullName>
            </value>
            <value>
                <fullName>Family of Un-validated Homeowner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BrightPatternAddressCreation_AC.cls
/*******************************************************************************************************************
Created by: MST
Description: Agent will create Person Account via Brightpattern popup page(Brightpatterncreatepoup).  At before going to create
person account and user address, it will search the address is already existing address or valid address, if it is 
already existing, then it will create new person account and user address(Associate with existing address). 
If Address is not exist, but if it valid, then it will create new person account, address and user address records.
If address is not valid then agent could not create Person Account.
****************************************************************************************************************/

Public Class BrightPatternAddressCreation_AC
{
    public String streetNumber{get;set;}
    public String streetName{get;set;}
    public String city{get;set;}
    public String State{get;set;}
    public String Country{get;set;}
    public String zipCode{get;set;}
    Public List<Address__c> addressList{get;set;}
    public AddressWrapper requestAddressWrap {get;set;}
    public AddressWrapper responseAddressWrap {get;set;}
    public String request;
    public String response;
    public Boolean isConfirm {get;set;}
    public Boolean isError {get;set;}
    public String FirstName{get;set;}
    public String lastName{get;set;}
    public String scanCode{get;set;}
    public String PersonEmail{get;set;}
    public String phone{get;set;}
    public string addType{get;set;}
    public string Didid{get;set;}
    public string stepId{get;set;}
    public string campaign{get;set;}
    public string acknowledge{get;set;}
    public String addressId{get;set;}
    public BrightPatternAddressCreation_AC()
    {
        Didid = ApexPages.currentPage().getParameters().get('Didid');
        stepId = ApexPages.currentPage().getParameters().get('stepid');
        campaign = ApexPages.currentPage().getParameters().get('campaign');
        addressId = ApexPages.currentPage().getParameters().get('address');
        List<Address__c> addressList = [SELECT Id,Street__c,City__c,State__c,Full_Zip_Code__c,Country__c FROM Address__c WHERE Id =: (Id)addressId];
        if(addressList.size() > 0){
            streetName = addressList[0].Street__c;
            city = addressList[0].City__c;
            state = addressList[0].State__c;
            zipCode = addressList[0].Full_Zip_Code__c;
            country = addressList[0].Country__c;
        }
    }
    // Searching the Address.
    public pagereference SearchAddress()
    {
        String Query = 'Select id,State__c, Street__c, Zip_Code__c, Country__c,City__c FROM Address__c WHERE ';
        
        StreetName = StreetName.trim();
        zipCode = zipCode.trim();
        city  = city.trim();
        Country = Country.trim();
        // State  = State.trim();
        
        if(streetName != Null && streetName !='' && zipCode != Null && zipCode !='')
        {
            
            Query +=' (Street__c like \'%'+ streetName +'%\''+ ' AND';
            Query +='  Zip_Code__c like \'%'+ zipCode +'%\'' +')'+' OR';
        }
        
        
        Query += '(';
        
        if(streetName != Null && streetName !='' )
        {
            Query +=' Street__c like \'%'+ streetName +'%\''+ ' AND';
        }
        
        if(zipCode != Null && zipCode !='')
        {
            Query +=' Zip_Code__c like \'%'+ zipCode +'%\'' +' AND';
        }
        
        if(city != '' && city != Null)
        {
            Query +=' City__c like \'%'+ city +'%\'' + ' AND';
        }
        
        
        if(State != '' && State != 'None' && state!=Null)
        {
            Query +=' State__c like \'%'+ State +'%\'' + ' AND';
        }
        
        
        
        Query = query.removeEnd('AND');
        Query += ')';
        System.debug('Query ++++++++++++++++++++++++++++++++++ ' + Query);
        addressList = Database.Query(Query);
        
        if(addressList.size() > 0)
        {
            String addressId;
            
            addressId = addressList[0].id;
            Address__c updateAdd = new Address__c();
            updateAdd.invalid__c = false;
            updateAdd.id = addressList[0].id;
            update updateAdd;
            
            String branch ='';
            List<Branch__c> branchList = new List<Branch__c>();
            if(addressList[0].state__c != Null && addressList[0].city__c!= Null)
                branch = addressList[0].state__c+'-'+addressList[0].city__c;
            
            if(branch != '')
            {
                branchList = [SELECT Id, Name FROM Branch__c WHERE Name = :branch limit 1];
            }
            
            
            
            
            Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
            Account newAcc = new Account();
            newAcc.lastName = lastName;
            newAcc.firstName = firstName;
            newAcc.PersonEmail = PersonEmail;
            newAcc.Recordtypeid = accountRecordTypeId;
            newAcc.phone = phone;
            newAcc.scan_code__c = scanCode;
            newAcc.respond_Date__c = Date.Today();
            insert newAcc; // creating new account.
            
            User_Address__c newUserAddress = new User_Address__c();
            newUserAddress.Address__c = addressId;
            newUserAddress.UserAccount__c = newAcc.id;
            newUserAddress.Phone__c = phone;
            newUserAddress.active__c= true;
            newUserAddress.user_address_type__c= addType;
            newUserAddress.CreatedfromBP__c = true;
            newUserAddress.X1st_IB_Agent__c = userInfo.getUserId();
            newUserAddress.X1st_IB_Agent_Date__c = System.Now();
            newUserAddress.InteractionStepId__c = stepId;
            insert newUserAddress;   // creating new user address.
            
            PageReference reference=new PageReference('/apex/BrightPatternpopup?id='+newAcc.id+'&Didid='+Didid+'&Campaign='+campaign+'&stepid='+stepId+'&userAddressId='+newUserAddress.id);
            reference.setRedirect(true);     
            return reference;
        }
        
        
        else
        { // Validating the address.
            
            AddressWrapper requestAddressWrap = new AddressWrapper();
            AddressWrapper responseAddressWrapper = new AddressWrapper();
            requestAddressWrap.Line1 = '';
            requestAddressWrap.Line2 =(String)(streetName != '' ? streetName :'');
            requestAddressWrap.City = (String)(City != '' ? City : '');
            requestAddressWrap.State = (String)(State != '' ? State : '');
            requestAddressWrap.Zip5 = (String)(zipCode != '' ? zipCode : '');
            System.Debug('Request Wrapper+++++'+requestAddressWrap);            
            request = requestAddressWrap.createJson(requestAddressWrap);
            HttpRequest req = new HttpRequest();
            HttpResponse res = new HttpResponse();
            Http http = new Http();
            req.setEndpoint(' https://address-verification.nuhome.com/v1/address/verify');
            req.setMethod('POST');
            req.setHeader('Accept', 'application/Json');
            req.setBody(request);
            //req.setCompressed(true); // otherwise we hit a limit of 32000
            try {
                
                Integer responseCode;
                if(test.isRunningTest())
                    responseCode = 200;
                else
                {
                    res = http.send(req);
                    responseCode = res.getStatuscode();
                }
                if(responseCode == 200){
                    System.debug('Response============>'+res.getBody());
                    // Parse JSON response to get all the totalPrice field values.
                    JSONParser parser = JSON.createParser(res.getBody());
                    isConfirm = True;
                    while (parser.nextToken() != null) {
                        if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && 
                            (parser.getText() == 'Description')) {
                                isConfirm = false;
                                // Get the value of the description.
                                parser.nextToken();
                                system.debug('Description: ' + parser.getText());
                                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,parser.getText()));
                                return null;
                            }
                    }
                    if(!test.isRunningTest())
                        responseAddressWrap = responseAddressWrapper.parse(res.getBody());
                    system.debug('!!!isConfirm: ' + isConfirm);
                    if( isConfirm == false)
                    {
                        
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Invalid Address'));
                        return null;
                    }
                    
                    if(isConfirm == True)
                    {
                        
                        String street;
                        if(streetNumber == Null)
                            streetNumber = '';
                        if(streetName == Null)
                            streetName = '';
                        
                        Street =  streetNumber+' '+ streetName;
                        String branch ='';
                        List<Branch__c> branchList = new List<Branch__c>();
                        if(responseAddressWrap.city != Null && responseAddressWrap.state != Null)
                            branch = responseAddressWrap.state+'-'+responseAddressWrap.city;
                        
                        if(branch != '')
                        {
                            
                            branchList = [SELECT Id, Name FROM Branch__c WHERE Name = :branch limit 1];
                        }
                        
                        String street1 = responseAddressWrap.Line1;
                        String Street2 = responseAddressWrap.Line2;
                        String zipCode = responseAddressWrap.Zip5;
                        
                        String uniqueKey1 = street1+':'+zipCode;
                        String uniqueKey2 = street2+':'+zipCode;
                        
                        List<Address__c> existingAddress = [SELECT id from Address__c WHERE (Unique_Key__c = :uniqueKey1 or Unique_Key__c = :uniqueKey2) Limit 1];
                        
                        
                        Address__c newAddress = new Address__C();
                        newAddress.name = street+':'+city+':'+state;
                        newAddress.Street__c = responseAddressWrap.Line1 != '' ? responseAddressWrap.Line1 : responseAddressWrap.Line2 != ''?responseAddressWrap.Line2:'';
                        newAddress.Zip_Code__c = responseAddressWrap.Zip5;
                        newAddress.City__c = responseAddressWrap.City;
                        newAddress.Country__c = country;
                        newAddress.State__c = responseAddressWrap.State;
                        newAddress.Zip_Plus_Four__c = responseAddressWrap.Zip4;
                        if(branchList.size() > 0)
                            newAddress.branch__c = branchList[0].id;
                        
                        try
                            
                        {   
                            
                            String addressId;
                            if(!(existingAddress.size() > 0))
                            {
                                insert newAddress;
                                addressId = newAddress.id;
                            }
                            else
                            {
                                addressId = existingAddress[0].id;
                                
                                Address__c updateAdd = new Address__c();
                                updateAdd.id = existingAddress[0].id;
                                updateAdd.invalid__c = false;
                                update updateAdd;
                                
                            }
                            
                            
                            
                            Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
                            Account newAcc = new Account();
                            newAcc.lastName = lastName;
                            newAcc.firstName = firstName;
                            newAcc.PersonEmail = PersonEmail;
                            newAcc.Recordtypeid = accountRecordTypeId;
                            newAcc.phone = phone;
                            newAcc.scan_code__c = scanCode;
                            newAcc.respond_Date__c = Date.Today();
                            insert newAcc; // creating new account.
                            
                            User_Address__c newUserAddress = new User_Address__c();
                            newUserAddress.Address__c = addressId;
                            newUserAddress.UserAccount__c = newAcc.id;
                            newUserAddress.Phone__c = phone;
                            newUserAddress.active__c= true;
                            newUserAddress.user_address_type__c= addType;
                            newUserAddress.CreatedfromBP__c = true;
                            newUserAddress.X1st_IB_Agent__c = userInfo.getUserId();
                            newUserAddress.X1st_IB_Agent_Date__c = System.Now();
							newUserAddress.InteractionStepId__c = stepId;                        
                            try
                            {
                                insert newUserAddress;  
                                PageReference reference=new PageReference('/apex/BrightPatternpopup?id='+newAcc.id+'&Didid='+Didid+'&Campaign='+campaign+'&stepid='+stepId+'&userAddressId='+newUserAddress.id);
                                reference.setRedirect(true);     
                                return reference; // creating new user address.
                            }
                            
                            Catch(DMLException e)
                            {
                                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
                            }
                        }
                        
                        Catch(DMLException e)
                        {
                            
                            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
                        }
                        
                        
                        
                        
                    }
                }
                else if(res.getStatuscode() == 400){
                    isConfirm = false;
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Address Not Found'));
                }
            } catch(System.CalloutException e) {
                System.debug('Callout error: '+ e);
                System.debug(res.toString());
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
                
            }
        }
        return null;
    }
    
    
    public class AddressWrapper{
        public String Line1 {get;set;}  //2027 E University Dr Unit 107
        public String Line2 {get;set;}  //
        public String City {get;set;}   //Tempe
        public String State {get;set;}  //AZ
        public String Zip5 {get;set;}
        public String Zip4 {get;set;}   //85281
        public AddressWrapper parse(String json){ 
            return (AddressWrapper)System.JSON.deserialize(json, AddressWrapper.class);
        }
        public String createJson(AddressWrapper addressWrapper){            
            return (String) System.JSON.serialize(addressWrapper);
        }
        
    } 
    
    
    
    
    // Getting State picklist values from USPS_States_List__c custom settings.
    public List<SelectOption> getStates()
    {
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult =  Address__c.State__c.getDescribe();
        
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        options.add(new SelectOption('', 'None')); 
        for( Schema.PicklistEntry currVal : picklistValues)
        {
            options.add(new SelectOption(currVal.getLabel(), currVal.getValue())); 
            
        }   
        
        return options;
    }
    
    // Getting Appointment Outcome picklist values from Inventory field.
    public List<SelectOption> getAddressType()
    {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Renter', 'Renter')); 
        options.add(new SelectOption('Un-validated Homeowner', 'Un-validated Homeowner')); 
        options.add(new SelectOption('Family of Renter', 'Family of Renter')); 
        options.add(new SelectOption('Family of Un-validated Homeowner', 'Family of Un-validated Homeowner')); 
        return options;
    }
    
    // Redirecting to Account Search Page.
    Public PageReference GotoAccSearchPage()
    {
        
        PageReference reference=new PageReference('/apex/BrightPatternSearchPopup?Didid='+Didid+'&stepid='+stepId+'&Campaign='+campaign); 
        reference.setRedirect(true);     
        return reference;
        
    } 
}