force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Carrier_ID__c.field-meta.xml
<CustomField>
    <fullName>Carrier_ID__c</fullName>
    <description>It holds the career code for the branch.This code will be used to send to the outbound call of the delivery object</description>
    <label>Carrier ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Region_MD__c.field-meta.xml
<CustomField>
    <fullName>Region_MD__c</fullName>
    <label>Region MD</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipCode__c/ZipCode__c.object-meta.xml
<CustomObject>
    <description>It contains all zip codes for the corresponding branches.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipCode__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Zip Codes</relationshipLabel>
    <relationshipName>Zip_code</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Zip Codes</relationshipLabel>
    <relationshipName>Zip_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZipCode</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiacoAssignRouteZipTest.cls
@isTest
public class DiacoAssignRouteZipTest {
    
    @isTest 
    static void setup() {
        
        List<Route__c> route = new List<Route__c>();
        route.add(new Route__c(
        	Name = 'Route 1'
        ));
        route.add(new Route__c(
        	Name = 'unknown'
        ));
        insert route;
        Region__c region = new Region__c();
        region.Name = 'Test';
        insert region;
        Branch__c branch = new Branch__c();
        branch.Name = 'Test';
        branch.Region_MD__c = region.Id;
        branch.Carrier_ID__c = 'test';
        insert branch;
        List<ZipCode__c> zips = new List<ZipCode__c>();
        zips.add( new ZipCode__c(
        	name = '11111',
            Route__c = route[0].Id,
            Branch__c = branch.Id
        ));
        zips.add( new ZipCode__c(
        	name = 'unknown',
            Route__c = route[1].Id,
            Branch__c = branch.Id
        ));
        insert zips;
        List<Account> accounts = new List<Account>();
        // insert 10 accounts
        for (Integer i=0;i<10;i++) {
            accounts.add(new Account(name='Account '+i, 
                billingcity='New York', billingcountry='USA'));
        }
        accounts.add(new Account(name='Account 10', 
                billingcity='New York', billingcountry='USA',Zip__c='11111'));
        insert accounts;
        List<DiacoAssignRouteZip.param> params = new List<DiacoAssignRouteZip.param>();
        //List<param> accountsId = new List<param>();
        for(Account acc : accounts){
            DiacoAssignRouteZip.param param = new DiacoAssignRouteZip.param();  
           	param.Id=acc.Id;
            param.Route=acc.Route__c;
            param.Zip=acc.Zip__c;
            params.add(param);
        }
        Test.startTest();
        DiacoAssignRouteZip.ConnectWebformAccount(params);
        Test.stopTest();
    }

}