force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_City__c</fullName>
    <label>Primary Billing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Country__c</fullName>
    <label>Primary Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
                <default>true</default>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_State__c</fullName>
    <label>Primary Billing State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Street__c</fullName>
    <label>Primary Billing Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Zip_Code__c</fullName>
    <label>Primary Billing Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
            <value>
                <fullName>CO-Colorado_Springs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forward_to_number__c.field-meta.xml
<CustomField>
    <fullName>Forward_to_number__c</fullName>
    <label>Forward To Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/nuHome_Docusign_OppStage_Handler_Test.cls
/**************************************************************************************************************
Created By: MST
Description : Test class for nuHome_Docusign_OppStage_Handler class.
Modified By: Ganesh
Modified on:
Description: Updated the test class as per best practices.
***************************************************************************************************************/
@isTest(seealldata=false)
private class nuHome_Docusign_OppStage_Handler_Test {
    //This method is to create docusign status records.
    @testsetup static void createtestdata(){
        Id personAccRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        //Creating account record.
        Account accIns = new Account();
        accIns.Lastname = 'test';
        accIns.Phone = '9876433325';
        accIns.RecordTypeId = personAccRTId;
        accIns.Primary_Billing_City__c='Sunnyvale';
        accIns.Primary_Billing_Country__c='US';
        accIns.Primary_Billing_State__c='CA';
        accIns.Primary_Billing_Street__c='260 N Mathilda Ave';
        accIns.Primary_Billing_Zip_Code__c='94086'; 
        Insert accIns;
        system.assertNotEquals(null, accIns.id);
        
        //Creating opportunity record with account id.
        Opportunity oppIns = new Opportunity();
        oppIns.Name = 'test';
        oppIns.AccountId = accIns.Id;
        oppIns.Type = 'Existing Business';
        oppIns.Forward_to_number__c = '9876543212';
        oppIns.Branch__c = 'AL-Birmingham';
        oppIns.StageName = 'Qualified';
        oppIns.CloseDate = system.today();
        Insert oppIns;
        system.assertNotEquals(null, oppIns.id);
        
        //Creating docusign status record with account id.
        dsfs__DocuSign_Status__c docusignStatus = new dsfs__DocuSign_Status__c();
        docusignStatus.dsfs__Company__c = accIns.Id;
        docusignStatus.dsfs__Envelope_Status__c = 'Sent';
        docusignStatus.dsfs__DocuSign_Envelope_ID__c = 'TEST Envelope';
        insert docusignStatus;
        
        //Updating the docusign status as Delivered.
        Update new  dsfs__DocuSign_Status__c(id= docusignStatus.Id,dsfs__Envelope_Status__c = 'Delivered');
        /* 
Insert new  dsfs__DocuSign_Status__c(dsfs__Company__c = accIns.Id,dsfs__DocuSign_Envelope_ID__c = 'TEST Envelope',dsfs__Envelope_Status__c = 'Completed'); 
*/
        system.assertEquals(1, [select count() from dsfs__DocuSign_Status__c]);
    }
    static testmethod void docstagetest(){
        
        Opportunity opp = [select id, StageName from Opportunity];
        List<dsfs__DocuSign_Status__c> docusignStatus = [select id,dsfs__Company__c,dsfs__Subject__c,dsfs__Envelope_Status__c,dsfs__DocuSign_Envelope_ID__c from dsfs__DocuSign_Status__c];
        test.startTest();
        nuHome_Docusign_OppStage_Handler.changeStage(docusignStatus);
        test.stopTest();
    }
    static testmethod void docstagetest1(){
        dsfs__DocuSign_Status__c doc1 = [select id,dsfs__Envelope_Status__c from dsfs__DocuSign_Status__c where dsfs__DocuSign_Envelope_ID__c = 'TEST Envelope' limit 1];
        doc1.dsfs__Envelope_Status__c = 'Completed';
        update doc1;
        
        Opportunity opp = [select id, StageName from Opportunity];
        List<dsfs__DocuSign_Status__c> docusignStatus = [select id,dsfs__Company__c,dsfs__Subject__c,dsfs__Envelope_Status__c,dsfs__DocuSign_Envelope_ID__c from dsfs__DocuSign_Status__c];
        test.startTest();
        nuHome_Docusign_OppStage_Handler.changeStage(docusignStatus);
        test.stopTest();
    }
}