force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Shipping_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_Zip_Code__c</fullName>
    <label>Primary Shipping Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DID__c/DID__c.object-meta.xml
<CustomObject>
    <label>DID</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}:{00}</displayFormat>
        <label>DID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Back_pdf__c.field-meta.xml
<CustomField>
    <fullName>Back_pdf__c</fullName>
    <label>Back PDF</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
            <value>
                <fullName>CO-Colorado_Springs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DID__c.field-meta.xml
<CustomField>
    <fullName>DID__c</fullName>
    <label>DID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Front_pdf__c.field-meta.xml
<CustomField>
    <fullName>Front_pdf__c</fullName>
    <label>Front PDF</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Operational_Stages__c.field-meta.xml
<CustomField>
    <fullName>Operational_Stages__c</fullName>
    <label>Operations Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage_Types__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Docusign Received</fullName>
            </value>
            <value>
                <fullName>Billing Setup</fullName>
            </value>
            <value>
                <fullName>DID Setup</fullName>
            </value>
            <value>
                <fullName>Gift Card Awaiting Artwork</fullName>
            </value>
            <value>
                <fullName>Gift Card Graphic Design</fullName>
            </value>
            <value>
                <fullName>Gift Card Proof Sent to Client</fullName>
            </value>
            <value>
                <fullName>Gift Card Pending</fullName>
            </value>
            <value>
                <fullName>Gift Card Client Approved</fullName>
            </value>
            <value>
                <fullName>Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Gift Card Proof Approved</fullName>
            </value>
            <value>
                <fullName>Gift Card Ordered</fullName>
            </value>
            <value>
                <fullName>Gift Card Received &amp; in Fulfillment</fullName>
            </value>
            <value>
                <fullName>Gift Card Active Customer</fullName>
            </value>
            <value>
                <fullName>Deactivated Customer</fullName>
            </value>
            <value>
                <fullName>Call Center DID</fullName>
            </value>
            <value>
                <fullName>Cancel Pending</fullName>
            </value>
            <value>
                <fullName>Gift Card Docusign Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>PricebookEntry.Product2.Branch__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Branch__c.Active_for_Campaigns__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GlobalTest2.cls
@isTest(SeeAllData = true)
private class GlobalTest2 {
        static testMethod void testMethod1(){
            String recTypeId = [Select id from recordType where developerName='PersonAccount' limit 1].Id;
            
            Contact con = new Contact();
            con.LastName = 'testcontact';
            insert con;

            Product2 prod = new Product2(Name = 'Prime Front cards');
            insert prod;

            Pricebook2 standard = [Select Id, Name, IsActive From Pricebook2 where IsStandard = true LIMIT 1];

            PriceBook2 pb2=new PriceBook2();
            pb2.Name = 'test';
            pb2.IsActive = true;
            insert pb2;

            PricebookEntry one = new PricebookEntry();
            one.pricebook2Id = standard.id;
            one.product2id = prod.id;
            one.unitprice = 1249.0;
            one.isactive = true;
            insert one;

            PricebookEntry ret = new PricebookEntry();
            ret.pricebook2Id = pb2.id;
            ret.product2id = prod.id;
            ret.unitprice = 1250.0;
            ret.isactive = true;
            insert ret;

            
            Account acc = new Account();
            acc.lastname = 'TestAccount';
            acc.recordTypeId = recTypeId;
            acc.Primary_Shipping_Zip_Code__c = '72832';
            acc.Phone = '2222222222';
            try{
                insert acc;
            }
            catch(exception e){
                system.assert(false,'Failed to insert the Account record. '+e.getMessage());
            }
            Opportunity opp = new Opportunity();
            opp.accountId = acc.Id;
            opp.name='TestOpp';
            opp.closeDate = date.today();
            opp.Operational_Stages__c = 'Gift Card Client Approved';
            opp.Branch__c = 'Asheville-NC';
            opp.type = 'Existing Business';
            opp.DID__c = 'Test';
            opp.Back_pdf__c = 2;
            opp.Front_pdf__c = 2;
            opp.stageName = 'Value Proposition';
            try{
                insert opp;
            }
            catch(exception e){
                system.assert(false,'Failed to insert the opp'+e.getMessage());
            }
            list<Product2> eachProd = [select id,name from product2 where name = 'Prime Front cards' limit 1];
            list<PricebookEntry> peId = [Select id from PricebookEntry where product2Id =:eachProd[0].id limit 1];
            list<OpportunityLineItem> opllist = new list<OpportunityLineItem>();

            OpportunityLineItem opl = new OpportunityLineItem();
            opl.PricebookEntryId = peId[0].Id;
            opl.opportunityId = opp.id;
            opl.Quantity = 1;
            opl.totalPrice = 100;
            opllist.add(opl);

            OpportunityLineItem opl1 = new OpportunityLineItem();
            opl1.PricebookEntryId = peId[0].Id;
            opl1.opportunityId = opp.id;
            opl1.Quantity = 1;
            opl1.totalPrice = 100;
            opllist.add(opl1);

             try{
                insert opllist;
            }
            catch(exception e){
                system.assert(false,'Failed to insert the oppline'+e.getMessage());
            }
            try{
                delete opllist[0];
            }
            catch(exception e){
                system.assert(false,'Failed to delete the oppline'+e.getMessage());
            }
        }
}