force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CPL_Joins__c/CPL_Joins__c.object-meta.xml
<CustomObject>
    <label>CPL Joins</label>
    <nameField>
        <displayFormat>SC-{0}</displayFormat>
        <label>CPL Join Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPL Joins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CPL_Joins__c/fields/Active_CPL_Join__c.field-meta.xml
<CustomField>
    <fullName>Active_CPL_Join__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active CPL Join</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPL_Joins__c/fields/Billing_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Billing_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The destination CPL business opportunity.</description>
    <label>Billing Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>SPECCARD1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CPL_Joins__c/fields/Lead_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Lead_Distribution__c</fullName>
    <label>Lead Distribution</label>
    <referenceTo>Lead_Distribution__c</referenceTo>
    <relationshipLabel>CPL Joins</relationshipLabel>
    <relationshipName>CPL_Joins</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CPL_Joins__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Distribution__c/Lead_Distribution__c.object-meta.xml
<CustomObject>
    <label>Lead Distribution</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Lead Distribution ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Distribution__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lead Distributions</relationshipLabel>
    <relationshipName>Lead_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Distribution__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>Text(Opportunity__r.Branch__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Distribution__c/fields/LastDialedNumber__c.field-meta.xml
<CustomField>
    <fullName>LastDialedNumber__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This box will be check by Bright Pattern as a call comes in or by a trigger when we see an inventory record show up with this as the dialed number on a forward to business call.</description>
    <label>Last Dialed Number</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
            <value>
                <fullName>CO-Colorado_Springs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forward_to_number__c.field-meta.xml
<CustomField>
    <fullName>Forward_to_number__c</fullName>
    <label>Forward To Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NuCard_Industry__c.field-meta.xml
<CustomField>
    <fullName>NuCard_Industry__c</fullName>
    <label>NuCard Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>Air Duct Cleaning</fullName>
            </value>
            <value>
                <fullName>Appliance Repair</fullName>
            </value>
            <value>
                <fullName>Appliance Store</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Auto Detailing</fullName>
            </value>
            <value>
                <fullName>Auto Glass</fullName>
            </value>
            <value>
                <fullName>Auto Repair</fullName>
            </value>
            <value>
                <fullName>Awnings</fullName>
            </value>
            <value>
                <fullName>Bathroom Remodeling</fullName>
            </value>
            <value>
                <fullName>Bedding/Linens/Drapes</fullName>
            </value>
            <value>
                <fullName>Billiard</fullName>
            </value>
            <value>
                <fullName>Blinds/Shutters</fullName>
            </value>
            <value>
                <fullName>Cabinetry / Carpentry</fullName>
            </value>
            <value>
                <fullName>Cable/Satellite TV/Internet</fullName>
            </value>
            <value>
                <fullName>Carpet/Tile Cleaning</fullName>
            </value>
            <value>
                <fullName>Chimney Sweep</fullName>
            </value>
            <value>
                <fullName>Chiropractor</fullName>
            </value>
            <value>
                <fullName>Closet Organization</fullName>
            </value>
            <value>
                <fullName>Closet Remodel</fullName>
            </value>
            <value>
                <fullName>Computer Repair</fullName>
            </value>
            <value>
                <fullName>Computer Setup</fullName>
            </value>
            <value>
                <fullName>Custom BBQ</fullName>
            </value>
            <value>
                <fullName>Day/Med Spas</fullName>
            </value>
            <value>
                <fullName>Day Care Provider/Pre School</fullName>
            </value>
            <value>
                <fullName>Deck/Patio - Build</fullName>
            </value>
            <value>
                <fullName>Dentist</fullName>
            </value>
            <value>
                <fullName>Disaster Recovery</fullName>
            </value>
            <value>
                <fullName>Dog Grooming/Boarding</fullName>
            </value>
            <value>
                <fullName>Driveways/Repaving</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateCPLJoinInfoHandlerTest.cls
/****************************************************************
Description : This test class created for UpdateCPLJoinInfoHandler class.
*****************************************************************/

@isTest
public class UpdateCPLJoinInfoHandlerTest{

    // create test records.
    static testMethod void Test_afterUpdate(){ 
        
        Account acc = new Account();
        acc.Name = 'TestAccount';
        insert acc;
        
        
        Opportunity opp = new Opportunity();
        opp.Name = 'TestOpportunity';
        opp.AccountId = acc.Id ;
        opp.Type = 'New Business';
        opp.StageName = 'Value Proposition';
        opp.CloseDate = system.today()+2;
        opp.NuCard_Industry__c = 'Chiropractor';
        opp.Branch__c = 'AZ-Phoenix_East';
        opp.LeadSource = 'CoreLogic';
        opp.Forward_to_number__c = '8220708920';
        insert opp;
        
        Lead_Distribution__c leadDistribute = new Lead_Distribution__c();
         leadDistribute.Account__c = acc.Id;
        leadDistribute.LastDialedNumber__c = false;
        insert leadDistribute;

        CPL_Joins__c cpl = new CPL_Joins__c();
        cpl.Billing_Opportunity__c = opp.Id;
        cpl.Lead_Distribution__c = leadDistribute.id;
        cpl.Active_CPL_Join__c  = true;
        cpl.Sort_Order__c = 0;
        insert cpl;
       
        leadDistribute.LastDialedNumber__c = true;
       
        update leadDistribute; 
   }
    
    

}