force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_City__c</fullName>
    <label>Primary Shipping City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_Country__c</fullName>
    <label>Primary Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
                <default>true</default>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Shipping_State__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_State__c</fullName>
    <label>Primary Shipping State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Primary_Shipping_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Shipping_Street__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_Street__c</fullName>
    <label>Primary Shipping Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Shipping_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_Zip_Code__c</fullName>
    <label>Primary Shipping Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Product__c/Delivery_Product__c.object-meta.xml
<CustomObject>
    <description>This object store the Product details that will be send as Delivery.</description>
    <label>Delivery Product</label>
    <nameField>
        <label>Delivery Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
            <value>
                <fullName>CO-Colorado_Springs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gift_Card_Orders__c/Gift_Card_Orders__c.object-meta.xml
<CustomObject>
    <label>Gift Card Order</label>
    <nameField>
        <label>Gift Card Orders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Card Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UtilClass.cls
/********************************************************
Description : It will return the record types values dynamically based on the input parameter.
********************************************************/

Public class UtilClass{
    //Used to store some default driver record Id.
    static Id driverId;  
    //Used to verify incoming driver name and its contains combination of driver firstname & driver lastname
    static string tempDriverName;
    //Used to store cheetah Gift Card Order Id.
    static Id cheetahGiftCardOrderId;
    //Used to verify incoming products are same or not
    static String tempSelectedProducts;
    //
    static String jsonProductNames;
    //Used to store branchId for given branch name
    static Id branchId;
    //Used to verify incoming branch is same or not
    static String tempBranchName;
    
    // It will return record type info based on the input object.
    public static Map<Id,String> getRecordTypeDetails(String objectname){
        Schema.DescribeSObjectResult sobjectResult = Schema.getGlobalDescribe().get(objectname).getDescribe();
        List<Schema.RecordTypeInfo> recordTypeInfo = sobjectResult.getRecordTypeInfos();
        Map<Id,String> mapofCaseRecordTypeNameandId = new Map<Id,String>();
        for(Schema.RecordTypeInfo info : recordTypeInfo){
            mapofCaseRecordTypeNameandId.put(info.getRecordTypeId(),info.getName());
        }
        return mapofCaseRecordTypeNameandId;
    }
    //Used to get the driver id by passing firstName & lastName. Since we have some default driver in our Nuhome so,
    //Driver = Cheetah (first name) Driver (last name) => To get cheetah driver id
    //Driver = Invalid (first name) Driver (last name) => To get Invalid driver id
    public static Id getDriverId(String firstName,String lastName){
        if(tempDriverName == firstName+lastName){
            return driverId;
        }
        else{
            List<Driver__c> driverList = [SELECT Id,First_Name__c,Last_Name__c FROM Driver__c WHERE First_Name__c =: firstName AND Last_Name__c =: lastName];   
            if(driverList.size() > 0){                
                tempDriverName = driverList.get(0).First_Name__c+driverList.get(0).Last_Name__c;
                driverId = driverList.get(0).id;
            }
        }
        return driverId;
    }
    //Used to get the Cheetah Gift Card Order id
    public static Id getCheetahGiftCardOrderId(){
        if(cheetahGiftCardOrderId == null){
            List<Gift_card_orders__c> giftCardOrderList = [SELECT Id,Name FROM Gift_Card_Orders__c WHERE Name = 'Cheetah Gift Card Order'];
            if(giftCardOrderList.size() > 0){
                cheetahGiftCardOrderId = giftCardOrderList.get(0).id;
            }
        }
        return cheetahGiftCardOrderId;
    }
    //Used to get selected values from selectList
    public static String getValuesFromSelectList(List<SelectOption> selectedValues){
        Boolean first = true;
        String values;
        if(selectedValues.size() > 0){
            for ( SelectOption so : selectedValues ) {
                if(!first){
                    values += ',' + so.getlabel();
                }
                else{
                    values = so.getlabel(); 
                }            
                first = false;
            }
        }
        else{//No values in selectedValues then return empty.
            values = '';
        } 
        return values;
    }
    //Used to validate user account address
    public static boolean validateAccAddress(Account acc){
        if(acc.Primary_Shipping_City__c != null && acc.Primary_Shipping_Country__c != null && acc.Primary_Shipping_State__c != null
           && acc.Primary_Shipping_Zip_Code__c != null && acc.Primary_Shipping_Street__c != null){
               return true;
           }
        return false;
    }
    public static string genarateJson(String StrToJson){
        if(StrToJson == null){
            return null;
        }
        if(tempSelectedProducts == StrToJson){
            return jsonProductNames;
        }
        else{
            tempSelectedProducts = StrToJson;
            Set<String> productNames = new Set<String>();
            productNames.addAll(StrToJson.split(','));
            List<Delivery_Product__c> prodList = [SELECT id,name FROM Delivery_Product__c WHERE Name =: productNames];
            if(prodList.size() > 0){
                jsonProductNames = json.serialize(prodList);  
            }
        }
        return jsonProductNames;
    }
    //Used to get the Cheetah Gift Card Order id
    public static Id getBranchId(String branchName){
        if(tempbranchName == branchName){
            return branchId;
        }
        else{
            List<Branch__c> branchList = [SELECT Id,name FROM Branch__c WHERE Name =: branchName];
            if(branchList.size() > 0){
                tempbranchName = branchList.get(0).name;
                branchId = branchList.get(0).id;
            }            
            return branchId;
        }
    }
    //Used to format the given phone number. Fg, (987) 654-3211  
    public static string getPhoneFormat(String phone){
        Pattern p = Pattern.compile('[-() ]');
        String tempPhone = p.matcher(Phone).replaceAll('');
        if(tempPhone.length() == 10){
            return '('+tempPhone.substring(0, 3) + ') '+tempPhone.substring(3, 6) + '-' + tempPhone.substring(6, 10);
        }
        return null;
    }
}