force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry_Values__c/Industry_Values__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to find the industries for creating inventory records</description>
    <label>Industry Values</label>
</CustomObject>

force-app/main/default/objects/Industry_Values__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>It contains  field label</description>
    <label>Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Industry_Values__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>It will contain the Door Tag Script Survey questions</description>
    <label>Question</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>TEXT ( Opportunity__r.Branch__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/idCPL_Billing_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>idCPL_Billing_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>idCPL Billing Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Inventory (idCPL Billing Opportunity)</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>This field will hold product list price</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>It will hold the matching product name.</description>
    <label>Product Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Price__c</fullName>
    <description>It will store matching product price</description>
    <label>Product Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>This field contains quantity info</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <label>Survey Question</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Survey_Response__c.field-meta.xml
<CustomField>
    <fullName>Survey_Response__c</fullName>
    <description>It holds the value of Survey Response.</description>
    <label>Survey Response</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/UnMatching_Invetnory__c.field-meta.xml
<CustomField>
    <fullName>UnMatching_Invetnory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag will identify the inventory is created from Matching products or not matching product</description>
    <label>UnMatching Inventory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>PricebookEntry.Product2.Branch__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Branch__c.Active_for_Campaigns__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchUpdatingPriceonInv_AC.cls
global class BatchUpdatingPriceonInv_AC implements Database.Batchable<Aggregateresult>
{

  Public Id invRecordTypeId = Schema.SObjectType.Inventory__C.getRecordTypeInfosByName().get('nuHome Door Tag Script').getRecordTypeId();
 

   global iterable<Aggregateresult> start(Database.BatchableContext BC)
   { 
         list<AggregateResult> batchAggregationlist = NEW list<AggregateResult>();
         batchAggregationlist =  [SELECT idCPL_Billing_Opportunity__c oppId FROM Inventory__C WHERE UnMatching_Invetnory__c = FALSE AND Product_price__c = Null AND (Survey_Response__c ='Y' OR Survey_Response__c ='M' OR Survey_Response__c ='Blinds' OR Survey_Response__c ='Shutters' OR Survey_Response__c ='Blinds and Shutters') AND  recordtypeid =: invRecordTypeId and  idCPL_Billing_Opportunity__c != NULL  GROUP BY idCPL_Billing_Opportunity__c];
         return batchAggregationlist;
   }
   
   
   
    global void execute(Database.BatchableContext BC, List<AggregateResult> scope) {
    
        Set<id> oppIds = NEW Set<id>();
        
        Set<String> productNamesSet = new Set<String>();
        Map<Id,List<Inventory__c>> oppwithInventoryMap = new Map<Id,List<Inventory__c>>();
        
        Map<Id,String> productNameMap = new Map<Id,String>();
        Set<String> lineItemsSet = new Set<String>();
        Set<String> inventoryIds = new Set<String>();
        
         String Industry;
         
        List<Inventory__c> invList = new List<Inventory__c>();
        
        
        For(AggregateResult INv:scope){
           String oppId = String.valueof(inv.get('oppId'));
           oppIds.add(oppId);
         }
    
    
        Map<String,String> industryCustomSettingMap = new Map<String,String>();
        
        for(Industry_Values__c currIndustry : Industry_Values__c.getAll().Values())
        {
            industryCustomSettingMap.put(currIndustry.Question__c,currIndustry.Label__c);
        }
        
        
       if(oppIds.size() > 0)
       {
          for(Inventory__c currRec : [SELECT Id,Name,Survey_Question__c,Survey_Response__c,idCPL_Billing_Opportunity__c,
                                      Account__r.Branch__c FROM Inventory__c WHERE recordtypeid =: invRecordTypeId AND  
                                      UnMatching_Invetnory__c = FALSE AND  Product_price__c = Null AND
                                      (Survey_Response__c ='Y' OR Survey_Response__c ='M' OR Survey_Response__c ='Blinds' OR Survey_Response__c ='Shutters' 
                                      OR Survey_Response__c ='Blinds and Shutters') AND  
                                      idCPL_Billing_Opportunity__c IN :oppIds])
          {
          
              industry = '';
               
              if(industryCustomSettingMap.containsKey(currRec.Survey_Question__c))
                    Industry = industryCustomSettingMap.get(currRec.Survey_Question__c);
             
             
             if(!oppwithInventoryMap.containsKey(currRec.idCPL_Billing_Opportunity__c))
              {
                   oppwithInventoryMap.put(currRec.idCPL_Billing_Opportunity__c,new List<Inventory__c>{currRec});
                   
                   productNamesSet.add(currRec.Account__r.Branch__c+'-'+Industry);
              }
              else if(oppwithInventoryMap.containsKey(currRec.idCPL_Billing_Opportunity__c))
              {
                   oppwithInventoryMap.get(currRec.idCPL_Billing_Opportunity__c).add(currRec);
                   productNamesSet.add(currRec.Account__r.Branch__c+'-'+Industry);
              }
              
                productNameMap.put(currRec.id,currRec.Account__r.Branch__c+'-'+Industry);
          
          }
       
       }
       
       
        for(OpportunityLineItem lineItem : [SELECT ListPrice,Id,product2.Name,pricebookentry.product2.name,OpportunityId,unitprice,quantity,pricebookentryid FROM OpportunityLineItem WHERE 
                                            OpportunityId IN :oppwithInventoryMap.keySet() AND pricebookentry.product2.name IN :productNamesSet])
        {
        
            for(Inventory__c currInv : oppwithInventoryMap.get(lineItem.OpportunityId))
            {
               if(productNameMap.containsKey(currInv.id))
               {
                  if(productNameMap.get(currInv.id) == lineItem.pricebookentry.product2.name)
                  {
                  
                 
                      
                   if(!lineItemsSet.contains(lineItem.id) && !inventoryIds.contains(currInv.id))
                    {
                       
                       Inventory__c updateInvRec = new Inventory__c();
                       updateInvRec.id = currInv.id;
                        updateInvRec.Product_Name__c = lineItem.product2.name;
                        updateInvRec.Product_Price__c = lineItem.unitprice;
                        updateInvRec.List_Price__c = lineItem.listprice;
                        updateInvRec.Quantity__c = lineItem.Quantity;
                         invList.add(updateInvRec);
                       
                        lineItemsSet.add(lineItem.id);
                        inventoryIds.add(currInv.id);
                    }
                  
                  }
               
               
               }
            
            }   
        }
        
        
        if(invList.size() > 0)
        {
            update invList;
        }
        
    
    }
    
    global void finish(Database.BatchableContext BC) {

      

    }
}