force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test-Use for Training only</fullName>
            </value>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_City__c</fullName>
    <label>Primary Billing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Country__c</fullName>
    <label>Primary Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
                <default>true</default>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_State__c</fullName>
    <label>Primary Billing State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Street__c</fullName>
    <label>Primary Billing Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Zip_Code__c</fullName>
    <label>Primary Billing Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Verbal_Consent__c.field-meta.xml
<CustomField>
    <fullName>Verbal_Consent__c</fullName>
    <label>Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <color>#33CC00</color>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
                <color>#FF0000</color>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Art_File__c.field-meta.xml
<CustomField>
    <fullName>Art_File__c</fullName>
    <label>Art File</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Back_pdf__c.field-meta.xml
<CustomField>
    <fullName>Back_pdf__c</fullName>
    <label>Back PDF</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
            <value>
                <fullName>CO-Colorado_Springs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forward_to_number__c.field-meta.xml
<CustomField>
    <fullName>Forward_to_number__c</fullName>
    <label>Forward To Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Front_pdf__c.field-meta.xml
<CustomField>
    <fullName>Front_pdf__c</fullName>
    <label>Front PDF</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Operational_Stages__c.field-meta.xml
<CustomField>
    <fullName>Operational_Stages__c</fullName>
    <label>Operations Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage_Types__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Docusign Received</fullName>
            </value>
            <value>
                <fullName>Billing Setup</fullName>
            </value>
            <value>
                <fullName>DID Setup</fullName>
            </value>
            <value>
                <fullName>Gift Card Awaiting Artwork</fullName>
            </value>
            <value>
                <fullName>Gift Card Graphic Design</fullName>
            </value>
            <value>
                <fullName>Gift Card Proof Sent to Client</fullName>
            </value>
            <value>
                <fullName>Gift Card Pending</fullName>
            </value>
            <value>
                <fullName>Gift Card Client Approved</fullName>
            </value>
            <value>
                <fullName>Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Gift Card Proof Approved</fullName>
            </value>
            <value>
                <fullName>Gift Card Ordered</fullName>
            </value>
            <value>
                <fullName>Gift Card Received &amp; in Fulfillment</fullName>
            </value>
            <value>
                <fullName>Gift Card Active Customer</fullName>
            </value>
            <value>
                <fullName>Deactivated Customer</fullName>
            </value>
            <value>
                <fullName>Call Center DID</fullName>
            </value>
            <value>
                <fullName>Cancel Pending</fullName>
            </value>
            <value>
                <fullName>Gift Card Docusign Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_ChoosepricebookController.cls
/***************************************************************
* Description : This test class created for Choosepricebookcontroller class.
* Modified By: Ganesh
* Modified on:
* Description: Updated the test class as per best practices. 
****************************************************************/

@isTest(seealldata=false)
private class Test_ChoosepricebookController
{
    // creating test records.
    @testsetup static void createtestdata()
    {
        String oppRecTypeId = Schema.Sobjecttype.Opportunity.getRecordTypeInfosByName().get('nuHome Door Tag Script').getRecordTypeId();
        //Account Creation
        Account acc = new Account();
        acc.name = 'testAccount';  
        acc.Primary_Billing_City__c='Sunnyvale';    
        acc.Primary_Billing_Country__c='US';
        acc.Primary_Billing_State__c='CA';
        acc.Primary_Billing_Street__c='260 N Mathilda Ave';
        acc.Primary_Billing_Zip_Code__c='94086'; 
        acc.branch__c = 'CA-San_Jose'; 
        acc.Phone = '1234567892';
        acc.verbal_consent__c = 'Yes';  
        insert acc;
        system.assertnotEquals(null, acc.id);
        
        Pricebook2 pbook = new Pricebook2();
        pbook.Name = 'nuHome Hot Leads - Tier 2';
        pbook.IsActive = True;
        insert pbook;
        system.assertnotEquals(null, pbook.id);
        
        //Opportunity creation
        Opportunity opp = new Opportunity();
        opp.accountId = acc.Id;
        opp.name='TestOpp';
        opp.closeDate = date.today();
        opp.Operational_Stages__c = 'Gift Card Active Customer';
        opp.Forward_to_number__c = 'Test';
        opp.stageName = 'Needs Analysis';
        opp.Art_File__c='sunnyvale'; 
        opp.Back_pdf__c=2;
        opp.Front_pdf__c=2;
        //opp.pricebook2Id = pbook.id;
        opp.recordTypeId = oppRecTypeId;
        opp.OB_Operation_Stage__c = 'Active';
        insert opp;
        system.assertnotEquals(null, opp.id);
    }
    
    static testmethod void createOpp()
    {
        Opportunity opp = [select id from Opportunity limit 1];
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        ChoosepricebookController myextention = new ChoosepricebookController(sc); 
        myextention.selectedPriceBookId = '0';
        myextention.savePriceBookName();
        test.stopTest();
    }
    static testmethod void assignPricebook()
    {
        Opportunity opp = [select id from Opportunity limit 1];
        Pricebook2 pb = [select id from Pricebook2 limit 1];
        Update new Opportunity(id = opp.id,pricebook2Id = pb.id);
        Opportunity opp1 = [select id from Opportunity limit 1];
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(opp1);
        ChoosepricebookController myextention = new ChoosepricebookController(sc); 
        myextention.savePriceBookName();
        test.stopTest();
    }
    
}