force-app/main/default/objects/Account/fields/bypass_PB__c.field-meta.xml
<CustomField>
    <fullName>bypass_PB__c</fullName>
    <defaultValue>false</defaultValue>
    <label>bypass PB</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Captures the date at which the package was dropped and delivered to the customer.</description>
    <inlineHelpText>Captures the date at which the package was dropped and delivered to the customer.</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Scan_Code__c.field-meta.xml
<CustomField>
    <fullName>Scan_Code__c</fullName>
    <description>The scan code of the card</description>
    <inlineHelpText>Identifies Batch / Order / Card / Box</inlineHelpText>
    <label>Scan Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>To keep the county name. It is not unique. The same county name can exist for different states.</description>
    <label>County</label>
    <nameField>
        <displayFormat>CN-{000}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>To hold the state of the branch</description>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Cheetah_Driver_Code__c.field-meta.xml
<CustomField>
    <fullName>Cheetah_Driver_Code__c</fullName>
    <externalId>true</externalId>
    <label>Cheetah Driver Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Driver_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Driver_Lead_Status__c</fullName>
    <label>Driver Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Data</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Hung_Status__c.field-meta.xml
<CustomField>
    <fullName>Hung_Status__c</fullName>
    <label>Hung Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrived</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hung</fullName>
            </value>
            <value>
                <fullName>COMPLETED GATED</fullName>
            </value>
            <value>
                <fullName>Gated</fullName>
            </value>
            <value>
                <fullName>Cant Find</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Invld</fullName>
            </value>
            <value>
                <fullName>Remove: Management</fullName>
            </value>
            <value>
                <fullName>Too Far</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Wrong House Number</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Remove: Gated</fullName>
            </value>
            <value>
                <fullName>Remove: Aging</fullName>
            </value>
            <value>
                <fullName>Sent To Cheetah</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Gio - In Process</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Access Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/IsRecent__c.field-meta.xml
<CustomField>
    <fullName>IsRecent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This filed used to identify the recently created Delivery Object record.</description>
    <label>IsRecent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/No_of_Attempts__c.field-meta.xml
<CustomField>
    <fullName>No_of_Attempts__c</fullName>
    <description>This field is used to store the number of attempts the Delivery Object record is  created for an Account</description>
    <label>Attempt Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Scan_Code__c.field-meta.xml
<CustomField>
    <fullName>Scan_Code__c</fullName>
    <label>Scan Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Status_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Updated_Date__c</fullName>
    <description>This filed will capture the date in which the status is get updated by Cheetha</description>
    <label>Status Updated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Welcome_Gift__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Gift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Welcome Gift</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Welcome Gift Deliveries</relationshipLabel>
    <relationshipName>Welcome_Gift</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <label>ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift_Card_Orders__c/Gift_Card_Orders__c.object-meta.xml
<CustomObject>
    <label>Gift Card Order</label>
    <nameField>
        <label>Gift Card Orders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Card Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Card_Orders__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Gift Card Orders</relationshipLabel>
    <relationshipName>Gift_Card_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift_Card_Orders__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associating Gift Card under User Address Object</description>
    <label>User Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Parent_Gift_Card_Order__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Gift Card Orders</relationshipLabel>
    <relationshipName>Gift_Card_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Respond_Date_Created_by__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date_Created_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It will holds the value of user who updated the respond date</description>
    <label>Respond Date Created by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Scan_code__c.field-meta.xml
<CustomField>
    <fullName>Scan_code__c</fullName>
    <description>The scan code of the card</description>
    <inlineHelpText>Identifies Batch / Order / Card / Box</inlineHelpText>
    <label>Scan code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DeliveryObjtTriggerHelper.cls
/*
 * Diaco
 * @author             Jull Quintero Daza
 * Project:            Delivery Object Trigger unifications
 * TestClass:          DeliveryObjtTriggerTest
 * Description:        Helper
 *
 * Changes (Version)
 * _________________________________________
 *            No.        Date            Author                    Description
 *            ____    __________        __________________      _____________________________________
 * @version    1.0    01-21-2021         Jull Quintero D         Initial implementation of the class.
 **/

public class DeliveryObjtTriggerHelper {

    private static Id invId;
    private static Id getDriverInvId {
        get {
            if ( invId == null ) {
                invId = [SELECT Id FROM Driver__c WHERE name='Invalid Driver' LIMIT 1]?.Id;
            }
            return invId;
        }
    }

    /*
     * This method is responsible to set delivery Fields
     * 
     * This method is run Before insert and update
     * 
     * This method is used in:
     * DeliveryObject
     * 
     * @param List Delivery
     **/
    public static void setDeliveryFields(List<Delivery_Object__c> deliveries,Map<Id,Delivery_Object__c> oldMapDeliveries,Boolean isInsert, Boolean IsUpdate) 
    {
        set<string> scanCodeSet = new set<string>();
        set<String> driverCodeSet = new set<String>();
        Integer deliverieSize = deliveries.size();

        for (Integer i = 0; i < deliverieSize; i++) {
            Delivery_Object__c current = deliveries[i];
            Delivery_Object__c old =  isUpdate ? oldMapDeliveries.get(current.Id) : null;

            if ( isUpdate ) {  
                // update GiftFields
                if( current.Scan_Code__c != null ) {
                    scanCodeSet.add(current.Scan_Code__c);
                    if(current.Scan_Code__c.length() >= 9) {
                        scanCodeSet.add(current.Scan_Code__c.substring(0,9)+' 0000 0000');
                    }
                } 
            }     

            // assign driver
            driverCodeSet.add(current.Cheetah_Driver_Code__c); 
        }

        if( !driverCodeSet.isEmpty() ) assigndriver(deliveries,oldMapDeliveries,driverCodeSet,isInsert,IsUpdate);
        if( !scanCodeSet.isEmpty() ) setGiftFields(deliveries,scanCodeSet);
    }


    /*
     * This method is responsible to set delivery Fields: 
     * Welcome_Gift__c, Parent_Gift_Card_Order__c
     * 
     * This method is run Before insert and update
     * 
     * This method is used in:
     * this class
     * 
     * @param List Delivery
     * @param giftcard (Set<string>) 
     **/
    private static void setGiftFields(List<Delivery_Object__c> deliveries,Set<string> giftcard)
    { 
        Map<string,id> giftCardsMap = new Map<string,id>();
        List<Gift_Card_Orders__c> GiftCardOrders = [SELECT id,name From Gift_Card_Orders__c WHERE name IN :giftcard];

        Integer GiftCardOrdersSize = GiftCardOrders.size();
        for (Integer i = 0; i < GiftCardOrdersSize; i++) {
            Gift_Card_Orders__c current = GiftCardOrders[i];
            if(!giftCardsMap.containsKey(current.name)) {
                giftCardsMap.put(current.name,current.id);
            }
        }

        Integer deliverieSize = deliveries.size();
        for (Integer i = 0; i < deliverieSize; i++) {
            Delivery_Object__c current = deliveries[i];
            String scanCode;
            if(current.Scan_Code__c != null) {
                current.Welcome_Gift__c = giftCardsMap.get(current.Scan_Code__c);
                if(current.Scan_Code__c.length() >= 9) {
                    scanCode = current.Scan_Code__c.substring(0,9)+' 0000 0000';
                    current.Parent_Gift_Card_Order__c = giftCardsMap.get(scanCode);            
                }
            }
        }
    }


    /*
     * This method is responsible to Assign driver 
     * Cheetah_Driver_Code__c
     * This method is run Before insert and update
     * 
     * This method is used in:
     * This class
     * 
     * @param List Delivery, Map Old Delivery
     **/
    private static void assigndriver(List<Delivery_Object__c> deliveries, Map<Id,Delivery_Object__c> oldMapDeliveries,set<String> driverCodeSet,Boolean isInsert, Boolean IsUpdate ) 
    {
        map<String,String> drNameVsId = new map<String,String>();

        List<Driver__c> drivers =  [SELECT Id,ID__c,name FROM Driver__c WHERE ID__c IN:driverCodeSet];
        Integer driverSize = drivers.size();
        for (Integer i = 0; i < driverSize; i++) {
            Driver__c current = drivers[i];
            drNameVsId.put(current.ID__c,current.Id);
        }
        Integer deliverieSize = deliveries.size();
        for (Integer i = 0; i < deliverieSize; i++) {
            Delivery_Object__c current = deliveries[i];
            Boolean changeDriverCode = false;
            if( isInsert ) {
                changeDriverCode = current.Cheetah_Driver_Code__c != null && current.Cheetah_Driver_Code__c != '';
            }else if ( isUpdate ) {
                Delivery_Object__c old = oldMapDeliveries.get(current.Id);
                changeDriverCode = current.Cheetah_Driver_Code__c != null && current.Cheetah_Driver_Code__c != '' && current.Cheetah_Driver_Code__c != old.Cheetah_Driver_Code__c;
            }
            if(drNameVsId.containsKey(current.Cheetah_Driver_Code__c))
                current.Driver__c = drNameVsId.get(current.Cheetah_Driver_Code__c);
            else if( changeDriverCode )
                current.Driver__c = getDriverInvId; 
        } 
    }
    
    /*
     * This method is responsible to update user Address Scan_Code__c
     * 
     * This method is run After insert and update
     * 
     * This method is used in:
     * DeliveryObject
     * 
     * @param List Delivery, Map Old Delivery
     **/
    public static void setUserAddresScanCode(List<Delivery_Object__c> deliveries, Map<Id,Delivery_Object__c> oldMapDeliveries,Boolean isInsert, Boolean isUpdate) 
    {
        map<Id,String> scanCodeMap = new map<ID,String>();
        List<User_Address__c> userAddress = new List<User_Address__c>();
        
        Integer deliverieSize = deliveries.size();
        for (Integer i = 0; i < deliverieSize; i++) {
            Delivery_Object__c current = deliveries[i];
            Boolean changeScanCode = false;
            if( isInsert ) {
                changeScanCode = current.Scan_Code__c != null && current.Scan_Code__c != '' && current.User_Address__c != null;
            }else if( isUpdate ) {
                Delivery_Object__c old = oldMapDeliveries.get(current.Id);
                changeScanCode = current.Scan_Code__c != null && current.Scan_Code__c != '' && current.User_address__c != null 
                && current.Scan_Code__c != old.Scan_Code__c;
            }
            if( changeScanCode ) scanCodeMap.put(current.User_Address__c,current.Scan_Code__c);
            
        }

        if( !scanCodeMap.isEmpty() ) {
            for(Id userAddressId : scanCodeMap.keySet()) {
                userAddress.add(new User_Address__c(Id = userAddressId,Scan_Code__c = scanCodeMap.get(userAddressId)));
            }
        }
        TriggerHandler.bypass('UserAddressTrigger');
            update userAddress;
        TriggerHandler.clearBypass('UserAddressTrigger');
    }

    /*
     *Created By : Sailappa Vignesh P G
     *Created Date : 2/17/2016
     * Update field Driver_Lead_Status__c
     * 
     * This method is run Aftert update
     * 
     * This method is used in:
     * this class
     * 
     * @param List Delivery
     * @param Old Map Delvery
     **/
    public static void setDriverLeadStatus(List<Delivery_Object__c> deliveries,Map<Id,Delivery_Object__c> oldMapDeliveries) 
    { 
        Set<Id> userAddresIds= new Set<Id>();

        Integer deliverieSize = deliveries.size();
        for (Integer i = 0; i < deliverieSize; i++) {
            Delivery_Object__c current = deliveries[i];
            Delivery_Object__c old = oldMapDeliveries.get(current.Id);
            Boolean ischangeDeliveryDate = current.Delivery_Date__c != null && old.Delivery_Date__c != current.Delivery_Date__c && current.Hung_status__c == 'Hung' && current.Driver_Lead_Status__c == null && current.User_Address__c != null;
            if( ischangeDeliveryDate ) {
                userAddresIds.add(current.User_Address__c);
            }
        }

        List<Delivery_Object__c> toUpdateDeliveries = new List<Delivery_Object__c>();
        Set<Id> userAddressIds = new Set<Id>();
        List<Delivery_Object__c> dls = [SELECT id,bypass_PB__c,Name,Driver_Lead_Status__c,Hung_Status__c,User_Address__c,Delivery_Date__c,Person_Account__c,User_Address__r.Respond_date__c FROM Delivery_Object__c WHERE User_Address__c IN: userAddresIds AND (Name ='1' OR Name ='2') AND Hung_Status__c = 'Hung' ORDER BY createdDate DESC];
        for(Delivery_Object__c current : dls ) {        
            if ( current.Delivery_Date__c != null ) {
                if( current.Name == '1' ) {
                    if ( !userAddressIds.contains(current.User_Address__c ) ) {
                        //Here we can make sure that, respond date always equal to the delivery date or not
                        if( current.Delivery_Date__c.Date() == current.User_Address__r.Respond_date__c ) {
                            userAddressIds.add(current.User_Address__c );
                            if( current.Driver_Lead_Status__c == null ) {
                                toUpdateDeliveries.add(new Delivery_Object__c(id = current.id, bypass_PB__c=!current.bypass_PB__c, Driver_Lead_Status__c = 'Data'));
                            }
                        }
                    }
                    else if( current.Driver_Lead_Status__c == 'Data' ) {
                        toUpdateDeliveries.add(new Delivery_Object__c(id = current.id, bypass_PB__c=!current.bypass_PB__c,Driver_Lead_Status__c = ''));
                    }
                
                }else if ( current.Name == '2' ) {
                    if( current.Delivery_Date__c.Date() < current.User_Address__r.Respond_date__c ) {
                    
                        if(current.Driver_Lead_Status__c == null){
                            toUpdateDeliveries.add( new Delivery_Object__c(id = current.id, bypass_PB__c=!current.bypass_PB__c,Driver_Lead_Status__c = 'Data') );
                        }
                    }
                }  
            } 
        }

        if( !toUpdateDeliveries.isEmpty() ) {
            TriggerHandler.bypass('DeliveryObjectTrigger');
                update toUpdateDeliveries;
            TriggerHandler.clearBypass('DeliveryObjectTrigger');
        }
    }

    /*
     *Created By : Sailappa Vignesh P G
     *Created Date : 2/17/2016
     * Update Field IsRecent__c,Status_Updated_Date__c 
     * 
     * This method is run Aftert insert
     * 
     * This method is used in:
     * this class
     * 
     * @param List Delivery
     * @param Old Map Delvery
     **/
    public static void setDeliveryIsRecent(list<Delivery_Object__c> deliveryObjectTriggerInstance)
    {
        List<String> userAddressIds = new List<String>();
        List<Delivery_Object__c> deliveryObjectLst =  new List<Delivery_Object__c>();
        Map<ID,Map<String,Integer>> deliveryObjectCountMap = new Map<ID,map<String,Integer>>(); 
        for(Delivery_Object__c currDeliveryObject : deliveryObjectTriggerInstance){
            userAddressIds.add(currDeliveryObject.User_Address__c); 
        }

        for(AggregateResult aggregateResult : [SELECT User_Address__c,count(id),Name FROM Delivery_Object__c WHERE User_Address__c in :userAddressIds group by User_Address__c,Name]) {
            if(deliveryObjectCountMap.get((ID)aggregateResult.get('User_Address__c')) == null){
                deliveryObjectCountMap.put((ID)aggregateResult.get('User_Address__c'), new Map<String,Integer>{(String)aggregateResult.get('Name') => (Integer)aggregateResult.get('expr0')});
            }
            else{
                deliveryObjectCountMap.get((ID)aggregateResult.get('User_Address__c')).put((String)aggregateResult.get('Name'), (Integer)aggregateResult.get('expr0'));
            } 
        }
        
        for(Delivery_Object__c currDeliveryObject : deliveryObjectTriggerInstance){                
            Delivery_Object__c newDeliveryObject = new Delivery_Object__c();
            newDeliveryObject.id = currDeliveryObject.Id;  
            newDeliveryObject.No_of_Attempts__c = (deliveryObjectCountMap.containsKey(currDeliveryObject.User_Address__c) ? deliveryObjectCountMap.get(currDeliveryObject.User_Address__c).get((string)currDeliveryObject.Name) : 0);
            newDeliveryObject.IsRecent__c = true;
            newDeliveryObject.Status_Updated_Date__c = System.today();
            deliveryObjectLst.add(newDeliveryObject);
        }    
        for(Delivery_Object__c currDeliveryObject : [SELECT ID,IsRecent__c,bypass_PB__c FROM Delivery_Object__c WHERE User_Address__c in :userAddressIds and Id not in : deliveryObjectTriggerInstance]){
            Delivery_Object__c newDeliveryObject = new Delivery_Object__c();
            newDeliveryObject.id = currDeliveryObject.Id;
            newDeliveryObject.IsRecent__c = false;
            newDeliveryObject.bypass_PB__c = !currDeliveryObject.bypass_PB__c;     
            deliveryObjectLst.add(newDeliveryObject);
        }
        if( !deliveryObjectLst.isEmpty() ) {
            TriggerHandler.bypass('DeliveryObjectTrigger');
                update deliveryObjectLst;
            TriggerHandler.clearBypass('DeliveryObjectTrigger');
        }   
    }

    /** 
    @author: Jull Quintero D - 07-06-2021
    * This method is responsible to update Account Geolocation when Address is change
    * This method is run and after Update.    
    * This method is used in:
    * DeliveryObjtTriggerHandler
    * 
    * @param List Delivery
    * @param Map delivery      
    **/
    public static void getAccountGeoLocation(List<Delivery_Object__c> deliveries, Map<Id,Delivery_Object__c> oldeliveryMap) {
        Map<Id,Account> accounts = new Map<Id,Account>();
        Integer deliverieSize = deliveries.size();
        for (Integer i = 0; i < deliverieSize; i++) {
            Delivery_Object__c current = deliveries[i];
            Delivery_Object__c oldelivery = oldeliveryMap.get(current.Id);

            if( DeliveryEval.geoCodeChange(current, oldelivery) && !accounts.containsKey(current.Person_Account__c) ) {
                accounts.put( 
                    current.Person_Account__c,
                    new Account(
                        Id = current.Person_Account__c,
                        Street__c = current.Street__c,
                        City__c = current.City__c,
                        State__c = current.State__c,
                        Zip__c = current.Zip__c,
                        County__c = current.County__c,
                        BillingLongitude = current.Maps_longitude__c,
                        BillingLatitude = current.Maps_latitude__c
                    )
                );
            }    
        }
    
        if( !accounts.isEmpty() ) {
            System.debug('Delivery Update Account');
            update accounts.values(); 
        }
    }
}