force-app/main/default/objects/Account/fields/bypass_PB__c.field-meta.xml
<CustomField>
    <fullName>bypass_PB__c</fullName>
    <defaultValue>false</defaultValue>
    <label>bypass PB</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Canvasser_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Canvasser_Disposition__c</fullName>
    <label>Canvasser Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Moved In</fullName>
            </value>
            <value>
                <fullName>Not Home</fullName>
            </value>
            <value>
                <fullName>Consent Y</fullName>
            </value>
            <value>
                <fullName>Consent N</fullName>
            </value>
            <value>
                <fullName>Gated Community</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Find</fullName>
            </value>
            <value>
                <fullName>Renter</fullName>
            </value>
            <value>
                <fullName>Lease back</fullName>
            </value>
            <value>
                <fullName>Card Sent</fullName>
            </value>
            <value>
                <fullName>DT Left</fullName>
            </value>
            <value>
                <fullName>Duplicate Tag</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Captured_Date__c.field-meta.xml
<CustomField>
    <fullName>Consent_Captured_Date__c</fullName>
    <description>The date that the consent was captured.</description>
    <inlineHelpText>The date that the consent was captured.</inlineHelpText>
    <label>Consent Captured Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dispositioned_By__c.field-meta.xml
<CustomField>
    <fullName>Dispositioned_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dispositioned By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Do_Not_Call_Date_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Call_Date_Stamp__c</fullName>
    <description>Captures the date at which the rep set the Person Account to Do Not Call per customer request.</description>
    <label>Do Not Call Date Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Geocode_Accuracy__c.field-meta.xml
<CustomField>
    <fullName>Geocode_Accuracy__c</fullName>
    <label>Geocode Accuracy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Canvasser_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Last_Canvasser_Attempt__c</fullName>
    <label>Last Canvasser Attempt</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Who_Captured_Verbal_Consent__c.field-meta.xml
<CustomField>
    <fullName>User_Who_Captured_Verbal_Consent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup field to link to the user who captured consent so it can be used in reporting.</description>
    <inlineHelpText>This is a lookup field to link to the user who captured consent so it can be used in reporting.</inlineHelpText>
    <label>Consent By User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Verbal_Consent__c.field-meta.xml
<CustomField>
    <fullName>Verbal_Consent__c</fullName>
    <label>Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <color>#33CC00</color>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
                <color>#FF0000</color>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Verbal_Consent_Date_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Verbal_Consent_Date_Stamp__c</fullName>
    <description>The date that the consent was captured.</description>
    <inlineHelpText>The date that the consent was captured.</inlineHelpText>
    <label>Consent Date Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Geo_Accuracy__c.field-meta.xml
<CustomField>
    <fullName>Geo_Accuracy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Geo Accuracy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>To keep the county name. It is not unique. The same county name can exist for different states.</description>
    <label>County</label>
    <nameField>
        <displayFormat>CN-{000}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>To hold the state of the branch</description>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Geocode_Accuracy__c.field-meta.xml
<CustomField>
    <fullName>Geocode_Accuracy__c</fullName>
    <label>Geocode Accuracy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Hung_Status__c.field-meta.xml
<CustomField>
    <fullName>Hung_Status__c</fullName>
    <label>Hung Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrived</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hung</fullName>
            </value>
            <value>
                <fullName>COMPLETED GATED</fullName>
            </value>
            <value>
                <fullName>Gated</fullName>
            </value>
            <value>
                <fullName>Cant Find</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Invld</fullName>
            </value>
            <value>
                <fullName>Remove: Management</fullName>
            </value>
            <value>
                <fullName>Too Far</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Wrong House Number</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Remove: Gated</fullName>
            </value>
            <value>
                <fullName>Remove: Aging</fullName>
            </value>
            <value>
                <fullName>Sent To Cheetah</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Gio - In Process</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Access Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <formula>Address__r.County__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>County</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/PersonMobilePhone__c.field-meta.xml
<CustomField>
    <fullName>PersonMobilePhone__c</fullName>
    <description>This field will store the person Mobile Phone number</description>
    <label>PersonMobilePhone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field will store the person Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Verbal_Consent__c.field-meta.xml
<CustomField>
    <fullName>Verbal_Consent__c</fullName>
    <formula>Text(UserAccount__r.Verbal_Consent__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Verbal Consent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHelper.cls
/** 
 * Diaco
 * @author             Jull Quintero Daza
 * Project:            Account Trigger
 * TestClass:          AccountTriggerTest
 * Description:        Helper
 *
 * Changes (Version)
 * _________________________________________
 *            No.        Date            Author                    Description
 *            ____    __________        __________________      _____________________________________
 * @version    1.0    09-11-2020         Jull Quintero D         Initial implementation of the class.
 * @version    1.1    11-03-2020         Jull Quintero D         Implementation of the method geoAccuracy

 **/

public  class AccountTriggerHelper {
    private static Boolean UpdateDelivety = true;

    /*
     * This method is responsible update account.Respond_Date__c
     * This method is run before Insert and before Update.
     * 
     * This method is used in:
     * AccountTrigger
     * 
     * @param List account, map account
     */
    public static void responseDate(List<Account> accounts, Map<Id,Account> oldMap, Boolean isInsert, Boolean isUpdate){        
        integer accountsLength = accounts.size();
        for (Integer i = 0; i < accountsLength; i++) {
            Account acc = accounts[i];        
            if(acc.IsPersonAccount){
                if( isInsert && (acc.phone != null || acc.personmobilephone != null)){
                    acc.Respond_Date__c = System.today(); 
                }
                else if( (isUpdate && acc.Respond_Date__c == null && 
                        ( (acc.phone != null && acc.phone != oldMap.get(acc.id).phone) ||
                        (acc.personmobilephone != null &&  acc.personmobilephone != oldMap.get(acc.id).personmobilephone)) ) )
                        {                            
                            acc.Respond_Date__c = System.today();                            
                        }           
            }
        }
    } 

    /**
     * @author: Jull Quintero D - 11-03-2020
     * This method is responsible create a contract for Data Integration Rule (Geocodes for Account Billing Address) 
        updating account field Geocode_Accuracy_c
     * This method is run After Insert After Update 
     * This method is used in:
     * AccountTrigger
     * 
     * @param Map account
     * @param Map Account
     * @param Boolean isInsert
     * @param Boolean isUpdate      
     **/
    public static void geoAccuracy(List<Account> accounts, Map<Id,Account> accountsMap, Map<Id,Account> oldAcctMap, Boolean isInsert, Boolean isUpdate) {
        List<Contact> contacts = new List<Contact>();
        integer accountsLength = accounts.size();
        for (Integer i = 0; i < accountsLength; i++) {
            Account acc = accounts[i];            
            if( diacoKnifeFunc.getRecordTypeNameById('Account', acc.RecordTypeId) == 'Person Account' ) {
                Boolean isChanged = false;
                if( isInsert ) {
                    isChanged = AccountEval.addressNoNull(acc);
                }else if( isUpdate ) {
                    Account oldAcct = oldAcctMap.get(acc.Id);
                    isChanged = AccountEval.addressChange(acc, oldAcct);
                }
                if( isChanged ) {
                        Contact contact = new Contact();
                        contact.FirstName = acc.FirstName;
                        contact.LastName = acc.LastName;
                        contact.Person_Account__c = acc.Id;
                        contact.MailingCity = acc.City__c;
                        contact.MailingState = acc.State__c;
                        contact.MailingStreet = acc.Street__c;
                        contact.MailingPostalCode = acc.Zip__c;
                        contact.MailingCountry = acc.County__c;
                        contact.Geo_Accuracy__c = true;
                        contacts.add(contact);
                    }
                }   
        }
        if( !contacts.isEmpty() ) {
            System.debug('>> Geo contact Data.com');
            insert contacts;
        }
    }  

    /** 
    @author: Jull Quintero D - 07-06-2021 
    * This method is responsible to update Deliveries Geolocation when Address is change
    * This method is run and after Update.    
    * This method is used in:
    * AccountTrigger
    * 
    * @param Map NewAccount
    * @param Map oldAccount      
    **/
    public static void getDeliveryGeoLocation(Map<Id,Account> newAccounts, Map<Id,Account> oldAcctMap) {
        if ( AccountTriggerHelper.UpdateDelivety ) {
            set<Id> personAccIds = new set<Id>();
            List<Account> accts = newAccounts.values();
            integer accountSize = newAccounts.size();
            for (Integer i = 0; i < accountSize; i++) {
                Account current = accts[i];
                Account oldAcct = oldAcctMap.get(current.Id);
                if( !personAccIds.contains(current.Id) && AccountEval.geoCodeChange(current, oldAcct) ) {
                    personAccIds.add(current.Id);
                }
            }
            
            if( !personAccIds.isEmpty() ) {
                System.debug('>> Account geoCodeChange');
                List<Delivery_Object__c> deliveries = [
                    SELECT 
                        Id,
                        Person_Account__c,
                        bypass_PB__c 
                    FROM Delivery_Object__c 
                    WHERE Person_Account__c IN :personAccIds AND CreatedDate = THIS_MONTH AND Hung_Status__c != 'Hung' 
                    LIMIT 50000 
                    FOR UPDATE ];
    
                integer deliverySize = deliveries.size();
                List<Delivery_Object__c> updateDeliveries = new List<Delivery_Object__c>();
                for (Integer i = 0; i < deliverySize; i++) {
                    Delivery_Object__c current = deliveries[i];
                    Account acct = newAccounts.get(current.Person_Account__c);                                 
                    current.Street__c = acct.Street__c;
                    current.City__c  = acct.City__c;
                    current.State__c = acct.State__c;
                    current.Zip__c = acct.Zip__c;
                    current.County__c = acct.County__c;                
                    current.Geocode_Accuracy__c = acct.Geocode_Accuracy__c;
                    current.Maps_latitude__c = acct.BillingLatitude;
                    current.Maps_longitude__c = acct.BillingLongitude;
                    current.bypass_PB__c = !current.bypass_PB__c;
                    updateDeliveries.add(current);
                }
                
                TriggerHandler.bypass('DeliveryObjectTrigger');
                    if( !updateDeliveries.isEmpty() ) {
                        System.debug('>> update deliveries ' + updateDeliveries.size() );
                        update updateDeliveries;
                        AccountTriggerHelper.UpdateDelivety = false;
                    } 
                TriggerHandler.clearBypass('DeliveryObjectTrigger');
            }
        }
    }

    /*
     * This method is responsible to update  User_Address__c.Phone__c with Account.Phone
     * 
     * This method is run after Update.
     * 
     * This method is used in:
     * AccountTrigger
     * 
     * @param Map New Accounts, Map Old Accounts
     **/
    public static void setPhoneForUserAddress(Map<Id,Account> newMap, Map<Id,Account> oldMap) {
        
        boolean thereIsAChange = false;
        List<Account> acctsNew = newMap.values();
        integer acctsLength = acctsNew.size();
        for (Integer i = 0; i < acctsLength; i++) {
            Account accNew = acctsNew[i];            
            Account accOld = oldMap.get(accNew.Id);
            
            if(accNew.Phone != accOld.Phone || accNew.PersonMobilePhone != accOld.PersonMobilePhone){
                thereIsAChange = true;
                break;
            }
        }
        
        if(thereIsAChange){ 
            list<User_Address__c> userAddressListToUpdate = new list<User_Address__c>();           

            List<User_Address__c> userAddress = [SELECT Id,UserAccount__c,Phone__c,PersonMobilePhone__c,Respond_Date__c 
                                                FROM User_Address__c 
                                                WHERE UserAccount__c IN :newMap.keyset()];   
            integer userAddressLength = userAddress.size();
            for (Integer i = 0; i < userAddressLength; i++) {
                User_Address__c  usAddress = userAddress[i];
                Account currentAcct = newMap.get(usAddress.UserAccount__c);
                Account oldAcct = oldMap.get(currentAcct.Id);  

                Boolean ischangePhone = (currentAcct.Phone != null && currentAcct.Phone != oldAcct.Phone && currentAcct.Phone != usAddress.Phone__c);
                Boolean ischangePersonPhone = (currentAcct.PersonMobilePhone != null && currentAcct.PersonMobilePhone != oldAcct.PersonMobilePhone && 
                                                currentAcct.PersonMobilePhone != usAddress.PersonMobilePhone__c);

                if( currentAcct.Respond_Date__c == System.today() ) usAddress.Respond_Date__c =  currentAcct.Respond_Date__c;
                if( ischangePhone && ischangePersonPhone ) {

                    usAddress.Phone__c = currentAcct.Phone;    
                    usAddress.PersonMobilePhone__c = currentAcct.PersonMobilePhone;
                    userAddressListToUpdate.add(usAddress);  
                }else if( ischangePhone ) {

                    usAddress.Phone__c = currentAcct.Phone;    
                    userAddressListToUpdate.add(usAddress); 
                }else if( ischangePersonPhone ) {

                    usAddress.PersonMobilePhone__c = currentAcct.PersonMobilePhone;
                    userAddressListToUpdate.add(usAddress); 
                }                  
            }
            if(!userAddressListToUpdate.isEmpty()) {
                TriggerHandler.bypass('UserAddressTrigger');
                    update userAddressListToUpdate; 
                TriggerHandler.clearBypass('UserAddressTrigger');
            }
        }
    }

    /*
     * This method is responsible to update  Opportunity.Ownerid
     * 
     * This method is run after Update.
     * 
     * This method is used in:
     * AccountTrigger
     * 
     * @param Map New Accounts, Map Old Accounts
     **/
    public static void opportunityonChangeOWner(Map<Id,Account> newMap, Map<Id,Account> oldMap) {
        List<Opportunity> opportunities = [ SELECT id,Ownerid,Accountid,StageName 
                                            FROM Opportunity 
                                            WHERE Accountid in :newMap.keyset()];
        List<Opportunity> opports = new List<Opportunity>(); 

        integer opportunitiesLength = opportunities.size();
        for (Integer i = 0; i < opportunitiesLength; i++) 
        {
            Opportunity opty = opportunities[i];
            if(opty.StageName <> 'Closed Lost'){
                if(newMap.get(opty.Accountid).Ownerid <> oldMap.get(opty.Accountid).Ownerid){
                    opty.Ownerid=newMap.get(opty.Accountid).Ownerid;
                    opports.add(opty);
                }
            }
        }
        if(!opports.isEmpty()){
            update opports;
        }
    }

    /*
     * This method is responsible to change values account fields
     * 
     * This method is run before Update.
     * 
     * This method is used in:
     * AccountTrigger
     * 
     * @param Account List
     **/
    public static void setAccounts(List<Account> accounts,Map<Id,Account> oldAccMap) {
        
        integer accountsLength = accounts.size();
        for (Integer i = 0; i < accountsLength; i++) {
            Account acct = accounts[i];
            Account oldAcct = oldAccMap.get(acct.id);

            AddDoNotCallDateStamp(acct);
            
            // consent Info
            if( acct.Verbal_Consent__c != oldAcct.Verbal_Consent__c ) setConsentInfo(acct);

            // Canvasser Info
            if( acct.Canvasser_Disposition__c != oldAcct.Canvasser_Disposition__c ) setCanvasserInfo(acct);

            // location changes manually in salesforce map    
            if( AccountEval.mapLayerChangeLocation(acct, oldAcct) ) setMapLocationInfo(acct);
            
        } 
    }

    /*
     * This method is responsible to change Accouunt.Do_Not_Call_Date_Stamp__c 
     *  
     * This method is used in:
     * setAccounts - This class
     * 
     * @param Account record
     **/
    private static void AddDoNotCallDateStamp(Account accts) {
        
        //if Do Not Call is checked, set the Do Not Call Date Stamp to todays date and time, else keep blank
        //As per latest requirement from cody, if donotcall is true and timestamp is empty then only fill the current day
        if(accts.PersonDoNotCall == True && accts.Do_Not_Call_Date_Stamp__c == null) {
            
            accts.Do_Not_Call_Date_Stamp__c = System.Now();
        }
        else if(accts.PersonDoNotCall == False) {
            
            accts.Do_Not_Call_Date_Stamp__c = null;
        }       
    }

    /**
     * @author Jull Quintero D - 06-09-2021
     * This method is responsible to set consent info 
     *  
     * This method is used in:
     * setAccounts - This class
     * 
     * @param Account(Account)
     **/
    private static void setConsentInfo(Account account) {
        account.User_Who_Captured_Verbal_Consent__c = userInfo.getUserId();
        account.Verbal_Consent_Date_Stamp__c = Datetime.now();
        account.Consent_Captured_Date__c = Date.today();
    }

    /**
     * @author Jull Quintero D - 06-24-2021
     * This method is responsible to set canvasser info 
     *  
     * This method is used in:
     * setAccounts - This class
     * 
     * @param Account(Account)
     **/
    private static void setCanvasserInfo(Account account) {
        account.Last_Canvasser_Attempt__c = Datetime.now();
        account.Dispositioned_By__c = userInfo.getUserId();
    }

    /**
     * @author Jull Quintero D - 07-08-2021
     * This method is responsible to set location info of changend latitude and longitude in salesforce map
     *  
     * This method is used in:
     * setAccounts - This class
     * 
     * @param Account(Account)
     **/
    private static void setMapLocationInfo(Account account) {
        System.debug('>> Account locationChange is Manual ');
        account.Geocode_Accuracy__c = 'Manual';
        account.Location_Updated__c = System.Now();
        account.Location_updated_by__c = UserInfo.getUserId();
    }
}