force-app/main/default/objects/Account/fields/Canvasser_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Canvasser_Disposition__c</fullName>
    <label>Canvasser Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Moved In</fullName>
            </value>
            <value>
                <fullName>Not Home</fullName>
            </value>
            <value>
                <fullName>Consent Y</fullName>
            </value>
            <value>
                <fullName>Consent N</fullName>
            </value>
            <value>
                <fullName>Gated Community</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Find</fullName>
            </value>
            <value>
                <fullName>Renter</fullName>
            </value>
            <value>
                <fullName>Lease back</fullName>
            </value>
            <value>
                <fullName>Card Sent</fullName>
            </value>
            <value>
                <fullName>DT Left</fullName>
            </value>
            <value>
                <fullName>Duplicate Tag</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_Email__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Email__c</fullName>
    <label>Homeowner #2 Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_First_Name__c</fullName>
    <label>Homeowner #2 First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Last_Name__c</fullName>
    <label>Homeowner #2 Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Mobile__c</fullName>
    <label>Homeowner #2 Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Phone_Number__c</fullName>
    <label>Homeowner #2 Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_AC_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_AC_Units__c</fullName>
    <label>Number of AC Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>+4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Stories__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Stories__c</fullName>
    <label>Number of Stories</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Pool__c.field-meta.xml
<CustomField>
    <fullName>Pool__c</fullName>
    <label>Pool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Verbal_Consent__c.field-meta.xml
<CustomField>
    <fullName>Verbal_Consent__c</fullName>
    <label>Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <color>#33CC00</color>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
                <color>#FF0000</color>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Year_Built__c.field-meta.xml
<CustomField>
    <fullName>Year_Built__c</fullName>
    <label>Year Built</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Cheetah_Driver_Code__c.field-meta.xml
<CustomField>
    <fullName>Cheetah_Driver_Code__c</fullName>
    <externalId>true</externalId>
    <label>Cheetah Driver Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Card_Orders__c/Gift_Card_Orders__c.object-meta.xml
<CustomObject>
    <label>Gift Card Order</label>
    <nameField>
        <label>Gift Card Orders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Card Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Card_Orders__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Gift Card Orders</relationshipLabel>
    <relationshipName>Gift_Card_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift_Card_Orders__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associating Gift Card under User Address Object</description>
    <label>User Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Parent_Gift_Card_Order__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Gift Card Orders</relationshipLabel>
    <relationshipName>Gift_Card_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Verbal_Consent__c.field-meta.xml
<CustomField>
    <fullName>Verbal_Consent__c</fullName>
    <formula>Text(UserAccount__r.Verbal_Consent__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Verbal Consent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verbal_Consent__c/Verbal_Consent__c.object-meta.xml
<CustomObject>
    <description>This object will holds the verbal consents records</description>
    <label>Verbal Consent</label>
    <nameField>
        <displayFormat>VC-{0000}</displayFormat>
        <label>Verbal Consent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verbal Consents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SiteMapsCanvasserTest.cls
@isTest
public class SiteMapsCanvasserTest {
    @TestSetup
    static void makeData() {

        // SMS
        dsms.diacoSmsExternalTest.setSetup();
        DiacoSMSettingsTest.consentCanvasser();

        // Account
        List<Account> accounts = new List <Account>();
        Id personAcctRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        for(Integer i=0;i<10;i++)
        {
            accounts.add(new Account(
                FirstName='test',
                BillingState = 'CA', LastName = 'Pass v2'+i,
                RecordTypeId = personAcctRecordTypeId,
                PersonDoNotCall =True,
                Verbal_Consent__c='No',
                phone=null));
        }
        insert accounts;


        // Delivery
        TestClassUtil.createZipcodeForBranch();
        TestClassUtil.createCheetahGiftCardOrder();
        TestClassUtil.createDriver();  
        TestClassUtil.createProductAndHungStatus();
        TestClassUtil.createBranch();
        TestClassUtil.createAddress(2);
        TestClassUtil.createUserAddress(2);
        TestClassUtil.createDeliveryParameter(1);

    }
    
    @IsTest
    static void test() {
        
        Test.startTest();
        
            Id giftCardOrderId = [SELECT Id FROM Gift_Card_Orders__c LIMIT 1]?.Id;
            Id driverId =  [SELECT Id FROM Driver__c LIMIT 1]?.Id;
            Id userAddressId = [SELECT ID FROM User_Address__c LIMIT 1]?.Id;

            List<Account> accounts = [SELECT Id,FirstName,LastName,Phone,PersonEmail,
                                    Street__c,Zip__c,State__c,City__c,Year_Built__c,Pool__c,
                                    Number_of_AC_Units__c,Number_of_Stories__c,
                                    Homeowner_2_First_Name__c,Homeowner_2_Last_Name__c,
                                    Homeowner_2_Email__c,Homeowner_2_Phone_Number__c,
                                    Homeowner_2_Mobile__c,Canvasser_Disposition__c 
                                    FROM Account ];       
                                    
            Decimal latitude = 10.3867885;         
            Decimal longitude = -75.4906915;

            Delivery_Object__c delivery = new Delivery_Object__c();        
            delivery.Person_Account__c = accounts[0].Id;
            delivery.Driver__c = driverId;
            delivery.name = '1';
            delivery.Parent_Gift_Card_Order__c = giftCardOrderId;
            delivery.User_Address__c = userAddressId;
            delivery.Cheetah_Driver_Code__c = '0';           
            
            insert delivery;

            SiteMapsCanvasserController.getDataAccount(accounts[0].Id,new List<String>{'Canvasser_Disposition__c'});
            SiteMapsCanvasserController.getDataAccount(delivery.Id,new List<String>{'Canvasser_Disposition__c'});
            SiteMapsCanvasserController.setAccount(accounts[0],latitude,longitude);

            // SMS Magic
            List<String> phoneNumbers = new List <String>();
            for(Integer i=0;i<2;i++){
                phoneNumbers.add('1234567890');
            }
            SiteMapsCanvasserController.sendSMSto(accounts[0],'15428502', phoneNumbers);        
        Test.stopTest();
        
    }
}