force-app/main/default/objects/Account/fields/Canvasser_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Canvasser_Disposition__c</fullName>
    <label>Canvasser Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Moved In</fullName>
            </value>
            <value>
                <fullName>Not Home</fullName>
            </value>
            <value>
                <fullName>Consent Y</fullName>
            </value>
            <value>
                <fullName>Consent N</fullName>
            </value>
            <value>
                <fullName>Gated Community</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Find</fullName>
            </value>
            <value>
                <fullName>Renter</fullName>
            </value>
            <value>
                <fullName>Lease back</fullName>
            </value>
            <value>
                <fullName>Card Sent</fullName>
            </value>
            <value>
                <fullName>DT Left</fullName>
            </value>
            <value>
                <fullName>Duplicate Tag</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field having picklist values</description>
    <label>Verbal Consent Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level1</fullName>
            </value>
            <value>
                <fullName>Level2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Recording_Date__c.field-meta.xml
<CustomField>
    <fullName>Recording_Date__c</fullName>
    <description>The date that the house sale was recorded.</description>
    <label>Recording Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Verbal_Consent__c.field-meta.xml
<CustomField>
    <fullName>Verbal_Consent__c</fullName>
    <label>Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <color>#33CC00</color>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
                <color>#FF0000</color>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Holds the City Name</description>
    <inlineHelpText>Enter the City Name</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Holds the state information</description>
    <inlineHelpText>Enter the state</inlineHelpText>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Holds the street information</description>
    <inlineHelpText>Enter the street information</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Used to store 5 digit zipCode.</description>
    <label>Primary Shipping Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Confirmation_Number__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Number__c</fullName>
    <description>It holds the confirmation number of the account. And it should be greater than lead id value.</description>
    <externalId>true</externalId>
    <label>Confirmation Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/fFirstName__c.field-meta.xml
<CustomField>
    <fullName>fFirstName__c</fullName>
    <formula>UserAccount__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fFirstName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/fLastName__c.field-meta.xml
<CustomField>
    <fullName>fLastName__c</fullName>
    <formula>UserAccount__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fLastName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Kunnect_Sync__c.field-meta.xml
<CustomField>
    <fullName>Kunnect_Sync__c</fullName>
    <label>Kunnect Sync</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>contact_metro_inbound</fullName>
            </value>
            <value>
                <fullName>source_contact_01_water</fullName>
            </value>
            <value>
                <fullName>source_contact_01_security</fullName>
            </value>
            <value>
                <fullName>source_contact_windows_and_blinds</fullName>
            </value>
            <value>
                <fullName>source_contact_srp_solar</fullName>
            </value>
            <value>
                <fullName>source_contact_pest_control</fullName>
            </value>
            <value>
                <fullName>source_contact_hvac</fullName>
            </value>
            <value>
                <fullName>source_contact_solar</fullName>
            </value>
            <value>
                <fullName>KunnectToSF</fullName>
            </value>
            <value>
                <fullName>gravel_contact_security</fullName>
            </value>
            <value>
                <fullName>gravel_contact_water</fullName>
            </value>
            <value>
                <fullName>gravel_contact_solar</fullName>
            </value>
            <value>
                <fullName>gravel_contact_remodel</fullName>
            </value>
            <value>
                <fullName>gravel_contact_pest_control</fullName>
            </value>
            <value>
                <fullName>gravel_contact_hvac</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field will store the person Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Verbal_Consent__c.field-meta.xml
<CustomField>
    <fullName>Verbal_Consent__c</fullName>
    <formula>Text(UserAccount__r.Verbal_Consent__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Verbal Consent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verbal_Consent__c/Verbal_Consent__c.object-meta.xml
<CustomObject>
    <description>This object will holds the verbal consents records</description>
    <label>Verbal Consent</label>
    <nameField>
        <displayFormat>VC-{0000}</displayFormat>
        <label>Verbal Consent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verbal Consents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OutboundGravelBatch.cls
/**
 * Diaco
 * @author             Jull Quintero Daza
 * Project:            Kunnect Sync renplace jitterbit
 * TestClass:          OutboundGravelSheduleTest
 * Description:        kunnect Outbound Gravel - implements Batchable
 *
 * Changes (Version)
 * _________________________________________
 *            No.        Date            Author                    Description
 *            ____    __________        __________________      _____________________________________
 * @version    1.0    05/08/2021         Jull Quintero D         Initial implementation of the class.
 **/

public class OutboundGravelBatch implements 
    Database.Batchable<sObject>,Database.AllowsCallouts, Database.Stateful {
        private KunnectSync contact_security = new KunnectSync();
        private KunnectSync contact_water = new KunnectSync();
        private KunnectSync contact_remodel = new KunnectSync();
        private KunnectSync contact_hvac = new KunnectSync();
        private KunnectSync contact_pest_control = new KunnectSync();
        private KunnectSync contact_solar = new KunnectSync();

        List<String> tablesNames = KunnectSync.GRAVELTABLES;
        private Boolean sendEmail = false;
        private string message = null;
        private set<Integer> resConfirmationNumbers = new set<Integer>();

        public Database.QueryLocator start(Database.BatchableContext bc) {
            System.debug('>> start');
            // collect the batches of records or objects to be passed to execute
            return  Database.getQueryLocator(
                [
                    SELECT Id,
                    Kunnect_Sync__c,
                    fFirstName__c, 
                    fLastName__c,
                    Phone__c, 
                    Email__c, 
                    Confirmation_Number__c, 
                    Recording_Date__c, 
                    Respond_Date__c,  
                    Sales_Price__c,
                    Address__r.Street__c,  
                    Address__r.City__c, 
                    Address__r.State__c, 
                    Address__r.Zip_Code__c
                    FROM User_Address__c 
                    WHERE Phone__c != '' AND Respond_Date__c = YESTERDAY AND 
                    ( Verbal_Consent__c='Yes' OR (UserAccount__r.Verbal_Consent__c=null AND UserAccount__r.Canvasser_Disposition__c='Consent Y'))  AND 
                    Kunnect_Sync__c EXCLUDES(:String.join(tablesNames, ';'))
                ]
            );
        }

        public void execute(Database.BatchableContext bc, List<User_Address__c> records) {
            System.debug('>> execute');
            sendEmail = true;
            try {
                // Process each batch of records
                KunnectUsAddressDTO requestUserAddress = new KunnectUsAddressDTO();
                set<Integer> confNumbers = new set<Integer>();
                integer recordSize = records.size();
                for (Integer i = 0; i < recordSize; i++) {
                    User_Address__c current = records[i];

                    // Set miltipicklist Kunnect_Sync__c
                    list<String> syncValues = new List<String>();
                    if( current.Kunnect_Sync__c != null ) syncValues = current.Kunnect_Sync__c.split(';');
                    for (string item : tablesNames) {
                        if ( item == 'gravel_contact_solar' ) {
                            if( current.Address__r != null ) {
                                if( KunnectSync.ZIPCODES.contains(current.Address__r.Zip_Code__c) ) {
                                    if( !syncValues.contains(item) ) syncValues.add(item);
                                }
                            }
                            continue;
                        }
                        if( !syncValues.contains(item) ) syncValues.add(item);
                    }
                    current.Kunnect_Sync__c = diacoKnifeFunc.formatMultipickList(syncValues);

                    // Confirmation numbers
                    confNumbers.add( integer.valueOf(current.Confirmation_Number__c) );
                    resConfirmationNumbers.add( integer.valueOf(current.Confirmation_Number__c) );
                }
                string endPoint = 'https://salesforcewebsiteapi.herokuapp.com/api/v1.0/outbound-gravel';
                //string endPoint = 'https://fe6767873dd0.ngrok.io/api/v1.0/outbound-gravel';
                requestUserAddress.userAddress = records;
                requestUserAddress.confNumbers = confNumbers;
                requestUserAddress.endPoint    = endPoint;
                contact_security.syncUserAddress('contact_security', requestUserAddress);
                contact_water.syncUserAddress('contact_water', requestUserAddress);
                contact_remodel.syncUserAddress('contact_remodel', requestUserAddress);
                contact_hvac.syncUserAddress('contact_hvac', requestUserAddress);
                contact_pest_control.syncUserAddress('contact_pest_control', requestUserAddress);
                contact_solar.syncUserAddress('contact_solar', requestUserAddress);

                if( KunnectSync.isUpdate ) Database.update(records, false);
            } catch (Exception e) {
                message = 'Apex Error: line ' + e.getLineNumber() + ' ' + e.getMessage();
            }
        }

        public void finish(Database.BatchableContext bc) {
            System.debug('>> finish');
            // execute any post-processing operations
            if( sendEmail ) {
                String body ='Salseforce to Kunnect Daily Import Gravel on ' + System.date.today().format() +
                '\nReport: ' + 
                '\n'+contact_security.emailReport +
                '\n'+contact_water.emailReport +
                '\n'+contact_remodel.emailReport +
                '\n'+contact_hvac.emailReport +
                '\n'+contact_pest_control.emailReport +
                '\n'+contact_solar.emailReport;

                if( !resConfirmationNumbers.isEmpty() ) body += '\nConfirmation Numbers: ' + resConfirmationNumbers.size() + ' '+ KunnectUsAddressDTO.createJson(resConfirmationNumbers);
                    
                if( message != null ) body += '\n' + message;
                Messaging.SendEmailResult[] results = diacoKnifeFunc.sendEmail
                (
                    new String[] {'my_home@diaco.us','emorales@diaco.us','cody@diaco.us','cgarrett@myhomeservices.com','jhinson@myhomes.services'},
                    'KunnectDB Outbound Gravel',
                    body 
                );
            }
        }            
    }