force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field having picklist values</description>
    <label>Verbal Consent Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level1</fullName>
            </value>
            <value>
                <fullName>Level2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Holds the City Name</description>
    <inlineHelpText>Enter the City Name</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Holds the state information</description>
    <inlineHelpText>Enter the state</inlineHelpText>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Holds the street information</description>
    <inlineHelpText>Enter the street information</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Already_have_a_system__c.field-meta.xml
<CustomField>
    <fullName>Already_have_a_system__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Already have a system</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/ApptSetter__c.field-meta.xml
<CustomField>
    <fullName>ApptSetter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appointment Setter</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Personnel__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Personnel__c.Appt_Setter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Home Services (Appointment Setter)</relationshipLabel>
    <relationshipName>Home_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Bottled_Water__c.field-meta.xml
<CustomField>
    <fullName>Bottled_Water__c</fullName>
    <label>Monthly bottled water spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/People_in_the_home_water__c.field-meta.xml
<CustomField>
    <fullName>People_in_the_home_water__c</fullName>
    <label>WA # of people in the home</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Pre_Plumb__c.field-meta.xml
<CustomField>
    <fullName>Pre_Plumb__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pre-Plumb</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT( Account__r.State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <formula>Account__r.Street__c</formula>
    <label>Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/WebSite__c.field-meta.xml
<CustomField>
    <fullName>WebSite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>From WebSite?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <formula>Account__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/webForm__c/webForm__c.object-meta.xml
<CustomObject>
    <label>Web Form</label>
    <nameField>
        <label>webForm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/webForm__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Web Forms</relationshipLabel>
    <relationshipName>Web_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/Already_have_a_system__c.field-meta.xml
<CustomField>
    <fullName>Already_have_a_system__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Already have a system</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/ApptSetter__c.field-meta.xml
<CustomField>
    <fullName>ApptSetter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ApptSetter</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Personnel__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Web Forms</relationshipLabel>
    <relationshipName>Web_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/Bottled_Water__c.field-meta.xml
<CustomField>
    <fullName>Bottled_Water__c</fullName>
    <label>Bottled Water</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/Hour__c.field-meta.xml
<CustomField>
    <fullName>Hour__c</fullName>
    <label>Hour</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/People_in_the_home_water__c.field-meta.xml
<CustomField>
    <fullName>People_in_the_home_water__c</fullName>
    <label># of People in the home</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/Pre_Plumb__c.field-meta.xml
<CustomField>
    <fullName>Pre_Plumb__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pre-Plumb</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <formula>Account__r.Street__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/WebSite__c.field-meta.xml
<CustomField>
    <fullName>WebSite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Web Site</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/diacoTriggerWebTest.cls
/**
* Diaco
* @author 			Jorge Martinez href=<jorgeality29@gmail.com>
* Project:			Web sites integration
* Description:		Class responsible to test diacoCreateAccountAFWeb and diacoCreateHSByWebSite
*
* Changes (Version)
* -------------------------------------
*			No.		Date			Author					Description
*			-----	----------		--------------------	---------------
* @version	1.0		11/17/2018		Jorge Martinez (JM)		Initial implementation of the class.
**/
@isTest
public class diacoTriggerWebTest {
   /*@isTest static void testToDiacoCreateAccountAFWebClass(){
        Test.startTest();
        webForm__c web = new webForm__c(
            email__c = 'test@test.com',
            firstName__c = 'test',
            lastName__c = 'test',
            phone__c = '1234567',
            Address__c = 'AZ,Glendale,Cll 89,12351',
            date__c = '11/19/2018',
            hour__c = '12:00 PM - 02:00 PM',
            type__c =  'aqua'
        );
        insert web;
        Test.stopTest();
        
    }
    
   
    @isTest static void testTodiacoDiacoCreateHSByWebSiteClass(){
        
         webForm__c web = new webForm__c(
             email__c = 'test@test.com',
             firstName__c = 'test',
             lastName__c = 'test',
             phone__c = '1234567',
             Address__c = 'AZ,Glendale,Cll 89,12351',
             date__c = '11/19/2018',
             hour__c = '12:00 PM - 02:00 PM',
             type__c =  'aqua'
         );
         insert web;
         List<String> address = web.address__c.split(',');
         Account account = new Account(
             FirstName = web.firstName__c,
             LastName = web.lastName__c,
             Phone = web.phone__c,
             PersonEmail = web.email__c,
             State__c = address[0],
             City__c = address[1],
             Street__c = address[2],
             Zip__c = address[3],
             RecordTypeId = '012410000012NOKAA2'
         );
         insert account;
         web.Account__c = account.Id;
         update web;
         Test.startTest();
         Test.setMock(HttpCalloutMock.class, new diacoHttpCalloutMock2());
          Home_Services__c home = new Home_Services__c(
             ApptSetter__c = 'a131K000006V5d8QAC',//a1329000001M9weAAC  a131K000006V5d8QAC 
             Account__c = account.Id,
             RecordTypeId = '012410000013G9OAAU',
             WebSite__c = true,
             Already_have_a_system__c = true,
             Pre_Plumb__c = true,
             People_in_the_home_water__c = 5,
             Bottled_Water__c = 500
         );
         insert home;
         Test.stopTest();
         
    } */
   
    
}