force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field having picklist values</description>
    <label>Verbal Consent Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level1</fullName>
            </value>
            <value>
                <fullName>Level2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Industry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Web_Form__c.field-meta.xml
<CustomField>
    <fullName>Web_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Web Form</label>
    <referenceTo>webForm__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Holds the City Name</description>
    <inlineHelpText>Enter the City Name</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Holds the state information</description>
    <inlineHelpText>Enter the state</inlineHelpText>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Holds the street information</description>
    <inlineHelpText>Enter the street information</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Appointment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date_Time__c</fullName>
    <label>Appointment Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Appt_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Appt_End_Time__c</fullName>
    <label>Appt End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/ApptSetter__c.field-meta.xml
<CustomField>
    <fullName>ApptSetter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appointment Setter</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Personnel__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Personnel__c.Appt_Setter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Home Services (Appointment Setter)</relationshipLabel>
    <relationshipName>Home_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT( Account__r.State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <formula>Account__r.Street__c</formula>
    <label>Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Web_Form__c.field-meta.xml
<CustomField>
    <fullName>Web_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Web Form</label>
    <referenceTo>webForm__c</referenceTo>
    <relationshipLabel>Home Services</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <formula>Account__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Industry__c/Industry__c.object-meta.xml
<CustomObject>
    <label>Industry</label>
    <nameField>
        <label>Industry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/webForm__c/webForm__c.object-meta.xml
<CustomObject>
    <label>Web Form</label>
    <nameField>
        <label>webForm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/webForm__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Web Forms</relationshipLabel>
    <relationshipName>Web_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/ApptSetter__c.field-meta.xml
<CustomField>
    <fullName>ApptSetter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ApptSetter</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Personnel__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Web Forms</relationshipLabel>
    <relationshipName>Web_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <formula>Account__r.Street__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiacoCmpTaskController.cls
/*

Diaco
@author 			Esnayder Morales Corpas href=<esnaydermorales25@gmail.com>
Project:			diacoCmpTask
Description:		Class reponsible provide method to diacocmp task 

Changes (Version)
_________________________________________

No.		Date			Author					Description
____	__________      __________________      _____________________________________
@version	1.0		21/10/2019		Esnayder Morales (ES)	Initial implementation  of the class.
*/
public class DiacoCmpTaskController {
    
    /**
    * 
    * This method is responsible to get webform's task
    * 
    * This method is used in:
    * DiacoTaskWebformHelper.js
    *  
    * 
    * @param String recordIds
    * @return tasks
    **/
    @AuraEnabled
    public static List<Task> getTasks(String RecordId){
        List<Task> tasks = [select Id, Subject, OwnerId, WhatId, Owner.Name, Status,
                            Owner.Type, What.Name, What.Type, CreatedDate
                            from Task where Web_Form__c =:RecordId ORDER BY CreatedDate DESC];        
        return tasks;
    } 
    
    /**
    * 
    * This method is responsible to get account's information by webForm
    * 
    * This method is used in:
    * DiacoWebformAccountHelper.js
    *  
    * 
    * @param String recordId
    * @return webForm__c
    **/
    @AuraEnabled
    public static webForm__c getIdAccount(String RecordId){
        webForm__c acc = [select Account__c, Account__r.State__c, FirstName__c,
                          LastName__c, Phone__c,  Address__c, Zip__c,
                          Email__c, State__c, City__c
                          from webForm__c where Id=:RecordId];        
        return acc;
    } 
    
    /**
    * 
    * This method is responsible to update task and create homeservices
    * 
    * This method is used in:
    * DiacoWebformActionTaskHelper.js
    *  
    * 
    * @param Task, String
    * @return String
    **/
    @AuraEnabled
    public static String updateTask(Task task, String services){
        Type idArrType = Type.forName('List<string>');
    	List<string> wrapperList = (List<string>) JSON.deserialize(services, idArrType);
        Task task2 = [select Id, Name__c, ActivityDate, WhatId, Web_Form__c, What.type,
                      Web_Form__r.firstName__c, Web_Form__r.lastName__c,Web_Form__r.email__c,
                      Web_Form__r.Phone__c, Web_Form__r.Zip__c, Web_Form__r.City__c,Web_Form__r.Address__c,
                      Web_Form__r.State__c, Web_Form__r.type__c, Description, Web_Form__r.Account__c
                      from Task where Id =:task.Id];
        
        //Change firstName to Name in prod
        Personnel__c personnel = [select Id from Personnel__c where Name='1- None' limit 1];
        List<Home_Services__c> homeservices = new List<Home_Services__c>();
        Account account = new Account();
        
        
        //List<DateTime> datesActivity = DiacoResourceTaskController.ActivityDate(task2.ActivityDate,task2.Hours__c);
        if(task.Status == 'Completed' && 
           task2.Web_Form__r.Account__c != null){ 
               for(String hsId : wrapperList){
                   Home_Services__c hs = new Home_Services__c();
                   hs.Account__c = task2.Web_Form__r.Account__c;
                   hs.Industry__c= task2.Description;
                   //hs.Appointment_Date_Time__c = datesActivity[0];
                   //hs.Appt_End_Time__c = datesActivity[1];
                   hs.ApptSetter__c = personnel.Id;
                   hs.RecordTypeId = hsId;
                   homeservices.add(hs);
                      
               }
               insert homeservices;
               
           }else {
               account.FirstName=task2.Web_Form__r.firstName__c;
               account.LastName=task2.Web_Form__r.lastName__c;
               account.PersonEmail=task2.Web_Form__r.email__c;
               account.Phone=task2.Web_Form__r.Phone__c;
               account.State__c=task2.Web_Form__r.State__c;
               account.City__c=task2.Web_Form__r.City__c;
               account.Street__c=task2.Web_Form__r.Address__c;
               account.Zip__c=task2.Web_Form__r.Zip__c;
               account.Web_Form__c = task2.Web_Form__c;
               insert account;
               System.debug(account);
               for(String hsId : wrapperList){     
                   Home_Services__c hs2 = new Home_Services__c();
                   hs2.Account__c=account.Id;
                   hs2.Industry__c= task2.Description;
                   //hs.Appointment_Date_Time__c = datesActivity[0];
                   //hs.Appt_End_Time__c = datesActivity[1];
                   hs2.ApptSetter__c=personnel.Id;
                   hs2.RecordTypeId = hsId;
                   homeservices.add(hs2);
               }
               insert homeservices;
               System.debug(homeservices);
           }
        update task;
        return 'Updated';
    }
    
    /**
    * 
    * This method is responsible to get task by Id
    * 
    * This method is used in:
    * DiacoWebformActionTaskHelper.js
    *  
    * 
    * @param Task
    * @return Task
    **/
    @AuraEnabled
    public static Task getDataTask(String recordId){
        Task task = [select Description, Status from Task where Id=:recordId];
        System.debug(task);
        return task;
    }
    
    /**
    * 
    * This method is responsible to get task by Id
    * 
    * This method is used in:
    * DiacoWebformActionTaskHelper.js
    *  
    * 
    * @param nothing
    * @return List<RecordType>
    **/
    @AuraEnabled
    public static List<RecordType> getDataHS(){
        List<RecordType> RT = [select Id,Name from RecordType where sObjectType='Home_Services__c' and Name like '%Sales'];
        return RT;
    }
    
    
    /**
    * 
    * This method is responsible to update webform with a new account
    * 
    * This method is used in:
    * DiacoWebformActionTaskHelper.js
    *  
    * 
    * @param nothing
    * @return List<RecordType>
    **/
    @AuraEnabled
    public static String updateWebForm(String accountId, String WebformId){
        webForm__c wf = new webForm__c();
        wf.Id = WebformId;
        wf.Account__c = accountId;
        update wf;
        return 'Success';
    }
    
}