force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Geo_Accuracy__c.field-meta.xml
<CustomField>
    <fullName>Geo_Accuracy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Geo Accuracy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/diacoAssignContactBatchTest.cls
@isTest
public class diacoAssignContactBatchTest {
	@testSetup 
    static void setup() {
        List<Account> accounts = new List<Account>();
        // insert 10 accounts
        ID Rt = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
                .get('PersonAccount').getRecordTypeId();
        for (Integer i=0;i<10;i++) {
            accounts.add(new Account(FirstName= 'Test'+i, LastName='Test'+i,
                billingcity='New York', billingcountry='USA',
                                    Street__c='Test', Zip__c='12345',
                                    State__c='AZ', City__c='City',
                                    RecordTypeId = Rt));
        }
        insert accounts;
    }
    
    static testmethod void test() {        
        Test.startTest();
        diacoAssignContactBatch uca = new diacoAssignContactBatch(10);
        Id batchId = Database.executeBatch(uca);
        Test.stopTest();
        // after the testing stops, assert records were updated properly
    }


    static testmethod void deleteContact() {      
        List<Contact> contacts = new List<Contact>();
        List<Account> accounts = [select Id, FirstName, LastName, PersonEmail, Phone, Street__c, Zip__c, State__c, City__c from Account];
        for(Account acc : accounts) {
            Contact contact = new Contact();
            contact.FirstName = acc.FirstName;
            contact.LastName = acc.LastName;
            contact.MailingCity = acc.City__c;
            contact.MailingState = acc.State__c;
            contact.MailingStreet = acc.Street__c;
            contact.Geo_Accuracy__c = true;
            contact.MailingPostalCode = acc.Zip__c;
            contact.Person_Account__c = acc.Id;
            contacts.add(contact);
        }
        Test.startTest();
        insert contacts;
            DiacoDelateContactGeoAccuracyBatch uca = new DiacoDelateContactGeoAccuracyBatch(10);
            Id batchId = Database.executeBatch(uca);
        Test.stopTest();
    }
}