force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Finance_Package__c/Finance_Package__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Finance Package</label>
</CustomObject>

force-app/main/default/objects/Finance_Package__c/fields/Activation_Emergency_Video_LEASE__c.field-meta.xml
<CustomField>
    <fullName>Activation_Emergency_Video_LEASE__c</fullName>
    <label>Activation (Emergency &amp; Video)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Activation_Emergency_Video_PURCHASE__c.field-meta.xml
<CustomField>
    <fullName>Activation_Emergency_Video_PURCHASE__c</fullName>
    <label>Activation (Emergency &amp; Video)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/APR__c.field-meta.xml
<CustomField>
    <fullName>APR__c</fullName>
    <defaultValue>12.99</defaultValue>
    <label>APR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Customer_Owned_LEASE__c.field-meta.xml
<CustomField>
    <fullName>Customer_Owned_LEASE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Owned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Customer_Owned_PURCHASE__c.field-meta.xml
<CustomField>
    <fullName>Customer_Owned_PURCHASE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Owned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Equipment_Min_Payment__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Min_Payment__c</fullName>
    <label>Equipment Min Payment</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Monitoring__c.field-meta.xml
<CustomField>
    <fullName>Monitoring__c</fullName>
    <label>Monitoring</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Monthly_Payment_LEASE__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Payment_LEASE__c</fullName>
    <label>Monthly Payment</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Monthly_Payment_PURCHASE__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Payment_PURCHASE__c</fullName>
    <label>Monthly Payment</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Monthly_Renewal_LEASE__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Renewal_LEASE__c</fullName>
    <label>Monthly Renewal</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Monthly_Renewal_PURCHASE__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Renewal_PURCHASE__c</fullName>
    <label>Monthly Renewal</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Monthly_Term_LEASE__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Term_LEASE__c</fullName>
    <label>Monthly Term</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Monthly_Term_PURCHASE__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Term_PURCHASE__c</fullName>
    <label>Monthy Term</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Payment_Factor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Factor__c</fullName>
    <label>Payment Factor</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Payment_Number__c.field-meta.xml
<CustomField>
    <fullName>Payment_Number__c</fullName>
    <label># Payments</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Purchase__c.field-meta.xml
<CustomField>
    <fullName>Purchase__c</fullName>
    <label>Purchase</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Total_Min_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Min_Payments__c</fullName>
    <label>Total Min Payments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/Video__c.field-meta.xml
<CustomField>
    <fullName>Video__c</fullName>
    <label>Video</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Finance_Package__c/fields/X12_Months_Same_As_Cash__c.field-meta.xml
<CustomField>
    <fullName>X12_Months_Same_As_Cash__c</fullName>
    <defaultValue>false</defaultValue>
    <label>12 Months Same As Cash</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/APR__c.field-meta.xml
<CustomField>
    <fullName>APR__c</fullName>
    <label>APR</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <label>Card Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>Exp_Date__c</fullName>
    <label>Exp Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/FinanceId__c.field-meta.xml
<CustomField>
    <fullName>FinanceId__c</fullName>
    <label>FinanceId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Home_Services_Status__c.field-meta.xml
<CustomField>
    <fullName>Home_Services_Status__c</fullName>
    <label>Sales Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Dispatch</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Bid Submitted</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Rehash</fullName>
            </value>
            <value>
                <fullName>Sale Pending</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Won/Canceled</fullName>
            </value>
            <value>
                <fullName>Closed Won / Service Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Method_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Method_Of_Payment__c</fullName>
    <label>Method Of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Sales_Event_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_Event_Current_Status__c</fullName>
    <label>Sales Event Current Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Home_Services_Sales_Rep</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT( Account__r.State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <formula>Account__r.Street__c</formula>
    <label>Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <formula>Account__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/CSV__c.field-meta.xml
<CustomField>
    <fullName>CSV__c</fullName>
    <label>CSV</label>
    <length>4</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/HomeService__c.field-meta.xml
<CustomField>
    <fullName>HomeService__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentMethodType__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodType__c</fullName>
    <label>Payment Method Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentMethodTypePick</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/DiacoFinanceClassTest.cls
/**
* Diaco
* @author 			Kevin Vega Hernandez href=<kevin.vega.h@hotmail.com>
* Project:			Finance Component
* Description:		Migrate the Finance Component from SFI Org to Home Service Org .
*
* Changes (Version)
* -------------------------------------
*			No.		Date			Author						 Description
*			-----	----------		--------------------		 ---------------
* @version	1.0		30/06/2020		Kevin Vega Hernandez (KVH)	 Migrate the Finance Component from SFI Org to Home Service Org. 
**/

@isTest
public class DiacoFinanceClassTest {
    	
/*    @isTest static void SetupAll() {
        
        ddsign__DiacoSign_Account__c dacc = new ddsign__DiacoSign_Account__c(Name='Test',ddsign__Type__c='Live',ddsign__API_Account_ID__c='test Apy');
        insert dacc;
        ddsign__DiacoSign_User__c duser = new ddsign__DiacoSign_User__c(Name='Pinnacle Finance',ddsign__Username__c='test@test.com',ddsign__IntegratorKey__c='test',
                                                                        ddsign__DiacoSign_Account__c=dacc.Id,ddsign__Password__c='pasww');
        insert duser;
        Account Acc = new Account();
        Acc.FirstName = 'Account ';
        Acc.LastName = 'Test';
        Acc.RecordTypeId ='012410000012NOKAA2';
        Acc.Street__c='test';
        Acc.City__c='test';
        Acc.State__c='AZ';
        Acc.Zip__c='test';
        insert Acc;
        
        Home_Services__c hs = new  Home_Services__c();
        hs.Account__c = Acc.Id;
        hs.RecordTypeId = '012410000013G9OAAU';
        hs.Card_Number__c = '123456789';
        hs.CSV__c = '123';
        hs.Method_Of_Payment__c = 'Credit Card';		 
        hs.Exp_Date__c = '7/24';
        hs.Name='test test test test';
        hs.Home_Services_Status__c='Schedule';
        hs.Sales_Event_Current_Status__c='Schedule';
        hs.Event_Count__c=1;
        //hs.Sales_Rep__c = u.Id;
        insert hs;
        
        Event event = new Event(
            Home_Service__c = hs.Id,
            RecordTypeId = '012410000013G9CAAU',
            DurationInMinutes=1,
            WhatId = hs.Id,
            ActivityDateTime= Date.Today()
        );
        insert event;
        PaymentMethod__c PayM = new PaymentMethod__c(HomeService__c=hs.Id,PaymentMethodType__c='ACH');
        insert PayM;
        
        Finance__c FinancePackage = new Finance__c();
        FinancePackage.name = 'Package A';
        Finance__c fPackage = DiacoFinanceClass.create_update_Finance_package(FinancePackage);
        DiacoFinanceClass.delete_Finance_package(fPackage.Id);
        
        DiacoFinanceClass.getInfo_Finance_package();
        DiacoFinanceClass.getInfo_Finance(hs.Id);
        DiacoFinanceClass.setInfo_Finance(hs.Id,0.0,0.0,fPackage.name,'Finance',0.0,0.0,true,0.0);
        DiacoFinanceClass.setInHouse(hs.Id,true);
        
        DiacoFinanceClass.getInfo_Finance(event.Id);
        DiacoFinanceClass.getInfo_Finance(event.Id);
        DiacoFinanceClass.setInfo_Finance(event.Id,0.0,0.0,fPackage.name,'Finance',0.0,0.0,true,0.0);
        DiacoFinanceClass.setInHouse(event.Id,true);
        
        DiacoFinanceClass.getRecordTypeFromHS(hs.Id);
        DiacoFinanceClass.thereAreSigned(hs.Id);
        DiacoFinanceClass.sendToDocusign(hs.Id);
        
        
        
    }
  */ 
    
    
    
    @isTest
    static void testContract(){
        ddsign__DiacoSign_Account__c dacc = new ddsign__DiacoSign_Account__c(
            Name='Test',ddsign__Type__c='Live',ddsign__API_Account_ID__c='test Apy'
        );
        insert dacc;
        
        Account Acc = new Account();
        Acc.FirstName = 'Account ';
        Acc.LastName = 'Test';
        Acc.Street__c='test';
        Acc.City__c='test';
        Acc.State__c='AZ';
        Acc.Zip__c='test';
        insert Acc;
        
        Id devRecordTypeId = Schema.SObjectType.Home_Services__c.getRecordTypeInfosByName().get('Home Automation Sales').getRecordTypeId();
        
        Home_Services__c hs = new  Home_Services__c();
        hs.Account__c = Acc.Id;
        hs.Card_Number__c = '123456789';
        hs.CSV__c = '123';
        hs.Method_Of_Payment__c = 'Credit Card';		 
        hs.Exp_Date__c = '7/24';
        hs.Name='test1';
        hs.Home_Services_Status__c='Schedule';
        hs.Sales_Event_Current_Status__c='Schedule';
        hs.Event_Count__c=1;
        //hs.Sales_Rep__c = u.Id;
        insert hs;
        DiacoFinanceClass.getAlarmField(hs.Id);
        Event event = new Event(
            Home_Service__c = hs.Id,
            RecordTypeId = '012410000013G9CAAU',
            DurationInMinutes=1,
            WhatId = hs.Id,
            ActivityDateTime= Date.Today()
        );
      //  insert event;
        
        PaymentMethod__c PayM = new PaymentMethod__c(HomeService__c=hs.Id,PaymentMethodType__c='ACH',Bank_Account_Name__c='Test OK 1');
        insert PayM;
        
        Finance_Package__c pack = new Finance_Package__c(Name=hs.Id,Payment_Number__c=96,type__c='purchase',APR__c=12.99,
                                                        Purchase__c=123,Payment_Factor__c=0.016802,Monthly_Renewal_PURCHASE__c=12,
                                                        Monthly_Renewal_LEASE__c=1,Monthly_Term_PURCHASE__c=123,Monthly_Term_LEASE__c=1235,
                                                        Monthly_Payment_PURCHASE__c=1352,Monthly_Payment_LEASE__c=58,Monitoring__c=53,
                                                        Equipment_Min_Payment__c=63,X12_Months_Same_As_Cash__c=true,Total_Min_Payments__c=123,
                                                        Activation_Emergency_Video_PURCHASE__c=12,Activation_Emergency_Video_LEASE__c=12);
        insert pack;
        DiacoFinance2Class.sendToDocusign(hs.Id);
        ddsign__DiacoSign_User__c duser = new ddsign__DiacoSign_User__c(
            Name='Pinnacle Finance',ddsign__Username__c='scott@pinnaclefinance.com',ddsign__IntegratorKey__c='test',
            ddsign__DiacoSign_Account__c=dacc.Id,ddsign__Password__c='pasww'
        );
        insert duser;
        ddsign__Pre_Designed_Envelope__c Pevn = new ddsign__Pre_Designed_Envelope__c(
            Name='Pinnacle Contract',ddsign__DiacoSign_User__c=duser.Id
        );
        insert Pevn;
        
        DiacoFinance2Class.getRecordTypeFromHS(hs.Id);
        DiacoFinance2Class.thereAreSigned(hs.Id);
        DiacoFinance2Class.sendToDocusign(hs.Id);
        DiacoFinance2Class.getAlarmField(hs.Id);
        
        
         DiacoFinance2Class.getInfo_Finance_HS(hs.Id);
        DiacoFinance2Class.getInfo_Finance_HS(null);
        
        Finance_Package__c finance = new Finance_Package__c(Name='Default',
                                             X12_Months_Same_As_Cash__c =true,
                                             Activation_Emergency_Video_LEASE__c=0.0,
                                             Activation_Emergency_Video_PURCHASE__c=0.0,
                                             Customer_Owned_LEASE__c=true,
                                             Customer_Owned_PURCHASE__c=true,
                                             Equipment_Min_Payment__c=0.0,
                                             Monitoring__c=0.0,
                                             Monthly_Payment_LEASE__c=12,
                                             Monthly_Payment_PURCHASE__c=12,
                                             Monthly_Renewal_LEASE__c=10,
                                             Monthly_Renewal_PURCHASE__c=10,
                                             Monthly_Term_LEASE__c=10,
                                             Monthly_Term_PURCHASE__c=10,
                                             Payment_Factor__c=0.0,
                                             Purchase__c=10,
                                             Tax__c=true,
                                             Total_Min_Payments__c=10,
                                             type__c='yes',
                                             Video__c='yes',
                                             APR__c=0.0,
                                             Payment_Number__c=10);
        
        DiacoFinance2Class.create_update_Finance_HS(hs.Id,finance);
    	Finance_Package__c financeResponse = DiacoFinance2Class.create_update_Finance(finance);
        
        Home_Services__c hs2 = new Home_Services__c(Id = hs.Id, FinanceId__c = financeResponse.Id);
        update hs;
    	DiacoFinance2Class.getInfo_Finance_HS(hs2.Id);
        DiacoFinance2Class.getInfo_Finance_HS(null);
      //  DiacoFinance2Class.getInfo_Finance_Hs_With_Tax('a1203000000CpYUAA9', hs2.Id);
      //  DiacoFinance2Class.getInfo_Finance_Hs_With_Tax(pack.Id, hs2.Id);
      //  DiacoFinance2Class.getInfo_Finance_Hs_With_Tax(null, hs2.Id);
        DiacoFinance2Class.getInfo_Finance();
		
        DiacoFinance2Class.create_update_Finance_HS(hs.Id,financeResponse);
        DiacoFinance2Class.getInfo_HS(hs.Id);
        
    }
}