force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/ApptSetter__c.field-meta.xml
<CustomField>
    <fullName>ApptSetter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appointment Setter</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Personnel__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Personnel__c.Appt_Setter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Home Services (Appointment Setter)</relationshipLabel>
    <relationshipName>Home_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <label>Card Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>Exp_Date__c</fullName>
    <label>Exp Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.FirstName),&apos;&apos;,Account__r.FirstName)</formula>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Home_Services_Status__c.field-meta.xml
<CustomField>
    <fullName>Home_Services_Status__c</fullName>
    <label>Sales Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Dispatch</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Bid Submitted</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Rehash</fullName>
            </value>
            <value>
                <fullName>Sale Pending</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Won/Canceled</fullName>
            </value>
            <value>
                <fullName>Closed Won / Service Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Home Service</relationshipLabel>
    <relationshipName>Home_Service</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.LastName),&apos;&apos;,Account__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Method_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Method_Of_Payment__c</fullName>
    <label>Method Of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Sales_Event_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_Event_Current_Status__c</fullName>
    <label>Sales Event Current Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Home_Services_Sales_Rep</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Home Services</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT( Account__r.State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <formula>Account__r.Street__c</formula>
    <label>Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <formula>Account__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <label>Installation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Installation</relationshipLabel>
    <relationshipName>Installation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Installations_Sales_Rep</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/recordTypes/Water.recordType-meta.xml
<RecordType>
    <fullName>Water</fullName>
    <active>true</active>
    <label>Water Treatment</label>
</RecordType>

force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Line Items (HS)</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items (Product)</relationshipLabel>
    <relationshipName>Line_Items_Product</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/fields/Kunnect_ID__c.field-meta.xml
<CustomField>
    <fullName>Kunnect_ID__c</fullName>
    <inlineHelpText>This is a Required field.  If this person does not have a Kunnect account please put &quot;none&quot;</inlineHelpText>
    <label>Kunnect ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sales Rep</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product HS</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products HS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Home_Service_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Rep_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/recordTypes/Water.recordType-meta.xml
<RecordType>
    <fullName>Water</fullName>
    <active>true</active>
    <label>Water Treatment</label>
</RecordType>

force-app/main/default/classes/DiacoLineItemsControllerTest.cls
@isTest
public class DiacoLineItemsControllerTest {
    @isTest static void testAll(){
        Account Acc = new Account();
        Acc.FirstName = 'Account ';
        Acc.LastName = 'Test';
        Acc.RecordTypeId ='012410000012NOKAA2';
        Acc.Street__c='test';
        Acc.City__c='test';
        Acc.State__c='AZ';
        Acc.Zip__c='test';
        insert Acc;
        
        Personnel__c per = new Personnel__c();
        per.Name = 'test';
        per.First_Name__c = 'test';
        per.Last_Name__c = 'test';
        per.Kunnect_ID__c = 'none';
        insert per;
        
        Home_Services__c hs = new  Home_Services__c();
        hs.Account__c = Acc.Id;
        hs.RecordTypeId = '012410000013G9OAAU';
        hs.Card_Number__c = '123456789';
        hs.CSV__c = '123';
        hs.Method_Of_Payment__c = 'Credit Card';		 
        hs.ApptSetter__c = per.Id;
        hs.Exp_Date__c = '7/24';
        hs.Name='test test test test';
        hs.Home_Services_Status__c='Schedule';
        hs.Sales_Event_Current_Status__c='Schedule';
        hs.Event_Count__c=1;
        //hs.Sales_Rep__c = u.Id;
        insert hs;
        
        Installation__c i = new Installation__c();
        i.Name = 'Test';
        i.Home_Service__c = hs.Id;
        i.RecordTypeId = '012410000013IFMAA2';
        insert i;

        Product__c pr = new Product__c();
        pr.Name = 'test';
        pr.Product_Type__c = 'Water';
        pr.active__c = true;
        insert pr;

        Product__c prS = new Product__c();
        prS.Name = 'test';
        prS.Product_Type__c = 'Water';
        prS.active__c = true;
        prS.Service__c = True;
        insert prS;
        
        Line_Item__c li = new Line_Item__c();
        li.Name = 'Test';
        li.Product__c = pr.Id;
        li.Home_Service__c = hs.Id;
        insert li;

        List<Line_Item__c> lis = new List<Line_Item__c>();
        lis.add(li);
        
        list<String> selected = new List<String>();
        selected.add(pr.Id);
        
        list<String> selectedS = new List<String>();
        selectedS.add(prS.Id);

        test.startTest();
        DiacoLineItemsController.shouldDisplayInstallerPointColumn(hs.Id);
        DiacoLineItemsController.getLineItems(hs.Id);
        DiacoLineItemsController.getLineItemsServices(hs.Id);
        DiacoLineItemsController.updateLineItems(lis);
        DiacoLineItemsController.getProducts(hs.Id);
        DiacoLineItemsController.getServices(hs.Id);
        DiacoLineItemsController.addProductsToHS(hs.Id, selected);
        DiacoLineItemsController.addServicesToHS(hs.Id, selectedS, 'Monthly');
        DiacoLineItemsController.deleteLineItem(li.Id);
        DiacoLineItemsController.updatePaymentItemsServices(li.Id,'Monthly');
        test.stopTest();

    }
}