force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift_Card_Orders__c/Gift_Card_Orders__c.object-meta.xml
<CustomObject>
    <label>Gift Card Order</label>
    <nameField>
        <label>Gift Card Orders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Card Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Card_Orders__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Parent_Gift_Card_Order__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Gift Card Orders</relationshipLabel>
    <relationshipName>Gift_Card_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Appt_Window_Time__c.field-meta.xml
<CustomField>
    <fullName>Appt_Window_Time__c</fullName>
    <formula>IF( 
ISBLANK(Appointment_Date_Time__c ),&quot;&quot;, 

IF( 
OR( 
VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24), 12, 2 ) ) = 0, 
VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24 ), 12, 2 ) ) = 12 
), 
&quot;12&quot;, 
TEXT( VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24), 12, 2 ) ) 
- 
IF( 
VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24), 12, 2 ) ) &lt; 12, 
0, 
12 
) 
) 
) 
&amp; &quot;:&quot; &amp; 
MID( TEXT(  Appointment_Date_Time__c  - 7/24 ), 15, 2 ) 
&amp; &quot; &quot; &amp; 
IF( 
VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24), 12, 2 ) ) &lt; 12, 
&quot;AM&quot;, 
&quot;PM&quot;) 

+ &quot; - &quot; + 

IF( 
OR( 
VALUE( MID( TEXT( Appt_End_Time__c - 7/24), 12, 2 ) ) = 0, 
VALUE( MID( TEXT( Appt_End_Time__c - 7/24 ), 12, 2 ) ) = 12 
), 
&quot;12&quot;, 
TEXT( VALUE( MID( TEXT( Appt_End_Time__c - 7/24), 12, 2 ) ) 
- 
IF( 
VALUE( MID( TEXT( Appt_End_Time__c - 7/24), 12, 2 ) ) &lt; 12, 
0, 
12 
) 
) 
) 
&amp; &quot;:&quot; &amp; 
MID( TEXT( Appt_End_Time__c - 7/24 ), 15, 2 ) 
&amp; &quot; &quot; &amp; 
IF( 
VALUE( MID( TEXT( Appt_End_Time__c - 7/24), 12, 2 ) ) &lt; 12, 
&quot;AM&quot;, 
&quot;PM&quot; 
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Appt Window Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/ApptSetter__c.field-meta.xml
<CustomField>
    <fullName>ApptSetter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appointment Setter</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Personnel__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Personnel__c.Appt_Setter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Home Services (Appointment Setter)</relationshipLabel>
    <relationshipName>Home_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.FirstName),&apos;&apos;,Account__r.FirstName)</formula>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.LastName),&apos;&apos;,Account__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT( Account__r.State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <formula>Account__r.Street__c</formula>
    <label>Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <formula>Account__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Form__c/Lead_Form__c.object-meta.xml
<CustomObject>
    <label>Lead Form</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lead Forms</relationshipLabel>
    <relationshipName>Lead_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/fields/Kunnect_ID__c.field-meta.xml
<CustomField>
    <fullName>Kunnect_ID__c</fullName>
    <inlineHelpText>This is a Required field.  If this person does not have a Kunnect account please put &quot;none&quot;</inlineHelpText>
    <label>Kunnect ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/Text_Settings_Appt__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Text Settings</label>
</CustomObject>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_Confirmation_C_Home_Automation__c.field-meta.xml
<CustomField>
    <fullName>Sale_Confirmation_C_Home_Automation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - Confirmation &quot;C&quot; Home Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_Confirmation_C_Pest_Control__c.field-meta.xml
<CustomField>
    <fullName>Sale_Confirmation_C_Pest_Control__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - Confirmation &quot;C&quot; Pest Control</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_Confirmation_C_Water__c.field-meta.xml
<CustomField>
    <fullName>Sale_Confirmation_C_Water__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - Confirmation &quot;C&quot; Water</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DiacoHsCountTaskTest.cls
/*

 Diaco
 @author 			Esnayder Morales Corpas href=<esnaydermorales25@gmail.com>
 Project:			diacoHsCountTask
 Description:		Test to trigger DiacoTaskUnified
     
 Changes (Version)
 _________________________________________

   No.		Date			Author					Description
   ____	__________      __________________      _____________________________________
@version	1.0		07/10/2019		            Esnayder Morales (ES)	Initial implementation  of the class.
@version	2.0		01/01/2021		            JUll Quintero Daza - Maps delivery date check in
*/

@isTest
public class DiacoHsCountTaskTest {

    @TestSetup static void makeData() {

        // Settings magic sms
        smagicinteract__SMS_SenderId__c senderSolar = new smagicinteract__SMS_SenderId__c(
        	smagicinteract__Label__c = 'Sales:Solar',
            smagicinteract__senderId__c = '1233423544'
        ); 
        insert senderSolar;
        smagicinteract__SMS_SenderId__c senderWater = new smagicinteract__SMS_SenderId__c(
        	smagicinteract__Label__c = 'Sales:Water',
            smagicinteract__senderId__c = '1233423544'
        ); 
        insert senderWater;
        smagicinteract__SMS_Template__c template = new smagicinteract__SMS_Template__c();
		template.smagicinteract__Text__c = 'Hello {!Home_Services__c.first_name__c}, this is N-Ergy with a friendly reminder for your solar appointment today between {!Home_Services__c.appt_window_time__c}. Please text “C” to confirm. We look forward to meeting with you!';
		template.smagicinteract__Name__c = 'Automatic Text - Confirmation "C" Solar';
		insert template;
        smagicinteract__SMS_Template__c template2 = new smagicinteract__SMS_Template__c();
		template2.smagicinteract__Text__c = 'Hello {!Home_Services__c.first_name__c}, this is Water with a friendly reminder for your Water appointment today between {!Home_Services__c.appt_window_time__c}. Please text “C” to confirm. We look forward to meeting with you!';
		template2.smagicinteract__Name__c = 'Automatic Text - Confirmation "C" Water';
        insert template2;
        
        Text_Settings_Appt__c text = new Text_Settings_Appt__c(
        	Sale_Confirmation_C_Home_Automation__c = true,
            Sale_Confirmation_C_Pest_Control__c = true,
            Sale_Confirmation_C_Water__c = true
        );
        insert text;

        Account Acc = new Account();
        Acc.FirstName = 'Account ';
        Acc.LastName = 'Test';
        Acc.RecordTypeId ='012410000012NOKAA2';
        Acc.Street__c='test';
        Acc.City__c='test';
        Acc.State__c='AZ';
        Acc.Zip__c='test';
        Acc.Phone = '000000000';
        insert Acc; 

        Personnel__c per = new Personnel__c();
        per.Name = 'test';
        per.First_Name__c = 'test';
        per.Last_Name__c = 'test';
        per.Kunnect_ID__c = 'none';
        insert per;
        
        Home_Services__c hs = new  Home_Services__c();
        hs.Account__c = Acc.Id;
        hs.RecordTypeId = '012410000013G9KAAU';
        hs.Name='test test test test';
        hs.ApptSetter__c = per.Id;

        Home_Services__c hs2 = new  Home_Services__c();
        hs2.Account__c = Acc.Id;
        hs2.RecordTypeId = '012410000013G9MAAU';
        hs2.Name='test test test test';
        hs2.ApptSetter__c = per.Id;
        List<Home_Services__c> homeServices = new List<Home_Services__c>{hs,hs2};
        insert homeServices;

        // Deliveries
        TestClassUtil.createZipcodeForBranch();
        TestClassUtil.createAccount(2);
        TestClassUtil.createCheetahGiftCardOrder();
        TestClassUtil.createDriver();  
        TestClassUtil.createProductAndHungStatus();
        TestClassUtil.createBranch();
        TestClassUtil.createAddress(2);
        TestClassUtil.createUserAddress(2);
        TestClassUtil.createDeliveryParameter(1);
        Gift_Card_Orders__c giftCardOrder = [SELECT ID FROM Gift_Card_Orders__c LIMIT 1];
        Driver__c driver =  [SELECT ID FROM Driver__c LIMIT 1];
        Branch__c branch = [SELECT ID FROM Branch__c LIMIT 1];
        List<Delivery_Object__c> deliveryObjectLst = new List<Delivery_Object__c>();
        
        for(User_Address__c current : [SELECT Id,UserAccount__c FROM User_Address__c]){
            Delivery_Object__c deliveryObject = new Delivery_Object__c();
            deliveryObject.Person_Account__c = current.UserAccount__c;
            deliveryObject.User_Address__c = current.Id;
            deliveryObject.Driver__c = driver.id;
            deliveryObject.name = '1';
            deliveryObject.Branch_Object__c = branch.id;
            deliveryObject.Parent_Gift_Card_Order__c = giftCardOrder.id;
            deliveryObject.Hung_Status__c = 'Cant Find';            
            deliveryObjectLst.add(deliveryObject);
        }        
        insert deliveryObjectLst;   
    }

    @IsTest
    static void test() {

        test.startTest();

        test.setMock(HttpCalloutMock.class, new diacoSendSweepstakeHttpCallOutMock());

        Home_Services__c[] homeServices = [SELECT Id FROM Home_Services__c];
        Delivery_Object__c[] deliveries = [SELECT Id FROM Delivery_Object__c];

        List<Task> tasks = new List<Task>();
        for(Integer i = 0; i<=3; i++) {
            
            Task task = new Task();
            task.Subject = 'Confirmation Call - No answer';
            task.WhatId = homeServices[0].Id;
            task.Description = 'Test'+i;
            task.Call_Notes__c = 'TEST '+i;
            task.Call_Purpose__c ='Confirmation';
            task.Call_Status__c = 'Attempted Call';

            Task task2 = new Task();
            task2.Subject = 'Confirmation Call - No answer';
            task2.WhatId = homeServices[1].Id;
            task2.Description = 'Test'+i;
            task2.Call_Notes__c = 'TEST '+i;
            task2.Call_Purpose__c ='Confirmation';
            task2.Call_Status__c = 'Attempted Call';

            Task task3 = new Task();
            task3.Subject = 'Check In';
            task3.WhatId = deliveries[0].Id;
            task3.Description = 'Test'+i;
            tasks.add(task); tasks.add(task2); tasks.add(task3);
        }        
        insert tasks;
        test.stopTest();
        
    }
    
    @isTest static void testAllLeadFormLogs(){
        //Verificar dado caso se actualicen mas task del mismo LF 

        Lead_Form__c newLF=new Lead_Form__c();
        insert newLF;
    
        Task task2 = new Task();
        task2.Subject = 'Confirmation Call - No answer';
        task2.WhatId = newLF.Id;
        task2.Dispositions__c='No Answer';
        Test.startTest();
        insert task2;
        Test.stopTest();    
    }

}