force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hot_Leads_Tier_1_Date__c.field-meta.xml
<CustomField>
    <fullName>Hot_Leads_Tier_1_Date__c</fullName>
    <formula>IF( OR(
        ISNULL(Respond_Date__c),
        PersonDoNotCall = TRUE,
        PersonHasOptedOutOfEmail ),
    NUll,
    Respond_Date__c + 3)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hot Leads Tier 1 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field holds the branch details</description>
    <inlineHelpText>Select the branch where the address resides in.</inlineHelpText>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Holds the City Name</description>
    <inlineHelpText>Enter the City Name</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Holds the state information</description>
    <inlineHelpText>Enter the state</inlineHelpText>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Holds the street information</description>
    <inlineHelpText>Enter the street information</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Used to store 5 digit zipCode.</description>
    <label>Primary Shipping Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/ANI__c.field-meta.xml
<CustomField>
    <fullName>ANI__c</fullName>
    <label>ANI</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Billing_Stage__c.field-meta.xml
<CustomField>
    <fullName>Billing_Stage__c</fullName>
    <description>It will hold the details about inventory, it is billable inventory or not.</description>
    <label>Billing Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Billable</fullName>
            </value>
            <value>
                <fullName>Non-Billable</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/fBilling_Opp_Account__c.field-meta.xml
<CustomField>
    <fullName>fBilling_Opp_Account__c</fullName>
    <formula>idCPL_Billing_Opportunity__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fBilling Opp Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/fHome_Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>fHome_Sale_Price__c</fullName>
    <description>This is the sale price of the house per the county recorder or agency we purchased the lead from.</description>
    <formula>User_Address__r.Sales_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fHome Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Hot_Leads_Tier_1_Date__c.field-meta.xml
<CustomField>
    <fullName>Hot_Leads_Tier_1_Date__c</fullName>
    <description>This field will contains Hot Leads Tier 1 Date info</description>
    <label>Hot Leads Tier 1 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/idCPL_Billing_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>idCPL_Billing_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>idCPL Billing Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Inventory (idCPL Billing Opportunity)</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/isProcessed__c.field-meta.xml
<CustomField>
    <fullName>isProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It will define that records processed for billing records creation or not.</description>
    <label>isProcessed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/OB_Call_Center_Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>OB_Call_Center_Appointment_Date__c</fullName>
    <label>OB Call Center Appointment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Operational_Stage_Hot_Leads__c.field-meta.xml
<CustomField>
    <fullName>Operational_Stage_Hot_Leads__c</fullName>
    <description>It captures Operational stage field values from Opportunity.</description>
    <label>Operational Stage - Hot Leads</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Tier 1</fullName>
            </value>
            <value>
                <fullName>Active Tier 2</fullName>
            </value>
            <value>
                <fullName>Active Tier 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Survey_Response__c.field-meta.xml
<CustomField>
    <fullName>Survey_Response__c</fullName>
    <description>It holds the value of Survey Response.</description>
    <label>Survey Response</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/UnMatching_Invetnory__c.field-meta.xml
<CustomField>
    <fullName>UnMatching_Invetnory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag will identify the inventory is created from Matching products or not matching product</description>
    <label>UnMatching Inventory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Hot_Leads_Tier_1_Date__c.field-meta.xml
<CustomField>
    <fullName>Hot_Leads_Tier_1_Date__c</fullName>
    <formula>IF(OR(ISNULL(Respond_Date__c), 
 UserAccount__r.PersonDoNotCall = TRUE, 
 UserAccount__r.PersonHasOptedOutOfEmail), 
NUll, 
Respond_Date__c + 3)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hot Leads Tier 1 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BatchBillingCreation_AC.cls
/*********************************************************************************
*Created by  : MST
*Description : This Schedule class is to auto creation of Billing and the Billing Line records for CPL,SPEC,SUB,Hot lead and DTS weekly,
*so that billing person can generate the Invoices for the Business Accounts correctly.
If there are multiple Inventory for which the Person Account and the Business Account is the same, 
then just one Billing record and the Billing Line record needs to be created.
If there are multiple Person Accounts associated to the same business account, then one billing record should be created and 
multiple billing line record needs to be created under the same billing record.
*************************************************************************************/

global class BatchBillingCreation_AC implements Database.Batchable<Aggregateresult> {
    Public String recordTypeName;
    Public Id accRecordTypeId;
    Public Id devRecordTypeId;
    Public Id oppRecordTypeId;
    // Getting Record type Id.
    Public BatchBillingCreation_AC(String recordTypeNameValue){
        recordTypeName = recordTypeNameValue;
        accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Accounts').getRecordTypeId();
        devRecordTypeId = Schema.SObjectType.Inventory__C.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
        if(recordTypeName.equalsIgnoreCase('nuHome Hot Lead'))
            oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
    }
    
    global iterable<Aggregateresult> start(Database.BatchableContext BC){ 
        list<AggregateResult> batchAggregationlist = NEW list<AggregateResult>();
        // Querying records to process for each record type.
        if(recordTypeName.equalsIgnorecase('nuHome OB Campaign'))
        {
            batchAggregationlist =  [SELECT idCPL_Billing_Opportunity__r.AccountID acc FROM Inventory__C WHERE ANI__c != NULL  
                                     AND isProcessed__c = false AND  fHome_Sale_Price__c != NULL AND Name != NULL AND OB_Call_Center_Appointment_Date__c != NULL 
                                     AND User_Address__r.Address__r.City__c != NULL AND User_Address__r.Address__r.State__c != NULL AND User_Address__r.Address__r.Street__c != NULL 
                                     AND Billing_Stage__c = 'Billable'  AND  User_Address__r.Address__r.zip_code__c != NULL AND recordtypeid =: devRecordTypeId AND Account__c != NULL AND fBilling_Opp_Account__c != NULL 
                                     AND idCPL_Billing_Opportunity__c != NULL AND idCPL_Billing_Opportunity__r.AccountID != NULL AND idCPL_Billing_Opportunity__r.Account.recordtypeid =: accRecordTypeId 
                                     GROUP BY idCPL_Billing_Opportunity__r.AccountID];
        }
        else if(recordTypeName.equalsIgnorecase('nuHome nuCard CPL'))
        {
            batchAggregationlist =  [SELECT idCPL_Billing_Opportunity__r.AccountID acc FROM Inventory__C WHERE recordtypeid =: devRecordTypeId  
                                     AND isProcessed__c = false and  Account__c != NULL AND Billing_Stage__c = 'Billable' AND fBilling_Opp_Account__c != NULL AND idCPL_Billing_Opportunity__c != NULL 
                                     AND idCPL_Billing_Opportunity__r.AccountID != NULL AND idCPL_Billing_Opportunity__r.Account.recordtypeid =: accRecordTypeId 
                                     GROUP BY idCPL_Billing_Opportunity__r.AccountID];
        }
        else if(recordTypeName.equalsIgnorecase('nuHome nuCard SUB'))
        {
            batchAggregationlist =  [SELECT idCPL_Billing_Opportunity__r.AccountID acc FROM Inventory__C WHERE recordtypeid =: devRecordTypeId 
                                     AND isProcessed__c = false and Account__c != NULL  AND Billing_Stage__c = 'Billable' AND fBilling_Opp_Account__c != NULL AND idCPL_Billing_Opportunity__c != NULL 
                                     AND idCPL_Billing_Opportunity__r.AccountID != NULL AND idCPL_Billing_Opportunity__r.Account.recordtypeid =: accRecordTypeId 
                                     GROUP BY idCPL_Billing_Opportunity__r.AccountID];
        }
        else if(recordTypeName.equalsIgnorecase('nuHome nuCard SPEC')){
            batchAggregationlist =  [SELECT idCPL_Billing_Opportunity__r.AccountID acc FROM Inventory__C WHERE recordtypeid =: devRecordTypeId  
                                     AND isProcessed__c = false and Account__c != NULL AND Billing_Stage__c = 'Billable' AND fBilling_Opp_Account__c != NULL 
                                     AND idCPL_Billing_Opportunity__c != NULL AND idCPL_Billing_Opportunity__r.AccountID != NULL 
                                     AND idCPL_Billing_Opportunity__r.Account.recordtypeid =: accRecordTypeId 
                                     GROUP BY idCPL_Billing_Opportunity__r.AccountID];
        }
        else if(recordTypeName.equalsIgnorecase('nuHome Door Tag Script')){
            batchAggregationlist =  [SELECT idCPL_Billing_Opportunity__r.AccountID acc FROM Inventory__C WHERE UnMatching_Invetnory__c = FALSE 
                                     AND isProcessed__c = false AND Billing_Stage__c = 'Billable' AND (Survey_Response__c ='Yes' OR Survey_Response__c ='Blinds' OR Survey_Response__c ='Shutters' OR Survey_Response__c ='Blinds and Shutters') AND  
                                     recordtypeid =: devRecordTypeId and  Account__c != NULL AND fBilling_Opp_Account__c != NULL AND idCPL_Billing_Opportunity__c != NULL 
                                     AND idCPL_Billing_Opportunity__r.AccountID != NULL AND idCPL_Billing_Opportunity__r.Account.recordtypeid =: accRecordTypeId 
                                     GROUP BY idCPL_Billing_Opportunity__r.AccountID];
        }
        else if(recordTypeName.equalsIgnorecase('nuHome Hot Lead')){
            batchAggregationlist =  [SELECT idCPL_Billing_Opportunity__r.AccountID acc FROM Inventory__C WHERE (((idCPL_Billing_Opportunity__r.Pricebook2.Name = 'nuHome Hot Leads - Tier 1' OR idCPL_Billing_Opportunity__r.Pricebook2.Name = 'Hot Leads Price Book') 
                                                                                                                 AND (User_Address__r.Hot_Leads_Tier_1_Date__c <: Date.Today() AND User_Address__r.Hot_Leads_Tier_1_Date__c >: Date.Today()-8) AND Operational_Stage_Hot_Leads__c = 'Active Tier 1') 
                                                                                                                OR ((idCPL_Billing_Opportunity__r.Pricebook2.Name = 'nuHome Hot Leads - Tier 2' OR idCPL_Billing_Opportunity__r.Pricebook2.Name = 'Hot Leads Price Book') AND (User_Address__r.Hot_Leads_Tier_2_Date__c <: Date.Today() AND User_Address__r.Hot_Leads_Tier_2_Date__c >: Date.Today()-8) AND Operational_Stage_Hot_Leads__c = 'Active Tier 2') 
                                                                                                                OR ((idCPL_Billing_Opportunity__r.Pricebook2.Name = 'nuHome Hot Leads - Tier 3' OR idCPL_Billing_Opportunity__r.Pricebook2.Name = 'Hot Leads Price Book') AND (User_Address__r.Hot_Leads_Tier_3_Date__c <: Date.Today() AND User_Address__r.Hot_Leads_Tier_3_Date__c >: Date.Today()-8) AND Operational_Stage_Hot_Leads__c = 'Active Tier 3'))  AND  recordtypeid =: devRecordTypeId 
                                     AND isProcessed__c = false  and  idCPL_Billing_Opportunity__r.recordtypeid =:oppRecordTypeId and  Account__c != NULL AND fBilling_Opp_Account__c != NULL AND idCPL_Billing_Opportunity__c != NULL AND idCPL_Billing_Opportunity__r.AccountID != NULL  AND Billing_Stage__c = 'Billable' AND idCPL_Billing_Opportunity__r.Account.recordtypeid =: accRecordTypeId GROUP BY idCPL_Billing_Opportunity__r.AccountID];
        }
        return batchAggregationlist;
    }
    
    global void execute(Database.BatchableContext BC, List<AggregateResult> scope) {
        Set<id> businessAccountIDSet = NEW Set<id>();
        Map<id,Set<ID>> unMatchingAccountMap = NEW Map<id,Set<ID>>();
        Map<id,Inventory__C> inventoryMap = NEW Map<id,Inventory__C>();
        Map<String,inventory__C> personAccountMap = NEW Map<string,inventory__C>();
        Map<String,inventory__C> personAccountMap1 = NEW Map<String,inventory__C>();
        Map<id,List<Inventory__c>> unMatchingDoorTagMap = NEW Map<id,List<Inventory__c>>();
        List<inventory__C> inventoryList = NEW  List<inventory__C>();
        Map<Id,Inventory__c> inventoryToUpdateMap = new Map<Id,Inventory__c>();
        // parsing the aggregate ids.
        For(AggregateResult INv:scope){
            String accIds = String.valueof(inv.get('acc'));
            businessAccountIDSet.add(accIds);
        }
        
        // Querying inventory records based on the acceptance criteria and record types.
        if(recordTypeName.equalsIgnorecase('nuHome OB Campaign')){
            inventoryList =  [SELECT Name,Survey_Question__c,Survey_Response__c,Account__r.MSA__c,Phone_Mobile__c,createdDate,fHome_Sale_Price__c,OB_Call_Center_Appointment_Date__c,ANI__c,User_Address__r.Address__r.City__c,
                              User_Address__r.Address__r.State__c,User_Address__r.Address__r.Street__c,fAccount_Email__c,User_Address__r.Address__r.zip_code__c,Account__c,Account__r.Name,fBilling_Opp_Account_ID__c,fBilling_Opp_Account__c,
                              idCPL_Billing_Opportunity__r.Account.Primary_Billing_City__c,idCPL_Billing_Opportunity__r.Account.Primary_Billing_State__c,User_Address__r.Address__r.Country__c,
                              idCPL_Billing_Opportunity__r.Account.Primary_Billing_Street__c,idCPL_Billing_Opportunity__r.Account.Phone,idCPL_Billing_Opportunity__r.Account.Primary_Billing_Zip_Code__c,
                              idCPL_Billing_Opportunity__r.Account.Primary_Billing_Country__c,user_address__r.address__r.Branch__r.Name,fBilling_Opp_Industry__c,Account__r.phone, Account__r.personmobilephone,
                              account__r.Primary_Shipping_Country__c,Product_Name__c,Product_Price__c,Quantity__c,List_Price__c,user_Address__r.Address__r.MSA__c
                              FROM Inventory__C WHERE idCPL_Billing_Opportunity__r.AccountID IN:businessAccountIDSet   AND Billing_Stage__c = 'Billable' AND 
                              ANI__c != NULL AND isProcessed__c = false AND fHome_Sale_Price__c != NULL AND Name != NULL AND OB_Call_Center_Appointment_Date__c != NULL AND User_Address__r.Address__r.City__c != NULL AND User_Address__r.Address__r.State__c != NULL AND fAccount_Street__c != NULL AND User_Address__r.Address__r.zip_code__c != NULL AND recordtypeid =: devRecordTypeId and  Account__c != NULL AND fBilling_Opp_Account__c != NULL AND idCPL_Billing_Opportunity__c != NULL AND idCPL_Billing_Opportunity__r.AccountID != NULL AND idCPL_Billing_Opportunity__r.Account.recordtypeid =: accRecordTypeId];
        }
        
        else if(recordTypeName.equalsIgnorecase('nuHome nuCard CPL') || recordTypeName.equalsIgnorecase('nuHome nuCard SUB')){
            inventoryList =  [SELECT Name,Survey_Question__c,Survey_Response__c,Account__r.MSA__c,Phone_Mobile__c,createdDate,fHome_Sale_Price__c,OB_Call_Center_Appointment_Date__c,ANI__c,User_Address__r.Address__r.City__c,
                              User_Address__r.Address__r.State__c,User_Address__r.Address__r.Street__c,fAccount_Email__c,User_Address__r.Address__r.zip_code__c,Account__c,Account__r.Name,fBilling_Opp_Account_ID__c,fBilling_Opp_Account__c,
                              idCPL_Billing_Opportunity__r.Account.Primary_Billing_City__c,idCPL_Billing_Opportunity__r.Account.Primary_Billing_State__c,User_Address__r.Address__r.Country__c,
                              user_address__r.address__r.Branch__r.Name,idCPL_Billing_Opportunity__r.Account.Primary_Billing_Street__c,idCPL_Billing_Opportunity__r.Account.Primary_Billing_Zip_Code__c,
                              idCPL_Billing_Opportunity__r.Account.Primary_Billing_Country__c,fBilling_Opp_Industry__c,idCPL_Billing_Opportunity__r.Account.Phone,Account__r.phone, Account__r.personmobilephone,
                              account__r.Primary_Shipping_Country__c,Product_Name__c,Product_Price__c,Quantity__c,List_Price__c,user_Address__r.Address__r.MSA__c
                              FROM Inventory__C WHERE idCPL_Billing_Opportunity__r.AccountID IN:businessAccountIDSet  AND Billing_Stage__c = 'Billable' AND
                              recordtypeid =: devRecordTypeId AND isProcessed__c = false AND Account__c != NULL AND fBilling_Opp_Account__c != NULL AND idCPL_Billing_Opportunity__c != NULL AND idCPL_Billing_Opportunity__r.AccountID != NULL AND idCPL_Billing_Opportunity__r.Account.recordtypeid =: accRecordTypeId];
        }
        
        else if(recordTypeName.equalsIgnorecase('nuHome nuCard SPEC')){
            inventoryList =  [SELECT Name,Survey_Question__c,Survey_Response__c,Account__r.MSA__c,Phone_Mobile__c,createdDate,fHome_Sale_Price__c,OB_Call_Center_Appointment_Date__c,ANI__c,User_Address__r.Address__r.City__c,
                              User_Address__r.Address__r.State__c,User_Address__r.Address__r.Street__c,fAccount_Email__c,User_Address__r.Address__r.zip_code__c,Account__c,Account__r.Name,fBilling_Opp_Account_ID__c,fBilling_Opp_Account__c, 
                              idCPL_Billing_Opportunity__r.Account.Primary_Billing_City__c,idCPL_Billing_Opportunity__r.Account.Primary_Billing_State__c,
                              user_address__r.address__r.Branch__r.Name,idCPL_Billing_Opportunity__r.Account.Primary_Billing_Street__c,idCPL_Billing_Opportunity__r.Account.Primary_Billing_Zip_Code__c,
                              account__r.Primary_Shipping_Country__c,Product_Name__c,Product_Price__c,Quantity__c,List_Price__c,User_Address__r.Address__r.Country__c,user_Address__r.Address__r.MSA__c,
                              idCPL_Billing_Opportunity__r.Account.Primary_Billing_Country__c,fBilling_Opp_Industry__c,idCPL_Billing_Opportunity__r.Account.Phone,Account__r.phone, Account__r.personmobilephone
                              FROM Inventory__C WHERE idCPL_Billing_Opportunity__r.AccountID IN:businessAccountIDSet  AND 
                              recordtypeid =: devRecordTypeId and isProcessed__c = false AND Billing_Stage__c = 'Billable' AND Account__c != NULL AND fBilling_Opp_Account__c != NULL AND idCPL_Billing_Opportunity__c != NULL AND idCPL_Billing_Opportunity__r.AccountID != NULL AND idCPL_Billing_Opportunity__r.Account.recordtypeid =: accRecordTypeId];
        }
        
        else if(recordTypeName.equalsIgnorecase('nuHome Door Tag Script')){
            inventoryList =  [SELECT Name,Product_Name__c,Product_Price__c,Quantity__c,List_Price__c,Survey_Question__c,Survey_Response__c,user_address__r.address__r.Branch__r.Name,
                              Account__r.MSA__c,Phone_Mobile__c,createdDate,fHome_Sale_Price__c,OB_Call_Center_Appointment_Date__c,ANI__c,User_Address__r.Address__r.City__c,
                              User_Address__r.Address__r.State__c,User_Address__r.Address__r.Street__c,fAccount_Email__c,User_Address__r.Address__r.zip_code__c,Account__c,Account__r.Name,fBilling_Opp_Account_ID__c,fBilling_Opp_Account__c, 
                              idCPL_Billing_Opportunity__r.Account.Primary_Billing_City__c,idCPL_Billing_Opportunity__r.Account.Primary_Billing_State__c,
                              idCPL_Billing_Opportunity__r.Account.Primary_Billing_Country__c,idCPL_Billing_Opportunity__r.Account.Primary_Billing_Street__c,idCPL_Billing_Opportunity__r.Account.Primary_Billing_Zip_Code__c,
                              account__r.Primary_Shipping_Country__c,User_Address__r.Address__r.Country__c,user_Address__r.Address__r.MSA__c,
                              fBilling_Opp_Industry__c,idCPL_Billing_Opportunity__r.Account.Phone,Account__r.phone, Account__r.personmobilephone
                              FROM Inventory__C WHERE idCPL_Billing_Opportunity__r.AccountID IN:businessAccountIDSet  AND
                              UnMatching_Invetnory__c = FALSE  AND Billing_Stage__c = 'Billable' AND isProcessed__c = false AND (Survey_Response__c ='Yes' OR Survey_Response__c ='Blinds' OR Survey_Response__c ='Shutters' OR Survey_Response__c ='Blinds and Shutters') AND  recordtypeid =: devRecordTypeId and  Account__c != NULL AND fBilling_Opp_Account__c != NULL AND idCPL_Billing_Opportunity__c != NULL AND idCPL_Billing_Opportunity__r.AccountID != NULL AND idCPL_Billing_Opportunity__r.Account.recordtypeid =: accRecordTypeId];
        }
        
        else if(recordTypeName.equalsIgnorecase('nuHome Hot Lead')){
            inventoryList =  [SELECT Name,Survey_Question__c,Survey_Response__c,Account__r.MSA__c,user_address__r.address__r.Branch__r.Name,Phone_Mobile__c,createdDate,fHome_Sale_Price__c,OB_Call_Center_Appointment_Date__c,ANI__c,User_Address__r.Address__r.City__c,
                              User_Address__r.Address__r.State__c,User_Address__r.Address__r.Street__c,User_Address__r.Address__r.Country__c,fAccount_Email__c,User_Address__r.Address__r.zip_code__c,Account__c,Account__r.Name,fBilling_Opp_Account_ID__c,fBilling_Opp_Account__c ,
                              idCPL_Billing_Opportunity__r.Account.Primary_Billing_City__c,idCPL_Billing_Opportunity__r.Account.Primary_Billing_State__c,
                              idCPL_Billing_Opportunity__r.Account.Primary_Billing_Street__c,idCPL_Billing_Opportunity__r.Account.Primary_Billing_Zip_Code__c,
                              idCPL_Billing_Opportunity__r.Account.Primary_Billing_Country__c,fBilling_Opp_Industry__c,idCPL_Billing_Opportunity__r.Account.Phone,Account__r.phone, Account__r.personmobilephone,
                              account__r.Primary_Shipping_Country__c,Product_Name__c,Product_Price__c,Quantity__c,List_Price__c,user_Address__r.Address__r.MSA__c
                              FROM Inventory__C WHERE idCPL_Billing_Opportunity__r.AccountID IN:businessAccountIDSet AND Billing_Stage__c = 'Billable'
                              AND (((idCPL_Billing_Opportunity__r.Pricebook2.Name = 'nuHome Hot Leads - Tier 1' OR idCPL_Billing_Opportunity__r.Pricebook2.Name = 'Hot Leads Price Book') AND (User_Address__r.Hot_Leads_Tier_1_Date__c <: Date.Today() AND User_Address__r.Hot_Leads_Tier_1_Date__c >: Date.Today()-8) AND Operational_Stage_Hot_Leads__c = 'Active Tier 1') 
                                   OR ((idCPL_Billing_Opportunity__r.Pricebook2.Name = 'nuHome Hot Leads - Tier 2' OR idCPL_Billing_Opportunity__r.Pricebook2.Name = 'Hot Leads Price Book') AND (User_Address__r.Hot_Leads_Tier_2_Date__c <: Date.Today() AND User_Address__r.Hot_Leads_Tier_1_Date__c >: Date.Today()-8) AND Operational_Stage_Hot_Leads__c = 'Active Tier 2') 
                                   OR ((idCPL_Billing_Opportunity__r.Pricebook2.Name = 'nuHome Hot Leads - Tier 3' OR idCPL_Billing_Opportunity__r.Pricebook2.Name = 'Hot Leads Price Book') AND (User_Address__r.Hot_Leads_Tier_3_Date__c <: Date.Today() AND User_Address__r.Hot_Leads_Tier_1_Date__c >: Date.Today()-8) AND Operational_Stage_Hot_Leads__c = 'Active Tier 3')) 
                              AND recordtypeid =: devRecordTypeId and idCPL_Billing_Opportunity__r.recordtypeid =:OppRecordTypeId AND  Account__c != NULL AND fBilling_Opp_Account__c != NULL 
                              AND isProcessed__c = false AND idCPL_Billing_Opportunity__c != NULL AND idCPL_Billing_Opportunity__r.AccountID != NULL AND idCPL_Billing_Opportunity__r.Account.recordtypeid =: accRecordTypeId];
        }
        
        Set<String> surveyQuestionsSet = new Set<String>(); 
        Map<Id,List<Inventory__c>> businessAccountMap = new Map<Id,List<Inventory__c>>(); 
        Map<Id,List<Inventory__c>> billingOppIdMap = new  Map<Id,List<Inventory__c>>();
        String Industry;
        Map<String,String> industryCustomSettingMap = new Map<String,String>();
        Set<String> productNamesSet = new Set<String>();
        Set<Id> opportunityIds = new Set<Id>();
        
        Map<Id,Set<Id>> cplOppMap = new Map<Id,Set<Id>>();
        
        Set<String> zipCodesSet = new Set<String>();
        
        For(Inventory__C inv : inventoryList){
            inv.isProcessed__c = True;
            inventoryToUpdateMap.put(inv.id, inv);
            productNamesSet.add(inv.user_address__r.address__r.branch__r.name+'-'+inv.fBilling_Opp_Industry__c);
            
            opportunityIds.add(inv.idCPL_Billing_Opportunity__c);
            zipCodesSet.add(inv.User_Address__r.Address__r.zip_code__c);
            
            if(!recordTypeName.equalsIgnorecase('nuHome Door Tag Script')){
                
                if(!unMatchingAccountMap.containsKey(inv.fBilling_Opp_Account_ID__c))
                {
                    unMatchingAccountMap.put(inv.fBilling_Opp_Account_ID__c,new set<ID>{inv.Account__c}); 
                    cplOppMap.put(inv.fBilling_Opp_Account_ID__c,new Set<ID>{inv.idCPL_Billing_Opportunity__c});
                }
                
                else if(unMatchingAccountMap.containsKey(inv.fBilling_Opp_Account_ID__c))
                {
                    unMatchingAccountMap.get(inv.fBilling_Opp_Account_ID__c).add(inv.Account__c);
                    cplOppMap.get(inv.fBilling_Opp_Account_ID__c).add(inv.idCPL_Billing_Opportunity__c);
                }
                
                inventoryMap.put(inv.fBilling_Opp_Account_ID__c,inv);
                System.debug('Idvalues+++++++++++++++++++++++++++++++++++++++++++++++++++++= ' + (inv.idCPL_Billing_Opportunity__c+'-'+inv.account__c));
                personAccountMap.put(inv.idCPL_Billing_Opportunity__c+'-'+inv.account__c,inv);
            }
            
            if(recordTypeName.equalsIgnorecase('nuHome Door Tag Script')){
                
                if(!businessAccountMap.containsKey(inv.fBilling_Opp_Account_ID__c))
                    businessAccountMap.put(inv.fBilling_Opp_Account_ID__c,new List<Inventory__c>{inv});
                else if(businessAccountMap.containsKey(inv.fBilling_Opp_Account_ID__c))
                    businessAccountMap.get(inv.fBilling_Opp_Account_ID__c).add(inv);
                inventoryMap.put(inv.fBilling_Opp_Account_ID__c,inv);
                personAccountMap.put(inv.idCPL_Billing_Opportunity__c+'-'+inv.account__c,inv);
            }
        }
        
        Map<String, List<OpportunityLineITem>> productLineItemMap = new Map<String, List<OpportunityLineITem>>();
        for(OpportunityLineITem currItem : [SELECT Id, Name, Product2.Name, OpportunityId, Quantity, ListPrice, UnitPrice FROM OpportunityLineItem
                                            WHERE Product2.Name IN :productNamesSet AND OpportunityId IN :opportunityIds])
        {
            if(!productLineItemMap.containsKey(currItem.OpportunityId+'-'+currItem.product2.Name))
                productLineItemMap.put(currItem.OpportunityId+'-'+currItem.product2.Name, new List<OpportunityLineITem>{currItem});
            else
                productLineItemMap.get(currItem.OpportunityId+'-'+currItem.product2.Name).add(currItem);
        }
      
        if(!recordTypeName.equalsIgnorecase('nuHome Door Tag Script') && !unMatchingAccountMap.isEmpty() && !inventoryMap.isEmpty()){
            BatchBillingHandler.ProcessUnMatchingBillingRecords(unMatchingAccountMap,cplOppMap,inventoryMap,personAccountMap,recordTypeName,inventoryToUpdateMap,productLineItemMap);
        }
        
        if(recordTypeName.equalsIgnorecase('nuHome Door Tag Script') && !businessAccountMap.isEmpty()){
            BatchBillingHandler.ProcessDoorTagScriptBillingRecords(businessAccountMap,recordTypeName,inventoryMap,inventoryToUpdateMap);
        }
    }
    global void finish(Database.BatchableContext BC) {
    }
}