force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Home_Automation_Status__c.field-meta.xml
<CustomField>
    <fullName>Home_Automation_Status__c</fullName>
    <label>Home Automation Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pest_Control_Status__c.field-meta.xml
<CustomField>
    <fullName>Pest_Control_Status__c</fullName>
    <label>Pest Control Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Solar_Status__c.field-meta.xml
<CustomField>
    <fullName>Solar_Status__c</fullName>
    <label>Solar Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Water_Status__c.field-meta.xml
<CustomField>
    <fullName>Water_Status__c</fullName>
    <label>Water Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Window_Status__c.field-meta.xml
<CustomField>
    <fullName>Window_Status__c</fullName>
    <label>Window Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/neverBounce__c/neverBounce__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>neverBounce</label>
</CustomObject>

force-app/main/default/objects/neverBounce__c/fields/ApiKey__c.field-meta.xml
<CustomField>
    <fullName>ApiKey__c</fullName>
    <label>ApiKey</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/Emails_per_page__c.field-meta.xml
<CustomField>
    <fullName>Emails_per_page__c</fullName>
    <label>Emails per page</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/First_Job__c.field-meta.xml
<CustomField>
    <fullName>First_Job__c</fullName>
    <label>First Job</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/Job_id__c.field-meta.xml
<CustomField>
    <fullName>Job_id__c</fullName>
    <label>Job id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/next_page__c.field-meta.xml
<CustomField>
    <fullName>next_page__c</fullName>
    <defaultValue>0</defaultValue>
    <label>next page</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/number_of_pages__c.field-meta.xml
<CustomField>
    <fullName>number_of_pages__c</fullName>
    <label>number of pages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/Second_Job__c.field-meta.xml
<CustomField>
    <fullName>Second_Job__c</fullName>
    <label>Second Job</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Send_Grid__c/Send_Grid__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global value sendgrid</description>
    <label>Send Grid</label>
</CustomObject>

force-app/main/default/objects/Send_Grid__c/fields/Api_Key__c.field-meta.xml
<CustomField>
    <fullName>Api_Key__c</fullName>
    <label>Api Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiacoOffersSendGridTest.cls
@isTest
public class DiacoOffersSendGridTest {
    
    @isTest static void testSendgrid(){
        neverBounce__c nb = new neverBounce__c(
            Job_id__c = '277461',
            number_of_pages__c = 10,
            next_page__c = 1, 
            ApiKey__c = 'Apikey******', 
            First_Job__c = 3, 
            Second_Job__c =1, 
            Emails_per_page__c = 10 
        );
        upsert nb;
        Send_Grid__c sendgrid = new Send_Grid__c(
            Api_Key__c = '277461'
        );
        upsert sendgrid;
        Account acc = new Account(
            FirstName = 'Test acc',
            LastName = 'last test',
            PersonEmail = 'test@test.com',
            Street__c= 'Test street',
            State__c= 'AZ',
            City__c = 'Arizona',
            Zip__c = '12345',
            Solar_Status__c= 'Test solar',
            Water_Status__c= 'Test water',
            Window_Status__c = 'Test Window',
            Pest_Control_Status__c= 'Test Pest',
            Home_Automation_Status__c= 'Test HA'
        );
        List<Account> accounts = new List<Account>();
        accounts.add(acc);
        insert accounts;
        List<String> ids = new List<String>();
        ids.add(accounts[0].Id);
		test.startTest();
        test.setMock(HttpCalloutMock.class, new diacoSendGridSincronizeHttpCallOutMock());
        DiacoOfferSendGrid.SendEmail(ids);
        test.stopTest();
    }
}