force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field having picklist values</description>
    <label>Verbal Consent Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level1</fullName>
            </value>
            <value>
                <fullName>Level2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Form__c/Lead_Form__c.object-meta.xml
<CustomObject>
    <label>Lead Form</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lead Forms</relationshipLabel>
    <relationshipName>Lead_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/DiacoLeadFormsManageController.cls
public class DiacoLeadFormsManageController {
    @AuraEnabled
    public static List<Lead_Form__c> getLeadForms(){  
        String query = 'select Id, First_Name__c, Last_Name__c, Street__c, City__c, State__c, Zip__c, Phone__c'
            + ' from Lead_Form__c'
            + ' order by CreatedDate desc';
        
        system.debug(query);
        List<Lead_Form__c> LeadFormsList = Database.query(query);
        
        return LeadFormsList;
    }
    @AuraEnabled
    public static Lead_Form__c saveLeadForm(Lead_Form__c leadForm){
        update leadForm;
        return leadForm;
    }
    @AuraEnabled
    public static List<Task> createLogCall(Task task){
        insert task;
        
        String query = 'select Subject, ActivityDate, Description, Dispositions__c'
            + ' from Task'
            + ' where WhatId = \'' + task.WhatId + '\''
            + ' order by CreatedDate desc';
        List<Task> TaskList = Database.query(query);   
        
        return TaskList;
    }
    @AuraEnabled
    public static DataSet getLeadForm(String recordId){  
        String query = 'select Id, First_Name__c, Last_Name__c, Street__c, City__c, State__c, Zip__c, Phone__c,Account__c,Email__c'
            + ' from Lead_Form__c'
            + ' where Id = \'' + recordId + '\'';
        system.debug(query);
        List<Lead_Form__c> LeadFormsList = Database.query(query);
        
        if(LeadFormsList.size() > 0){
            query = 'select Subject, ActivityDate, Description, Dispositions__c'
                + ' from Task'
                + ' where WhatId = \'' + recordId + '\''
                + ' order by CreatedDate desc';
           	List<Task> TaskList = Database.query(query);
            
            return new DataSet(LeadFormsList[0], TaskList);
        }
        return null;
    }
    
    
    
    public class DataSet{
        @AuraEnabled
        public Lead_Form__c LeadForm {get;set;}
        @AuraEnabled
        public List<Task> Tasks {get;set;}
        
        public DataSet(Lead_Form__c LeadForm, List<Task> Tasks){
            this.LeadForm  = LeadForm; 
            this.Tasks     = Tasks;
        }
        
    }
    @AuraEnabled
    public static List<Account> getPossibleAccounts(String LeadPhone,String LeadEmail){
        List<Account> accounts=[SELECT id,Name,City__c,Phone,PersonEmail,State__c FROM Account Where Phone=:LeadPhone and PersonEmail=:LeadEmail];
        return accounts;
    }
    
    @AuraEnabled
    public static void associateLeadFormWithAccount(String LeadId,String AccountId){
        Lead_Form__c lead=[SELECT Id,Account__c FROM Lead_Form__c where Id=:LeadId];
        lead.Account__c=AccountId;
        update lead;
    }
    
    @AuraEnabled
    public static Account AccountgetAssociatedAccount(String AccountId){
        Account account=[SELECT id,Name,City__c,Phone,PersonEmail,State__c FROM Account Where Id=:AccountId Limit 1];
        return account;
    }
    
    @AuraEnabled
    public static Lead_Form__c getIndividualLeadForm(String recordId){
        Lead_Form__c lead=[SELECT Id, First_Name__c, Last_Name__c, 
                           Street__c, City__c, State__c, Zip__c, Phone__c,
                           Account__c,Email__c FROM Lead_Form__c where Id=:recordId Limit 1];
        return lead;
    }
    
    @AuraEnabled
    public static Map<String, String> getCountyData() {
        return DiacoWaterContractController.getCountyData();
    }
}