force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountBillingAddressBatchTest.cls
/**
* Diaco
* @author 			Giovanni Ulloque href=<Gulloque@diaco.us>
* Project:			Script to update Billing Address from Address. 
* Description:		class responsible to update Billing Address.
* Test:             AccountBillingAddressBatchTest
*
* Changes (Version)
* -------------------------------------
*			No.		Date			Author						Description
*			-----	----------		--------------------		---------------
* @version	1.0		31/10/2020	    Giovanni Ulloque (GU)		Initial implementation of the class.
**/

@isTest
public class AccountBillingAddressBatchTest {
    @testSetup 
    static void setup() {
        List<Account> accounts = new List<Account>();
        // insert 10 accounts
        for (Integer i = 0; i<10; i++) {
            accounts.add(new Account(name='Account ' + i, 
                Street__c = '', City__c = '', State__c = '', Zip__c = ''));
        }
        insert accounts;
    }
    
    static testmethod void test() {        
        Test.startTest();
        Id batchId = Database.executeBatch(new AccountBillingAddressBatch(10));
        Test.stopTest();
        // after the testing stops, assert records were updated properly
    }

}