force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field having picklist values</description>
    <label>Verbal Consent Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level1</fullName>
            </value>
            <value>
                <fullName>Level2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Holds the City Name</description>
    <inlineHelpText>Enter the City Name</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Holds the state information</description>
    <inlineHelpText>Enter the state</inlineHelpText>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Holds the street information</description>
    <inlineHelpText>Enter the street information</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Used to store 5 digit zipCode.</description>
    <label>Primary Shipping Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/neverBounce__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>neverBounce</label>
</CustomObject>

force-app/main/default/objects/neverBounce__c/fields/ApiKey__c.field-meta.xml
<CustomField>
    <fullName>ApiKey__c</fullName>
    <label>ApiKey</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/First_Job__c.field-meta.xml
<CustomField>
    <fullName>First_Job__c</fullName>
    <label>First Job</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/Job_id__c.field-meta.xml
<CustomField>
    <fullName>Job_id__c</fullName>
    <label>Job id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/next_page__c.field-meta.xml
<CustomField>
    <fullName>next_page__c</fullName>
    <defaultValue>0</defaultValue>
    <label>next page</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/number_of_pages__c.field-meta.xml
<CustomField>
    <fullName>number_of_pages__c</fullName>
    <label>number of pages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/fields/Kunnect_ID__c.field-meta.xml
<CustomField>
    <fullName>Kunnect_ID__c</fullName>
    <inlineHelpText>This is a Required field.  If this person does not have a Kunnect account please put &quot;none&quot;</inlineHelpText>
    <label>Kunnect ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/salesRabbitUserId__c.field-meta.xml
<CustomField>
    <fullName>salesRabbitUserId__c</fullName>
    <label>SalesRabbit User Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/SF_User__c.field-meta.xml
<CustomField>
    <fullName>SF_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Personnels2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/salesRabbitSchedule__c/salesRabbitSchedule__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>this object is responsible of organize the schedules to update records in salesforce when some record in salesrabbit has been updated and delete some record in salesrabbit after some time.</description>
    <label>SalesRabbit Schedule</label>
</CustomObject>

force-app/main/default/objects/salesRabbitSchedule__c/fields/deleteAfter__c.field-meta.xml
<CustomField>
    <fullName>deleteAfter__c</fullName>
    <label>Delete After</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/salesRabbitSchedule__c/fields/deleteAfterOptions__c.field-meta.xml
<CustomField>
    <fullName>deleteAfterOptions__c</fullName>
    <label>Delete After Options</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/salesRabbitSchedule__c/fields/knockCounter__c.field-meta.xml
<CustomField>
    <fullName>knockCounter__c</fullName>
    <label>Knock Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/salesRabbitSchedule__c/fields/maxSalePrice__c.field-meta.xml
<CustomField>
    <fullName>maxSalePrice__c</fullName>
    <label>maximun sale price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/salesRabbitSchedule__c/fields/minSalePrice__c.field-meta.xml
<CustomField>
    <fullName>minSalePrice__c</fullName>
    <label>minimum sale price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/salesRabbitSchedule__c/fields/options__c.field-meta.xml
<CustomField>
    <fullName>options__c</fullName>
    <label>Options</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/salesRabbitSchedule__c/fields/quantityDayOrHour__c.field-meta.xml
<CustomField>
    <fullName>quantityDayOrHour__c</fullName>
    <label>How often?</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/salesRabbitSchedule__c/fields/token__c.field-meta.xml
<CustomField>
    <fullName>token__c</fullName>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/knock_counter__c.field-meta.xml
<CustomField>
    <fullName>knock_counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>knock counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/PersonMobilePhone__c.field-meta.xml
<CustomField>
    <fullName>PersonMobilePhone__c</fullName>
    <description>This field will store the person Mobile Phone number</description>
    <label>PersonMobilePhone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field will store the person Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/sales_rabbit_leadId__c.field-meta.xml
<CustomField>
    <fullName>sales_rabbit_leadId__c</fullName>
    <label>salesrabbit lead Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DiacoSalesRabbitIntegrationTest.cls
/**
* Diaco
* @author 			Jorge Martinez href=<jorgeality29@gmail.com>
* Project:			SalesRabbit Integration
* Description:		Class responsible for testing DiacoSalesRabbitIntegrationc class
*
* Changes (Version)
* -------------------------------------
*			No.		Date			Author					Description
*			-----	----------		--------------------	---------------
* @version	1.0		04/09/2018		Jorge Martinez (JM)		Initial implementation of the class.
**/
@isTest
public class DiacoSalesRabbitIntegrationTest {
    @isTest static void Test() {
        
        
        UserRole r = new UserRole(DeveloperName = 'MyCustomRole', Name = 'My Role');
        insert r;
        User user = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'puser000@amamama.com',
            Username = 'puser000@amamama.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            UserRoleId = r.Id
        );
        insert user;
        
        
        
        
        
        System.runAs ( user ) {
            Personnel__c personnel = new Personnel__c(
                    Name = 'tst',
                    Kunnect_ID__c = 'none',
                    salesRabbitUserId__c = '911705138',
                	SF_User__c = user.Id
            );
            insert personnel;
            salesRabbitSchedule__c customsetting = new salesRabbitSchedule__c(
                    quantityDayOrHour__c = 2,
                    options__c = 'hours',
                    knockCounter__c = 5,
                    deleteAfter__c = 5,
                    minSalePrice__c = 20000,
                    maxSalePrice__c = 100000,
                    deleteAfterOptions__c = 'days',
                	token__c = 'T3ok8e9nt7e4s1t1'
            );
            upsert customsetting;
            Account acc = new Account(
                FirstName ='test',
                LastName = 'test',
                Phone = '6643433',
                PersonMobilePhone = '1234567890',
                Street__c = 'cll 43',
                State__c = 'CO',
                City__c = 'cartagena',
                Zip__c  = '12345'
            );
            insert acc;
            Address__c ads = new Address__c(
                City__c = 'cartagena',
                Country__c = 'US',
                State__c = 'CO',
                Street__c = 'test',
                Zip_Code__c = '12352'
            );
            insert ads;
            User_Address__c uadd = new User_Address__c(
                Email__c = 'test@test.com',
                Phone__c = '6627786',
                status__c ='Other',
                knock_counter__c = 4,
                PersonMobilePhone__c= '3014263364',
                UserAccount__c = acc.Id,
                Address__c = ads.Id,
                sales_rabbit_leadId__c = '85',
                Sales_Price__c = 50000
            );
            insert uadd;
            User_Address__c uadd2 = new User_Address__c(
                Email__c = 'test@test.com',
                Phone__c = '6627786',
                status__c ='Other',
                knock_counter__c = 3,
                PersonMobilePhone__c= '3014263364',
                UserAccount__c = acc.Id,
                Address__c = ads.Id,
                sales_rabbit_leadId__c = '85',
                Sales_Price__c = 50000
            );
            insert uadd2;
            neverBounce__c nb = new neverBounce__c(
                Job_id__c = '277461',
                number_of_pages__c = 10,
                next_page__c = 1, 
                ApiKey__c = 'Apikey******', 
                First_Job__c = 3, 
                Second_Job__c =1, 
                Emails_per_page__c = 10 
            );
            upsert nb;
            

            String token = 'e9d241343edfbe085176aeae2661282c8cb8e62490ff5b09563dddf22523158ed53b2142cd9e4f3d551c375b6489eaebac663f7eca480dd002c4c44fc357c307'; 
            String body = '{"data": {"userId":911705138,"firstName":"jorge test","lastName":"martinez","phonePrimary":"6627786","phoneAlternate":"(301) 426-3364","street1":"la candelaria","city":"cartagena","state":"AR","zip":"523621","status":"New Lead","email":"test@test.com"}}';
            Date ifModifiedSince = Date.newInstance(2018, 08, 07);
            Test.startTest();
            Integer leadId = 85;
            Test.setMock(HttpCalloutMock.class, new DiacoSalesRabbitIntegrationCalloutMock());
            DiacoSalesRabbitIntegration.leadsToUpdate(
                DiacoSalesRabbitIntegration.allLeads(token, ifModifiedSince)
            );
            DiacoSalesRabbitIntegration.createLeadSR(token, body, uadd.Id);
            DiacoSalesRabbitIntegration.createLeads(token, body);
            DiacoSalesRabbitIntegration.dateStmap('2018-08-16T17:51:02+00:00');
            DiacoSalesRabbitIntegration.allLeadsSR(token, ifModifiedSince);
            DiacoSalesRabbitIntegration.deleteLead(token, leadId);
            Test.stopTest();
            
        }
    }
}