force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Down_Payment__c.field-meta.xml
<CustomField>
    <fullName>Down_Payment__c</fullName>
    <label>Down Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/FileNumber__c.field-meta.xml
<CustomField>
    <fullName>FileNumber__c</fullName>
    <description>File Number from Ion Data</description>
    <externalId>true</externalId>
    <label>FileNumber</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Home_Type__c.field-meta.xml
<CustomField>
    <fullName>Home_Type__c</fullName>
    <label>Home Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>MF</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>SF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/New__c.field-meta.xml
<CustomField>
    <fullName>New__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recording_Date__c.field-meta.xml
<CustomField>
    <fullName>Recording_Date__c</fullName>
    <description>The date that the house sale was recorded.</description>
    <label>Recording Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Holds the City Name</description>
    <inlineHelpText>Enter the City Name</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>County that belongs to the primary shipping address</description>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Data_Provider__c.field-meta.xml
<CustomField>
    <fullName>Data_Provider__c</fullName>
    <description>Identify name of the data provider.</description>
    <label>Data Provider</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/FileNumber__c.field-meta.xml
<CustomField>
    <fullName>FileNumber__c</fullName>
    <externalId>true</externalId>
    <label>FileNumber</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Home_Type__c.field-meta.xml
<CustomField>
    <fullName>Home_Type__c</fullName>
    <description>Describes the type of home that the person needs.</description>
    <inlineHelpText>Specify the type of home.</inlineHelpText>
    <label>Home Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>MF</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>SF</fullName>
            </value>
            <value>
                <fullName>User Created</fullName>
                <default>true</default>
                <label>User Created</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Holds the state information</description>
    <inlineHelpText>Enter the state</inlineHelpText>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Holds the street information</description>
    <inlineHelpText>Enter the street information</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Used to store 5 digit zipCode.</description>
    <label>Primary Shipping Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>To keep the county name. It is not unique. The same county name can exist for different states.</description>
    <label>County</label>
    <nameField>
        <displayFormat>CN-{000}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>To hold the state of the branch</description>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hung_Status_Setting__c/Hung_Status_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom Setting is used to store next delivery days count for &apos;Hung&apos; Status of the delivery.</description>
    <label>Hung Status Setting</label>
</CustomObject>

force-app/main/default/objects/Hung_Status_Setting__c/fields/Buffer_Days__c.field-meta.xml
<CustomField>
    <fullName>Buffer_Days__c</fullName>
    <description>Used to calculate additional days for creating delivery based on delivery date.</description>
    <label>Buffer Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hung_Status_Setting__c/fields/Days_Until_Next_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Days_Until_Next_Delivery__c</fullName>
    <description>This field is used to store the no Days until the next delivery to proceed.</description>
    <label>Days Until Next Delivery</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <formula>Address__r.County__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>County</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Data_Provider_ID__c.field-meta.xml
<CustomField>
    <fullName>Data_Provider_ID__c</fullName>
    <label>Data Provider ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Down_Payment__c.field-meta.xml
<CustomField>
    <fullName>Down_Payment__c</fullName>
    <label>Down Payment</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/FileNumber__c.field-meta.xml
<CustomField>
    <fullName>FileNumber__c</fullName>
    <externalId>true</externalId>
    <label>FileNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Home_Type__c.field-meta.xml
<CustomField>
    <fullName>Home_Type__c</fullName>
    <formula>TEXT( Address__r.Home_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Home Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/New__c.field-meta.xml
<CustomField>
    <fullName>New__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/User_Address_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Address_Type__c</fullName>
    <description>holds the type of address</description>
    <label>User Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Owner</fullName>
            </value>
            <value>
                <fullName>Secondary Owner</fullName>
            </value>
            <value>
                <fullName>Mailing Address</fullName>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Renter</fullName>
            </value>
            <value>
                <fullName>Un-validated Homeowner</fullName>
            </value>
            <value>
                <fullName>Family of Renter</fullName>
            </value>
            <value>
                <fullName>Family of Un-validated Homeowner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DiacoImportFeaturesTest.cls
/*

 Diaco
 @author 			Jeison Hernandez Sanchez  href=<jeison14.99@gmail.com>
 Project:			Jitterbit Replacement
 Description:		Support the account import process
     
 Changes (Version)
 _________________________________________

            No.		Date			Author					Description
            ____	__________      ____________________    _____________________________________
@version	1.0		07/10/2019		Jeison Hernandez (JH)	Initial implementation  of the class.
*/
@isTest
public class DiacoImportFeaturesTest {
    @TestSetup
    static void setup(){
        String s = '"Hometype","Rental","New","SalePrice","Down","Firstname","Lastname","phone","address","city","state","plus4","zip","DATE","PostDate","Update","County","FileNumber","BMPS"\n'+
        '"SF",,,510000.00,288329.00,"OMAR","GASTELUM COTA",,"6303 N 65TH DR","GLENDALE","AZ","4315","85301","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359061","14415011"\n'+
        '"SF",,"N",342990.00,10289.00,"PETER & CAROL","VALENTINO",,"2727 W APOLLO RD","PHOENIX","AZ","5486","85041","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359063","10592048"\n'+
        '"SF",,,364000.00,36400.00,"MARGARET","JOHNSON",,"3813 E PARK AVE","PHOENIX","AZ","8255","85044","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359070","30601625"\n'+
        '"CT",,,265000.00,105000.00,"KEITH & KIMBERLY","EWING",,"2101 S YELLOW WOOD UNIT 14","MESA","AZ","1486","85209","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359072","31212008"\n'+
        '"SF",,,650000.00,154000.00,"MICHAEL","ALLEN",,"26250 N 46TH ST","PHOENIX","AZ","8510","85050","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359082","21209227"\n'+
        '"SF",,"N",469699.00,23485.00,"ARIEL & TROY","AUELUA",,"4706 S MARS","MESA","AZ","3270","85212","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359089","31216546"\n'+
        '"SF",,,610000.00,610000.00,"PAUL","INDELICATO",,"8212 E SHERIDAN ST","SCOTTSDALE","AZ","2344","85257","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359156","13133059"\n'+
        '"SF",,,585000.00,58500.00,"BRIAN & LAUREN","WEST",,"2481 E BELLERIVE PL","CHANDLER","AZ","4142","85249","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359164","30356382"';
        String contractName = 'test document 3';
        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.PathOnClient = '.csv';
        //cv.OwnerId = at.OwnerId;
        cv.Title = contractName;
        cv.VersionData = blob.valueOf(s);
        insert cv;
        Hung_Status_Setting__c af = new Hung_Status_Setting__c(Name='Hung',Buffer_Days__c=26,Days_Until_Next_Delivery__c=7);
        insert af;
        diaco__diacoSlackApp__c app = new diaco__diacoSlackApp__c(
                Name = label.InternalAppSlackName,
                diaco__tokenApp__c = 'xoxa-408782345031-419122738544-419859988770-6b6f61c477d9067446e812035c7d14ac',
                diaco__byDefault__c = true
        );
        insert app;

        diaco__diacoSlackChat__c channelsapp = new diaco__diacoSlackChat__c(
                Name = 'testChannel',
                diaco__channelId__c ='CBZMYR96E',
                diaco__Slack_App__c = app.Id,
                diaco__members__c = 'UBZMYR69G,UBZMYR69G'
        );
        insert channelsapp;
        diaco__diacoSlackUser__c slackUser = new diaco__diacoSlackUser__c(
                name = 'test',
                diaco__slackUserId__c = 'UBZMYR69G',
                diaco__Slack_App__c = app.Id
        );
        insert slackUser;
        diaco__diacoSlackUser__c slackUser2 = new diaco__diacoSlackUser__c(
                name = 'test',
                diaco__slackUserId__c = 'UBZN1GYPL',
                diaco__Slack_App__c = app.Id
        );
        insert slackUser2;
    }

    @isTest
    static void importTest() {
        List<Account> Accts = new List<Account>();
        List<Address__c> Address = new List<Address__c>();
        List<User_Address__c> Uaddress = new List<User_Address__c>();
        String contractName = 'test document 3';
        string contentDocumentId;
        ContentVersion[] contentV= [select ContentDocumentId FROM ContentVersion WHERE Title = :contractName];
        if(contentV.size() > 0) {
            contentDocumentId = contentV[0].ContentDocumentId;
            System.debug(contentDocumentId);
        }
        List<DiacoImportFeatures.csvRecord> csvs = new List<DiacoImportFeatures.csvRecord>();
        Test.setMock(HttpCalloutMock.class, new DiacoImportFeaturesMockTest());
        Test.startTest();
        csvs = DiacoImportFeatures.GetCsvData(contentDocumentId);
        if(!csvs.isEmpty()){
        	System.assert(8==csvs.size());
        }
        for (DiacoImportFeatures.csvRecord item:csvs){
        	Account account = new Account(
                FirstName=item.Firstname, LastName=item.Lastname, 
                City__c=item.city, County__c= item.County, Down_Payment__c=item.Down,
                FileNumber__c=item.FileNumber, Home_Type__c=item.Hometype, New__c= (item.iNew=='N'?true:false),
                Recording_Date__c=item.iDATE,Sales_Price__c=item.SalePrice, State__c=item.state, 
                Street__c=item.address, Zip__c= item.zip
            );
            Accts.add(account);
            Address__c address1 = new Address__c(
                City__c=item.city,County__c=item.County, Data_Provider__c= 'ION',
                FileNumber__c=item.FileNumber, Home_Type__c= item.Hometype,
                State__c=item.state, Street__c=item.address, Zip_Code__c=item.zip
            );
            Address.add(address1);
            User_Address__c uaddress1 = new User_Address__c(
                Active__c=true,Data_Provider_ID__c='ION',Down_Payment__c=item.Down,FileNumber__c=item.FileNumber,
                New__c=(item.iNew=='N'?true:false),Recording_Date__c=item.iDATE,Sales_Price__c=item.SalePrice,
                Start_Date__c=item.iDATE,User_Address_Type__c='Primary Owner'
            );
            Uaddress.add(uaddress1);
        }

        DiacoImportFeatures.recordsInsert(Accts,Address,Uaddress,true);
        DiacoImportFeaturesSchedule p = new DiacoImportFeaturesSchedule();
        Datetime tem = Datetime.now().addSeconds(10);
        String cron = tem.second()+' '+tem.minute()+' '+tem.hour()+' '+tem.day()+' '+tem.month()+' ?';
        system.schedule('Import test', cron, p);
        //DiacoImportFeatures.createDeliveries();
        Test.stopTest();
        List<Account> re = [Select Id,Name from Account where New__c=true order by Name];
        System.assert(2==re.size());
    }
}