force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Home_Automation_Status__c.field-meta.xml
<CustomField>
    <fullName>Home_Automation_Status__c</fullName>
    <label>Home Automation Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_SendGrid__c.field-meta.xml
<CustomField>
    <fullName>Id_SendGrid__c</fullName>
    <label>Id SendGrid</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pest_Control_Status__c.field-meta.xml
<CustomField>
    <fullName>Pest_Control_Status__c</fullName>
    <label>Pest Control Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sms_sweepstake__c.field-meta.xml
<CustomField>
    <fullName>Sms_sweepstake__c</fullName>
    <label>Sms sweepstake</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Solar_Status__c.field-meta.xml
<CustomField>
    <fullName>Solar_Status__c</fullName>
    <label>Solar Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Utility__c.field-meta.xml
<CustomField>
    <fullName>Utility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Utility</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Validate_Email__c.field-meta.xml
<CustomField>
    <fullName>Validate_Email__c</fullName>
    <label>Validate Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
            <value>
                <fullName>accept_all_unverifiable</fullName>
            </value>
            <value>
                <fullName>disposable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Water_Status__c.field-meta.xml
<CustomField>
    <fullName>Water_Status__c</fullName>
    <label>Water Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Window_Status__c.field-meta.xml
<CustomField>
    <fullName>Window_Status__c</fullName>
    <label>Window Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sms_Url__c/Sms_Url__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations to activate sms function.</description>
    <label>SMS Url</label>
</CustomObject>

force-app/main/default/objects/Sms_Url__c/fields/Activate_sms_function__c.field-meta.xml
<CustomField>
    <fullName>Activate_sms_function__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate sms function</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sms_Url__c/fields/Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Sender_Id__c</fullName>
    <label>Sender Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sms_Url__c/fields/Sms_Text__c.field-meta.xml
<CustomField>
    <fullName>Sms_Text__c</fullName>
    <label>Sms Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/diacoSmsHS.cls
/******************
* 
* Class to responsible 
* to send SMS
* 
*******************/

public class diacoSmsHS {
    
    @InvocableMethod(label='Check send sms sweepstake' description='Send sms sweepstake when check sms sendsweepstake.')
    public static void Sweepstake(List<String> param) {
            List<Account> Acc = [Select Id, Validate_Email__c, PersonEmail, FirstName, Id_SendGrid__c,
                       LastName, Utility__r.Name, Street__c, State__c, Phone, Sms_sweepstake__c,
                       City__c, Zip__c, Solar_Status__c, Water_Status__c, Window_Status__c,
                       Pest_Control_Status__c, Home_Automation_Status__c
                       from Account where Id IN :param]; 
        for(Account account: Acc){
            String sms = diacoSmsHS.Sweepstake(account,0);
            diacoSendSweepstake.sendSmsSweepstakeTrigger(sms);
            System.debug('Process builder #3Condition PersonEmail check : '+account.PersonEmail);
            System.debug('Process builder #3Condition PersonEmail check: '+account.State__c);
        }
        
        return;

        }
    
    //Method to responsible to send sweepstake
    public static String Sweepstake(Account account, Integer option){
        List<Sms_Url__c> config = [select Activate_sms_function__c, Sms_Text__c, Sender_Id__c, Function__c 
                                   from Sms_Url__c where Function__c= 'Sweepstake' Limit 1];
        String body = ', "status_sms": "true" ';
        
        if(config.size()>0 && config[0].Function__c=='Sweepstake'
           && config[0].Activate_sms_function__c == true && account.Phone != null
           && config[0].Sender_Id__c != null && config[0].Sender_Id__c != ''
           && config[0].Sms_Text__c != '' && config[0].Sms_Text__c != null){
               //&& account.Sms_sweepstake__c == null
               String text = 'Hello '+account.FirstName+', '+config[0].Sms_Text__c+
            ' https://myhsaz.com/s/?id='+account.Id;
               System.debug('Sent sms True');
               body = ', "sender_id": "'+ config[0].Sender_Id__c+'",'+
                   '"Phone": "'+account.Phone+'", '+
                   '"sms_text": "'+ text+'" ';
               //insert sms;
               if(option == 0){
                   body = '{ "sender_id": "'+ config[0].Sender_Id__c+'",'+
                   			'"Phone": "'+account.Phone+'", '+
                       		'"Id_Account": "'+account.Id+'", '+
                       		'"sms_text": "'+ text+'" }';
               }
               
           }else{
               System.debug('No Sent sms True');
               body = ', "status_sms": "true" ';
           }
        return body;
        
    }
}