force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>18</precision>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>18</precision>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Geo_Accuracy__c.field-meta.xml
<CustomField>
    <fullName>Geo_Accuracy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Geo Accuracy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiacoGetGeoLocation.cls
/** 
* Diaco
* @author 			Jull Quintero D
* Project:			Geo Accurracy - Custom Buttom Delivery and Account Object
* Description:		Create a contract for Data Integration Rule (Geocodes for Account Billing Address) 
* Test class :      DiacoGetGeoLocationTest
*
* Changes (Version)
* ___________________________________
*			No.		Date			Author					Description
*			_____	__________		____________________	____________________________________
* @version	1.0		03/02/2021		Jull Quintero D		    Initial implementation of the component.
**/

public with sharing class DiacoGetGeoLocation {

    @AuraEnabled
    public static void contractInit(Id recordId) {

        String objectName = recordId.getSobjectType().getDescribe().getName();
        id currentId;
        if ( objectName == 'Account' ) {
            currentId = recordId;

        }else if ( objectName == 'Delivery_Object__c' ) {
            currentId  = [SELECT Id,Person_Account__c FROM Delivery_Object__c WHERE Id = :recordId ]?.Person_Account__c;
        }
        Id recordTypeId = diacoKnifeFunc.getRecordTypeIdbyName('Account','Person Account');
        List<Account> accounts = [SELECT Id,FirstName,LastName,City__c,State__c,Street__c,Zip__c 
                                FROM Account 
                                WHERE Id = :currentId AND recordTypeId = :recordTypeId];

        if ( !accounts.isEmpty() ) {
            Account account = accounts[0];
            Contact contact = new Contact();
            contact.Person_Account__c = account.Id;
            contact.FirstName = account.FirstName;
            contact.LastName = account.LastName;
            contact.MailingCity = account.City__c;
            contact.MailingState = account.State__c;
            contact.MailingStreet = account.Street__c;
            contact.MailingPostalCode = account.Zip__c;
            contact.Geo_Accuracy__c = true;
            insert contact;

            /*if ( objectName == 'Delivery_Object__c' ) {
                List<Account> accts = [SELECT Id,Latitude__c,Longitude__c FROM Account WHERE Id = :account.Id ];
                if ( !accts.isEmpty() ) { 
                    Account acc = accts[0];
                    Delivery_Object__c delivary = new Delivery_Object__c();
                    delivary.Id = recordId;
                    delivary.Maps_Latitude__c = acc.Latitude__c;
                    delivary.Maps_Longitude__c = acc.Longitude__c;
                    update delivary;
                }
            }*/
        }
    }
}