force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_Email__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Email__c</fullName>
    <label>Homeowner #2 Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_First_Name__c</fullName>
    <label>Homeowner #2 First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Last_Name__c</fullName>
    <label>Homeowner #2 Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Mobile__c</fullName>
    <label>Homeowner #2 Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Phone_Number__c</fullName>
    <label>Homeowner #2 Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_State__c</fullName>
    <label>Primary Billing State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/ApptSetter__c.field-meta.xml
<CustomField>
    <fullName>ApptSetter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appointment Setter</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Personnel__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Personnel__c.Appt_Setter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Home Services (Appointment Setter)</relationshipLabel>
    <relationshipName>Home_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>Exp_Date__c</fullName>
    <label>Exp Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.FirstName),&apos;&apos;,Account__r.FirstName)</formula>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Home_Services_Status__c.field-meta.xml
<CustomField>
    <fullName>Home_Services_Status__c</fullName>
    <label>Sales Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Dispatch</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Bid Submitted</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Rehash</fullName>
            </value>
            <value>
                <fullName>Sale Pending</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Won/Canceled</fullName>
            </value>
            <value>
                <fullName>Closed Won / Service Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Homeowner_2_Email__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Email__c</fullName>
    <formula>Account__r.Homeowner_2_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Homeowner #2 Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Homeowner_2_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Mobile__c</fullName>
    <formula>Account__r.Homeowner_2_Mobile__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Homeowner #2 Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.LastName),&apos;&apos;,Account__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Sales_Event_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_Event_Current_Status__c</fullName>
    <label>Sales Event Current Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT( Account__r.State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <formula>Account__r.Street__c</formula>
    <label>Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <formula>Account__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/fields/Kunnect_ID__c.field-meta.xml
<CustomField>
    <fullName>Kunnect_ID__c</fullName>
    <inlineHelpText>This is a Required field.  If this person does not have a Kunnect account please put &quot;none&quot;</inlineHelpText>
    <label>Kunnect ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/diacoTabsInformationCompletionTest.cls
@isTest
public class diacoTabsInformationCompletionTest {
    @TestSetup static void setup() {
        //Account for positive Test
        Account Acc = new Account();
        Acc.FirstName = 'Account ';
        Acc.LastName = 'Test-positive';
        Acc.RecordTypeId ='012410000012NOKAA2';
        Acc.Primary_Billing_State__c ='NY';
        Acc.Street__c='test';
        Acc.City__c='test';
        Acc.State__c='AZ';
        Acc.Zip__c='test';
        Acc.Phone='2121212121';
        Acc.PersonMobilePhone='221212121';
        Acc.PersonEmail='212121@gmail.com';
        Acc.Homeowner_2_Phone_Number__c='21212121';
        Acc.Homeowner_2_Last_Name__c='SecondName Test';
        Acc.Homeowner_2_First_Name__c='firstNameTest';
        Acc.Homeowner_2_Mobile__c='212122121';
        Acc.Homeowner_2_Email__c='212121@gmail.com';
        Acc.Zip__c='12212';
        insert Acc;

        //Account for negative tests
        Account Acc2 = new Account();
        Acc2.FirstName = 'Account ';
        Acc2.LastName = 'Test-negative';
        Acc2.RecordTypeId ='012410000012NOKAA2';
        Acc2.Street__c='test';
        Acc2.City__c='test';
        Acc2.State__c='AZ';
        Acc2.Zip__c='test';
        Acc2.PersonEmail='212121@gmail.com';
        Acc2.Zip__c='12212';
        insert Acc2;
        
        Personnel__c per = new Personnel__c();
        per.Name = 'test';
        per.First_Name__c = 'test';
        per.Last_Name__c = 'test';
        per.Kunnect_ID__c = 'none';
        insert per;
        //HomeServices for positive Test
        Home_Services__c hs = new  Home_Services__c();
        hs.Account__c = Acc.Id;
        hs.RecordTypeId = '012410000013G9OAAU';		 
        hs.ApptSetter__c = per.Id;
        hs.Exp_Date__c = '7/24';
        hs.Name='testChecked';
        hs.Home_Services_Status__c='Schedule';
        hs.Sales_Event_Current_Status__c='Schedule';
        hs.Event_Count__c=1;
        hs.Communication_By__c='POTS';
        hs.Utility_Company__c='SRP';
        hs.Username__c='SRP user';
        hs.Password__c='SRP password';
        hs.Sales_Rep__c=UserInfo.getUserId();
        hs.Requested_Install_Date__c=System.now();

        insert hs;

        Installation__c i = new Installation__c();
        i.Name = 'Test';
        i.Home_Service__c = hs.Id;
        i.RecordTypeId = '012410000013IFMAA2';
        insert i;

        Product__c pr = new Product__c();
        pr.Name = 'test';
        pr.Product_Type__c = 'Water';
        pr.active__c = true;
        insert pr;

        Line_Item__c li = new Line_Item__c();
        li.Name = 'Test';
        li.Product__c = pr.Id;
        li.Home_Service__c = hs.Id;
        insert li;

        PaymentMethod__c payment1= New PaymentMethod__c();
        payment1.PaymentMethodType__c='ACH';
        payment1.Amount__c=3000;
        payment1.HomeService__c=hs.Id;
        insert payment1;
//HomeService for negative Tests
        Home_Services__c hs2 = new  Home_Services__c();
        hs2.Account__c = Acc2.Id;
        hs2.RecordTypeId = '012410000013G9OAAU';		 
        hs2.ApptSetter__c = per.Id;
        hs2.Exp_Date__c = '7/24';
        hs2.Name='testChecked';
        hs2.Home_Services_Status__c='Schedule';
        hs2.Sales_Event_Current_Status__c='Schedule';
        hs2.Event_Count__c=1;
        hs2.Sales_Rep__c=UserInfo.getUserId();
        
        //hs.Sales_Rep__c = u.Id;
        insert hs2;
        
    }
    
    
    @isTest static void testAll(){

        Home_Services__c hsPositive= [select Id,Name,Account__r.LastName from Home_Services__c where Account__r.LastName = 'Test-positive' Limit 1];
        Home_Services__c hsNegative= [select Id,Name,Account__r.LastName from Home_Services__c where Account__r.LastName = 'Test-negative'  limit 1];

        test.startTest();
        //Check First customer tab
        Boolean testFirstCustomerPositive = diacoTabsInformationCompletion.checkSolarFirstCustomer(hsPositive.Id);
        system.assert(testFirstCustomerPositive == true, 'Customer check should be positive');
        //System.assertEquals(true, testFirstCustomerPositive);
        Boolean testFirstCustomerNegative = diacoTabsInformationCompletion.checkSolarFirstCustomer(hsNegative.Id);
        //System.assertEquals(false, testFirstCustomerNegative);
       
       // Check Second Customer Tab
       Boolean testSecondCustomerPositive = diacoTabsInformationCompletion.checkSecondCustomer(hsPositive.Id);
       //System.assertEquals(true, testSecondCustomerPositive);
       Boolean testSecondCustomerNegative = diacoTabsInformationCompletion.checkSecondCustomer(hsNegative.Id);
       //System.assertEquals(false, testSecondCustomerNegative);

        // Check Product and services Customer Tab
        Boolean testProductsAndServicesPositive = diacoTabsInformationCompletion.checkProductsOrServices(hsPositive.Id);
      //  System.assertEquals(true, testProductsAndServicesPositive);
        Boolean testProductsAndServicesNegative = diacoTabsInformationCompletion.checkProductsOrServices(hsNegative.Id);
    //    System.assertEquals(false, testProductsAndServicesNegative);


        // Check Payments Method  Tab
        Boolean testPaymentsPositive = diacoTabsInformationCompletion.checkPayments(hsPositive.Id);
  //      System.assertEquals(true, testPaymentsPositive);
        Boolean testPaymentsNegative = diacoTabsInformationCompletion.checkPayments(hsNegative.Id);
//        System.assertEquals(false, testPaymentsNegative);

        // Check Billing addres
        Boolean testBillingAddressPositive = diacoTabsInformationCompletion.checkBillingInformation(hsPositive.Id);
        //System.assertEquals(true, testBillingAddressPositive);
        Boolean testBillingAddressNegative = diacoTabsInformationCompletion.checkBillingInformation(hsNegative.Id);
        //System.assertEquals(false, testBillingAddressNegative);
        
        
        // Check Instalattion Date
        Boolean testInstalattionDatePositive = diacoTabsInformationCompletion.checkInstallationDate(hsPositive.Id);
        //System.assertEquals(true, testInstalattionDatePositive);
        Boolean testInstalattionDateNegative = diacoTabsInformationCompletion.checkInstallationDate(hsNegative.Id);
        //System.assertEquals(false, testInstalattionDateNegative);
        
        // Check checkServicePackage
        Boolean testServicePackagePositive = diacoTabsInformationCompletion.checkServicePackage(hsPositive.Id);
        //System.assertEquals(true, testServicePackagePositive);
        Boolean testServicePackageNegative = diacoTabsInformationCompletion.checkServicePackage(hsNegative.Id);
        //System.assertEquals(false, testServicePackageNegative);
        
        // Check utilityInformation
        Boolean testUtilityInfoPositive = diacoTabsInformationCompletion.checkUtilityInformation(hsPositive.Id);
        //System.assertEquals(true, testUtilityInfoPositive);
        Boolean testUtilityInfoNegative = diacoTabsInformationCompletion.checkUtilityInformation(hsNegative.Id);
       // System.assertEquals(false, testUtilityInfoNegative);
      
        test.stopTest();
    }
    
}