force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_Email__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Email__c</fullName>
    <label>Homeowner #2 Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_First_Name__c</fullName>
    <label>Homeowner #2 First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Last_Name__c</fullName>
    <label>Homeowner #2 Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Mobile__c</fullName>
    <label>Homeowner #2 Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Homeowner_2_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Phone_Number__c</fullName>
    <label>Homeowner #2 Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_State__c</fullName>
    <label>Primary Billing State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Communication_By__c.field-meta.xml
<CustomField>
    <fullName>Communication_By__c</fullName>
    <label>Communication By</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POTS</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>VoIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Homeowner_2_Email__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Email__c</fullName>
    <formula>Account__r.Homeowner_2_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Homeowner #2 Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Homeowner_2_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Homeowner_2_Mobile__c</fullName>
    <formula>Account__r.Homeowner_2_Mobile__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Homeowner #2 Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Monthly_Security_Services__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Security_Services__c</fullName>
    <label>Monthly Security Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Alarm Signal Verification</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Requested_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Install_Date__c</fullName>
    <label>Requested Install Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Home_Services_Sales_Rep</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT( Account__r.State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <formula>Account__r.Street__c</formula>
    <label>Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <formula>Account__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Bill_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Start_Date__c</fullName>
    <label>Bill Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Line Items (HS)</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Monthly_Investment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Investment__c</fullName>
    <label>Monthly Investment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items (Product)</relationshipLabel>
    <relationshipName>Line_Items_Product</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Service_Check__c.field-meta.xml
<CustomField>
    <fullName>Service_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Unit_Price__c *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/HomeService__c.field-meta.xml
<CustomField>
    <fullName>HomeService__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/Payment_Destination__c.field-meta.xml
<CustomField>
    <fullName>Payment_Destination__c</fullName>
    <label>Payment Destination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentMethodType__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodType__c</fullName>
    <label>Payment Method Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentMethodTypePick</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/diacoTabsInformationCompletion.cls
public class diacoTabsInformationCompletion {
    
    @AuraEnabled
    public static Boolean checkSolarFirstCustomer(String RecordId) {
        Home_Services__c home =  [select Account__c from Home_Services__c where id = :RecordId];
        Account account = [select Id, FirstName, LastName,  Phone, PersonMobilePhone,
                            Street__c ,Zip__c,City__c,State__c,PersonEmail
                            from Account  where Id = :home.Account__c ];
        
        if(account !=null){
            if(
            account.FirstName!=null && account.LastName!=null &&
            account.Phone!=null && account.PersonMobilePhone!=null &&    
            account.Street__c!=null && account.Zip__c!=null &&
            account.City__c!=null && account.State__c!=null &&
            account.PersonEmail!=null 
            ){
                return true;
            }
        }
        return false;
        
    }
    
    @AuraEnabled
    public static Boolean checkSecondCustomer(String RecordId) {
        Home_Services__c home =  [select Account__c from Home_Services__c where id = :RecordId];
        Account account = [select Id, Homeowner_2_First_Name__c,Homeowner_2_Last_Name__c, Homeowner_2_Phone_Number__c,
                           Homeowner_2_Mobile__c, Homeowner_2_Email__c
                           from Account 
                           where Id = :home.Account__c ];
        
        if(account !=null){
            if(account.Homeowner_2_First_Name__c!=null && account.Homeowner_2_Last_Name__c!=null && (account.Homeowner_2_Phone_Number__c!=null || account.Homeowner_2_Mobile__c!=null)
               && account.Homeowner_2_Email__c!=null
            ){
                return true;
            }
        }
        return false;
        
    }
    
    //At least one product/Service added
    @AuraEnabled
    public static Boolean checkProductsOrServices(String recordId) {
        
        
        List<Line_Item__c> cos=[select Id, Name, Unit_Price__c, Total_Price__c, Quantity__c,Product__c,Home_Service__c
                                from Line_Item__c
                                where Home_Service__c = :recordId  and Service_Check__c = false
                                order by CreatedDate desc];
        
        List<Line_Item__c> ois=[select Id, Name, Billing_Frequency__c, Bill_Start_Date__c, Monthly_Investment__c 
                                from Line_Item__c
                                where Home_Service__c = :recordId  and Service_Check__c = true
                                order by CreatedDate desc];
        
        if(cos.size()>0 || ois.size()>0 ){
            return true;
        }
        return false;
        
    }
    
    //At least one payment method added
    @AuraEnabled
    public static Boolean checkPayments(String recordId) {
        
        List<PaymentMethod__c> payments = [Select Id, PaymentMethodType__c, HomeService__c, Payment_Destination__c, Amount__c
                                           from PaymentMethod__c where HomeService__c=:recordId];
        
        if(payments.size()>0){
            return true;
        }
        return false;
        
    }
    
    @AuraEnabled
    public static Boolean checkBillingInformation(String recordId) {
        Home_Services__c home =  [select Id, Account__c, Account__r.Primary_Billing_State__c
                                  from Home_Services__c 
                                  where Id = :recordId Limit 1];
        
        if(home.Account__r.Primary_Billing_State__c != null ){
            return true;
        }
        return false;
    }
    @AuraEnabled
    public static Boolean checkInstallationDate(String recordId) {
        Home_Services__c home = [select Id, Sales_Rep__c, Requested_Install_Date__c
                                 from Home_Services__c 
                                 where id = :recordId];
        if(home.Requested_Install_Date__c != null){
            return true;
        }
        return false;
    }
    
    @AuraEnabled
    public static Boolean checkServicePackage(String recordId) {
        Home_Services__c home =  [select Id,Communication_By__c,Monthly_Security_Services__c
                                  from Home_Services__c where id = :recordId];
        
        if(home.Communication_By__c != null || home.Monthly_Security_Services__c != null ){
            return true;
        }
        return false;
    }
    
    @AuraEnabled
    public static Boolean checkUtilityInformation(String recordId) {
        Home_Services__c homeService = [
            SELECT Utility_Company__c, Username__c,Password__c
            FROM Home_Services__c WHERE Id = :recordId LIMIT 1
        ];
        if(homeService.Utility_Company__c != null && homeService.Username__c != null && homeService.Password__c != null){
            return true;
        }
        return false;
    }
    
}