force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Home_Automation_Status__c.field-meta.xml
<CustomField>
    <fullName>Home_Automation_Status__c</fullName>
    <label>Home Automation Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pest_Control_Status__c.field-meta.xml
<CustomField>
    <fullName>Pest_Control_Status__c</fullName>
    <label>Pest Control Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Send_Sweepstake__c.field-meta.xml
<CustomField>
    <fullName>Send_Sweepstake__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Sweepstake</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Solar_Status__c.field-meta.xml
<CustomField>
    <fullName>Solar_Status__c</fullName>
    <label>Solar Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Utility__c.field-meta.xml
<CustomField>
    <fullName>Utility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Utility</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Validate_Email__c.field-meta.xml
<CustomField>
    <fullName>Validate_Email__c</fullName>
    <label>Validate Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
            <value>
                <fullName>accept_all_unverifiable</fullName>
            </value>
            <value>
                <fullName>disposable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Water_Status__c.field-meta.xml
<CustomField>
    <fullName>Water_Status__c</fullName>
    <label>Water Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Window_Status__c.field-meta.xml
<CustomField>
    <fullName>Window_Status__c</fullName>
    <label>Window Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/neverBounce__c/neverBounce__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>neverBounce</label>
</CustomObject>

force-app/main/default/objects/neverBounce__c/fields/ApiKey__c.field-meta.xml
<CustomField>
    <fullName>ApiKey__c</fullName>
    <label>ApiKey</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/Emails_per_page__c.field-meta.xml
<CustomField>
    <fullName>Emails_per_page__c</fullName>
    <label>Emails per page</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/First_Job__c.field-meta.xml
<CustomField>
    <fullName>First_Job__c</fullName>
    <label>First Job</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/Job_id__c.field-meta.xml
<CustomField>
    <fullName>Job_id__c</fullName>
    <label>Job id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/next_page__c.field-meta.xml
<CustomField>
    <fullName>next_page__c</fullName>
    <defaultValue>0</defaultValue>
    <label>next page</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/number_of_pages__c.field-meta.xml
<CustomField>
    <fullName>number_of_pages__c</fullName>
    <label>number of pages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/neverBounce__c/fields/Second_Job__c.field-meta.xml
<CustomField>
    <fullName>Second_Job__c</fullName>
    <label>Second Job</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sms_Url__c/Sms_Url__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations to activate sms function.</description>
    <label>SMS Url</label>
</CustomObject>

force-app/main/default/objects/Sms_Url__c/fields/Activate_sms_function__c.field-meta.xml
<CustomField>
    <fullName>Activate_sms_function__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate sms function</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sms_Url__c/fields/Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Sender_Id__c</fullName>
    <label>Sender Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sms_Url__c/fields/Sms_Text__c.field-meta.xml
<CustomField>
    <fullName>Sms_Text__c</fullName>
    <label>Sms Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/diacoSendSweepstakeTest.cls
@isTest
public class diacoSendSweepstakeTest {
	@isTest static void testAll(){
        neverBounce__c nb = new neverBounce__c(
            Job_id__c = '277461',
            number_of_pages__c = 10,
            next_page__c = 1, 
            ApiKey__c = 'Apikey******', 
            First_Job__c = 3, 
            Second_Job__c =1, 
            Emails_per_page__c = 10 
        );
        upsert nb;
        Sms_Url__c sms = new Sms_Url__c(
            Activate_sms_function__c =true,
            Sender_Id__c = '1244',
            Function__c = 'Sweepstake',
            Sms_Text__c = 'Sms text'
        );
        upsert sms;
        diacoSendGrid send = new diacoSendGrid();
        Account accBussines = new Account(
        	Name = 'ASP TEST'
        );
        insert accBussines;
        Date day = Date.parse('05/17/2019');
		Account acc = new Account(
            FirstName = 'Test acc',
            LastName = 'last test',
            PersonEmail = 'test@test.com',
            Utility__c =accBussines.Id,
            Street__c= 'Test street',
            State__c= 'AZ',
            City__c = 'Arizona',
            Zip__c = '12345',
            Solar_Status__c= 'Test solar',
            Water_Status__c= 'Test water',
            Window_Status__c = 'Test Window',
            Pest_Control_Status__c= 'Test Pest',
            Home_Automation_Status__c= 'Test HA',
            Respond_Date__c = day
            
        );
        Account acc2 = new Account(
            FirstName = 'Test acc',
            LastName = 'last test',
            PersonEmail = 'test@test.com',
            Utility__c =accBussines.Id,
            Street__c= 'Test street',
            State__c= 'AZ',
            City__c = 'Arizona',
            Zip__c = '12345',
            Solar_Status__c= 'Test solar',
            Water_Status__c= 'Test water',
            Window_Status__c = 'Test Window',
            Pest_Control_Status__c= 'Test Pest',
            Home_Automation_Status__c= 'Test HA',
            Validate_Email__c = 'valid'
        );
        Account acc3 = new Account(
            FirstName = 'Test acc',
            LastName = 'last test',
            PersonEmail = 'test@test.com',
            Phone = '312'
        );
        insert acc3;
        List<Account> accounts = new List<Account>();
        accounts.add(acc);
        accounts.add(acc2);
        insert accounts;
        diacoSendSweepstake sweepstake = new diacoSendSweepstake();
        test.startTest();
        test.setMock(HttpCalloutMock.class, new diacoSendSweepstakeHttpCallOutMock());
        List<String> accountsId = new List<String>();
        accountsId.add(acc.Id);
        sweepstake.accountsSms(accounts);
        diacoSendSweepstake.SweepstakeSms(accountsId);
		sweepstake.sendSweepstake(sweepstake.accounts(accounts));
         String sms2 = diacoSmsHS.Sweepstake(acc3,0);
         diacoSendSweepstake.sendSmsSweepstakeTrigger(sms2);
        acc.Validate_Email__c = 'valid';
        update acc;
        acc2.Send_Sweepstake__c = true;
        update acc2;  
        acc3.Phone = '312455';
        update acc3;
        test.stopTest();
    }
}