force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/Commission_Status__c.field-meta.xml
<CustomField>
    <fullName>Commission_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Commission Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personnel</label>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/ApptSetter__c.field-meta.xml
<CustomField>
    <fullName>ApptSetter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appointment Setter</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Personnel__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Personnel__c.Appt_Setter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Home Services (Appointment Setter)</relationshipLabel>
    <relationshipName>Home_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <label>Card Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <formula>Total_Commission__c  /  Total_Gross_Sale__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>Exp_Date__c</fullName>
    <label>Exp Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.FirstName),&apos;&apos;,Account__r.FirstName)</formula>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Home_Services_Status__c.field-meta.xml
<CustomField>
    <fullName>Home_Services_Status__c</fullName>
    <label>Sales Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Dispatch</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Bid Submitted</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Rehash</fullName>
            </value>
            <value>
                <fullName>Sale Pending</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Won/Canceled</fullName>
            </value>
            <value>
                <fullName>Closed Won / Service Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.LastName),&apos;&apos;,Account__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Method_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Method_Of_Payment__c</fullName>
    <label>Method Of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Sales_Event_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_Event_Current_Status__c</fullName>
    <label>Sales Event Current Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Home_Services_Sales_Rep</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT( Account__r.State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <formula>Account__r.Street__c</formula>
    <label>Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <formula>Account__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/fields/Kunnect_ID__c.field-meta.xml
<CustomField>
    <fullName>Kunnect_ID__c</fullName>
    <inlineHelpText>This is a Required field.  If this person does not have a Kunnect account please put &quot;none&quot;</inlineHelpText>
    <label>Kunnect ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sales Rep</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/SF_User__c.field-meta.xml
<CustomField>
    <fullName>SF_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Personnels2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiacoCountPaidCommissionsXHSTest.cls
@istest
public class DiacoCountPaidCommissionsXHSTest {
 
        @istest static void testAll(){
            Account Acc = new Account();
            Acc.FirstName = 'Account ';
            Acc.LastName = 'Test';
            Acc.RecordTypeId ='012410000012NOKAA2';
            Acc.Street__c='test';
            Acc.City__c='test';
            Acc.State__c='AZ';
            Acc.Zip__c='test';
            insert Acc;
            
            Personnel__c per = new Personnel__c();
            per.Name = 'test';
            per.First_Name__c = 'test';
            per.Last_Name__c = 'test';
            per.Kunnect_ID__c = 'none';
            insert per;
            
            User u = new user();
            u.LastName = 'Test Event';
            u.Email = 'test@test.com';
            u.Alias = 'Tcode';
            u.Username = 'TestEvent@test.com';
            u.CommunityNickname = 'test12';
            u.LocaleSidKey = 'en_US';
            u.TimeZoneSidKey = 'GMT';
            u.ProfileID = '00e41000001hNuFAAU';
            u.LanguageLocaleKey = 'en_US';
            u.EmailEncodingKey = 'UTF-8';
            u.Personnel__c=per.Id;
            insert u;
            
            //per.SF_User__c=u.Id;
            //Update per;
            
            Home_Services__c hs = new  Home_Services__c();
            hs.Account__c = Acc.Id;
            hs.RecordTypeId = '012410000013G9OAAU';
            hs.Card_Number__c = '123456789';
            hs.CSV__c = '123';
            hs.Method_Of_Payment__c = 'Credit Card';		 
            hs.ApptSetter__c = per.Id;
            hs.Exp_Date__c = '7/24';
            hs.Name='test test test test';
            hs.Home_Services_Status__c='Schedule';
            hs.Sales_Event_Current_Status__c='Schedule';
            hs.Event_Count__c=1;
            //hs.Sales_Rep__c = u.Id;
            insert hs;
            
            Home_Services__c hs2 = new  Home_Services__c();
            hs2.Account__c = Acc.Id;
            hs2.RecordTypeId = '012410000013G9OAAU';
            hs2.Card_Number__c = '123456789';
            hs2.CSV__c = '123';
            hs2.Method_Of_Payment__c = 'Credit Card';		 
            hs2.ApptSetter__c = per.Id;
            hs2.Exp_Date__c = '7/24';
            hs2.Name='test test test test';
            hs2.Home_Services_Status__c='Schedule';
            hs2.Sales_Event_Current_Status__c='Schedule';
            hs2.Event_Count__c=1;
            //hs.Sales_Rep__c = u.Id;
            insert hs2;
            
            Commission__c c= new Commission__c();
            c.Name='Test';
            c.Home_Service__c=hs.Id;
            c.Personnel__c=per.Id;
            c.Commission_Status__c = 'Paid';
            
            insert c;
            
            test.startTest();
            
            c.Home_Service__c=hs2.Id;
            update c;
           
            test.stopTest();
        }
}