force-app/main/default/objects/Account/fields/County_Lookup__c.field-meta.xml
<CustomField>
    <fullName>County_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County Lookup</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>To keep the county name. It is not unique. The same county name can exist for different states.</description>
    <label>County</label>
    <nameField>
        <displayFormat>CN-{000}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/County_Name__c.field-meta.xml
<CustomField>
    <fullName>County_Name__c</fullName>
    <description>It holds counties name.</description>
    <label>County Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiacoAccountCounty.cls
/**
 * Diaco LLC
 * @author 			Giovanni Ulloque Olivares href = <Gulloque@diaco.us>
 * Project:			County on Account
 * Test:            DiacoAccountCountyTest
 * Description:		Relate a County record with the Account.
 *
 * Changes (Version)
 * ______________________________________________________________________________________________
 *			No.		Date			Author					Description
 *			____	__________		__________________  	_____________________________________
 * @version	1.0		24/06/2020		Giovanni Ulloque (GU)	Initial implementation of the class.
 **/

global class DiacoAccountCounty {
    @InvocableMethod(label='Account County' description='Relate Account with County')



    public static void  paramList(List<param> requests) {



     
        List<Account> Acc = new List<Account>();
        for(param nAcc : requests){

                Acc.add(new Account(
                County__c = nAcc.countyId,
                Id        = nAcc.accountId
                ));
            
        }

        System.debug(requests[0] + ' ' + requests[0].countyId);
      
        List <String> county = new List <String>();
   
        for(Account account: Acc){
            if(account.County__c != null){
                county.add(account.County__c);
            }
        }

        county.add('Unknown');
        List <County__c> c = [SELECT id, County_Name__c FROM County__c WHERE County_Name__c IN: county];

        for(County__c Unknowns:c){
            if(Unknowns.County_Name__c == 'Unknown'){
            currentAccount(Acc, c, Unknowns.Id);
            break; 
            }
        }



        }

    global class param {
        @InvocableVariable
        global String countyId;
        @InvocableVariable(required=true)
        global ID accountId;
    }

    public static String currentAccount( List <Account> accounts , List <County__c> counties, String Unknown ){
       List <Account> acc = new List<Account>();

       for (Account ac:accounts){
           Account a = new Account();
           a.id = ac.Id;
           

           for (County__c c:counties){
               
               if(ac.County__c == c.County_Name__c){
                 a.County_Lookup__c = c.Id;
                 break;

               }
   
               else {
                System.debug('####ERROR###');
                System.debug(Unknown);
                a.County_Lookup__c = Unknown;
            

               }


           }

          acc.add(a);
       }
       
        update acc;
        return 'Account updated';
    }


}