force-app/main/default/objects/Account/fields/Customer_1_DOB__c.field-meta.xml
<CustomField>
    <fullName>Customer_1_DOB__c</fullName>
    <label>Customer #1 DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_1_Drivers_License_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Customer_1_Drivers_License_Expiration__c</fullName>
    <label>Customer #1 Drivers License Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_1_Drivers_License_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_1_Drivers_License_Issue_Date__c</fullName>
    <label>Customer #1 Drivers License Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_2_DOB__c.field-meta.xml
<CustomField>
    <fullName>Customer_2_DOB__c</fullName>
    <label>Customer #2 DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_2_Drivers_License_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Customer_2_Drivers_License_Expiration__c</fullName>
    <label>Customer #2 Drivers License Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_2_Drivers_License_Issue__c.field-meta.xml
<CustomField>
    <fullName>Customer_2_Drivers_License_Issue__c</fullName>
    <label>Customer #2 Drivers License Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Interests__c.field-meta.xml
<CustomField>
    <fullName>Interests__c</fullName>
    <label>Interests</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Bath</fullName>
            </value>
            <value>
                <fullName>Blinds &amp; Shutters</fullName>
            </value>
            <value>
                <fullName>Closet Organization</fullName>
            </value>
            <value>
                <fullName>Garage Floor Coating</fullName>
            </value>
            <value>
                <fullName>Addition(s)</fullName>
            </value>
            <value>
                <fullName>Garage Organization</fullName>
            </value>
            <value>
                <fullName>Handyman</fullName>
            </value>
            <value>
                <fullName>Windows</fullName>
            </value>
            <value>
                <fullName>Security Doors</fullName>
            </value>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
            <value>
                <fullName>Landscape Design/Installation</fullName>
            </value>
            <value>
                <fullName>Pool</fullName>
            </value>
            <value>
                <fullName>Pool Design/Installation</fullName>
            </value>
            <value>
                <fullName>Concrete</fullName>
            </value>
            <value>
                <fullName>Sunroom Patio Enclosure</fullName>
            </value>
            <value>
                <fullName>Landscape Maintenance</fullName>
            </value>
            <value>
                <fullName>Pool Maintenance</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Garage Doors</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Water Filtration</fullName>
            </value>
            <value>
                <fullName>HVAC</fullName>
            </value>
            <value>
                <fullName>Smart Home Automation</fullName>
            </value>
            <value>
                <fullName>TV &amp; Internet</fullName>
            </value>
            <value>
                <fullName>Locksmith</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/webForm__c/webForm__c.object-meta.xml
<CustomObject>
    <label>Web Form</label>
    <nameField>
        <label>webForm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/webForm__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Web Forms</relationshipLabel>
    <relationshipName>Web_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/Interests__c.field-meta.xml
<CustomField>
    <fullName>Interests__c</fullName>
    <label>Interests</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Smart Home Automation</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Blinds &amp; Shutters</fullName>
            </value>
            <value>
                <fullName>House Cleaning</fullName>
            </value>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
            <value>
                <fullName>Bath</fullName>
            </value>
            <value>
                <fullName>Garage Floor Coating</fullName>
            </value>
            <value>
                <fullName>Locksmith</fullName>
            </value>
            <value>
                <fullName>Floor Cleaning</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
            <value>
                <fullName>Handyman</fullName>
            </value>
            <value>
                <fullName>Water Filtration</fullName>
            </value>
            <value>
                <fullName>Windows</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Pool</fullName>
            </value>
            <value>
                <fullName>HVAC</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>TV &amp; Internet</fullName>
            </value>
            <value>
                <fullName>Garage Organization</fullName>
            </value>
            <value>
                <fullName>Garage Door</fullName>
            </value>
            <value>
                <fullName>Weed Removal</fullName>
            </value>
            <value>
                <fullName>Maid Service</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DiacoManageWebFormControllerTest.cls
@isTest
public class DiacoManageWebFormControllerTest {
    @isTest static void testAll(){
        Account Acc = new Account();
        Acc.FirstName = 'Account ';
        Acc.LastName = 'Test';
        Acc.RecordTypeId ='012410000012NOKAA2';
        Acc.Customer_1_DOB__c =  Date.newInstance(2018, 7, 3);
        Acc.Customer_2_DOB__c =  Date.newInstance(2018, 7, 3);
        Acc.Customer_1_Drivers_License_Issue_Date__c =  Date.newInstance(2018, 7, 3);
        Acc.Customer_2_Drivers_License_Issue__c =  Date.newInstance(2018, 7, 3);
        Acc.Customer_1_Drivers_License_Expiration__c =  Date.newInstance(2018, 7, 3);
        Acc.Customer_2_Drivers_License_Expiration__c =  Date.newInstance(2018, 7, 3);
        insert Acc;     
        
        webForm__c w = new webForm__c();
        w.Name = 'Test';
        w.Account__c = Acc.Id;
        insert w;
        
        test.startTest();
        
        DiacoManageWebFormController.getCurrentInfo(Acc.Id);
        DiacoManageWebFormController.saveAccount(Acc);
        DiacoManageWebFormController.createWebForm(w);
        DiacoManageWebFormController.getWebForms(Acc.Id);
        DiacoManageWebFormController.getPickListValuesIntoList('Account','Interests__c');
        DiacoManageWebFormController.deleteWebForm(w.Id);
        DiacoManageWebFormController.getDataRecordType();
        
        test.stopTest();
        
    }
}