force-app/main/default/objects/Account/fields/Customer_1_DOB__c.field-meta.xml
<CustomField>
    <fullName>Customer_1_DOB__c</fullName>
    <label>Customer #1 DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_1_Drivers_License_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Customer_1_Drivers_License_Expiration__c</fullName>
    <label>Customer #1 Drivers License Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_1_Drivers_License_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_1_Drivers_License_Issue_Date__c</fullName>
    <label>Customer #1 Drivers License Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_2_DOB__c.field-meta.xml
<CustomField>
    <fullName>Customer_2_DOB__c</fullName>
    <label>Customer #2 DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_2_Drivers_License_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Customer_2_Drivers_License_Expiration__c</fullName>
    <label>Customer #2 Drivers License Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_2_Drivers_License_Issue__c.field-meta.xml
<CustomField>
    <fullName>Customer_2_Drivers_License_Issue__c</fullName>
    <label>Customer #2 Drivers License Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attention__c/Attention__c.object-meta.xml
<CustomObject>
    <label>Attention</label>
    <nameField>
        <label>Attention Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attentions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attention__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Personnel</label>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Attentions</relationshipLabel>
    <relationshipName>Attentions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attention__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Attentions</relationshipLabel>
    <relationshipName>Attentions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/fields/Kunnect_ID__c.field-meta.xml
<CustomField>
    <fullName>Kunnect_ID__c</fullName>
    <inlineHelpText>This is a Required field.  If this person does not have a Kunnect account please put &quot;none&quot;</inlineHelpText>
    <label>Kunnect ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>&apos;Medium&apos;</defaultValue>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Very Low</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Very High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ticket Type</label>
    <referenceTo>Ticket_Type__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket_Type__c/Ticket_Type__c.object-meta.xml
<CustomObject>
    <label>Ticket Type</label>
    <nameField>
        <label>Ticket Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DiacoTicketComponentControllerTest.cls
@isTest
public class DiacoTicketComponentControllerTest {
    @isTest static void testAll(){
        Account Acc = new Account();
        Acc.FirstName = 'Account ';
        Acc.LastName = 'Test';
        Acc.RecordTypeId ='012410000012NOKAA2';
        Acc.Customer_1_DOB__c =  Date.newInstance(2018, 7, 3);
        Acc.Customer_2_DOB__c =  Date.newInstance(2018, 7, 3);
        Acc.Customer_1_Drivers_License_Issue_Date__c =  Date.newInstance(2018, 7, 3);
        Acc.Customer_2_Drivers_License_Issue__c =  Date.newInstance(2018, 7, 3);
        Acc.Customer_1_Drivers_License_Expiration__c =  Date.newInstance(2018, 7, 3);
        Acc.Customer_2_Drivers_License_Expiration__c =  Date.newInstance(2018, 7, 3);
        insert Acc;
        
        Personnel__c per = new Personnel__c();
        per.Name = 'test';
        per.First_Name__c = 'test';
        per.Last_Name__c = 'test';
        per.Kunnect_ID__c = 'none';
        insert per;
        
        Ticket_Type__c tt = new Ticket_Type__c();
        tt.Name = 'Test Ticket Type';
        insert tt;
        
        Ticket__c tk = new Ticket__c();
        tk.Name = 'Ticket Test';
        tk.Ticket_Type__c = tt.Id;
        tk.Priority__c = 'Low';
        insert tk;
        
        Attention__c at = new Attention__c();
        at.Name = 'Test';
        at.Ticket__c = tk.Id;
        at.Personnel__c = per.Id;
        insert at;
        
        List<String> data = new List<String>();
        data.add('');
        data.add('');
        data.add('');
        data.add('');
        data.add('');
        
        test.startTest();
        
        DiacoTicketComponentController.getAllTickets();
        DiacoTicketComponentController.getAllTicketTypes();
        DiacoTicketComponentController.deleteAttention(at.Id);
        DiacoTicketComponentController.getAttentions(tk.Id);
        DiacoTicketComponentController.getAllFilterTickets(data);
        data[4] = 'Low';
        DiacoTicketComponentController.getAllFilterTickets(data);
        
        test.stopTest();
        
    }
}