force-app/main/default/objects/Account/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Captures the date at which the package was dropped and delivered to the customer.</description>
    <inlineHelpText>Captures the date at which the package was dropped and delivered to the customer.</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Geocode_Accuracy__c.field-meta.xml
<CustomField>
    <fullName>Geocode_Accuracy__c</fullName>
    <label>Geocode Accuracy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Arrival_Latitude__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Latitude__c</fullName>
    <label>Arrival Latitude</label>
    <precision>18</precision>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Arrival_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Longitude__c</fullName>
    <label>Arrival Longitude</label>
    <precision>18</precision>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Assigned_Route__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Route__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assigned Route</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Geocode_Accuracy__c.field-meta.xml
<CustomField>
    <fullName>Geocode_Accuracy__c</fullName>
    <label>Geocode Accuracy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Hung_DateTieme__c.field-meta.xml
<CustomField>
    <fullName>Hung_DateTieme__c</fullName>
    <label>Hung Status Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Hung_Status__c.field-meta.xml
<CustomField>
    <fullName>Hung_Status__c</fullName>
    <label>Hung Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrived</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hung</fullName>
            </value>
            <value>
                <fullName>COMPLETED GATED</fullName>
            </value>
            <value>
                <fullName>Gated</fullName>
            </value>
            <value>
                <fullName>Cant Find</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Invld</fullName>
            </value>
            <value>
                <fullName>Remove: Management</fullName>
            </value>
            <value>
                <fullName>Too Far</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Wrong House Number</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Remove: Gated</fullName>
            </value>
            <value>
                <fullName>Remove: Aging</fullName>
            </value>
            <value>
                <fullName>Sent To Cheetah</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Gio - In Process</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Access Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hung_Status__c/Hung_Status__c.object-meta.xml
<CustomObject>
    <description>This object will different Hung Status details for the Products</description>
    <label>Hung Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Hung Status No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hung Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Confirmation_Number__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Number__c</fullName>
    <description>It holds the confirmation number of the account. And it should be greater than lead id value.</description>
    <externalId>true</externalId>
    <label>Confirmation Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MapsWaypointTriggerHelper.cls
/*
 * Diaco
 * @author             Jull Quintero Daza
 * Project:            Maps Waypoint Trigger
 * TestClass:          MapsWaypointTriggerTest
 * Description:        helper
 *
 * Changes (Version)
 * _________________________________________
 *            No.        Date            Author                    Description
 *            ____    __________        __________________      _____________________________________
 * @version    1.0    08/02/2021         Jull Quintero D         Initial implementation of the class.
 * @version    1.0    04/03/2021         Jeison Hernandez S      Delivery Driver
 **/

public without sharing class MapsWaypointTriggerHelper {

    public static Boolean flagControlExecution = false;
    /**
     * This method is responsible Update Delivery Object Assigned_Route__c
     * This method is run Before Insert
     * 
     * This method is used in:
     * MapsWaypointTrigger
     * 
     * @param List wayPoints
     **/
    public static void setFields(List<maps__Waypoint__c> wayPoints) {
        Set<Id> deliveryIds = new Set<Id>();
        Integer wayPointsSize = wayPoints.size();
        for (Integer i = 0; i < wayPointsSize; i++) {
            maps__Waypoint__c current = wayPoints[i];

            // Assign Delivery Object
            if( current.Delivery_Object__c == null ) {
                if( current.maps__LinkId__c != null ) {
                    Id deliveryId =  Id.valueOf(current.maps__LinkId__c);
                    String objectName = deliveryId.getSobjectType().getDescribe().getName();
                    if( objectName == 'Delivery_Object__c' ) {
                        current.Delivery_Object__c = deliveryId;
                        deliveryIds.add(deliveryId);
                    }
                }
            }
        }
        if ( !deliveryIds.isEmpty() ) setName(wayPoints,deliveryIds);
    }
    
    /**
     * This method is responsible assign format name
     * This method is run Before insert
     * 
     * This method is used in:
     * MapsWaypointTrigger
     * 
     * @param List wayPoints
     **/
    private static void setName(List<maps__Waypoint__c> wayPoints,Set<Id> deliveryIds) {

        Map<Id,Delivery_Object__c> deliveryMap = new  Map<Id,Delivery_Object__c>(
            [SELECT Id,Hung_Status__c,person_Account__r.FirstName,person_Account__r.LastName,
                    person_Account__r.Geocode_Accuracy__c,User_Address__r.Confirmation_Number__c 
            FROM Delivery_Object__c 
            WHERE Id IN :deliveryIds]);
        
        integer wayPointsSize = wayPoints.size();
        for (Integer i = 0; i < wayPointsSize; i++) {
            maps__Waypoint__c current = wayPoints[i];
            if( current.Delivery_Object__c != null ) {
                Delivery_Object__c delivery =  deliveryMap.get(current.Delivery_Object__c);
                Account account = delivery.person_Account__r;
                String geocurracy = account.Geocode_Accuracy__c != 'Address' ? 'Z-' : '';
                String hungStatus = delivery.Hung_Status__c != null && delivery.Hung_Status__c != 'NULL' ? delivery.Hung_Status__c.left(4) + '-' : '';
                String confirmation = delivery.User_Address__r.Confirmation_Number__c;
                String confirNumber = confirmation != null ? confirmation + '-' : '';
                String firstName = account.FirstName != null ? account.FirstName.left(1) + '-' : '';
                String LastName = account.LastName != null ? account.LastName : '';
                String name = geocurracy + hungStatus + confirNumber + firstName + LastName;
                if ( name.length() > 80 ) name = geocurracy + hungStatus + confirNumber + firstName + LastName.left(1);
                current.Name = name;
            }
        }
    }

    /**
     * This method is responsible Update Delivery Object Assigned_Route__c
     * This method is run After Insert
     * 
     * This method is used in:
     * MapsWaypointTrigger
     * 
     * @param List wayPoints
     **/
    public static void deliveryAssignRoute(List<maps__Waypoint__c> wayPoints) {
        Map<Id,Delivery_Object__c> deliveries = new Map<Id,Delivery_Object__c>();
        Integer wayPointsSize = wayPoints.size();
        for (Integer i = 0; i < wayPointsSize; i++) {
            maps__Waypoint__c current = wayPoints[i];
            if( current.Delivery_Object__c != null ) {
                if ( !deliveries.containsKey(current.Delivery_Object__c) ) {
                    deliveries.put(
                        current.Delivery_Object__c,
                        new Delivery_Object__c(
                            Id = current.Delivery_Object__c,
                            Assigned_Route__c = true
                        )
                    );
                }//else{//current.addError('Deliveries cant be duplicated');}
            }
        }
        if ( !deliveries.isEmpty() ) {
            TriggerHandler.bypass('DeliveryObjectTrigger');
                update deliveries.values();
            TriggerHandler.clearBypass('DeliveryObjectTrigger');
        }
    }

        /**
     * This method is responsible Update Delivery Object Assigned_Route__c
     * This method is run Before delete
     * 
     * This method is used in:
     * MapsWaypointTrigger
     * 
     * @param List wayPoints
     **/
    public static void deliveryUnAssignRoute(Map<Id,maps__Waypoint__c> oldWaypointsMap) {
        List<maps__Waypoint__c> wayPoints = [SELECT Id,Delivery_Object__c,maps__Route__r.maps__Date__c,maps__Route__r.Stop__c FROM maps__Waypoint__c WHERE Id IN :oldWaypointsMap.keySet()];
        
        Map<Id,Delivery_Object__c> deliveries = new Map<Id,Delivery_Object__c>();
        Integer wayPointsSize = wayPoints.size();
        for (Integer i = 0; i < wayPointsSize; i++) {
            maps__Waypoint__c current = wayPoints[i];
            Boolean isAllowed = current.maps__Route__r.maps__Date__c >= Date.today() && current.maps__Route__r.Stop__c == null; 
            
            if( current.Delivery_Object__c != null ) {
                if( isAllowed ) {
                    if ( !deliveries.containsKey(current.Delivery_Object__c) ) {
                        deliveries.put(
                            current.Delivery_Object__c,
                            new Delivery_Object__c(
                                Id = current.Delivery_Object__c,
                                Assigned_Route__c = false
                            )
                        );
                    } 
                }else {
                    maps__Waypoint__c wayPoint = oldWaypointsMap.get(current.Id);
                    wayPoint.addError('Route Date Is Overdue, Cannot Make Route Changes');
                }
            }
        }

        if ( !deliveries.isEmpty() ) {
            TriggerHandler.bypass('DeliveryObjectTrigger');
                update deliveries.values();
            TriggerHandler.clearBypass('DeliveryObjectTrigger');
        }
    }

    /**@author Jeison Hernandez S | 05-03-2021
     * 
     * This method is responsible Update Delivery Object Delivery_Date__c, Hung_Status__c, Arrival_GeoLocation__c, Driver__c
     * This method is run After Update
     * 
     * This method is used in:
     * MapsWaypointTrigger
     * 
     * @param List wayPoints
     **/

    public static void driverCmpDeliveryUpdates(Map<Id,maps__Waypoint__c> oldWaypointsMap, Map<Id,maps__Waypoint__c> newWaypointsMap){
        if (flagControlExecution == true) {
            return;
        }
        List<Delivery_Object__c> deliveries = new List<Delivery_Object__c>();
        List<maps__Waypoint__c> waypoints = new List<maps__Waypoint__c>();
        List<Driver__c> driver = new List<Driver__c>();
        driver = [select Id from Driver__c where User__c =: UserInfo.getUserId()];
        for(String currentId: oldWaypointsMap.keySet()){
            maps__Waypoint__c oldWaypoint = oldWaypointsMap.get(currentId);
            maps__Waypoint__c newWaypoint = newWaypointsMap.get(currentId);
            if(newWaypoint.Maps_Delivery_Driver__c ==true && newWaypoint.Delivery_Object__c!=null){
                waypoints.add(new maps__Waypoint__c(Id=newWaypoint.Id,Maps_Delivery_Driver__c=false));
                Delivery_Object__c Delivery = new Delivery_Object__c(Id=newWaypoint.Delivery_Object__c);
                Boolean flat=false;
                if(oldWaypoint.Checkout__c != newWaypoint.Checkout__c){
                    //Delivery.Hung_DateTieme__c = newWaypoint.Checkout__c; flat=true;
                }
                if(oldWaypoint.Hung_Status__c != newWaypoint.Hung_Status__c){
                    Delivery.Hung_Status__c = newWaypoint.Hung_Status__c; flat=true;
                    Delivery.Delivery_Date__c = newWaypoint.Hung_Date_Time__c;
                    Delivery.Hung_DateTieme__c = newWaypoint.Hung_Date_Time__c;
                    if(!driver.isEmpty()){
                        Delivery.Driver__c=driver[0].Id;
                    }
                }
                if( oldWaypoint.Delivery_Driver_Latitude__c != newWaypoint.Delivery_Driver_Latitude__c ||
                    oldWaypoint.Delivery_Driver_Longitude__c != newWaypoint.Delivery_Driver_Longitude__c){
                    Delivery.Arrival_Latitude__c = newWaypoint.Delivery_Driver_Latitude__c;
                    Delivery.Arrival_Longitude__c = newWaypoint.Delivery_Driver_Longitude__c;
                    flat=true;
                }
                if(flat){
                    deliveries.add(Delivery);
                }
           }
        }
        if(!deliveries.isEmpty()){
            flagControlExecution = true;
            update deliveries;
            flagControlExecution = false;
        }
        if(!waypoints.isEmpty()){
            TriggerHandler.bypass('MapsWaypointTrigger');
            update waypoints;
            TriggerHandler.clearBypass('MapsWaypointTrigger');
        }

    }
}