force-app/main/default/objects/Account/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Captures the date at which the package was dropped and delivered to the customer.</description>
    <inlineHelpText>Captures the date at which the package was dropped and delivered to the customer.</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Scan_Code__c.field-meta.xml
<CustomField>
    <fullName>Scan_Code__c</fullName>
    <description>The scan code of the card</description>
    <inlineHelpText>Identifies Batch / Order / Card / Box</inlineHelpText>
    <label>Scan Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Hung_Status__c.field-meta.xml
<CustomField>
    <fullName>Hung_Status__c</fullName>
    <label>Hung Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrived</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hung</fullName>
            </value>
            <value>
                <fullName>COMPLETED GATED</fullName>
            </value>
            <value>
                <fullName>Gated</fullName>
            </value>
            <value>
                <fullName>Cant Find</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Invld</fullName>
            </value>
            <value>
                <fullName>Remove: Management</fullName>
            </value>
            <value>
                <fullName>Too Far</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Wrong House Number</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Remove: Gated</fullName>
            </value>
            <value>
                <fullName>Remove: Aging</fullName>
            </value>
            <value>
                <fullName>Sent To Cheetah</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Gio - In Process</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Access Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/IsRecent__c.field-meta.xml
<CustomField>
    <fullName>IsRecent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This filed used to identify the recently created Delivery Object record.</description>
    <label>IsRecent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Scan_Code__c.field-meta.xml
<CustomField>
    <fullName>Scan_Code__c</fullName>
    <label>Scan Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Card_Orders__c/Gift_Card_Orders__c.object-meta.xml
<CustomObject>
    <label>Gift Card Order</label>
    <nameField>
        <label>Gift Card Orders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Card Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Card_Orders__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Gift Card Orders</relationshipLabel>
    <relationshipName>Gift_Card_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift_Card_Orders__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associating Gift Card under User Address Object</description>
    <label>User Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Parent_Gift_Card_Order__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Gift Card Orders</relationshipLabel>
    <relationshipName>Gift_Card_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hung_Status__c/Hung_Status__c.object-meta.xml
<CustomObject>
    <description>This object will different Hung Status details for the Products</description>
    <label>Hung Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Hung Status No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hung Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field will store the person Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Scan_code__c.field-meta.xml
<CustomField>
    <fullName>Scan_code__c</fullName>
    <description>The scan code of the card</description>
    <inlineHelpText>Identifies Batch / Order / Card / Box</inlineHelpText>
    <label>Scan code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeliveryObjectTriggerHandlerTest.cls
/*    Class Name : DeliveryObjectTriggerHandlerTest
* Created By : Sailappa Vignesh P G
* Created Date : 2/18/2016
* Description : This class will cover the code coverage for 'DeliveryObjectTrigger' and 'DeliveryObjectTriggerHandler'. 
* Modified By: Ganesh
* Modified on:
* Description: Updated the test class as per best practices.
*/
@isTest(seeAllData = false) 
private class DeliveryObjectTriggerHandlerTest {
    /*Description : This method will load the test data for test cases.*/
    @testSetup static void loadTestData() {
        TestClassUtil.createZipcodeForBranch();
        TestClassUtil.createAccount(5);
        TestClassUtil.createCheetahGiftCardOrder();
        TestClassUtil.createDriver(); 
        TestClassUtil.createAddress(5);
        TestClassUtil.createUserAddress(3);  
    }
    /*Description : This method will check whether the 'isRecent' is checked for all the newly created delivery Object records.*/    
    static testmethod void testIsRecentChecked(){
        Account testAccount = [SELECT ID FROM Account lIMIT 1];
        Gift_Card_Orders__c giftCardOrder = [SELECT ID FROM Gift_Card_Orders__c LIMIT 1];
        Driver__c driver =  [SELECT ID FROM Driver__c LIMIT 1];
        User_Address__c userAddress = [SELECT ID FROM User_Address__c LIMIT 1];
        Delivery_Object__c deliveryObject = new Delivery_Object__c();        
        deliveryObject.Person_Account__c = testAccount.id;
        deliveryObject.Driver__c = driver.id;
        deliveryObject.name = '1';
        deliveryObject.Parent_Gift_Card_Order__c = giftCardOrder.id;
        deliveryObject.User_Address__c = userAddress.id;
        test.startTest();
            insert deliveryObject; 
           
            deliveryObject.Scan_Code__c = '1234 2134 2132 2343'; 
            update deliveryObject;
        
            deliveryObject = [SELECT ID,IsRecent__c FROM Delivery_Object__c LIMIT 1];
           // System.assertEquals(true, deliveryObject.IsRecent__c);
        test.stopTest();        
    } 
    /*Description : This method will check whether the 'isRecent' is checked for all the 
        newly created delivery Object records and 'isRecent' is unchecked for the 
        old delivery Object records connected with the same Person Account  .*/    
    public static testmethod void testIsRecentUnChecked(){
        integer isRecentCheckedCount = 0;
        integer isRecentUnCheckedCount = 0;    
        Account testAccount = [SELECT ID FROM Account lIMIT 1];
        Gift_Card_Orders__c giftCardOrder = [SELECT ID FROM Gift_Card_Orders__c LIMIT 1];
        Driver__c driver =  [SELECT ID FROM Driver__c LIMIT 1];
        User_Address__c userAddress = [SELECT ID FROM User_Address__c LIMIT 1];
        Delivery_Object__c deliveryObject = new Delivery_Object__c();
        deliveryObject.Person_Account__c = testAccount.id;
        deliveryObject.Driver__c = driver.id;
        deliveryObject.name = '1';
        deliveryObject.Parent_Gift_Card_Order__c = giftCardOrder.id;
        deliveryObject.User_Address__c = userAddress.id;
        insert deliveryObject; 
        Delivery_Object__c deliveryObjectTwo = new Delivery_Object__c();
        deliveryObjectTwo.Person_Account__c = testAccount.id;
        deliveryObjectTwo.Driver__c = driver.id;
        deliveryObjectTwo.name = '1';
        deliveryObjectTwo.Parent_Gift_Card_Order__c = giftCardOrder.id;
        deliveryObjectTwo.User_Address__c = userAddress.id;
        insert deliveryObjectTwo;  
        test.startTest();
        for(Delivery_Object__c currDeliveryObject : [SELECT ID,IsRecent__c FROM Delivery_Object__c ]){
            if(currDeliveryObject.IsRecent__c){
                isRecentCheckedCount++;                
            }else{
                isRecentUnCheckedCount++;    
            }            
        }
       // System.assertEquals(1, isRecentCheckedCount);
        //System.assertEquals(1, isRecentUnCheckedCount);
        test.stopTest();        
    }
    static testmethod void testDeliveryDriverLeadStatus(){
        Account testAccount = [SELECT ID FROM Account lIMIT 1];
        Gift_Card_Orders__c giftCardOrder = [SELECT ID FROM Gift_Card_Orders__c LIMIT 1];
        Driver__c driver =  [SELECT ID FROM Driver__c LIMIT 1];
        User_Address__c userAddress = [SELECT ID,phone__c,Respond_Date__c FROM User_Address__c LIMIT 1];
        userAddress.Respond_Date__c = System.today();
        update userAddress;
        Delivery_Object__c deliveryObject = new Delivery_Object__c();        
        deliveryObject.Person_Account__c = testAccount.id;
        deliveryObject.Driver__c = driver.id;
        deliveryObject.name = '1';
        deliveryObject.Parent_Gift_Card_Order__c = giftCardOrder.id;
        deliveryObject.User_Address__c = userAddress.id;
        
        test.startTest();
            insert deliveryObject;   
            deliveryObject.Delivery_Date__c = System.today();
            deliveryObject.Hung_Status__c = 'Hung';
            update deliveryObject;
            deliveryObject = [SELECT ID,IsRecent__c FROM Delivery_Object__c LIMIT 1];
            //System.assertEquals(true, deliveryObject.IsRecent__c);
        test.stopTest();        
    }    
    
    public static testmethod void testDeliveryDriverLeadStatusDelivery2(){
        Account testAccount = [SELECT ID FROM Account lIMIT 1];
        Gift_Card_Orders__c giftCardOrder = [SELECT ID FROM Gift_Card_Orders__c LIMIT 1];
        Driver__c driver =  [SELECT ID FROM Driver__c LIMIT 1];
        User_Address__c userAddress = [SELECT ID,phone__c,Respond_Date__c FROM User_Address__c LIMIT 1];
        userAddress.Respond_Date__c = System.today()+2;
        update userAddress;
        Delivery_Object__c deliveryObject = new Delivery_Object__c();        
        deliveryObject.Person_Account__c = testAccount.id;
        deliveryObject.Driver__c = driver.id;
        deliveryObject.name = '2';
        deliveryObject.Parent_Gift_Card_Order__c = giftCardOrder.id;
        deliveryObject.User_Address__c = userAddress.id;
        
        test.startTest();
            insert deliveryObject;   
            deliveryObject.Delivery_Date__c = System.today();
            deliveryObject.Hung_Status__c = 'Hung';
            update deliveryObject;
            deliveryObject = [SELECT ID,IsRecent__c FROM Delivery_Object__c LIMIT 1];
           // System.assertEquals(true, deliveryObject.IsRecent__c);
        test.stopTest();        
    }    
}