force-app/main/default/objects/Account/fields/DNC_HVAC__c.field-meta.xml
<CustomField>
    <fullName>DNC_HVAC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DNC HVAC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Update_Order__c/Update_Order__c.object-meta.xml
<CustomObject>
    <label>Update Order</label>
    <nameField>
        <label>Update Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Update Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Update_Order__c/fields/Guest_User__c.field-meta.xml
<CustomField>
    <fullName>Guest_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Guest User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Update_Order__c/fields/List_of_Fields__c.field-meta.xml
<CustomField>
    <fullName>List_of_Fields__c</fullName>
    <label>List of Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Update_Order__c/fields/List_of_Values__c.field-meta.xml
<CustomField>
    <fullName>List_of_Values__c</fullName>
    <label>List of Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Update_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
                <default>true</default>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DiacoUpdateOrderTest.cls
/**
 * Diaco LLC
 * @author 			Giovanni Ulloque Olivares href = <Gulloque@diaco.us>
 * Project:			Update Order.
 * Test:            DiacoUpdateOrderTest
 * Description:		Update records with the Update Order parameters..
 *
 * Changes (Version)
 * ______________________________________________________________________________________________
 *			No.		Date			Author					Description
 *			____	__________		__________________  	_____________________________________
 * @version	1.0		30/07/2020		Giovanni Ulloque (GU)	Initial implementation of the class.
 **/
@istest
public class DiacoUpdateOrderTest {
    @istest static void test() {

        Account acc = new Account();
        acc.FirstName = 'Test acc';
        acc.LastName  = 'last test';
        insert acc;

        List<Update_Order__c> uOrder = new List<Update_Order__c>();
        uOrder.add(new Update_Order__c(
            name              = 'test',
            Status__c         = 'In Process',
            List_of_Fields__c = 'Phone/,/DNC_HVAC__c',
            List_of_Values__c = '3161111111/,/false',
            Parent_Id__c      = acc.id,
            Guest_User__c     = true

        ));

        uOrder.add(new Update_Order__c(
            name              = 'test',
            Status__c         = 'In Process',
            List_of_Fields__c = 'Phone',
            List_of_Values__c = '3161111111',
            Parent_Id__c      = acc.id,
            Guest_User__c     = false

        ));

        test.startTest();

        DateTime myDateTime = System.now().addMinutes(2);
        String title = 'Update Order';
        String sch = '0 '+myDateTime.minute()+' '+myDateTime.hour()+' '+myDateTime.day()+' '+myDateTime.month()+' ? '+myDateTime.year();
        String jobID = system.schedule(title, sch, new DiacoUpdateOrderScheduleJob());

        insert uOrder;

        test.stopTest();

    }
}