force-app/main/default/objects/Account/fields/Docusign_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Account_Number__c</fullName>
    <label>Docusign Account Number</label>
    <length>22</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Address_Line_1__c</fullName>
    <label>Docusign Address Line 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_Banking_Institution__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Banking_Institution__c</fullName>
    <label>Docusign Banking Institution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Card_Type__c</fullName>
    <label>Docusign Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>American Express</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_City__c.field-meta.xml
<CustomField>
    <fullName>Docusign_City__c</fullName>
    <label>Docusign City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_Credit_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Credit_Card_Number__c</fullName>
    <label>Docusign Credit Card Number</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_CVV_Security_Code_AMEX__c.field-meta.xml
<CustomField>
    <fullName>Docusign_CVV_Security_Code_AMEX__c</fullName>
    <label>Docusign CVV Security Code AMEX</label>
    <length>5</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_CVV_Security_Code_Diners_Club__c.field-meta.xml
<CustomField>
    <fullName>Docusign_CVV_Security_Code_Diners_Club__c</fullName>
    <label>Docusign CVV Security Code Diners Club</label>
    <length>5</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_CVV_Security_Code_Discover__c.field-meta.xml
<CustomField>
    <fullName>Docusign_CVV_Security_Code_Discover__c</fullName>
    <label>Docusign CVV Security Code Discover</label>
    <length>5</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_CVV_Security_Code_JCB__c.field-meta.xml
<CustomField>
    <fullName>Docusign_CVV_Security_Code_JCB__c</fullName>
    <label>Docusign CVV Security Code JCB</label>
    <length>5</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_CVV_Security_Code_Master__c.field-meta.xml
<CustomField>
    <fullName>Docusign_CVV_Security_Code_Master__c</fullName>
    <label>Docusign CVV Security Code Master</label>
    <length>5</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_CVV_Security_Code_MC__c.field-meta.xml
<CustomField>
    <fullName>Docusign_CVV_Security_Code_MC__c</fullName>
    <label>Docusign CVV Security Code MC</label>
    <length>5</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_CVV_Security_Code_UK__c.field-meta.xml
<CustomField>
    <fullName>Docusign_CVV_Security_Code_UK__c</fullName>
    <label>Docusign CVV Security Code UK</label>
    <length>5</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_CVV_Security_Code_Visa__c.field-meta.xml
<CustomField>
    <fullName>Docusign_CVV_Security_Code_Visa__c</fullName>
    <label>Docusign CVV Security Code Visa</label>
    <length>5</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_Expiration_Month__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Expiration_Month__c</fullName>
    <label>Docusign Expiration Month</label>
    <length>2</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_Expiration_Year__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Expiration_Year__c</fullName>
    <label>Docusign Expiration Year</label>
    <length>4</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Last_Name__c</fullName>
    <label>Docusign Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_Name_On_Account__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Name_On_Account__c</fullName>
    <label>Docusign Name On Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_Name_On_Credit_Card__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Name_On_Credit_Card__c</fullName>
    <label>Docusign Name On Credit Card</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Routing_Number__c</fullName>
    <label>Docusign Routing Number</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_State__c.field-meta.xml
<CustomField>
    <fullName>Docusign_State__c</fullName>
    <label>Docusign State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Guam</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Docusign_Zip__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Zip__c</fullName>
    <label>Docusign Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Hung_Status__c.field-meta.xml
<CustomField>
    <fullName>Hung_Status__c</fullName>
    <label>Hung Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrived</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hung</fullName>
            </value>
            <value>
                <fullName>COMPLETED GATED</fullName>
            </value>
            <value>
                <fullName>Gated</fullName>
            </value>
            <value>
                <fullName>Cant Find</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Invld</fullName>
            </value>
            <value>
                <fullName>Remove: Management</fullName>
            </value>
            <value>
                <fullName>Too Far</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Wrong House Number</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Remove: Gated</fullName>
            </value>
            <value>
                <fullName>Remove: Aging</fullName>
            </value>
            <value>
                <fullName>Sent To Cheetah</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Gio - In Process</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Access Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift_Card_Orders__c/Gift_Card_Orders__c.object-meta.xml
<CustomObject>
    <label>Gift Card Order</label>
    <nameField>
        <label>Gift Card Orders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Card Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Card_Orders__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Gift Card Orders</relationshipLabel>
    <relationshipName>Gift_Card_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hung_Status__c/Hung_Status__c.object-meta.xml
<CustomObject>
    <description>This object will different Hung Status details for the Products</description>
    <label>Hung Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Hung Status No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hung Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/nuHome_chargent_Handler.cls
/**************************************************************************************************************
Created By: MST
Description : Class to create chargent records based on account updates
***************************************************************************************************************/

public class nuHome_chargent_Handler {
    public static Integer testThis(){
        Return 2;
    }
/**************************************************************************************************************
    public static void CreateChargent(List<Account> AccList){
        list<ChargentOrders__ChargentOrder__c> chargent = new list<ChargentOrders__ChargentOrder__c>();
        list<Account> updateac = new list<Account>();        
        for(Account currAcc:AccList){
            //This block will execute only if credit card number or account number present in account, and will collect chargent record details from account.
            if(currAcc.Docusign_Credit_Card_Number__c!=Null||currAcc.Docusign_Account_Number__c!=Null){
                system.debug('Chargent Record creation');
                ChargentOrders__ChargentOrder__c currChargentOrder = new ChargentOrders__ChargentOrder__c();
                currChargentOrder.ChargentOrders__Account__c = currAcc.Id;
                currChargentOrder.ChargentOrders__Bank_Account_Number__c = currAcc.Docusign_Account_Number__c;
                currChargentOrder.ChargentOrders__Card_Type__c=currAcc.Docusign_Card_Type__c;
                currChargentOrder.ChargentOrders__Card_Number__c=currAcc.Docusign_Credit_Card_Number__c;                
                if(currAcc.Docusign_Card_Type__c=='American Express')
                    currChargentOrder.ChargentOrders__Card_Security_Code__c=currAcc.Docusign_CVV_Security_Code_AMEX__c;
                if(currAcc.Docusign_Card_Type__c=='Diners Club')
                    currChargentOrder.ChargentOrders__Card_Security_Code__c=currAcc.Docusign_CVV_Security_Code_Diners_Club__c;
                if(currAcc.Docusign_Card_Type__c=='Discover')
                    currChargentOrder.ChargentOrders__Card_Security_Code__c=currAcc.Docusign_CVV_Security_Code_Discover__c;
                if(currAcc.Docusign_Card_Type__c=='JCB Card')
                    currChargentOrder.ChargentOrders__Card_Security_Code__c=currAcc.Docusign_CVV_Security_Code_JCB__c;
                if(currAcc.Docusign_Card_Type__c=='Mastercard')
                    currChargentOrder.ChargentOrders__Card_Security_Code__c=currAcc.Docusign_CVV_Security_Code_Master__c;
                if(currAcc.Docusign_Card_Type__c=='MC Eurocard')
                    currChargentOrder.ChargentOrders__Card_Security_Code__c=currAcc.Docusign_CVV_Security_Code_MC__c;
                if(currAcc.Docusign_Card_Type__c=='UK Maestro')
                    currChargentOrder.ChargentOrders__Card_Security_Code__c=currAcc.Docusign_CVV_Security_Code_UK__c;
                if(currAcc.Docusign_Card_Type__c=='Visa')
                    currChargentOrder.ChargentOrders__Card_Security_Code__c=currAcc.Docusign_CVV_Security_Code_Visa__c;                
                currChargentOrder.ChargentOrders__Card_Expiration_Month__c=currAcc.Docusign_Expiration_Month__c;
                currChargentOrder.ChargentOrders__Card_Expiration_Year__c=currAcc.Docusign_Expiration_Year__c;
                currChargentOrder.ChargentOrders__Bank_Account_Name__c=currAcc.Docusign_Name_On_Account__c;
                currChargentOrder.ChargentOrders__Billing_First_Name__c =currAcc.Docusign_Name_On_Credit_Card__c;
                currChargentOrder.ChargentOrders__Billing_Last_Name__c =currAcc.Docusign_Last_Name__c;
                currChargentOrder.ChargentOrders__Bank_Routing_Number__c=currAcc.Docusign_Routing_Number__c;
                currChargentOrder.ChargentOrders__Billing_Address__c = currAcc.Docusign_Address_Line_1__c;
                currChargentOrder.ChargentOrders__Billing_State__c = currAcc.Docusign_State__c;
                currChargentOrder.ChargentOrders__Billing_City__c = currAcc.Docusign_City__c;
                currChargentOrder.ChargentOrders__Billing_Zip_Postal__c = currAcc.Docusign_Zip__c;
                currChargentOrder.ChargentOrders__Bank_Name__c = currAcc.Docusign_Banking_Institution__c;
                currChargentOrder.ChargentOrders_Origin__c = 'DocuSign';
                //Adding chargent records to chargent object list.
                chargent.add(currChargentOrder);
            }            
        }
        system.debug('Chargent Record creation list size'+chargent.size());
        if(chargent.size()>0)
            insert chargent;
        
        
    }
    //MST added for Delivery 2 object update 02/11
    public static void DeliveryUpdate(List<Account> AccountList,Map<Id,Account> oldMap){
        Set<Id> accIdset = new Set<Id>();
        List<Delivery_Object__c> DeliveryList = new List<Delivery_Object__c>();
        for(Account accountIns : AccountList){
            if( accountIns.Respond_date__c != null && oldMap.get(accountIns.Id).Respond_date__c == Null )
                accIdset.add(accountIns.id);
        }

        for(Delivery_Object__c Delivery : [SELECT Id,Name,Parent_Gift_Card_Order__c,Hung_Status__c FROM Delivery_Object__c WHERE
                                           Person_Account__c IN :accIdset  AND Parent_Gift_Card_Order__r.Name ='Cheetah Gift Card Order' AND Hung_Status__c ='Sent To Cheetah' AND Name = '2']){
                                               Delivery_Object__c deliveryIns = New Delivery_Object__c();
                                               deliveryIns.Id = Delivery.Id;
                                               deliveryIns.Hung_Status__c = 'Remove: Responded';
                                               DeliveryList.add(deliveryIns);
                                           }
        if(DeliveryList.size()>0)
            update DeliveryList;

    }
    
    

***************************************************************************************************************/
}