force-app/main/default/objects/Account/fields/Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Gift_Card_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_City__c</fullName>
    <label>Primary Billing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Country__c</fullName>
    <label>Primary Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
                <default>true</default>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_State__c</fullName>
    <label>Primary Billing State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Street__c</fullName>
    <label>Primary Billing Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Zip_Code__c</fullName>
    <label>Primary Billing Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Delivered__c.field-meta.xml
<CustomField>
    <fullName>Delivered__c</fullName>
    <defaultValue>0</defaultValue>
    <externalId>true</externalId>
    <label># Delivered</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Delivered__c.field-meta.xml
<CustomField>
    <fullName>Delivered__c</fullName>
    <label># Delivered</label>
    <summaryFilterItems>
        <field>Delivery_Object__c.Name</field>
        <operation>equals</operation>
        <value>1</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Delivery_Object__c.Hung_Status__c</field>
        <operation>equals</operation>
        <value>Hung</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Delivery_Object__c.Delivery_Date__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>Delivery_Object__c.Driver__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Gift_Card__c/Gift_Card__c.object-meta.xml
<CustomObject>
    <label>Gift Card</label>
    <nameField>
        <label>Gift Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Card__c/fields/Art_File__c.field-meta.xml
<CustomField>
    <fullName>Art_File__c</fullName>
    <formula>Opportunity__r.Art_File__c</formula>
    <label>Art File</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift_Card__c/fields/Back_PDF__c.field-meta.xml
<CustomField>
    <fullName>Back_PDF__c</fullName>
    <formula>Opportunity__r.Back_pdf__c</formula>
    <label>Back PDF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gift_Card__c/fields/Front_PDF__c.field-meta.xml
<CustomField>
    <fullName>Front_PDF__c</fullName>
    <formula>Opportunity__r.Front_pdf__c</formula>
    <label>Front PDF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gift_Card__c/fields/Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Gift_Card_Order__c</fullName>
    <label>Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Gift Cards</relationshipLabel>
    <relationshipName>Gift_Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Gift_Card__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Gift Cards</relationshipLabel>
    <relationshipName>Gift_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift_Card_Orders__c/Gift_Card_Orders__c.object-meta.xml
<CustomObject>
    <label>Gift Card Order</label>
    <nameField>
        <label>Gift Card Orders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Card Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Card_Orders__c/fields/Delivered__c.field-meta.xml
<CustomField>
    <fullName>Delivered__c</fullName>
    <label>Delivered</label>
    <summaryForeignKey>Delivery_Object__c.Parent_Gift_Card_Order__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Gift_Card_Orders__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Gift Card Orders</relationshipLabel>
    <relationshipName>Gift_Card_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Art_File__c.field-meta.xml
<CustomField>
    <fullName>Art_File__c</fullName>
    <label>Art File</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Back_pdf__c.field-meta.xml
<CustomField>
    <fullName>Back_pdf__c</fullName>
    <label>Back PDF</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forward_to_number__c.field-meta.xml
<CustomField>
    <fullName>Forward_to_number__c</fullName>
    <label>Forward To Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Front_pdf__c.field-meta.xml
<CustomField>
    <fullName>Front_pdf__c</fullName>
    <label>Front PDF</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Operational_Stages__c.field-meta.xml
<CustomField>
    <fullName>Operational_Stages__c</fullName>
    <label>Operations Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage_Types__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Docusign Received</fullName>
            </value>
            <value>
                <fullName>Billing Setup</fullName>
            </value>
            <value>
                <fullName>DID Setup</fullName>
            </value>
            <value>
                <fullName>Gift Card Awaiting Artwork</fullName>
            </value>
            <value>
                <fullName>Gift Card Graphic Design</fullName>
            </value>
            <value>
                <fullName>Gift Card Proof Sent to Client</fullName>
            </value>
            <value>
                <fullName>Gift Card Pending</fullName>
            </value>
            <value>
                <fullName>Gift Card Client Approved</fullName>
            </value>
            <value>
                <fullName>Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Gift Card Proof Approved</fullName>
            </value>
            <value>
                <fullName>Gift Card Ordered</fullName>
            </value>
            <value>
                <fullName>Gift Card Received &amp; in Fulfillment</fullName>
            </value>
            <value>
                <fullName>Gift Card Active Customer</fullName>
            </value>
            <value>
                <fullName>Deactivated Customer</fullName>
            </value>
            <value>
                <fullName>Call Center DID</fullName>
            </value>
            <value>
                <fullName>Cancel Pending</fullName>
            </value>
            <value>
                <fullName>Gift Card Docusign Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Operation_Stageset_GiftCard_Ordered_Test.cls
/*
--------------------------
 * Modified By: Ganesh
 * Modified on:
 * Description: Updated the test class as per best practices. 
-----------------------------
*/
@isTest(seealldata=false)
private class Operation_Stageset_GiftCard_Ordered_Test
{
    @testsetup static void createtestdata() { 
        
        //Account creation
        Account acc = new Account();
        acc.name = 'testAccount';  
        acc.Primary_Billing_City__c='Sunnyvale';    
        acc.Primary_Billing_Country__c='US';
        acc.Primary_Billing_State__c='CA';
        acc.Primary_Billing_Street__c='260 N Mathilda Ave';
        acc.Primary_Billing_Zip_Code__c='94086'; 
        acc.Phone = '1234567890';    
        insert acc;
        system.assertNotEquals(null, acc.id);
        
        //Opportunity creation
        Opportunity opp = new Opportunity();
        opp.accountId = acc.Id;
        opp.name='TestOpp';
        opp.closeDate = date.today();
        opp.Operational_Stages__c = 'Gift Card Proof Approved';
        opp.stageName = 'Closed Won';
        opp.Art_File__c='sunnyvale'; 
        opp.Back_pdf__c=2;
        opp.Front_pdf__c=2;
        opp.Forward_to_number__c = '8220708920';
        insert opp;
        system.assertNotEquals(null, opp.id);
        
        //Gift_Card_Orders__c creation
        Gift_Card_Orders__c pgo=new Gift_Card_Orders__c(Name='Test Gift card Order',Quantity_Ordered__c=2,Parent_Gift_Card_Order__c=null);
        insert pgo;
        
        Gift_Card_Orders__c go=new Gift_Card_Orders__c(Name='Test Gift card Order',Quantity_Ordered__c=2,Parent_Gift_Card_Order__c=pgo.id);
        insert go;
        system.assertEquals(2, [select count() from Gift_Card_Orders__c]);
        
        //Driver__c creation
        Driver__c dr=new Driver__c(Name='Invalid Driver');
        insert dr;
        system.assertNotEquals(null, dr.id);
        
        //Delivery_Object__c creation
        Delivery_Object__c d=new Delivery_Object__c(Name='Test Delivery',Parent_Gift_Card_Order__c=go.id,Delivered__c=1,Person_Account__c=acc.id);
        insert d;
		system.assertNotEquals(null, d.id);        
    }
    static testmethod void GCTrigTest(){
        test.startTest();
        Opportunity opp = [select id,Operational_Stages__c from Opportunity where stageName='Closed Won' limit 1];
        Gift_Card_Orders__c go = [select id from Gift_Card_Orders__c where Parent_Gift_Card_Order__c!=null limit 1];
        Gift_Card__c g=new Gift_Card__c(Name='Test Gift Card',Gift_Card_Order__c=go.id,Opportunity__c=opp.id);
        insert g;
        test.stopTest();
    } 
}