force-app/main/default/objects/Account/fields/I_Accept_Terms__c.field-meta.xml
<CustomField>
    <fullName>I_Accept_Terms__c</fullName>
    <defaultValue>false</defaultValue>
    <label>I Accept Terms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Interests__c.field-meta.xml
<CustomField>
    <fullName>Interests__c</fullName>
    <label>Interests</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Bath</fullName>
            </value>
            <value>
                <fullName>Blinds &amp; Shutters</fullName>
            </value>
            <value>
                <fullName>Closet Organization</fullName>
            </value>
            <value>
                <fullName>Garage Floor Coating</fullName>
            </value>
            <value>
                <fullName>Addition(s)</fullName>
            </value>
            <value>
                <fullName>Garage Organization</fullName>
            </value>
            <value>
                <fullName>Handyman</fullName>
            </value>
            <value>
                <fullName>Windows</fullName>
            </value>
            <value>
                <fullName>Security Doors</fullName>
            </value>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
            <value>
                <fullName>Landscape Design/Installation</fullName>
            </value>
            <value>
                <fullName>Pool</fullName>
            </value>
            <value>
                <fullName>Pool Design/Installation</fullName>
            </value>
            <value>
                <fullName>Concrete</fullName>
            </value>
            <value>
                <fullName>Sunroom Patio Enclosure</fullName>
            </value>
            <value>
                <fullName>Landscape Maintenance</fullName>
            </value>
            <value>
                <fullName>Pool Maintenance</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Garage Doors</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Water Filtration</fullName>
            </value>
            <value>
                <fullName>HVAC</fullName>
            </value>
            <value>
                <fullName>Smart Home Automation</fullName>
            </value>
            <value>
                <fullName>TV &amp; Internet</fullName>
            </value>
            <value>
                <fullName>Locksmith</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Services_Pick__c.field-meta.xml
<CustomField>
    <fullName>Services_Pick__c</fullName>
    <label>Services Pick</label>
    <length>700</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sweepstake_Date__c.field-meta.xml
<CustomField>
    <fullName>Sweepstake_Date__c</fullName>
    <label>Sweepstake Date</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sweepstake_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Sweepstake_In_Date__c</fullName>
    <label>Sweepstake In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/webForm__c/webForm__c.object-meta.xml
<CustomObject>
    <label>Web Form</label>
    <nameField>
        <label>webForm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/webForm__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Web Forms</relationshipLabel>
    <relationshipName>Web_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/I_Accept_Terms__c.field-meta.xml
<CustomField>
    <fullName>I_Accept_Terms__c</fullName>
    <defaultValue>false</defaultValue>
    <label>I Accept Terms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/Interests__c.field-meta.xml
<CustomField>
    <fullName>Interests__c</fullName>
    <label>Interests</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Smart Home Automation</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Blinds &amp; Shutters</fullName>
            </value>
            <value>
                <fullName>House Cleaning</fullName>
            </value>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
            <value>
                <fullName>Bath</fullName>
            </value>
            <value>
                <fullName>Garage Floor Coating</fullName>
            </value>
            <value>
                <fullName>Locksmith</fullName>
            </value>
            <value>
                <fullName>Floor Cleaning</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
            <value>
                <fullName>Handyman</fullName>
            </value>
            <value>
                <fullName>Water Filtration</fullName>
            </value>
            <value>
                <fullName>Windows</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Pool</fullName>
            </value>
            <value>
                <fullName>HVAC</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>TV &amp; Internet</fullName>
            </value>
            <value>
                <fullName>Garage Organization</fullName>
            </value>
            <value>
                <fullName>Garage Door</fullName>
            </value>
            <value>
                <fullName>Weed Removal</fullName>
            </value>
            <value>
                <fullName>Maid Service</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/webForm__c/fields/Services_Pick__c.field-meta.xml
<CustomField>
    <fullName>Services_Pick__c</fullName>
    <label>Services Pick</label>
    <length>700</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/Sweepstake_Date__c.field-meta.xml
<CustomField>
    <fullName>Sweepstake_Date__c</fullName>
    <label>Sweepstake Date</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/Sweepstake_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Sweepstake_In_Date__c</fullName>
    <label>Sweepstake In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/webForm__c/recordTypes/Sweepstake.recordType-meta.xml
<RecordType>
    <fullName>Sweepstake</fullName>
    <active>true</active>
    <label>Sweepstake</label>
</RecordType>

force-app/main/default/classes/diacoMigrateSweepstakeAccountBatch.cls
/**
* Diaco
* @author 			Esnayder Morales href=<esnaydermorales25@gmail.com>
* Project:			Script to migrate a sweepstake info to account object. 
* Description:		class responsible to migrate a sweepstake info to account object.
*
* Changes (Version)
* -------------------------------------
*			No.		Date			Author						Description
*			-----	----------		--------------------		---------------
* @version	1.0		18/07/2019		Esnayder Morales (EM)		Initial implementation of the class.
**/
global class diacoMigrateSweepstakeAccountBatch implements Database.Batchable<sObject>, Database.Stateful {
    global Integer recordsProcessed = 0;
    private Integer lim;
    
    public diacoMigrateSweepstakeAccountBatch(Integer lim ) {
        this.lim = lim;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        return  Database.getQueryLocator([Select Id, Name, I_Accept_Terms__c, Sweepstake_Date__c, 
                                          Sweepstake_In_Date__c, Services_Pick__c, Account__c 
                                          From webForm__c 
                                          where Account__c != null and Type__c='Sweepstake' limit :lim]);
    }
    
    global void execute(Database.BatchableContext bc, List<webForm__c> records){
        System.debug(records);
        // process each batch of records
        List<Account> accounts = new List<Account>();
        for(webForm__c wf : records){
                Account account = new Account();
                account.Id = wf.Account__c;
                account.Sweepstake_Date__c = wf.Sweepstake_Date__c;
                account.Sweepstake_In_Date__c = wf.Sweepstake_In_Date__c;
                account.Interests__c = wf.Services_Pick__c;
            	account.I_Accept_Terms__c = wf.I_Accept_Terms__c;
                if(!wf.I_Accept_Terms__c 
                   && (wf.Sweepstake_Date__c.indexOf('S-1') != -1
                      || wf.Sweepstake_Date__c.indexOf('S-2') != -1
                      || wf.Sweepstake_Date__c.indexOf('S-3') != -1)){
                       account.I_Accept_Terms__c = true;
                   }
                accounts.add(account);          
        }
        update accounts;
    }   
    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
                            JobItemsProcessed,
                            TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.toAddresses = new String[] { 'esnaydermorales25@gmail.com', 'giovanniyunior@gmail.com', 
            'emorales@diaco.us'};
            message.optOutPolicy = 'FILTER';
        message.subject = 'Records processed: '+ recordsProcessed;
        message.plainTextBody ='Id: '+job.Id+ '\n Status: '+job.Status+
            '\n Number of Error: '+ job.NumberOfErrors+
            '\n Job items Processed: '+ job.JobItemsProcessed+
            '\n Total Job items: '+ job.TotalJobItems;
        Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        
        if (results[0].success) {
            System.debug('The email was sent successfully.');
        } else {
            System.debug('The email failed to send: ' + results[0].errors[0].message);
        }
        
    }
}