force-app/main/default/objects/Account/fields/Installation_Company__c.field-meta.xml
<CustomField>
    <fullName>Installation_Company__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation Company</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/APS_Account__c.field-meta.xml
<CustomField>
    <fullName>APS_Account__c</fullName>
    <label>APS Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Electric_Behind_Fence__c.field-meta.xml
<CustomField>
    <fullName>Electric_Behind_Fence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Electric Behind Fence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Existing_Generating_Solar_System__c.field-meta.xml
<CustomField>
    <fullName>Existing_Generating_Solar_System__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Existing Generating Solar System</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/House_Square_Footage__c.field-meta.xml
<CustomField>
    <fullName>House_Square_Footage__c</fullName>
    <label>House Square Footage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Installation_Company__c.field-meta.xml
<CustomField>
    <fullName>Installation_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Company</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The lookup Account must be  checked with &apos;Installation Company&apos; field.</errorMessage>
        <filterItems>
            <field>Account.Installation_Company__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Installation Company)</relationshipLabel>
    <relationshipName>Home_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Pets__c.field-meta.xml
<CustomField>
    <fullName>Pets__c</fullName>
    <label>Pets</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Property_Owner__c.field-meta.xml
<CustomField>
    <fullName>Property_Owner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Property Owner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Type_of_Application__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Application__c</fullName>
    <description>Type of application for SRP contracts. Please avoid using semicolons in option labels or values.</description>
    <label>Type of Application</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
                <default>true</default>
                <label>Purchase</label>
            </value>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>New Home Construction</fullName>
            </value>
            <value>
                <fullName>Remove / Reinstall</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>User Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Utility_Company__c.field-meta.xml
<CustomField>
    <fullName>Utility_Company__c</fullName>
    <label>Utility Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SRP</fullName>
            </value>
            <value>
                <fullName>APS</fullName>
            </value>
            <value>
                <fullName>ED3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DiacoSolarUtilityInformationControllerT.cls
//Test class for: DiacoSolarUtilityInformationController
@isTest
public class DiacoSolarUtilityInformationControllerT {
	@testSetup
    public static void setup() {
        Account installationCompany = new Account(
            Name='Test Installation Company',
            Installation_Company__c= true
        );
        insert installationCompany;
        
        Home_Services__c homeService = new Home_Services__c(
            Utility_Company__c = null,
            Username__c = 'Test username',
            Password__c = 'Test password',
            Property_Owner__c = true,
            Electric_Behind_Fence__c = true,
            Existing_Generating_Solar_System__c = true,
            Pets__c = null,
            House_Square_Footage__c = 500,
            APS_Account__c = null,
            Installation_Company__c = installationCompany.Id
        );
        insert homeService;
    }
    
    @isTest
    public static void getUtilityContractsPicklistValuesTest() {
        Map<String, String> result = DiacoSolarUtilityInformationController.getUtilityContractsPicklistValues();
        
        System.assertNotEquals(result, null);
        System.assert(result.size() > 0);
    }
    
    @isTest
    public static void getTypeOfApplicationPicklistValuesTest() {
        Map<String, Map<String, Object>> result = DiacoSolarUtilityInformationController.getTypeOfApplicationPicklistValues();
        
        System.assertNotEquals(result, null);
        System.assert(result.size() > 0);
    }
    
    @isTest
    public static void getHomeServiceTest() {
        Home_Services__c homeService = [SELECT Id FROM Home_Services__c LIMIT 1];
        System.assertNotEquals(homeService, null);

        Home_Services__c result = DiacoSolarUtilityInformationController.getHomeService(homeService.Id);
        System.assertNotEquals(result, null);
        System.assertEquals(homeService.Id, result.Id);
    }
    
    @isTest
    public static void getInstallationCompany() {
        Home_Services__c homeService = [SELECT Id, Installation_Company__c FROM Home_Services__c LIMIT 1];
        System.assertNotEquals(homeService, null);
        
        Account result = DiacoSolarUtilityInformationController.getInstallationCompany(homeService.Installation_Company__c);
        System.assertNotEquals(result, null);
        System.assertEquals(homeService.Installation_Company__c, result.Id);
    }
    
    @isTest
    public static void updateHomeServiceTest() {
        Home_Services__c homeService = [SELECT Id, Username__c, Type_of_Application__c FROM Home_Services__c LIMIT 1];
        System.assertNotEquals(homeService, null);
        
        homeService.Username__c = 'New test username';
        homeService.Type_of_Application__c = null;
        DiacoSolarUtilityInformationController.updateHomeService(homeService);
        homeService.Type_of_Application__c = '';
        DiacoSolarUtilityInformationController.updateHomeService(homeService);
        
        homeService = [SELECT Id, Username__c, Type_of_Application__c FROM Home_Services__c LIMIT 1];
        System.assertNotEquals(homeService, null);
        System.assertEquals(homeService.Username__c, 'New test username');
        System.assertEquals(homeService.Type_of_Application__c, 'None Selected');
    }
}