force-app/main/default/objects/Account/fields/Installation_Company__c.field-meta.xml
<CustomField>
    <fullName>Installation_Company__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation Company</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Installation_Company.recordType-meta.xml
<RecordType>
    <fullName>Installation_Company</fullName>
    <active>true</active>
    <label>Installation Company</label>
</RecordType>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Annual_Estimated_Generation__c.field-meta.xml
<CustomField>
    <fullName>Annual_Estimated_Generation__c</fullName>
    <inlineHelpText>In kWh.</inlineHelpText>
    <label>Annual Estimated Generation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/APS_Account__c.field-meta.xml
<CustomField>
    <fullName>APS_Account__c</fullName>
    <label>APS Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Battery_Location_Garage__c.field-meta.xml
<CustomField>
    <fullName>Battery_Location_Garage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Garage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Battery_Location_Inside__c.field-meta.xml
<CustomField>
    <fullName>Battery_Location_Inside__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inside</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Battery_Location_Outside__c.field-meta.xml
<CustomField>
    <fullName>Battery_Location_Outside__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Outside</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Battery_Use_Backup_Power__c.field-meta.xml
<CustomField>
    <fullName>Battery_Use_Backup_Power__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Backup Power</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Battery_Use_Energy_Demand_Reduction__c.field-meta.xml
<CustomField>
    <fullName>Battery_Use_Energy_Demand_Reduction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Energy / Demand Reduction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Battery_Use_Solar_Self_consumption__c.field-meta.xml
<CustomField>
    <fullName>Battery_Use_Solar_Self_consumption__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solar Self-consumption</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Electric_Behind_Fence__c.field-meta.xml
<CustomField>
    <fullName>Electric_Behind_Fence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Electric Behind Fence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Existing_Generating_Solar_System__c.field-meta.xml
<CustomField>
    <fullName>Existing_Generating_Solar_System__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Existing Generating Solar System</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Explain_SRP__c.field-meta.xml
<CustomField>
    <fullName>Explain_SRP__c</fullName>
    <label>Explain SRP</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/House_Square_Footage__c.field-meta.xml
<CustomField>
    <fullName>House_Square_Footage__c</fullName>
    <label>House Square Footage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Installation_Company__c.field-meta.xml
<CustomField>
    <fullName>Installation_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Company</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The lookup Account must be  checked with &apos;Installation Company&apos; field.</errorMessage>
        <filterItems>
            <field>Account.Installation_Company__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Installation Company)</relationshipLabel>
    <relationshipName>Home_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Pets__c.field-meta.xml
<CustomField>
    <fullName>Pets__c</fullName>
    <label>Pets</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Property_Owner__c.field-meta.xml
<CustomField>
    <fullName>Property_Owner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Property Owner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Requested_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Install_Date__c</fullName>
    <label>Requested Install Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/System_Size__c.field-meta.xml
<CustomField>
    <fullName>System_Size__c</fullName>
    <label>System Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Type_of_Application__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Application__c</fullName>
    <description>Type of application for SRP contracts. Please avoid using semicolons in option labels or values.</description>
    <label>Type of Application</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
                <default>true</default>
                <label>Purchase</label>
            </value>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>New Home Construction</fullName>
            </value>
            <value>
                <fullName>Remove / Reinstall</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>User Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Utility_Company__c.field-meta.xml
<CustomField>
    <fullName>Utility_Company__c</fullName>
    <label>Utility Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SRP</fullName>
            </value>
            <value>
                <fullName>APS</fullName>
            </value>
            <value>
                <fullName>ED3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/way_restricted_or_impeded__c.field-meta.xml
<CustomField>
    <fullName>way_restricted_or_impeded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>way restricted or impeded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DiacoSolarUtilityInformationController.cls
/**
* Diaco
* @author 			Fabian Pineda href=<fpineda@diaco.us>
* Project:			Contracts
* Description:		Handles actions by component diacoSolarUtilityInformation.cmp
* Test Class :      DiacoSolarUtilityInformationControllerT
* Changes (Version)
* -------------------------------------
*			No.		Date			Author					Description
*			-----	----------		--------------------	---------------
* @version	1.0		15/06/2020		Fabian Pineda (FP)		Initial version.
* @version  1.0     29/06/2020		Fabian Pineda (FP)		Added Type of Application picklist values retrieval method.
* @version  1.0     01/07/2020		Fabian Pineda (FP)		Added getInstallationCompany(String).
* @version	1.0		11/07/2020		Esnayder Morales (EM)   Add System_Size__c field in soql getHomeService method
* @version	1.0		19/09/2020		John Hernandez (JH)     Change Account recordType validation for checkbox "Installation_company" validation.
**/
public class DiacoSolarUtilityInformationController {
    // Important: test class is DiacoSolarUtilityInformationControllerT, not DiacoSolarUtilityInformationControllerTest

    @AuraEnabled
    public static Map<String, String> getUtilityContractsPicklistValues() {
        Map<String, String> output = new Map<String, String>();
        
        Schema.DescribeFieldResult picklist = Home_Services__c.Utility_Company__c.getDescribe();
		List<Schema.PicklistEntry> picklistValues = picklist.getPicklistValues();
        
        for (Schema.PicklistEntry e: picklistValues) {
            if (e.isActive()) {
            	output.put(e.getLabel(), e.getValue());
            }
        }
        
        return output;
    }
    
    @AuraEnabled
    public static Map<String, Map<String, Object>> getTypeOfApplicationPicklistValues() {
        Map<String, Map<String, Object>> output = new Map<String, Map<String, Object>>();
        Map<String, Object> item;
        
        Schema.DescribeFieldResult picklist = Home_Services__c.Type_of_Application__c.getDescribe();
		List<Schema.PicklistEntry> picklistValues = picklist.getPicklistValues();
        
        for (Schema.PicklistEntry e: picklistValues) {
            if (e.isActive()) {
                item = new Map<String, Object>();
                
                item.put('label', e.getLabel());
                item.put('value', e.getValue());
                item.put('isDefault', e.isDefaultValue());
                
            	output.put(e.getLabel(), item);
            }
        }
        
        return output;
    }
    
	@AuraEnabled
    public static Home_Services__c getHomeService(String recordId) {
        Home_Services__c homeService = [
            SELECT
            Utility_Company__c,
            Username__c,
            Password__c,
            Property_Owner__c,
            Electric_Behind_Fence__c,
            Existing_Generating_Solar_System__c,
            Pets__c,
            House_Square_Footage__c,
            APS_Account__c,
            System_Size__c,
            way_restricted_or_impeded__c,
            Explain_SRP__c,
            Type_of_Application__c,
            Installation_Company__c,
			Battery_Use_Backup_Power__c,
            Battery_Use_Energy_Demand_Reduction__c,
            Battery_Use_Solar_Self_consumption__c,
            Battery_Location_Garage__c,
            Battery_Location_Inside__c,
            Battery_Location_Outside__c,
            Requested_Install_Date__c,
            Annual_Estimated_Generation__c
            FROM
            Home_Services__c
            WHERE
            Id = :recordId
            LIMIT 1
        ];
        
        return homeService;
    }
    
    @AuraEnabled
    public static Account getInstallationCompany(String recordId) {
        Account account = [
            SELECT
            Id,
            Name
            FROM
            Account
            WHERE
            (Id = :recordId AND Installation_Company__c= true)
            LIMIT 1
        ];
        
        return account;
    }
    
    @AuraEnabled
    public static Home_Services__c updateHomeService(Home_Services__c homeService) {
        if (homeService.Type_of_Application__c == null) {
            homeService.Type_of_Application__c = 'None Selected';
        } else if (homeService.Type_of_Application__c.trim().length() < 1) {
            homeService.Type_of_Application__c = 'None Selected';
        }
        
        update homeService;
        return homeService;
    }
}