force-app/main/default/objects/Account/fields/Interests__c.field-meta.xml
<CustomField>
    <fullName>Interests__c</fullName>
    <label>Interests</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Bath</fullName>
            </value>
            <value>
                <fullName>Blinds &amp; Shutters</fullName>
            </value>
            <value>
                <fullName>Closet Organization</fullName>
            </value>
            <value>
                <fullName>Garage Floor Coating</fullName>
            </value>
            <value>
                <fullName>Addition(s)</fullName>
            </value>
            <value>
                <fullName>Garage Organization</fullName>
            </value>
            <value>
                <fullName>Handyman</fullName>
            </value>
            <value>
                <fullName>Windows</fullName>
            </value>
            <value>
                <fullName>Security Doors</fullName>
            </value>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
            <value>
                <fullName>Landscape Design/Installation</fullName>
            </value>
            <value>
                <fullName>Pool</fullName>
            </value>
            <value>
                <fullName>Pool Design/Installation</fullName>
            </value>
            <value>
                <fullName>Concrete</fullName>
            </value>
            <value>
                <fullName>Sunroom Patio Enclosure</fullName>
            </value>
            <value>
                <fullName>Landscape Maintenance</fullName>
            </value>
            <value>
                <fullName>Pool Maintenance</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Garage Doors</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Water Filtration</fullName>
            </value>
            <value>
                <fullName>HVAC</fullName>
            </value>
            <value>
                <fullName>Smart Home Automation</fullName>
            </value>
            <value>
                <fullName>TV &amp; Internet</fullName>
            </value>
            <value>
                <fullName>Locksmith</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>Person_Account__r.FirstName</formula>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>Person_Account__r.LastName</formula>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Rekey</fullName>
            </value>
            <value>
                <fullName>Pest</fullName>
            </value>
            <value>
                <fullName>Weed</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Energy Efficiencies</fullName>
            </value>
            <value>
                <fullName>Service Existing System</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Replace Existing Windows</fullName>
            </value>
            <value>
                <fullName>Repair Existing Window Glass</fullName>
            </value>
            <value>
                <fullName>Blinds/Shades</fullName>
            </value>
            <value>
                <fullName>Wood Shutters</fullName>
            </value>
            <value>
                <fullName>Vertical Blinds</fullName>
            </value>
            <value>
                <fullName>Electric Blind/Shade Opener</fullName>
            </value>
            <value>
                <fullName>Sprinkler System</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Trees/Shrubs</fullName>
            </value>
            <value>
                <fullName>Drainage System</fullName>
            </value>
            <value>
                <fullName>Wood Structure(s), Deck(s), Gazebo(s), etc</fullName>
                <label>Wood Structure(s), Deck(s), etc</label>
            </value>
            <value>
                <fullName>Concrete Patio/Walkway, etc</fullName>
            </value>
            <value>
                <fullName>Masonry/Brick/Stone work</fullName>
            </value>
            <value>
                <fullName>Fencing</fullName>
            </value>
            <value>
                <fullName>Retaining wall</fullName>
            </value>
            <value>
                <fullName>Landscape lighting</fullName>
            </value>
            <value>
                <fullName>Pool/Spa</fullName>
            </value>
            <value>
                <fullName>Storage Shed</fullName>
            </value>
            <value>
                <fullName>Built in BBQ</fullName>
            </value>
            <value>
                <fullName>Pergola</fullName>
            </value>
            <value>
                <fullName>Firepit Gas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Type_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Service__c</fullName>
    <label>Type of Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pool</fullName>
            </value>
            <value>
                <fullName>Spa</fullName>
            </value>
            <value>
                <fullName>Interior</fullName>
            </value>
            <value>
                <fullName>Exterior</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>Tile</fullName>
            </value>
            <value>
                <fullName>Stone</fullName>
            </value>
            <value>
                <fullName>Carpet</fullName>
            </value>
            <value>
                <fullName>Waterproof Vinyl</fullName>
            </value>
            <value>
                <fullName>Wood Laminate</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Smooth</fullName>
            </value>
            <value>
                <fullName>Rough</fullName>
            </value>
            <value>
                <fullName>Roll Up</fullName>
            </value>
            <value>
                <fullName>Vertical</fullName>
            </value>
            <value>
                <fullName>Ground level addition</fullName>
            </value>
            <value>
                <fullName>Second story addition</fullName>
            </value>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Shelving</fullName>
            </value>
            <value>
                <fullName>Drawers</fullName>
            </value>
            <value>
                <fullName>Cabinets</fullName>
            </value>
            <value>
                <fullName>Hanging Storage</fullName>
            </value>
            <value>
                <fullName>Deadbolt</fullName>
            </value>
            <value>
                <fullName>Keyless Entry</fullName>
            </value>
            <value>
                <fullName>Cable</fullName>
            </value>
            <value>
                <fullName>Satellite</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Laminate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/recordTypes/Concrete.recordType-meta.xml
<RecordType>
    <fullName>Concrete</fullName>
    <active>true</active>
    <label>Concrete</label>
</RecordType>

force-app/main/default/objects/Appointment__c/recordTypes/HVAC.recordType-meta.xml
<RecordType>
    <fullName>HVAC</fullName>
    <active>true</active>
    <label>HVAC</label>
</RecordType>

force-app/main/default/objects/Appointment__c/recordTypes/Windows.recordType-meta.xml
<RecordType>
    <fullName>Windows</fullName>
    <active>true</active>
    <label>Windows</label>
</RecordType>

force-app/main/default/objects/Appointment_RecordType_mtd__c/Appointment_RecordType_mtd__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Appointment_RecordType_mtd</label>
</CustomObject>

force-app/main/default/objects/Appointment_RecordType_mtd__c/fields/Interest_Activate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Activate__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Interest Activate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Appointment_RecordType_mtd__c/fields/Interest_Name__c.field-meta.xml
<CustomField>
    <fullName>Interest_Name__c</fullName>
    <label>Interest Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Appointment_RecordType_mtd__c/fields/RT_Appointment_Id__c.field-meta.xml
<CustomField>
    <fullName>RT_Appointment_Id__c</fullName>
    <label>RT_Appointment_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment_RecordType_mtd__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Recordtype for three types of setting  : Appointment, HomeService, Interest.</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/fields/Kunnect_ID__c.field-meta.xml
<CustomField>
    <fullName>Kunnect_ID__c</fullName>
    <inlineHelpText>This is a Required field.  If this person does not have a Kunnect account please put &quot;none&quot;</inlineHelpText>
    <label>Kunnect ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/SF_User__c.field-meta.xml
<CustomField>
    <fullName>SF_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Personnels2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DiacoInterestWebformControllerTest.cls
@isTest
private class DiacoInterestWebformControllerTest {
    private static Id appointmentRtConcrete = Schema.SObjectType.Appointment__c.getRecordTypeInfosByName().get('Concrete Coating').getRecordTypeId();

    @TestSetup
    static void makeData() {
        List<String> interests = new List<String>{'Concrete Coating','Windows'};
        List<Appointment_RecordType_mtd__c> interestSettgn = new List<Appointment_RecordType_mtd__c>();
        integer interestSize = interests.size();
        for (Integer i = 0; i < interestSize; i++) {
            interestSettgn.add(
                new Appointment_RecordType_mtd__c(
                    Name = interests[i], 
                    Interest_Name__c =  interests[i],
                    Interest_Activate__c = true,
                    RT_Appointment_Id__c = diacoKnifeFunc.getRecordTypeIdbyName('Appointment__c', interests[i]),
                    Type__c = 'Interest'
                )
            );
        }
        insert interestSettgn;

        Account acc   = new Account(); 
        acc.FirstName = 'Test';
        acc.LastName  = 'test';
        acc.Interests__c = 'Windows;Bath;Garage Floor Coating';
        insert acc;

        Personnel__c personel  = new Personnel__c();                                                           
        personel.Kunnect_ID__c = 'test';
        personel.First_Name__c = 'test';
        personel.Last_Name__c  = 'test';
        personel.SF_User__c=UserInfo.getUserId();
        insert personel;
		
        Appointment__c appointment = new Appointment__c();
        appointment.Name='test';
        appointment.RecordTypeId = appointmentRtConcrete;
        appointment.Appointment_Start_Time__c = Datetime.now();
        appointment.Person_Account__c = acc.Id;
        insert appointment;
    }

    @IsTest
    static void test(){
        List<Account> accts = [SELECT Name FROM Account LIMIT 1];
        List<Appointment__c> appointments = [SELECT Name FROM Appointment__c LIMIT 1];
        String kunnectId = [SELECT Kunnect_ID__c FROM Personnel__c LIMIT 1]?.Kunnect_ID__c;

        Test.startTest();

            System.assertEquals(!accts.isEmpty(), true, 'list Account is Empty');
            System.assertEquals(!appointments.isEmpty(), true, 'list Appointments is Empty');
            System.assertEquals(kunnectId != null, true, 'Kunnect_ID__c is null');
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('getPicklistValueByRecordtype');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
            Test.setMock(HttpCalloutMock.class, mock);

            DiacoInterestWebformController.getData(accts[0].Id, new List<String>{'Project_Type__c','Type_of_Service__c'},kunnectId);
            DiacoInterestWebformController.getData(accts[0].Id, new List<String>{'Project_Type__c','Type_of_Service__c'},null);
            DiacoInterestWebformController.getData(null, new List<String>{'Project_Type__c','Type_of_Service__c'},null);
            DiacoInterestWebformController.getAppointment(accts[0].Id, new List<String>{'Windows','Bath','Concrete Coating'});
            DiacoInterestWebformController.getPicklistValueByRecordtype('Appointment__c', 'Project_Type__c', new List<Id>{appointmentRtConcrete});
            DiacoInterestWebformController.setAppointment(appointments[0],new list<String>{'2020', '10', '7', '20', '0'},2,accts[0],'HVAC');

        Test.stopTest();
        
    }
}