force-app/main/default/objects/Account/fields/Interests__c.field-meta.xml
<CustomField>
    <fullName>Interests__c</fullName>
    <label>Interests</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Bath</fullName>
            </value>
            <value>
                <fullName>Blinds &amp; Shutters</fullName>
            </value>
            <value>
                <fullName>Closet Organization</fullName>
            </value>
            <value>
                <fullName>Garage Floor Coating</fullName>
            </value>
            <value>
                <fullName>Addition(s)</fullName>
            </value>
            <value>
                <fullName>Garage Organization</fullName>
            </value>
            <value>
                <fullName>Handyman</fullName>
            </value>
            <value>
                <fullName>Windows</fullName>
            </value>
            <value>
                <fullName>Security Doors</fullName>
            </value>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
            <value>
                <fullName>Landscape Design/Installation</fullName>
            </value>
            <value>
                <fullName>Pool</fullName>
            </value>
            <value>
                <fullName>Pool Design/Installation</fullName>
            </value>
            <value>
                <fullName>Concrete</fullName>
            </value>
            <value>
                <fullName>Sunroom Patio Enclosure</fullName>
            </value>
            <value>
                <fullName>Landscape Maintenance</fullName>
            </value>
            <value>
                <fullName>Pool Maintenance</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Garage Doors</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Water Filtration</fullName>
            </value>
            <value>
                <fullName>HVAC</fullName>
            </value>
            <value>
                <fullName>Smart Home Automation</fullName>
            </value>
            <value>
                <fullName>TV &amp; Internet</fullName>
            </value>
            <value>
                <fullName>Locksmith</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment_RecordType_mtd__c/Appointment_RecordType_mtd__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Appointment_RecordType_mtd</label>
</CustomObject>

force-app/main/default/objects/Appointment_RecordType_mtd__c/fields/Interest_Activate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Activate__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Interest Activate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Appointment_RecordType_mtd__c/fields/Interest_Index__c.field-meta.xml
<CustomField>
    <fullName>Interest_Index__c</fullName>
    <label>Interest Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Appointment_RecordType_mtd__c/fields/Interest_Name__c.field-meta.xml
<CustomField>
    <fullName>Interest_Name__c</fullName>
    <label>Interest Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Appointment_RecordType_mtd__c/fields/PartnerId__c.field-meta.xml
<CustomField>
    <fullName>PartnerId__c</fullName>
    <label>PartnerId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment_RecordType_mtd__c/fields/RT_Appointment_Id__c.field-meta.xml
<CustomField>
    <fullName>RT_Appointment_Id__c</fullName>
    <label>RT_Appointment_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment_RecordType_mtd__c/fields/RT_Home_Service_Id__c.field-meta.xml
<CustomField>
    <fullName>RT_Home_Service_Id__c</fullName>
    <label>RT_Home_Service_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment_RecordType_mtd__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Recordtype for three types of setting  : Appointment, HomeService, Interest.</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Appointment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DiacoAppointmentRecordSetUp_ctr.cls
/**
 *
 * Diaco
 * Project:			Appointment Recordtype Set Up
 * Description:		Class reponsible provide method to DiacoAppointmentRecordtype_SetUp
 * Testclass        DiacoAppointmentRecordSetUp_tst
 * Changes (Version)
 * _________________________________________
 *
 * 			No.		Date			Author					Description
 * 			____	__________      __________________ 		_____________________________________
 * @version	1.0		12/08/2020		Jull Quintero Daza	    Initial implementation  of the class.
 * @version	2.0		24/09/2020		Jull Quintero Daza	    Initial implementation  of the class.

 */

public with sharing class DiacoAppointmentRecordSetUp_ctr {

/**
 * This method is responsible to get setting type HomeService
 * 
 * This method is used in:
 * DiacoAppointmentRecordType_HomeServiceSetUp.cmp
 * 
 * @return 
 * List setting type HomeService, 
 * List recordtype object Home_Services__c and Appointment__c
 **/
    @AuraEnabled
    public static WrappedResponse getHomesviceSetting() {
        List<Appointment_RecordType_mtd__c> appointment_mtd = [SELECT Id,Type__c,Name,RT_Home_Service_Id__c, PartnerId__c 
                                                                FROM Appointment_RecordType_mtd__c 
                                                                WHERE Type__c = 'HomeService'];
                                                                
        List<RecordType> homeservice_recordtypes = diacoKnifeFunc.getDataRecordType('Home_Services__c');
        List<RecordType> appointment_recordtypes = diacoKnifeFunc.getDataRecordType('Appointment__c');

        return new WrappedResponse(
            appointment_mtd,
            homeservice_recordtypes,
            appointment_recordtypes
        );
    }

/**
 * This method is responsible to get setting type Appointment
 * 
 * This method is used in:
 * DiacoAppointmentRecordType_HomeServiceSetUp
 * 
 * @return 
 * List setting type Appointment,
 * List recordtype object Home_Services__c and Appointment__c
 **/
    @AuraEnabled
    public static WrappedResponse getAppointmentSetting() {
        List<Appointment_RecordType_mtd__c> appointment_mtd = [SELECT Id,Type__c,Name,RT_Appointment_Id__c, PartnerId__c 
                                                                FROM Appointment_RecordType_mtd__c 
                                                                WHERE Type__c = 'Appointment'];
                                                                
        List<RecordType> homeservice_recordtypes = diacoKnifeFunc.getDataRecordType('Home_Services__c');
        List<RecordType> appointment_recordtypes = diacoKnifeFunc.getDataRecordType('Appointment__c');

        return new WrappedResponse(
            appointment_mtd,
            homeservice_recordtypes,
            appointment_recordtypes
        );
    }

/**
 * This method is responsible to get setting type Interest
 * 
 * This method is used in:
 * DiacoAppointmentRecordType_InterestSetUp
 * 
 * @return 
 * List setting type Interest, 
 * List Picklistvalues for field Interests__c in object Account 
 * List recordtype object Appointment__c
 **/
    @AuraEnabled
    public static WrappedResponse getInterestSetting() {
        List<Appointment_RecordType_mtd__c> appointment_mtd = [SELECT   Id, Type__c, Name, RT_Appointment_Id__c, Interest_Name__c, 
                                                                        Interest_Index__c,Interest_Activate__c 
                                                                FROM Appointment_RecordType_mtd__c 
                                                                WHERE Type__c = 'Interest' ORDER BY Interest_Index__c];

        Map<String, String>  account_interests = diacoKnifeFunc.getPicklistValues('Account', new list<String>{'Interests__c'})[0];

        List<RecordType> appointment_recordtypes = diacoKnifeFunc.getDataRecordType('Appointment__c');

        return new WrappedResponse(
            appointment_mtd,
            account_interests,
            appointment_recordtypes
        );
    }

/**
 * This method is responsible to inser and update custom setting Appointment_RecordType_mtd__c
 * 
 * This method is used in:
 * DiacoAppointmentRecordType_HomeServiceSetUp
 * 
 * @return 
 * List custom setting Appointment_RecordType_mtd__c
 **/
    @AuraEnabled
    public static List<Appointment_RecordType_mtd__c> setAppointmentRt(List<Appointment_RecordType_mtd__c> appointments_mtd) {

        try {
            upsert appointments_mtd;
            return appointments_mtd;
        } catch (DmlException e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

/**
 * This method is responsible to delete custom setting Appointment_RecordType_mtd__c
 * 
 * This method is used in:
 * DiacoAppointmentRecordType_HomeServiceSetUp
 *
 **/
    @AuraEnabled
    public static void delAppointmentRt(List<Appointment_RecordType_mtd__c> appointments_mtd) {
        try {
            delete appointments_mtd;
        } catch (DmlException e) {
            throw new AuraHandledException(e.getMessage());
        }
        
    }

    public class WrappedResponse {        
        @AuraEnabled
        public List<Appointment_RecordType_mtd__c> appointment_mtd {get;set;}
        @AuraEnabled
        public List<RecordType> homeservice_recordtypes{get;set;}
        @AuraEnabled
        public List<RecordType> appointment_recordtypes{get;set;}
        @AuraEnabled
        public Map<String, String>  account_interests{get;set;}
        
        public WrappedResponse(List<Appointment_RecordType_mtd__c> appointment_mtd, List<RecordType> homeservice_recordtypes, List<RecordType> appointment_recordtypes) {
            this.appointment_mtd = appointment_mtd;
            this.homeservice_recordtypes = homeservice_recordtypes;
            this.appointment_recordtypes = appointment_recordtypes;
        }

        public WrappedResponse(List<Appointment_RecordType_mtd__c> appointment_mtd,Map<String, String>  account_interests, List<RecordType> appointment_recordtypes) {
            this.appointment_mtd = appointment_mtd;
            this.account_interests = account_interests;
            this.appointment_recordtypes = appointment_recordtypes;
        }
	}

}