force-app/main/default/objects/Account/fields/Pool__c.field-meta.xml
<CustomField>
    <fullName>Pool__c</fullName>
    <label>Pool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Number_of_People_in_the_home__c.field-meta.xml
<CustomField>
    <fullName>Number_of_People_in_the_home__c</fullName>
    <label>Number of People in the home</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Number_of_Stories_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Stories_Picklist__c</fullName>
    <label>Number of Stories</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Pets__c.field-meta.xml
<CustomField>
    <fullName>Pets__c</fullName>
    <label>Pets</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Rekey</fullName>
            </value>
            <value>
                <fullName>Pest</fullName>
            </value>
            <value>
                <fullName>Weed</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Energy Efficiencies</fullName>
            </value>
            <value>
                <fullName>Service Existing System</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Replace Existing Windows</fullName>
            </value>
            <value>
                <fullName>Repair Existing Window Glass</fullName>
            </value>
            <value>
                <fullName>Blinds/Shades</fullName>
            </value>
            <value>
                <fullName>Wood Shutters</fullName>
            </value>
            <value>
                <fullName>Vertical Blinds</fullName>
            </value>
            <value>
                <fullName>Electric Blind/Shade Opener</fullName>
            </value>
            <value>
                <fullName>Sprinkler System</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Trees/Shrubs</fullName>
            </value>
            <value>
                <fullName>Drainage System</fullName>
            </value>
            <value>
                <fullName>Wood Structure(s), Deck(s), Gazebo(s), etc</fullName>
                <label>Wood Structure(s), Deck(s), etc</label>
            </value>
            <value>
                <fullName>Concrete Patio/Walkway, etc</fullName>
            </value>
            <value>
                <fullName>Masonry/Brick/Stone work</fullName>
            </value>
            <value>
                <fullName>Fencing</fullName>
            </value>
            <value>
                <fullName>Retaining wall</fullName>
            </value>
            <value>
                <fullName>Landscape lighting</fullName>
            </value>
            <value>
                <fullName>Pool/Spa</fullName>
            </value>
            <value>
                <fullName>Storage Shed</fullName>
            </value>
            <value>
                <fullName>Built in BBQ</fullName>
            </value>
            <value>
                <fullName>Pergola</fullName>
            </value>
            <value>
                <fullName>Firepit Gas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/recordTypes/Solar.recordType-meta.xml
<RecordType>
    <fullName>Solar</fullName>
    <active>true</active>
    <label>Solar</label>
</RecordType>

force-app/main/default/objects/Appointment_RecordType_mtd__c/Appointment_RecordType_mtd__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Appointment_RecordType_mtd</label>
</CustomObject>

force-app/main/default/objects/Appointment_RecordType_mtd__c/fields/RT_Home_Service_Id__c.field-meta.xml
<CustomField>
    <fullName>RT_Home_Service_Id__c</fullName>
    <label>RT_Home_Service_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Appointment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Pets__c.field-meta.xml
<CustomField>
    <fullName>Pets__c</fullName>
    <label>Pets</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DiacoAppointmentCreateHsTest.cls
@isTest
public class DiacoAppointmentCreateHsTest {
     
    @isTest
    public static void test(){
        
        List<Appointment_RecordType_mtd__c> res = new List<Appointment_RecordType_mtd__c>();
        List<String> Rtypes = new List<String>{'Home Automation','Water Filtration','Solar','Pest Control','Kitchen Remodel'};
        List<String> HRtypes = new List<String>{'Home Automation Sales','Water Treatment Sales','Solar Sales','Pest Control Sales','Remodel Sales'};
        Account ac = new Account(Name='test Acc');
        insert ac;
        List<Appointment__c> apps = new  List<Appointment__c>();
        for(Integer i=0 ; i<4; i++){
            Id TypeId = Schema.SObjectType.Appointment__c.getRecordTypeInfosByName().get(Rtypes[i]).getRecordTypeId();
            Id HTypeId = Schema.SObjectType.Home_Services__c.getRecordTypeInfosByName().get(HRtypes[i]).getRecordTypeId();
            res.add(new Appointment_RecordType_mtd__c(Name=TypeId,RT_Home_Service_Id__c=HTypeId));
        }
        insert res;
        for(String s: Rtypes){
            Id EventRecordTypeId = Schema.SObjectType.Appointment__c.getRecordTypeInfosByName().get(s).getRecordTypeId();
            Appointment__c a = new Appointment__c(Name='test Appointment');
            a.recordTypeId=EventRecordTypeId;
            a.Number_of_People_in_the_home__c=12;
            a.Person_Account__c=ac.Id;
            a.Appointment_Start_Time__c=Datetime.now();
            a.Appointment_End_Time__c=Datetime.now().addMinutes(30);
            apps.add(a);
        }
        apps[0].Pool__c=true;
        apps[0].Number_of_Stories_Picklist__c='2';
        apps[2].Pool__c=true;
        apps[2].Project_Type__c='Solar';
        apps[3].Project_Type__c='Solar';
        apps[3].Pets__c='Dog(s)';
        insert apps;
        Test.startTest();
        DiacoAppointmentCreateHs.createHs(apps);
        Test.stopTest();
    }
}