force-app/main/default/objects/Account/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field will store the person Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/User_Address_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Address_Type__c</fullName>
    <description>holds the type of address</description>
    <label>User Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Owner</fullName>
            </value>
            <value>
                <fullName>Secondary Owner</fullName>
            </value>
            <value>
                <fullName>Mailing Address</fullName>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Renter</fullName>
            </value>
            <value>
                <fullName>Un-validated Homeowner</fullName>
            </value>
            <value>
                <fullName>Family of Renter</fullName>
            </value>
            <value>
                <fullName>Family of Un-validated Homeowner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/KunnectScheduleSettingTest.cls
@isTest
private class KunnectScheduleSettingTest {
    @TestSetup
    static void makeData() {
        
        TestClassUtil.createAccount(1);

        Id accountID = [SELECT Id FROM Account LIMIT 1]?.Id;        

        List<User_Address__c> userAddress = new List<User_Address__c>();
        for (Integer i = 0; i < 10; i++) {
            userAddress.add(
                new User_Address__c(
                    //Address__c = address[j].id, 
                    UserAccount__c = accountID,
                    User_Address_Type__c = 'Primary Owner',
                    Active__c = true,
                    Respond_date__c = Date.Today().addDays(-1)
                    )            
                );
        }
        insert userAddress;

        for (Integer i = 0; i < 10; i++) {
            userAddress[i].Phone__c = '1234556770';
        }
        update userAddress;
    }
    @IsTest
        static void methodName(){
            
            Test.startTest();

            KunnectScheduleSetting setting = new KunnectScheduleSetting();
            setting.name = 'inboundUserAddress';
            setting.newUserAddress = true;
            setting.recordSize = 100;
            setting.nextRun = Datetime.now().addMinutes(70);

            setting.getInboundUserAddress();
            setting.getOutboundSourceUserAddress();
            setting.getOutboundGravelUserAddress();
            setting.sendEmail(20);

            string settingStr = KunnectScheduleSetting.createJson(setting);
            KunnectScheduleSetting.parse(settingStr);
            
            Test.stopTest();
            
        }
    }