force-app/main/default/objects/Account/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Verbal_Consent__c.field-meta.xml
<CustomField>
    <fullName>Verbal_Consent__c</fullName>
    <label>Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <color>#33CC00</color>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
                <color>#FF0000</color>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Verbal_Consent__c.field-meta.xml
<CustomField>
    <fullName>Verbal_Consent__c</fullName>
    <formula>Text(UserAccount__r.Verbal_Consent__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Verbal Consent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verbal_Consent__c/Verbal_Consent__c.object-meta.xml
<CustomObject>
    <description>This object will holds the verbal consents records</description>
    <label>Verbal Consent</label>
    <nameField>
        <displayFormat>VC-{0000}</displayFormat>
        <label>Verbal Consent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verbal Consents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DiacoAccountTriggerUnifiedTest.cls
@isTest (SeeAllData = true)
public class DiacoAccountTriggerUnifiedTest {
    
    @isTest static void testAll(){
        
        List<Account> Teste = new List <Account>();
        list<Opportunity> oportunityList = new list<Opportunity>();
        Map<Id,Account> AccountMap = new Map<Id,Account>();
         Map<Id,Account> AccountNewMap = new Map<Id,Account>();
        list<User_Address__c> userAddressList = new list<User_Address__c>();
        
        
        
        for(Integer i=0;i<10;i++)
        {
            
            Teste.add(new Account(BillingState = 'CA', LastName = 'Pass v2'+i,
                                  RecordTypeId = '012410000012NOKAA2',
                                  PersonDoNotCall =True,
                                  Verbal_Consent__c='No',
                                  phone='123456789'));
            
        }
        
        for(Integer j=0;j<10;j++)
        {
            Teste.add(new Account(BillingState = 'NY', LastName = 'Not Pass v2'+j,
                                  RecordTypeId = '012410000012NOKAA2',
                                  PersonDoNotCall=false,
                                  Verbal_Consent__c='xxxx',
                                  Respond_Date__c=null,
                                  phone=null));
        }
        insert Teste;
        
        for (Account acc : Teste) {
            
            if(acc.phone == null){
                acc.phone='123456789';
            }
            AccountMap.put(acc.Id, acc);
            oportunityList.add(new Opportunity(
                Name = 'TestOpportunity',
                AccountId = acc.Id,
                StageName = 'Qualified',
                CloseDate = system.today()
            ));  
            
             userAddressList.add(new User_Address__c(UserAccount__c = acc.Id));
        }
        
        insert oportunityList;
        insert userAddressList;
        
        list<Account> updateList = AccountMap.values();
        
        update updateList;
         
        for (Account acc : updateList) {
            AccountNewMap.put(acc.Id,acc);
        }
   
        test.startTest();
        DiacoAccountTriggerUnifiedClass.beforeTriggersToExecute(Teste);
        DiacoAccountTriggerUnifiedClass.AccountMain(Teste,AccountMap,true,false);
        DiacoAccountTriggerUnifiedClass.AccountMain(Teste,AccountMap,false,true);
        DiacoAccountTriggerUnifiedClass.Account_OwnerChange(AccountMap, AccountNewMap);
        DiacoAccountTriggerUnifiedClass.setPhoneForUserAddress(AccountMap, AccountNewMap);
        test.stopTest();
        
    }
}