force-app/main/default/objects/Account/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Log__c/Call_Log__c.object-meta.xml
<CustomObject>
    <label>Call Log</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Call Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account associated with this call.</description>
    <inlineHelpText>The account associated with this call.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/ANI__c.field-meta.xml
<CustomField>
    <fullName>ANI__c</fullName>
    <description>Caller ID Number</description>
    <inlineHelpText>Caller ID Number</inlineHelpText>
    <label>ANI</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup field to connect call log to the user address.</description>
    <inlineHelpText>This is a lookup field to connect call log to the user address.</inlineHelpText>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/fPhone__c.field-meta.xml
<CustomField>
    <fullName>fPhone__c</fullName>
    <formula>BLANKVALUE(Phone__c ,  PersonMobilePhone__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fPhone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field will store the person Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UpdateCalllogsWithAccount.cls
global class UpdateCalllogsWithAccount implements Database.Batchable<sObject>,schedulable{

   global void execute(SchedulableContext sc) {
      database.executebatch(new UpdateCalllogsWithAccount());
   }

   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator([select id,ANI__c,User_Address__c,Account__c 
                                       from Call_Log__c where ANI__c !=null 
                                       and (Account__c = null or  User_Address__c = null)]);
   }

   global void execute(Database.BatchableContext BC, List<Call_Log__c> scope){
       Date conditionedDate = Date.Today().addDays(-2);
       Set<string> phoneAccount = new Set<string>();
        Set<string> phoneAddress = new Set<string>();
        for(Call_Log__c rec : scope){
            if(rec.Account__c == null)
                phoneAccount.add(rec.ANI__c);
            if(rec.User_Address__c == null)
                phoneAddress.add(rec.ANI__c);           
        }
       system.debug('xxx'+phoneAccount);
        
        List<Account> lstAccount = [select id,Phone,PersonMobilePhone 
                                            from account 
                                            where (Phone in : phoneAccount or PersonMobilePhone in : phoneAccount) 
                                            and Respond_Date__c >=: conditionedDate order by lastmodifiedDate desc];
        system.debug('AAAAAAAAAAAA' + lstAccount);
        Map<string,Account> accountPhoneMap = new Map<string,Account>();
        Map<string,Account> accountPersonMobileMap = new Map<string,Account>();
        for(Account acc : lstAccount){
            system.debug('mobile oho'+acc);
            if(acc.Phone != null)
                accountPhoneMap.put(acc.Phone,acc);
            if(acc.PersonMobilePhone != null)
                accountPersonMobileMap.put(acc.PersonMobilePhone,acc);
        }
        
        List<User_Address__c> lstUserAddress = New List<User_Address__c>();
        lstUserAddress = [select id,Phone__c,fPhone__c from User_Address__c where Address__c != null 
                            and (Phone__c in : phoneAddress or fPhone__c in : phoneAddress) 
                            and Respond_Date__c >= : conditionedDate order by lastmodifieddate desc NULLS LAST];
        
        system.debug('AAAAAAAAAAAA' + lstUserAddress.size() );
        Map<string,User_Address__c> userAddressPhoneMap = new Map<string,User_Address__c>();
        Map<string,User_Address__c> userAddressFPhoneMap = new Map<string,User_Address__c>();
        for(User_Address__c userAdd : lstUserAddress ){
            if(userAdd.Phone__c != null)
                userAddressPhoneMap.put(userAdd.Phone__c,userAdd);
            if(userAdd.fPhone__c != null)
                userAddressFPhoneMap.put(userAdd.fPhone__c,userAdd);
        }
        
        for(Call_Log__c rec : scope){
            if(rec.Account__c == null){
                If(accountPhoneMap.containsKey(rec.ANI__c)){
                    rec.Account__c = accountPhoneMap.get(rec.ANI__c).Id;
                }
                else If(accountPersonMobileMap.containsKey(rec.ANI__c)){
                    rec.Account__c = accountPersonMobileMap.get(rec.ANI__c).Id;
                }
            }
            
            if(rec.User_Address__c == null){
                If(userAddressPhoneMap.containsKey(rec.ANI__c)){
                    rec.User_Address__c = userAddressPhoneMap.get(rec.ANI__c).Id;
                }
                else If(userAddressFPhoneMap.containsKey(rec.ANI__c)){
                    rec.User_Address__c = userAddressFPhoneMap.get(rec.ANI__c).Id;
                }
            }   
        }
        
        update scope;
   
   }

   global void finish(Database.BatchableContext BC){
   
   }
}