force-app/main/default/objects/Account/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipCode__c/ZipCode__c.object-meta.xml
<CustomObject>
    <description>It contains all zip codes for the corresponding branches.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipCode__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Zip Codes</relationshipLabel>
    <relationshipName>Zip_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZipCode</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiacoAssignRouteZip.cls
/**
* Diaco
* @author 			Esnayder Morales href=<esnaydermorales25@gmail.com>
* Project:			Unique webform 
* Description:		class responsible to assign webform to account.
*
* Changes (Version)
* -------------------------------------
*			No.		Date			Author						Description
*			-----	----------		--------------------		---------------
* @version	1.0		10/07/2019		Esnayder Morales (EM)		Initial implementation of the class.
**/
global class DiacoAssignRouteZip {
    
    @InvocableMethod(label='Account to Route' description='Account relationship to Route.')
    public static void ConnectWebformAccount(List<param> params) {	
        System.debug('Account to Route');
        System.debug('===========::::::::>>>>');
        //System.debug(params);
        for (param p: params){
            if(String.isEmpty(p.Route)){
                p.Route=null;
            }        
        }
        //List<Account> acct = [select Id,Zip__c,Route__c from Account where Id IN : Ids];
		updateRoute(params);
        return;
    }
  
    global class param {
        @InvocableVariable
        global String Id ;
        @InvocableVariable
        global String Zip;
        @InvocableVariable
        global String Route;
    }
    
    public static String updateRoute(List<param> records){
        List<Account> accounts = new List<Account>();
        List<ZipCode__c> routeId = [select Route__c from ZipCode__c where Name = 'unknown']; 
     	List<ZipCode__c> zipCode = [select Name, Route__c from ZipCode__c];
        System.debug('Activate process Builder #1');
        //System.debug(records[0].Route__c);
        for(param acc : records){
            for(ZipCode__c zip : zipCode){
                if(acc.Zip == zip.Name){
                	acc.Route = zip.Route__c;
                    break;
                }else{
                   acc.Route = null;
                }
            }
            System.debug(acc.Route);
            //System.debug(routeId[0].Route__c +'  |||-------------->>>s');
            if(acc.Route == null &&
              routeId.size()>0){
                acc.Route = routeId[0].Route__c;
            }
            Account ac = new Account(Id = acc.Id);
            if(acc.Route!=null){
                ac.Route__c=acc.Route;
            }            
            accounts.add(ac);
        }
        for(Account ac : accounts){
            System.debug(ac.Id+ ' ------------  ' +ac.Route__c);
        }
        update accounts;
        return 'Good';
    }

}