force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Required Field</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Cheetah_Driver_Code__c.field-meta.xml
<CustomField>
    <fullName>Cheetah_Driver_Code__c</fullName>
    <externalId>true</externalId>
    <label>Cheetah Driver Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Hung_Status__c.field-meta.xml
<CustomField>
    <fullName>Hung_Status__c</fullName>
    <label>Hung Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrived</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hung</fullName>
            </value>
            <value>
                <fullName>COMPLETED GATED</fullName>
            </value>
            <value>
                <fullName>Gated</fullName>
            </value>
            <value>
                <fullName>Cant Find</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Invld</fullName>
            </value>
            <value>
                <fullName>Remove: Management</fullName>
            </value>
            <value>
                <fullName>Too Far</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Wrong House Number</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Remove: Gated</fullName>
            </value>
            <value>
                <fullName>Remove: Aging</fullName>
            </value>
            <value>
                <fullName>Sent To Cheetah</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Gio - In Process</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Access Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Card_Orders__c/Gift_Card_Orders__c.object-meta.xml
<CustomObject>
    <label>Gift Card Order</label>
    <nameField>
        <label>Gift Card Orders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Card Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Card_Orders__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Gift Card Orders</relationshipLabel>
    <relationshipName>Gift_Card_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift_Card_Orders__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associating Gift Card under User Address Object</description>
    <label>User Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Parent_Gift_Card_Order__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Gift Card Orders</relationshipLabel>
    <relationshipName>Gift_Card_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hung_Status__c/Hung_Status__c.object-meta.xml
<CustomObject>
    <description>This object will different Hung Status details for the Products</description>
    <label>Hung Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Hung Status No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hung Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/MapsDeliveryDriverControllerTest.cls
@isTest
private class MapsDeliveryDriverControllerTest {
    @testSetup static void loadTestData() {
        TestClassUtil.createZipcodeForBranch();
        TestClassUtil.createAccount(5);
        TestClassUtil.createCheetahGiftCardOrder();
        TestClassUtil.createDriver(); 
        TestClassUtil.createAddress(5);
        TestClassUtil.createUserAddress(3);  
		String s = '"Hometype","Rental","New","SalePrice","Down","Firstname","Lastname","phone","address","city","state","plus4","zip","DATE","PostDate","Update","County","FileNumber","BMPS"\n'+
        '"SF",,,510000.00,288329.00,"OMAR","GASTELUM COTA",,"6303 N 65TH DR","GLENDALE","AZ","4315","85301","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359061","14415011"\n'+
        '"SF",,"N",342990.00,10289.00,"PETER & CAROL","VALENTINO",,"2727 W APOLLO RD","PHOENIX","AZ","5486","85041","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359063","10592048"\n'+
        '"SF",,,364000.00,36400.00,"MARGARET","JOHNSON",,"3813 E PARK AVE","PHOENIX","AZ","8255","85044","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359070","30601625"\n'+
        '"CT",,,265000.00,105000.00,"KEITH & KIMBERLY","EWING",,"2101 S YELLOW WOOD UNIT 14","MESA","AZ","1486","85209","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359072","31212008"\n'+
        '"SF",,,650000.00,154000.00,"MICHAEL","ALLEN",,"26250 N 46TH ST","PHOENIX","AZ","8510","85050","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359082","21209227"\n'+
        '"SF",,"N",469699.00,23485.00,"ARIEL & TROY","AUELUA",,"4706 S MARS","MESA","AZ","3270","85212","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359089","31216546"\n'+
        '"SF",,,610000.00,610000.00,"PAUL","INDELICATO",,"8212 E SHERIDAN ST","SCOTTSDALE","AZ","2344","85257","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359156","13133059"\n'+
        '"SF",,,585000.00,58500.00,"BRIAN & LAUREN","WEST",,"2481 E BELLERIVE PL","CHANDLER","AZ","4142","85249","3/31/2021",4/2/2021 0:00:00,,"MARICOPA","20210359164","30356382"';
        String contractName = 'test document 3';
        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.PathOnClient = '.csv';
        //cv.OwnerId = at.OwnerId;
        cv.Title = contractName;
        cv.VersionData = blob.valueOf(s);
        insert cv;
        Id accountId = [SELECT Id FROM Account lIMIT 1]?.Id;
        Id giftCardOrderId = [SELECT Id FROM Gift_Card_Orders__c LIMIT 1]?.Id;
        Id driverId =  [SELECT Id FROM Driver__c LIMIT 1]?.Id;
        Id userAddressId = [SELECT ID FROM User_Address__c LIMIT 1]?.Id;

            List<Delivery_Object__c> deliveries = new List<Delivery_Object__c>();
            for (Integer i = 0; i < 10; i++) {
                Delivery_Object__c delivery = new Delivery_Object__c();        
                delivery.Person_Account__c = accountId;
                delivery.Driver__c = driverId;
                delivery.name = '1';
                delivery.Parent_Gift_Card_Order__c = giftCardOrderId;
                delivery.User_Address__c = userAddressId;
                delivery.Hung_Status__c = 'Sent To Cheetah';  
                if ( i > 5 ) {
                    delivery.Cheetah_Driver_Code__c = 'invalid 728337';
                }         
                deliveries.add(delivery);   
            }

            insert deliveries;
    }	

    @IsTest
    static void test(){
        Delivery_Object__c[] deliveries = [SELECT Id,Street__c FROM Delivery_Object__c ];
        Test.setMock(HttpCalloutMock.class, new MapsDeliveryDriverControllerMockTest());
        Test.startTest();
    
            maps__Route__c route = new maps__Route__c(Name='Test',maps__Date__c=Date.today(),maps__User__c = UserInfo.getUserId() ) ;
            insert route;
            maps__Waypoint__c point = new maps__Waypoint__c(Name='Test',maps__Route__c=route.id,Delivery_Object__c=deliveries[0].id);
            insert point;
            MapsDeliveryDriverController.getData();
            String ids = [select ContentDocumentId from ContentVersion where Title='test document 3'].contentdocumentId;
            system.debug(ids);
            MapsDeliveryDriverController.uploadPhoto(ids,deliveries[0].id);
        Test.stopTest();
        
    }
}