force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UpdateDeliveryTest.cls
@isTest 
public class UpdateDeliveryTest 
{
    static testMethod void testMethod1() 
    {
        Address__c currAddress = new Address__c();
        currAddress.Name	= 'Test';
        Account currAccount = new Account();
        currAccount.name = 'Test';
        try{
        	insert currAddress;  
            Insert currAccount;
        }Catch(Exception ex){
            
        }
        List<User_Address__c> userAddressList = new List<User_Address__c>();
        for(Integer i=0 ;i <200;i++)
        {
            User_Address__c userAddress = new User_Address__c();
            userAddress.Address__c =currAddress.id;
            userAddress.UserAccount__c =currAccount.id;            
            userAddressList.add(userAddress);
        }
        try{
            insert userAddressList;
        }catch(exception ex){
        	    
        }
        
        
        Test.startTest();

            UpdateDelivery obj = new UpdateDelivery();
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
    }
}