force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Appointment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Home Service</relationshipLabel>
    <relationshipName>Home_Service</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Home Services</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <label>Installation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Installation</relationshipLabel>
    <relationshipName>Installation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Form__c/Lead_Form__c.object-meta.xml
<CustomObject>
    <label>Lead Form</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Home_Service_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/webForm__c/webForm__c.object-meta.xml
<CustomObject>
    <label>Web Form</label>
    <nameField>
        <label>webForm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/webForm__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Web Forms</relationshipLabel>
    <relationshipName>Web_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/webForm__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Web Forms</relationshipLabel>
    <relationshipName>Web_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MagicSMS.cls
/*
 * Diaco
 * @author             Jull Quintero D
 * Project:            SMS
 * Description:        Create Magic SMS
 *
 * Changes (Version)
 * _________________________________________
 *            No.        Date            Author                    Description
 *            ____    __________        __________________      _____________________________________
 * @version   1.0    02/12/2020         Jull Quintero D          Initial implementation of the class.
 **/
public class MagicSMS {
    public static List<smagicinteract__smsMagic__c> listSmsMagics = new List<smagicinteract__smsMagic__c>();
    
    private static Id ownerId;
    private static Id getOwnerId 
    {
        get{
            User[] user = [SELECT Id FROM User WHERE Name='Cody Garrett' limit 1];
            if( !user.isEmpty() ) ownerId = user[0].Id;
            return ownerId;
        }
    }

    private Id parentId{get;set;}
    private String senderId{get;set;}
    private Id templateId{get;set;} 
    private String SMSText{get;set;}
    private String mobileNumber{get;set;}
    private String source{get;set;}

    /*@Author: Jull Q Daza - 2/12/2020
     * This Constructor is Responsible to Create Magic SMS
     * 
     * This method is used in:
     * Constructor class CreateSMS
     * 
     *@param Id (record Id)
     *@param String (Sender Id) 
     *@param Id (Template Id)
     *@param String (SMSText ) 
     *@param String (Mobile Phone Number)
     *@param String (source)
     */
    public MagicSMS(Id parentId,String senderId,Id templateId,String SMSText,String mobileNumber,String source) {
        this.parentId = parentId;
        this.senderId = senderId;
        this.templateId = templateId;
        this.SMSText = SMSText;
        this.mobileNumber = mobileNumber;
        this.source = source;
        
        smagicinteract__smsMagic__c  sms = new smagicinteract__smsMagic__c(); 

        String objectName =  this.parentId.getSobjectType().getDescribe().getName();
        if( objectName == 'Home_Services__c' ) { sms.Home_Service__c = this.parentId;} else if( objectName == 'Installation__c' ) { sms.Installation__c = this.parentId;}
        else if( objectName == 'Account' ) { sms.smagicinteract__Account__c = this.parentId;} else if( objectName == 'Appointment__c'){sms.appointment__c = this.parentId;}
        else if( objectName == 'Lead_Form__c') { sms.lead_form__c = this.parentId;} else if( objectName == 'Service__c' ) { sms.Service__c = this.parentId;}
        else if( objectName == 'User_Address__c') { sms.user_address__c = this.parentId; } else if( objectName == 'webForm__c' ) { sms.webform__c = this.parentId;}
        sms.smagicinteract__SenderId__c = this.senderId;

        if( String.isNotBlank(this.SMSText) ) {
            sms.smagicinteract__SMSText__c = this.SMSText;
        }else {
            sms.smagicinteract__SMS_Template__c = this.templateId;
        }
        sms.smagicinteract__PhoneNumber__c = this.mobileNumber;
        sms.smagicinteract__Source__c = this.source;

        sms.smagicinteract__ObjectType__c = objectName;  
        sms.OwnerId = ownerId == null ? getOwnerId : ownerId;
        
        listSmsMagics.add(sms);
    }
}