force-app/main/default/objects/Account/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Confirmation_Call_Count__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Call_Count__c</fullName>
    <label>Confirmation Call Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Confirmation_Call_Notes__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Call_Notes__c</fullName>
    <label>Confirmation Call Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Confirmation_Call_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Call_Status__c</fullName>
    <label>Confirmation Call Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed Call</fullName>
            </value>
            <value>
                <fullName>Attempted Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Phone_Number_1__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_1__c</fullName>
    <formula>Account__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone Number 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/SMS_Notification_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SMS Notification Status</description>
    <label>SMS Notification Status</label>
</CustomObject>

force-app/main/default/objects/SMS_Notification_Status__c/fields/conditions__c.field-meta.xml
<CustomField>
    <fullName>conditions__c</fullName>
    <description>possible values OR, AND,CUSTOM_lOGIC</description>
    <inlineHelpText>possible values OR, AND,CUSTOM_lOGIC</inlineHelpText>
    <label>conditions</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Customize_Logic__c.field-meta.xml
<CustomField>
    <fullName>Customize_Logic__c</fullName>
    <description>Customize the logic for the filter conditions that you specified. For example: 1 &amp;&amp;  (2 || 3)</description>
    <inlineHelpText>Customize the logic for the filter conditions that you specified. For example: 1 &amp;&amp; (2 || 3)</inlineHelpText>
    <label>Customize Logic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Diaco_SenderId__c.field-meta.xml
<CustomField>
    <fullName>Diaco_SenderId__c</fullName>
    <label>Diaco SenderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Diaco_TemplateId__c.field-meta.xml
<CustomField>
    <fullName>Diaco_TemplateId__c</fullName>
    <label>Diaco TemplateId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_SenderId__c.field-meta.xml
<CustomField>
    <fullName>Magic_SenderId__c</fullName>
    <label>Magic SenderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_Source__c.field-meta.xml
<CustomField>
    <fullName>Magic_Source__c</fullName>
    <label>Magic Source</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_TemplateId__c.field-meta.xml
<CustomField>
    <fullName>Magic_TemplateId__c</fullName>
    <label>Magic TemplateId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Object_ApiName__c.field-meta.xml
<CustomField>
    <fullName>Object_ApiName__c</fullName>
    <label>Object ApiName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/ParentId_ApiName__c.field-meta.xml
<CustomField>
    <fullName>ParentId_ApiName__c</fullName>
    <label>ParentId ApiName</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/PhoneNumber_ApiName__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber_ApiName__c</fullName>
    <label>PhoneNumber ApiName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/SMSText__c.field-meta.xml
<CustomField>
    <fullName>SMSText__c</fullName>
    <description>Text Message</description>
    <inlineHelpText>You&apos;ll ignore the Template Id when If this field is populated</inlineHelpText>
    <label>SMSText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Confirmation_Number__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Number__c</fullName>
    <description>It holds the confirmation number of the account. And it should be greater than lead id value.</description>
    <externalId>true</externalId>
    <label>Confirmation Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DiacoSMSCallAttemptController.cls
/**
* Diaco
* @author             Jull Quintero D
* Project:            SMS Security campaing
* Description:        Show Call attempt count so Agent can determine when to send out SMS.
* TestClass:          DiacoSMSCallAttemptControllerTest
*
* Changes (Version)
* _________________________________________
*            No.        Date            Author                    Description
*            ____    __________        __________________      _____________________________________
* @version    1.0   17/02/2021         Jull Quintero D          Initial implementation of the class.
 **/

public with sharing class DiacoSMSCallAttemptController {
    @AuraEnabled
    public static WrappedResponse getData(string confirmationNum) {
        WrappedResponse response = new WrappedResponse();

        // user adders
        User_Address__c[] uAddress =  [SELECT Id,Confirmation_Number__c,UserAccount__c FROM User_Address__c WHERE Confirmation_Number__c=:confirmationNum ORDER BY CreatedDate DESC LIMIT 1];

        if( !uAddress.isEmpty() ) {
            Id accountId = uAddress[0].UserAccount__c;
            // Account
            Account[] accounts = [SELECT Id,Name,FirstName,LastName
                                FROM Account 
                                WHERE Id=:accountId LIMIT 1];
            // Home services
            Map<Id,RecordType> HomeAutomationIds = new Map<Id,RecordType>([SELECT Id, Name FROM RecordType WHERE sObjectType = 'Home_Services__c' AND NAME LIKE '%Home Automation%']);

            Home_Services__c[] homeServices = [SELECT Id,Name,Phone_Number_1__c,Confirmation_Call_Count__c,Confirmation_Call_Notes__c, Confirmation_Call_Status__c FROM Home_Services__c WHERE Account__c = :accountId AND RecordTypeId IN :HomeAutomationIds.keySet() ORDER BY CreatedDate DESC];
            
            if ( !accounts.isEmpty() ) {
                response.account = accounts[0];
                response.homeServices = homeServices;
                response.success = true;
                return response;
            }
        } 
        response.success = false; response.message = 'Home Service Not Found';
        return response;
    }

    @AuraEnabled
    public static WrappedResponse sendSMSTo(Home_Services__c homeService) {
        WrappedResponse response = new WrappedResponse();
        List<SMS_Notification_Status__c> activeNots = [SELECT Id,Name,ParentId_ApiName__c,Active__c,Category__c,Diaco_SenderId__c,
                                                            Diaco_TemplateId__c,Magic_SenderId__c,Magic_Source__c,Magic_TemplateId__c,
                                                            conditions__c,Customize_Logic__c,Object_ApiName__c,PhoneNumber_ApiName__c,
                                                            Provider__c,Type__c,SMSText__c
                                                        FROM SMS_Notification_Status__c
                                                        WHERE Name = 'OB Security Campaign' AND Active__c = true];

        if ( !activeNots.isEmpty() && homeService != null ) {
            try {
                SMS_Notification_Status__c notification = activeNots[0];
                CreateSMS.makeSMS(homeService,notification);
                CreateSMS.sendSMS();
                response.success = true; response.message = 'The SMS has been sent successfully';
            } catch (Exception e) {
                response.success = false; response.message = e.getMessage();
            }
        }else {
            response.success = false; response.message = 'SMS OB Security Campaig Not Found';
        }
        return response;
    }

    public class WrappedResponse {
        @AuraEnabled
        public Home_Services__c[] homeServices{get;set;}
        @AuraEnabled
        public Account account{get;set;}
        @AuraEnabled
        public Boolean success{get;set;}
        @AuraEnabled
        public String message{get;set;}
    }
}