force-app/main/default/objects/Account/fields/Verbal_Consent__c.field-meta.xml
<CustomField>
    <fullName>Verbal_Consent__c</fullName>
    <label>Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <color>#33CC00</color>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
                <color>#FF0000</color>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TCPA_Compliance__c/TCPA_Compliance__c.object-meta.xml
<CustomObject>
    <description>It is a custom object</description>
    <label>TCPA Compliance</label>
    <nameField>
        <label>TCPA Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TCPA Compliances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TCPA_Compliance__c/fields/Call_Center_Agent__c.field-meta.xml
<CustomField>
    <fullName>Call_Center_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Call Center Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TCPA_Compliances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TCPA_Compliance__c/fields/User_Account__c.field-meta.xml
<CustomField>
    <fullName>User_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TCPA Compliances (User Account)</relationshipLabel>
    <relationshipName>TCPA_Compliances1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verbal_Consent__c/Verbal_Consent__c.object-meta.xml
<CustomObject>
    <description>This object will holds the verbal consents records</description>
    <label>Verbal Consent</label>
    <nameField>
        <displayFormat>VC-{0000}</displayFormat>
        <label>Verbal Consent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verbal Consents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TCPAComplianceHandler.cls
Public class TCPAComplianceHandler
{
  
    public Static void CreateTCPACompliance(Map<Id,Account> newAccountMap)
    {
        List<TCPA_Compliance__c> ewcComplianceList = new List<TCPA_Compliance__c>();
        Set<Id> accountIds = new Set<Id>();
        Id ecwRTId= Schema.SObjectType.TCPA_Compliance__c.RecordTypeInfosByName.get('Express Written Consent').RecordTypeId;
        for(Account currAccount : newAccountMap.values())
        {
              
            TCPA_Compliance__c newEBRTCPA = new TCPA_Compliance__c();
          
           
            newEBRTCPA.RecordTypeId = ecwRTId;
            newEBRTCPA.Name =currAccount.FirstName+' '+ currAccount.LastName +'- EWC -' + currAccount.verbal_consent__c;
            newEBRTCPA.User_Account__c = currAccount.id;
            newEBRTCPA.Call_Center_Agent__c= userinfo.getUserId();
            newEBRTCPA.Is_Active__c = True;
            ewcComplianceList.add(newEBRTCPA);
            accountIds.add(currAccount.id);
            
            
        }
        
        if(ewcComplianceList.size() > 0)
        {
           
            
            List<TCPA_Compliance__c> updatExTCPARecords = new List<TCPA_Compliance__c>();
            updatExTCPARecords  = [SELECT Id,is_Active__c FROM TCPA_Compliance__c WHERE  User_Account__c IN :accountIds AND RecordTypeId = :ecwRTId AND is_Active__c=True];
            for(TCPA_Compliance__c updteRec : updatExTCPARecords)
            {
                updteRec.is_Active__c = False;
            }
          
           Update updatExTCPARecords; 
           insert ewcComplianceList;
        }
    
    }
    
   



}