force-app/main/default/objects/Account/fields/Verbal_Consent__c.field-meta.xml
<CustomField>
    <fullName>Verbal_Consent__c</fullName>
    <label>Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <color>#33CC00</color>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
                <color>#FF0000</color>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <formula>DATEVALUE( Appointment_Date_Time__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Appointment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Appointment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date_Time__c</fullName>
    <label>Appointment Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Appt_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Appt_End_Time__c</fullName>
    <label>Appt End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Appt_Window_Time__c.field-meta.xml
<CustomField>
    <fullName>Appt_Window_Time__c</fullName>
    <formula>IF( 
ISBLANK(Appointment_Date_Time__c ),&quot;&quot;, 

IF( 
OR( 
VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24), 12, 2 ) ) = 0, 
VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24 ), 12, 2 ) ) = 12 
), 
&quot;12&quot;, 
TEXT( VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24), 12, 2 ) ) 
- 
IF( 
VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24), 12, 2 ) ) &lt; 12, 
0, 
12 
) 
) 
) 
&amp; &quot;:&quot; &amp; 
MID( TEXT(  Appointment_Date_Time__c  - 7/24 ), 15, 2 ) 
&amp; &quot; &quot; &amp; 
IF( 
VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24), 12, 2 ) ) &lt; 12, 
&quot;AM&quot;, 
&quot;PM&quot;) 

+ &quot; - &quot; + 

IF( 
OR( 
VALUE( MID( TEXT( Appt_End_Time__c - 7/24), 12, 2 ) ) = 0, 
VALUE( MID( TEXT( Appt_End_Time__c - 7/24 ), 12, 2 ) ) = 12 
), 
&quot;12&quot;, 
TEXT( VALUE( MID( TEXT( Appt_End_Time__c - 7/24), 12, 2 ) ) 
- 
IF( 
VALUE( MID( TEXT( Appt_End_Time__c - 7/24), 12, 2 ) ) &lt; 12, 
0, 
12 
) 
) 
) 
&amp; &quot;:&quot; &amp; 
MID( TEXT( Appt_End_Time__c - 7/24 ), 15, 2 ) 
&amp; &quot; &quot; &amp; 
IF( 
VALUE( MID( TEXT( Appt_End_Time__c - 7/24), 12, 2 ) ) &lt; 12, 
&quot;AM&quot;, 
&quot;PM&quot; 
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Appt Window Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Automatic_Text_Confirmation_C__c.field-meta.xml
<CustomField>
    <fullName>Automatic_Text_Confirmation_C__c</fullName>
    <formula>IF(  $Setup.Text_Settings_Appt__c.Sale_Confirmation_C_Home_Automation__c  = TRUE, 
&quot;Home Automation&quot;+BR(),&quot;&quot;)+ 
IF(  $Setup.Text_Settings_Appt__c.Sale_Confirmation_C_Pest_Control__c  = TRUE, &quot;Pest Control&quot;+BR(),&quot;&quot;)+ 
IF(  $Setup.Text_Settings_Appt__c.Sale_Confirmation_C_Solar__c  = TRUE,&quot;Solar&quot;+BR(),&quot;&quot;)+ 
IF(  $Setup.Text_Settings_Appt__c.Sale_Confirmation_C_Water__c  = TRUE,&quot;Water&quot;+BR(),&quot;&quot;)+ 
IF(  $Setup.Text_Settings_Appt__c.Sale_Confirmation_C_Window__c  =TRUE,&quot;Remodel&quot;+BR(),&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Automatic Text - Confirmation &quot;C&quot;</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Confirmation_Call_Count__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Call_Count__c</fullName>
    <label>Confirmation Call Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.FirstName),&apos;&apos;,Account__r.FirstName)</formula>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Industry_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Industry_Company_Name__c</fullName>
    <formula>IF( 
CONTAINS( RecordType.Name , &quot;Home Automation&quot; ), &quot;Protection Source&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Solar&quot; ), &quot;N-Ergy&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Water&quot; ), &quot;Aqua Bright Water&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Remodel&quot; ), &quot;Latch&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Pest Control&quot; ), &quot;Jax Pro Pest&quot;, 
RecordType.Name)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry Company Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Industry_Formula__c.field-meta.xml
<CustomField>
    <fullName>Industry_Formula__c</fullName>
    <formula>IF(
CONTAINS( RecordType.Name , &quot;Home Automation&quot; ), &quot;Home Automation&quot;, 
IF(
CONTAINS(RecordType.Name, &quot;Solar&quot; ), &quot;Solar&quot;,
IF(
CONTAINS(RecordType.Name, &quot;Water&quot; ), &quot;Water Treatment&quot;,
IF(
CONTAINS(RecordType.Name, &quot;Remodel&quot; ), &quot;Remodel&quot;,
IF(
CONTAINS(RecordType.Name, &quot;Pest Control&quot; ), &quot;Pest Control&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Carpet &amp; Tile Cleaning&quot; ), &quot;Carpet &amp; Tile Cleaning&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Flooring&quot; ), &quot;Flooring&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Garage Doors&quot; ), &quot;Garage Doors&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Garage Floor Coating&quot; ), &quot;Garage Floor Coating&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Handy Man&quot; ), &quot;Handy Man&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Internet-Cable-Satellite&quot; ), &quot;Internet-Cable-Satelite&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Kitchen &amp; Bath&quot; ), &quot;Kitchen &amp; Bath&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Lock Smith&quot; ), &quot;Lock Smith&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Maid Service&quot; ), &quot;Maid Service&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Painting&quot; ), &quot;Painting&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Pool Maintenance&quot; ), &quot;Pool Maintenance&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;HVAC&quot; ), &quot;HVAC&quot;, 
&quot;&quot;)))))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry:</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Phone_Number_1__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_1__c</fullName>
    <formula>Account__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone Number 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/SMS_Notification_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SMS Notification Status</description>
    <label>SMS Notification Status</label>
</CustomObject>

force-app/main/default/objects/SMS_Notification_Status__c/fields/conditions__c.field-meta.xml
<CustomField>
    <fullName>conditions__c</fullName>
    <description>possible values OR, AND,CUSTOM_lOGIC</description>
    <inlineHelpText>possible values OR, AND,CUSTOM_lOGIC</inlineHelpText>
    <label>conditions</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Customize_Logic__c.field-meta.xml
<CustomField>
    <fullName>Customize_Logic__c</fullName>
    <description>Customize the logic for the filter conditions that you specified. For example: 1 &amp;&amp;  (2 || 3)</description>
    <inlineHelpText>Customize the logic for the filter conditions that you specified. For example: 1 &amp;&amp; (2 || 3)</inlineHelpText>
    <label>Customize Logic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Diaco_SenderId__c.field-meta.xml
<CustomField>
    <fullName>Diaco_SenderId__c</fullName>
    <label>Diaco SenderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Diaco_TemplateId__c.field-meta.xml
<CustomField>
    <fullName>Diaco_TemplateId__c</fullName>
    <label>Diaco TemplateId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_SenderId__c.field-meta.xml
<CustomField>
    <fullName>Magic_SenderId__c</fullName>
    <label>Magic SenderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_Source__c.field-meta.xml
<CustomField>
    <fullName>Magic_Source__c</fullName>
    <label>Magic Source</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_TemplateId__c.field-meta.xml
<CustomField>
    <fullName>Magic_TemplateId__c</fullName>
    <label>Magic TemplateId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Object_ApiName__c.field-meta.xml
<CustomField>
    <fullName>Object_ApiName__c</fullName>
    <label>Object ApiName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/ParentId_ApiName__c.field-meta.xml
<CustomField>
    <fullName>ParentId_ApiName__c</fullName>
    <label>ParentId ApiName</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/PhoneNumber_ApiName__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber_ApiName__c</fullName>
    <label>PhoneNumber ApiName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/SMSText__c.field-meta.xml
<CustomField>
    <fullName>SMSText__c</fullName>
    <description>Text Message</description>
    <inlineHelpText>You&apos;ll ignore the Template Id when If this field is populated</inlineHelpText>
    <label>SMSText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/SMS_Send_Condition__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SMS Send Condition</description>
    <label>SMS Send Condition</label>
</CustomObject>

force-app/main/default/objects/SMS_Send_Condition__c/fields/Compare_Static_Operation__c.field-meta.xml
<CustomField>
    <fullName>Compare_Static_Operation__c</fullName>
    <description>COMPAREC possible values ==, !=, &lt;, &lt;=, &gt;, &gt;=
FIND_BY_RECORDTYPE possible values Field Apiname&gt; Example: Id, Account.</description>
    <inlineHelpText>https://github.com/jdcrensh/apex-evalex</inlineHelpText>
    <label>Compare Static Operation / Field ApiName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/fields/Compare_Static_Value__c.field-meta.xml
<CustomField>
    <fullName>Compare_Static_Value__c</fullName>
    <label>Compare Static Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/fields/Condition_Type__c.field-meta.xml
<CustomField>
    <fullName>Condition_Type__c</fullName>
    <description>possible values CHANGEC, COMPAREC,FIND_BY_RECORDTYPE,CONTAINS,ISNULL,ISNOTNULL</description>
    <inlineHelpText>possible values CHANGEC, COMPAREC,FIND_BY_RECORDTYPE,CONTAINS,ISNULL,ISNOTNULL</inlineHelpText>
    <label>Condition Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <label>FieldApiName</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/fields/Notification_Id__c.field-meta.xml
<CustomField>
    <fullName>Notification_Id__c</fullName>
    <description>Notification Id</description>
    <label>Notification Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <description>When Notification condition equals Custom Logic</description>
    <inlineHelpText>1</inlineHelpText>
    <label>Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <label>ObjectApiName</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verbal_Consent__c/Verbal_Consent__c.object-meta.xml
<CustomObject>
    <description>This object will holds the verbal consents records</description>
    <label>Verbal Consent</label>
    <nameField>
        <displayFormat>VC-{0000}</displayFormat>
        <label>Verbal Consent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verbal Consents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Verbal_Consent__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This filed will give the information about the verbal consents whether it is active or not</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DiacoSMSettingsTest.cls
@isTest
public class DiacoSMSettingsTest {
    @TestSetup
    static void makeData(){
        confirmationCall();
    }

    public static void confirmationCall() {
        List<dsms__Phone_Number__c> diacoPhoneNumberSMS = new List<dsms__Phone_Number__c>();
        List<String> diacoNamesSMS = new List<String>{'Water','Pest','Remodel','HA','Solar'};
        Integer diacoNamesLgth = diacoNamesSMS.size();
        for (Integer i = 0; i < diacoNamesLgth; i++) {
            diacoPhoneNumberSMS.add(
                new dsms__Phone_Number__c(
                Name=diacoNamesSMS[i],
                Slack_Channel__c = 'test-slack',
                dsms__Active__c = true,
                dsms__Country_Code__c = '1',
                dsms__Phone_Number__c = '+123456789' + i)
            );
        }
        upsert diacoPhoneNumberSMS;

        // magic sender id
        List<smagicinteract__SMS_SenderId__c> magicSerderIdSMS = new List<smagicinteract__SMS_SenderId__c>();
        List<String> magicLabels = new List<String>{'Sales:Water','Sales:Pest','Sales:Remodel','Sales:HA','Sales:Solar'};
        Integer magicLabelLgth = magicLabels.size();
        for (Integer j = 0; j < magicLabelLgth; j++) {
            magicSerderIdSMS.add(
                new smagicinteract__SMS_SenderId__c(
                smagicinteract__senderId__c = '1480800079'+j,
                smagicinteract__Label__c = magicLabels[j])
            );
        }
        upsert magicSerderIdSMS;

        // Magic template
        List<smagicinteract__SMS_Template__c> magicTemplates = new List<smagicinteract__SMS_Template__c>();
        List<String> magicNamesTemplates = new List<String>{'Sales Appt Confirmation "C"'};
        Integer magicNamesTLgth = magicNamesTemplates.size();
        for (Integer t = 0; t < magicNamesTLgth; t++) {
            magicTemplates.add(
                new smagicinteract__SMS_Template__c(
                    smagicinteract__Name__c = magicNamesTemplates[t],
                    smagicinteract__Text__c = 'test'+t
                )
            );
        }
        upsert magicTemplates;

        //SMS Notification Status
        List<SMS_Notification_Status__c> notifications = new List<SMS_Notification_Status__c>();
        for (Integer z = 0; z < diacoNamesLgth; z++) {
            String conditions; String customLogic;
            if( diacoNamesSMS[z] == 'Water' ) {
                conditions = 'CUSTOM_lOGIC';
                customLogic = '1 && 2';
            }else if( diacoNamesSMS[z] == 'Pest' ){
                conditions = 'OR';
            }else {
                conditions = 'AND';
            }
            notifications.add(
                new SMS_Notification_Status__c (
                    Name='test'+z,
                    ParentId_ApiName__c = 'Id',
                    conditions__c = conditions,
                    Customize_Logic__c = customLogic,
                    Active__c = true,
                    Category__c = diacoNamesSMS[z],
                    Diaco_SenderId__c = diacoPhoneNumberSMS[z].dsms__Phone_Number__c,
                    Diaco_TemplateId__c = magicTemplates[0].Id,
                    Magic_SenderId__c = magicSerderIdSMS[z].smagicinteract__senderId__c,
                    Magic_Source__c = '12345',
                    Magic_TemplateId__c = magicTemplates[0].Id,
                    Object_ApiName__c = 'Home_Services__c',
                    PhoneNumber_ApiName__c = 'Phone_Number_1__c',
                    Provider__c = 'Diaco SMS',
                    Type__c = 'test'
                )
            );
        }

        upsert notifications;

        // SMS Send Condition
        List<SMS_Send_Condition__c> conditions = new List<SMS_Send_Condition__c>();
        integer notificationsLgth = notifications.size();
        for (Integer r = 0; r < notificationsLgth; r++) {
            conditions.add(
                new SMS_Send_Condition__c(
                    Name = 'COMPAREC'+r,
                    Number__c = r,
                    IsUpdate__c = true,
                    Notification_Id__c = notifications[r].Id,
                    FieldApiName__c = 'Confirmation_Call_Count__c',
                    Compare_Static_Operation__c = '==',
                    Compare_Static_Value__c = '5',
                    Condition_Type__c = 'COMPAREC',
                    ObjectApiName__c = 'Home_Services__c'
                )
            );
            conditions.add(
                new SMS_Send_Condition__c(
                    Name = 'CHANGEC'+r,
                    Number__c = r,
                    IsUpdate__c = true,
                    Notification_Id__c = notifications[r].Id,
                    FieldApiName__c = 'Confirmation_Call_Count__c',
                    Condition_Type__c = 'CHANGEC',
                    ObjectApiName__c = 'Home_Services__c'
                )
            );
            conditions.add(
                new SMS_Send_Condition__c(
                    Name = 'FIND_BY_RECORDTYPE'+r,
                    Number__c = r,
                    Compare_Static_Operation__c = 'Id',
                    IsUpdate__c = true,
                    Notification_Id__c = notifications[r].Id,
                    FieldApiName__c = 'RecordTypeId',
                    Compare_Static_Value__c = 'Solar',
                    Condition_Type__c = 'FIND_BY_RECORDTYPE',
                    ObjectApiName__c = 'Home_Services__c'
                )
            );
            conditions.add(
                new SMS_Send_Condition__c(
                    Name = 'CONTAINS'+r,
                    Number__c = r,
                    IsUpdate__c = true,
                    Notification_Id__c = notifications[r].Id,
                    FieldApiName__c = 'Name',
                    Compare_Static_Value__c = 'test',
                    Condition_Type__c = 'CONTAINS',
                    ObjectApiName__c = 'Home_Services__c'
                )
            );
            conditions.add(
                new SMS_Send_Condition__c(
                    Name = 'ISNOTNULL'+r,
                    Number__c = r,
                    IsUpdate__c = true,
                    Notification_Id__c = notifications[r].Id,
                    FieldApiName__c = 'Account__c',
                    Condition_Type__c = 'ISNOTNULL',
                    ObjectApiName__c = 'Home_Services__c'
                )
            );
            conditions.add(
                new SMS_Send_Condition__c(
                    Name = 'ISNULL'+r,
                    Number__c = r,
                    IsUpdate__c = true,
                    Notification_Id__c = notifications[r].Id,
                    FieldApiName__c = 'Appt_End_Time__c',
                    Condition_Type__c = 'ISNULL',
                    ObjectApiName__c = 'Home_Services__c'
                )
            );            
        }
        upsert conditions;
    }

    public static void consentCanvasser() {
        List<dsms__Phone_Number__c> diacoPhoneNumberSMS = new List<dsms__Phone_Number__c>();
        List<String> diacoNamesSMS = new List<String>{'Consent'};
        Integer diacoNamesLgth = diacoNamesSMS.size();
        for (Integer i = 0; i < diacoNamesLgth; i++) {
            diacoPhoneNumberSMS.add(
                new dsms__Phone_Number__c(
                Name=diacoNamesSMS[i],
                Slack_Channel__c = 'test-slack',
                dsms__Active__c = true,
                dsms__Country_Code__c = '1',
                dsms__Phone_Number__c = '+123456789' + i)
            );
        }
        upsert diacoPhoneNumberSMS;

        // magic sender id
        List<smagicinteract__SMS_SenderId__c> magicSerderIdSMS = new List<smagicinteract__SMS_SenderId__c>();
        List<String> magicLabels = new List<String>{'Consent'};
        Integer magicLabelLgth = magicLabels.size();
        for (Integer j = 0; j < magicLabelLgth; j++) {
            magicSerderIdSMS.add(
                new smagicinteract__SMS_SenderId__c(
                smagicinteract__senderId__c = '1480800079'+j,
                smagicinteract__Label__c = magicLabels[j])
            );
        }
        upsert magicSerderIdSMS;

        //SMS Notification Status
        SMS_Notification_Status__c notification = new SMS_Notification_Status__c (
            Name='Consent Canvasser',
            ParentId_ApiName__c = 'Id',
            conditions__c = 'AND',
            Active__c = true,
            Diaco_SenderId__c = diacoPhoneNumberSMS[0].dsms__Phone_Number__c,
            Magic_SenderId__c = magicSerderIdSMS[0].smagicinteract__senderId__c,
            Magic_Source__c = '12345',
            Object_ApiName__c = 'Account',
            PhoneNumber_ApiName__c = 'Phone',
            Provider__c = 'Diaco SMS',
            Type__c = 'test',
            SMSText__c = 'test'
        );

        upsert notification;
    }

    public static void OBSecurityCampaign() {

        // Diaco Template
        dsms__Template__c diacoTemplateSms = new dsms__Template__c(
            Name = 'OBSecurity',
            dsms__Message__c = 'test',
            dsms__Primary_Object__c = 'Home_Services__c'
        );
        
        upsert diacoTemplateSms;

        // Diaco Sender Id
        dsms__Phone_Number__c diacoPhoneNumber = new dsms__Phone_Number__c(
            Name='OBSecuritySenderId',
            Slack_Channel__c = 'test-slack',
            dsms__Active__c = true,
            dsms__Country_Code__c = '1',
            dsms__Phone_Number__c = '+123456789'
        );
        upsert diacoPhoneNumber;

        // Magic template
        smagicinteract__SMS_Template__c magicTemplateSMS = new smagicinteract__SMS_Template__c(
            smagicinteract__Name__c = 'OBSecuritySenderId',
            smagicinteract__Text__c = 'test'
        );
        upsert magicTemplateSMS;

        // magic sender id
        smagicinteract__SMS_SenderId__c magicSerderId = new smagicinteract__SMS_SenderId__c(
            smagicinteract__senderId__c = '1480800079',
            smagicinteract__Label__c = 'OBSecuritySenderID');
        upsert magicSerderId;

        //SMS Notification Status
        SMS_Notification_Status__c notification = new SMS_Notification_Status__c (
            Name='OB Security Campaign',
            ParentId_ApiName__c = 'Id',
            conditions__c = 'AND',
            Active__c = true,
            Diaco_TemplateId__c = diacoTemplateSms.Id,
            Diaco_SenderId__c = diacoPhoneNumber.dsms__Phone_Number__c,
            Magic_TemplateId__c = magicTemplateSMS.Id,
            Magic_SenderId__c =magicSerderId.smagicinteract__senderId__c,
            Magic_Source__c = '12345',            
            Object_ApiName__c = 'Home_Services__c',
            PhoneNumber_ApiName__c = 'Phone_Number_1__c',
            Provider__c = 'Diaco SMS' );

        upsert notification;
    }

    @IsTest
    static void test() {
        
        Test.startTest();

            Id personAcctRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
            Account account = new Account(
                FirstName='test',
                BillingState = 'CA', LastName = 'Pass v2',
                RecordTypeId = personAcctRecordTypeId,
                PersonDoNotCall =True,
                Verbal_Consent__c='No',
                phone='1234567890');
            insert account;

            Id hsSolarSL = Schema.SObjectType.Home_Services__c.getRecordTypeInfosByName().get('Solar Sales').getRecordTypeId();
            Home_Services__c hs = new Home_Services__c(
                    Name                          = '',
                    Account__c                    = account.Id,
                    Recordtypeid                  = hsSolarSL,
                    Appointment_Date_Time__c      = Datetime.now(),
                    Appt_End_Time__c              = null
                    
                );
            insert hs;

            // getConditionsToEvaluate
            DiacoSMSettings.NotCondData notCondactives = DiacoSMSettings.getConditionsToEvaluate('Home_Services__c',false,true);
            DiacoSMSettings.getConditionsToEvaluate('Home_Services__c',true,false);

            System.assertNotEquals(notCondactives.conditionsByNot.values().size(), 0);
            // evaluateConditions
            Map<Id,Home_Services__c>  oldHServiceMap = new Map<Id,Home_Services__c>([SELECT Id,Name,Account__c,RecordTypeId,Appointment_Date_Time__c,Appt_End_Time__c,First_Name__c,Appointment_Date__c,Industry_Company_Name__c,Industry_Formula__c,Confirmation_Call_Count__c,Phone_Number_1__c,Appt_Window_Time__c,Automatic_Text_Confirmation_C__c FROM Home_Services__c]);
            List<Home_Services__c> oldHS = oldHServiceMap.values();
            List<Home_Services__c> currentHS = new List<Home_Services__c>();

            Integer oldHSLength = oldHS.size();
            for (Integer i = 0; i < oldHSLength; i++) {
                Home_Services__c old = oldHS[i];
                Home_Services__c current = old.clone();
                current.Id = old.Id;
                current.Confirmation_Call_Count__c = 5;
                currentHS.add(current);
            }
            List<SMS_Send_Condition__c> conditions = notCondactives.conditionsByNot.values()[0];
            SMS_Notification_Status__c notification = notCondactives.notifications.get(conditions[0].Notification_Id__c);
            DiacoSMSettings.evaluateConditions(notification,conditions,currentHS[0],oldHS[0],true);
            System.assertEquals( DiacoSMSettings.containsRecordtype(currentHS[0].Id,currentHS[0].RecordTypeId,'Solar'), true);

            // getParentNames
            Set<Id> parentIds = new Set<Id>{hs.Id,account.Id};
            DiacoSMSettings.getParentNames(parentIds);

            // getDiacoSMSenderSlackChannel
            Set<String> diacoSenderIds = new Set<String>();
            List<dsms__Phone_Number__c> senderIds = [SELECT Id,Name,dsms__Phone_Number__c,dsms__Active__c 
                                                    FROM dsms__Phone_Number__c 
                                                    WHERE dsms__Active__c=true];
            Integer senderIdLength = senderIds.size();
            for (Integer j = 0; j < senderIdLength; j++) {
                diacoSenderIds.add(senderIds[j].dsms__Phone_Number__c);
            }
            DiacoSMSettings.getDiacoSMSenderSlackChannel(diacoSenderIds);
        Test.stopTest();        
    }
}