force-app/main/default/objects/Industry__c/Industry__c.object-meta.xml
<CustomObject>
    <label>Industry</label>
    <nameField>
        <label>Industry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Call_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Call_Disposition__c</fullName>
    <label>Call Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Appointment Set</fullName>
            </value>
            <value>
                <fullName>Appt Set: IB</fullName>
            </value>
            <value>
                <fullName>Appt Set: OB</fullName>
            </value>
            <value>
                <fullName>Appt set: Project Yes</fullName>
            </value>
            <value>
                <fullName>Appt Set and Inventory Created</fullName>
            </value>
            <value>
                <fullName>Transfer: IB</fullName>
            </value>
            <value>
                <fullName>Transfer: OB</fullName>
            </value>
            <value>
                <fullName>Transfer: Project Yes</fullName>
            </value>
            <value>
                <fullName>Business No Answer</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Call Back Appointment</fullName>
            </value>
            <value>
                <fullName>Delivered to Wrong House</fullName>
            </value>
            <value>
                <fullName>Disposition</fullName>
            </value>
            <value>
                <fullName>Dropped while talking</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Failed Transfer</fullName>
            </value>
            <value>
                <fullName>Hang Up</fullName>
            </value>
            <value>
                <fullName>Lead Returned</fullName>
            </value>
            <value>
                <fullName>Left Message</fullName>
            </value>
            <value>
                <fullName>Manager Call</fullName>
            </value>
            <value>
                <fullName>Need a Pro</fullName>
            </value>
            <value>
                <fullName>No Answer</fullName>
            </value>
            <value>
                <fullName>No Email</fullName>
            </value>
            <value>
                <fullName>No Email/Activation</fullName>
            </value>
            <value>
                <fullName>No English</fullName>
            </value>
            <value>
                <fullName>No Gift Box Delivered</fullName>
            </value>
            <value>
                <fullName>No Good</fullName>
            </value>
            <value>
                <fullName>No Home owner</fullName>
            </value>
            <value>
                <fullName>No Network</fullName>
            </value>
            <value>
                <fullName>Not Homeowner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>It will hold the industry value of the survey question and it would map to the Industry values custom settings.</description>
    <label>Industry</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/OB_Campaign_Member__c.field-meta.xml
<CustomField>
    <fullName>OB_Campaign_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OB Campaign Member</label>
    <referenceTo>OB_Campaign_Member__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Status_Post__c.field-meta.xml
<CustomField>
    <fullName>Status_Post__c</fullName>
    <label>Status Post</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OB_Campaign_Member__c/OB_Campaign_Member__c.object-meta.xml
<CustomObject>
    <label>OB Campaign Member</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>OB Campaign Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OB Campaign Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OB_Campaign_Member__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry</label>
    <referenceTo>Industry__c</referenceTo>
    <relationshipLabel>OB Campaign Members</relationshipLabel>
    <relationshipName>OB_Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OB_Campaign_Member__c/fields/Status_Post__c.field-meta.xml
<CustomField>
    <fullName>Status_Post__c</fullName>
    <description>Use for all call centers to post back their disposition.  This field is used for the automation process configuration.</description>
    <label>Status Post</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OB_Campaign_Member__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>OB Campaign Members</relationshipLabel>
    <relationshipName>OB_Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <formula>IF( 
CONTAINS(Profile.Name,&quot;Solar&quot;),&quot;Solar&quot;, 
IF( 
CONTAINS(Profile.Name,&quot;Water&quot;),&quot;Water&quot;, 
IF( 
CONTAINS(Profile.Name,&quot;Window&quot;),&quot;Window&quot;, 
IF( 
CONTAINS(Profile.Name,&quot;Automation&quot;), &quot;Home Automation&quot;, 
IF( 
CONTAINS(Profile.Name,&quot;Pest&quot;), &quot;Pest Control&quot;,&quot;&quot;)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/InventoryTriggerHandler.cls
/****************************************************************
 * Created By : MSTSolutions
 * Description: To update status post field in ob campaign member records 
 * when the appoinment is set for the particular industries
 * 
 * **************************************************************/
public class InventoryTriggerHandler {
    public static void updateOBCMembers(List<Inventory__c> inventoryList){
        Id inventoryOBCRecordtypeId = Schema.SObjectType.Inventory__c.getRecordTypeInfosByName().get('nuHome OB Campaign').getRecordTypeId();
        List<OB_Campaign_Member__c> toUpdateOBC = New List<OB_Campaign_Member__c>();
        Map<Id,Set<String>> inventoryIndustryMap = New Map<Id,Set<String>>();
        for(Inventory__c currInv:inventoryList){
            //Checking the record type and collecting matching inventory records.
            if(inventoryOBCRecordtypeId == currInv.RecordtypeId){
                if((currInv.User_Address__c != Null) && (currInv.Industry__c != '') && (currInv.Call_Disposition__c == 'Appointment Set')){
                    if(inventoryIndustryMap.containsKey(currInv.User_Address__c))
                        inventoryIndustryMap.get(currInv.User_Address__c).add(currInv.Industry__c);
                    else{
                        Set<String> industrySet = New Set<String>();
                        industrySet.add(currInv.Industry__c);
                        inventoryIndustryMap.put(currInv.User_Address__c,industrySet);
                    }
                }
            }
        }
        system.debug('inventoryIndustryMap values '+inventoryIndustryMap);
        if(!inventoryIndustryMap.isEmpty()){
            //Getting all obcampaign member record for the user addresses.
            Map<Id,List<OB_Campaign_Member__c>> userAddressOBCMem = New Map<Id,List<OB_Campaign_Member__c>>();
            for(OB_Campaign_Member__c OBCMem:[SELECT Id,User_Address__c,Industry__r.Name FROM OB_Campaign_Member__c WHERE User_Address__c IN :inventoryIndustryMap.keySet()]){
                if(userAddressOBCMem.containsKey(OBCMem.User_Address__c))
                    userAddressOBCMem.get(OBCMem.User_Address__c).add(OBCMem);
                else{
                    List<OB_Campaign_Member__c> OBCMemList = New List<OB_Campaign_Member__c>();
                    OBCMemList.add(OBCMem);
                    userAddressOBCMem.put(OBCMem.User_Address__c, OBCMemList);
                }
            }
            system.debug('userAddressOBCMem values '+userAddressOBCMem);
            if(!userAddressOBCMem.isEmpty()){
                //Looping through inventory and create update 
                for(Id id:inventoryIndustryMap.keySet()){
                    for(String industry:inventoryIndustryMap.get(id)){
                        if(userAddressOBCMem.containsKey(id)){
                            for(OB_Campaign_Member__c OBCMEMIns:userAddressOBCMem.get(id)){
                                if(OBCMEMIns.Industry__r.Name == industry){
                                    OB_Campaign_Member__c toUpdateOBCMem = New OB_Campaign_Member__c();
                                    toUpdateOBCMem.Id = OBCMEMIns.Id;
                                    toUpdateOBCMem.Status_Post__c = 'Appointment Set';
                                    toUpdateOBC.add(toUpdateOBCMem);
                                }
                            }
                        }
                    }
                }
            }
        }
        
        if(!toUpdateOBC.isEmpty())
            Update toUpdateOBC;
        system.debug('toUpdateOBC values '+toUpdateOBC);
    }
}