force-app/main/default/objects/Door_Tag_Script__c/Door_Tag_Script__c.object-meta.xml
<CustomObject>
    <label>Door Tag Script</label>
    <nameField>
        <displayFormat>Survey-{0000000000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Door Tag Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Door_Tag_Script__c/fields/Create_Task_Update__c.field-meta.xml
<CustomField>
    <fullName>Create_Task_Update__c</fullName>
    <description>It is a custom picklist field</description>
    <label>Create Task Update</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DTS Updated</fullName>
            </value>
            <value>
                <fullName>Email Sent</fullName>
            </value>
            <value>
                <fullName>Task Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Door_Tag_Script__c.field-meta.xml
<CustomField>
    <fullName>Door_Tag_Script__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This filed look up with Door Tag Script</description>
    <label>Door Tag Script</label>
    <referenceTo>Door_Tag_Script__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Lead_Emailed__c.field-meta.xml
<CustomField>
    <fullName>Lead_Emailed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lead Emailed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/nuHome_Email_Task_AC.cls
public class nuHome_Email_Task_AC {
    /* Created by : MSTSolutions
     * Date : 26 March 2016
     * Description : This will create task on when there is any email sent out to consumer after dts has been created or updated.
     * */
    public static void createTask(Map<Id, Door_Tag_Script__c> newMapRecordMap, Map<Id, Door_Tag_Script__c> oldMapRecordMap){
         system.debug('newMapRecordMap value '+newMapRecordMap);
        system.debug('oldMapRecordMap value '+oldMapRecordMap); 
        List<Task> taskList = New List<Task>();
        Set<Id> accountIds = new Set<Id>();
        Map<Id,Account> accountsMap = new Map<Id,Account>();
        List<Door_Tag_Script__c> updateDTS = new List<Door_Tag_Script__c>();
        for(Door_Tag_Script__c doorScript:newMapRecordMap.values()){
            //Filtering Records that has true and previous value false on create task field.
            if(doorScript.Create_Task_Update__c == 'Email Sent'){
               accountIds.add(doorScript.Account__c);
            }
        }
        
        system.debug('accountsMap value'+accountsMap);
        if(accountIds.size() > 0)
        {
            accountsMap.putAll( [SELECT id,personcontactId from Account WHERE Id IN:accountIds AND isPersonAccount = True]);
        }
        system.debug('accountsMap value'+accountsMap);
        for(Door_Tag_Script__c doorScript:newMapRecordMap.values()){
            //Filtering Records that has true and previous value false on create task field.
            if(doorScript.Create_Task_Update__c == 'Email Sent'){
               Door_Tag_Script__c dtsIns = new Door_Tag_Script__c();
                Task taskIns = New Task();
                if(accountsMap.containsKey(doorScript.Account__c))
                    taskIns.whoId = accountsMap.get(doorScript.Account__c).personcontactId;
                
                taskIns.WhatId = doorScript.id;
                taskIns.Status = 'Completed';
                taskIns.Subject = 'Consumer Email Summary Sent';
                taskIns.Priority = 'Normal';
                taskList.add(taskIns);
                dtsIns.Id = doorScript.id;
                dtsIns.Create_Task_Update__c = 'Task Created';
                updateDTS.add(dtsIns);
            }
        }
        
       if(taskList.size() > 0)
       {
           System.debug('taskList value ' + taskList);
           insert taskList;
           
       }
        if(updateDTS.size()>0)
            update updateDTS;
    }
    
    
    // It will create task for Inventory and PA once client email has sent.
    public static void createInventoryTask(Map<Id, Inventory__c> newMapRecordMap, Map<Id, Inventory__c> oldMapRecordMap){
    
      Set<Id> personAccountIds = new Set<Id>();
      Map<Id,Account> accountsMap = new Map<Id,Account>();
      List<Task> taskList = new List<Task>();
      
       for(Inventory__c currInv : newMapRecordMap.values())
       {
           if(currInv.Lead_Emailed__c == True && oldMapRecordMap.get(currInv.id).Lead_Emailed__c == false)
               personAccountIds.add(currInv.account__c);
       }
      
       if(personAccountIds.size() > 0)
        {
            accountsMap.putAll( [SELECT id,personcontactId from Account WHERE Id IN:personAccountIds AND isPersonAccount = True]);
        }
   
       for(Inventory__c currInv : newMapRecordMap.values())
       {
           if(currInv.Lead_Emailed__c == True && oldMapRecordMap.get(currInv.id).Lead_Emailed__c == false)
           {
           
               Task taskIns = New Task();
            
             /*   if(accountsMap.containsKey(currInv.Account__c))
                    taskIns.whoId = accountsMap.get(currInv.Account__c).personcontactId; */
           
                taskIns.WhatId = currInv.id;
                taskIns.Status = 'Completed';
                taskIns.Subject = 'Client Email Summary Sent';
                taskIns.Priority = 'Normal';
                taskList.add(taskIns);

           }

       }
       //DML operation
       if(taskList.size() > 0)
         insert taskList;
    
    }

}