force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field holds the branch details</description>
    <inlineHelpText>Select the branch where the address resides in.</inlineHelpText>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/MSA__c.field-meta.xml
<CustomField>
    <fullName>MSA__c</fullName>
    <label>MSA</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Austin-Round Rock-San Marcos TX</fullName>
            </value>
            <value>
                <fullName>Bakersfield Ca</fullName>
            </value>
            <value>
                <fullName>Dallas-Fort Worth-Arlington TX</fullName>
            </value>
            <value>
                <fullName>Houston-Sugar Land-Baytown TX</fullName>
            </value>
            <value>
                <fullName>Killeen-Temple TX</fullName>
            </value>
            <value>
                <fullName>Los Angeles--Riverside--Orange County Ca</fullName>
            </value>
            <value>
                <fullName>Phoenix-Mesa-Glendale AZ</fullName>
            </value>
            <value>
                <fullName>Provo-Orem Ut</fullName>
            </value>
            <value>
                <fullName>Salt Lake City-Ogden Ut</fullName>
            </value>
            <value>
                <fullName>San Antonio-New Braunfels TX</fullName>
            </value>
            <value>
                <fullName>San Diego-Carlsbad-San Marcos Ca</fullName>
            </value>
            <value>
                <fullName>Tucson AZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <label>Region Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Holds the state information</description>
    <inlineHelpText>Enter the state</inlineHelpText>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Used to store 5 digit zipCode.</description>
    <label>Primary Shipping Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/MSA__c.field-meta.xml
<CustomField>
    <fullName>MSA__c</fullName>
    <label>MSA</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/ZipCode__c.object-meta.xml
<CustomObject>
    <description>It contains all zip codes for the corresponding branches.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipCode__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Zip Codes</relationshipLabel>
    <relationshipName>Zip_code</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/fields/MSA__c.field-meta.xml
<CustomField>
    <fullName>MSA__c</fullName>
    <label>MSA</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZipCode</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/accountZipCodeMapper_Batch.cls
/********************************************************************************************
* Class Name : accountZipCodeMapper_Batch
* Created By : GIT CRM
* Modified By : Priyanka Shanmugam
* Created Date : 29/03/2016
* Author : MST
* Description: Get all the address of invalid zipcodes and populate values in Branch,MSA 
and Region Code fields of address based on the newly added zipcodes in th ezipcode custom object.
**********************************************************************************************/
global class accountZipCodeMapper_Batch implements Database.Batchable<Sobject>{
    global Database.queryLocator start(Database.BatchableContext bc){
        String query = 'SELECT id,Zip_Code__c,Branch__c,MSA__c,Region_Code__c FROM Address__c WHERE Zip_Code__c !=\'\'';
        query+=' AND (Branch__c = null'+' OR MSA__c ='+'\''+'Invalid Zip Code' + '\'' + ' OR Region_Code__c ='+'\''+'Invalid Zip Code' + '\'' +')';
        return Database.getQueryLocator(query); 
    }
    global void execute(Database.BatchableContext bc, List<Address__c> incomingAddress) {
        
        Set<String> zipCodeSet = new Set<String>();
        Map<String,ZipCode__c> zipCodeMap = new Map<String,ZipCode__c>();
        List<Address__c> addressList = new List<Address__c>();
        // Get thezipcodes from the address
        for(Address__c currAddress : incomingAddress){
            zipCodeSet.add(currAddress.Zip_Code__c);                   
        }     
        // Get the zipcode records based on the zipcodes obtained from address
        for(ZipCode__c currZipCode : [SELECT Name,Branch__c,MSA__c,Region_Code__c,State__c FROM ZipCode__c WHERE Name IN :zipCodeSet]){
            zipCodeMap.put(currZipCode.Name,currZipCode);   
        }
        // If the zip code is found on the zipcode object then assign the related branch,MSAand Region code
        for(Address__c currAddress : incomingAddress){              
            if(zipCodeMap.containsKey(currAddress.Zip_Code__c)){                      
                ZipCode__c zipCode = zipCodeMap.get(currAddress.Zip_Code__c);                
                currAddress.Branch__c = zipCode.Branch__c;
                currAddress.MSA__c = zipCode.MSA__c;
                currAddress.Region_Code__c = zipCode.Region_Code__c; 
                addressList.add(currAddress);
            }
        }
        // update the address 
        if(!addressList.isEmpty()){
            try{
                update addressList;
            }
            catch(exception e){
                System.debug('----Error occured while updating the address---'+e.getMessage());
            }
        }
    }
    
    global void finish(Database.BatchableContext bc){
         // Get the ID of the AsyncApexJob representing this batch job  
        // from Database.BatchableContext.Query the AsyncApexJob object to retrieve the current job's information.  
        
        AsyncApexJob asynchronousJob = [SELECT Id, Status,ExtendedStatus,NumberOfErrors, JobItemsProcessed,
                                        TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];       
        if(asynchronousJob.NumberOfErrors > 0){
            // Send an email to the Apex job's submitter to notify the job completion.  
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[] {asynchronousJob.CreatedBy.Email};
            //String[] toAddresses = new String[] {'priyanka@mstsolutions.com'};
            mail.setToAddresses(toAddresses);
            mail.setSubject('ZipCode Based Field Population: ' + asynchronousJob.Status);
            mail.setPlainTextBody('The current job is processed with ' + asynchronousJob.TotalJobItems +
                                  ' batches with '+ asynchronousJob.NumberOfErrors + ' failures.');
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }    
    }
    
}