force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Holds the City Name</description>
    <inlineHelpText>Enter the City Name</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Holds the state information</description>
    <inlineHelpText>Enter the state</inlineHelpText>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Holds the street information</description>
    <inlineHelpText>Enter the street information</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Used to store 5 digit zipCode.</description>
    <label>Primary Shipping Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Confirmation_Number__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Number__c</fullName>
    <description>It holds the confirmation number of the account. And it should be greater than lead id value.</description>
    <externalId>true</externalId>
    <label>Confirmation Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>Unique identifier for MYSQL data table.</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/fFirstName__c.field-meta.xml
<CustomField>
    <fullName>fFirstName__c</fullName>
    <formula>UserAccount__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fFirstName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/fLastName__c.field-meta.xml
<CustomField>
    <fullName>fLastName__c</fullName>
    <formula>UserAccount__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fLastName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Kunnect_Sync__c.field-meta.xml
<CustomField>
    <fullName>Kunnect_Sync__c</fullName>
    <label>Kunnect Sync</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>contact_metro_inbound</fullName>
            </value>
            <value>
                <fullName>source_contact_01_water</fullName>
            </value>
            <value>
                <fullName>source_contact_01_security</fullName>
            </value>
            <value>
                <fullName>source_contact_windows_and_blinds</fullName>
            </value>
            <value>
                <fullName>source_contact_srp_solar</fullName>
            </value>
            <value>
                <fullName>source_contact_pest_control</fullName>
            </value>
            <value>
                <fullName>source_contact_hvac</fullName>
            </value>
            <value>
                <fullName>source_contact_solar</fullName>
            </value>
            <value>
                <fullName>KunnectToSF</fullName>
            </value>
            <value>
                <fullName>gravel_contact_security</fullName>
            </value>
            <value>
                <fullName>gravel_contact_water</fullName>
            </value>
            <value>
                <fullName>gravel_contact_solar</fullName>
            </value>
            <value>
                <fullName>gravel_contact_remodel</fullName>
            </value>
            <value>
                <fullName>gravel_contact_pest_control</fullName>
            </value>
            <value>
                <fullName>gravel_contact_hvac</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field will store the person Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Respond_Date__c.field-meta.xml
<CustomField>
    <fullName>Respond_Date__c</fullName>
    <label>Respond Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Verbal_Consent__c.field-meta.xml
<CustomField>
    <fullName>Verbal_Consent__c</fullName>
    <formula>Text(UserAccount__r.Verbal_Consent__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Verbal Consent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verbal_Consent__c/Verbal_Consent__c.object-meta.xml
<CustomObject>
    <description>This object will holds the verbal consents records</description>
    <label>Verbal Consent</label>
    <nameField>
        <displayFormat>VC-{0000}</displayFormat>
        <label>Verbal Consent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verbal Consents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/KunnectScheduleSetting.cls
/**
 * Diaco
 * @author             Jull Quintero Daza
 * Project:            kunnect Integrations
 * Testclass           KunnectScheduleSettingTest
 * Description:        DTO Setting Shedule
 *
 * Changes (Version)
 * _________________________________________
 *            No.        Date            Author                    Description
 *            ____    __________        __________________      _____________________________________
 * @version    1.0    12/04/2021         Jull Quintero D         Initial implementation of the class.
 **/

public class KunnectScheduleSetting {
    public static final List<String> ZIPCODES = new List<String>{
        '85006','85007','85008','85009','85012','85014','85020','85022','85023','85024','85027','85028','85029','85032','85034','85050','85053','85054','85083','85085','85086','85087','85225','85253','85254','85255','85258','85259','85260','85262','85266','85301','85307','85308','85309','85310','85323','85326','85331','85335','85337','85338','85340','85345','85351','85354','85355','85361','85363','85373','85374','85375','85379','85382','85383','85387','85395','85396'};
    public static final List<String> SOURCETABLES = new List<String>{
        'source_contact_01_security','source_contact_01_water','source_contact_windows_and_blinds','source_contact_pest_control','source_contact_hvac','source_contact_solar','source_contact_srp_solar'};
    public static final List<String> GRAVELTABLES = new List<String>{
        'gravel_contact_security','gravel_contact_water','gravel_contact_remodel','gravel_contact_hvac','gravel_contact_pest_control','gravel_contact_solar'};
    public string name;
    public integer recordSize;
    public Boolean newUserAddress;
    public Datetime nextRun;
    public integer start;
    public integer currentUserAddreSize;
    private List<User_Address__c> records;

    public Map<String,String> emailReport = new Map<String,String>();

    /**
    * @author Jull Quintero | 9/04/2021 
    * @description: Outbound - Get user address, SOQL for Gravel and Proteccion source
    **/
    public List<User_Address__c> getOutboundSourceUserAddress() {
        if( this.newUserAddress ) {
            this.records = [
                SELECT Id,
                Kunnect_Sync__c,
                fFirstName__c, 
                fLastName__c,
                Phone__c, 
                Email__c, 
                Confirmation_Number__c, 
                Recording_Date__c, 
                Respond_Date__c,  
                Sales_Price__c,
                Address__r.Street__c,  
                Address__r.City__c, 
                Address__r.State__c, 
                Address__r.Zip_Code__c 
                FROM User_Address__c 
                WHERE Phone__c != '' AND Respond_Date__c = YESTERDAY AND Verbal_Consent__c='Yes' AND 
                Kunnect_Sync__c EXCLUDES(:String.join(SOURCETABLES, ';')) 
                ];
                this.currentUserAddreSize = this.records.size();
                this.start = 0;
        }
        return records;
    }

        /**
    * @author Jull Quintero | 9/04/2021 
    * @description: Outbound - Get user address, SOQL for Gravel and Proteccion source
    **/
    public List<User_Address__c> getOutboundGravelUserAddress() {
        if( this.newUserAddress ) {
            this.records = [
                SELECT Id,
                Kunnect_Sync__c,
                fFirstName__c, 
                fLastName__c,
                Phone__c, 
                Email__c, 
                Confirmation_Number__c, 
                Recording_Date__c, 
                Respond_Date__c,  
                Sales_Price__c,
                Address__r.Street__c,  
                Address__r.City__c, 
                Address__r.State__c, 
                Address__r.Zip_Code__c 
                FROM User_Address__c 
                WHERE Phone__c != '' AND Respond_Date__c = YESTERDAY AND Verbal_Consent__c='Yes' AND 
                Kunnect_Sync__c EXCLUDES(:String.join(GRAVELTABLES, ';')) 
                ];
                this.currentUserAddreSize = this.records.size();
                this.start = 0;
        }
        return records;
    }


    /**
    * @author Jull Quintero | 9/04/2021 
    * @description: Inbound - Get user address
    **/
    public List<User_Address__c> getInboundUserAddress() {
        if( this.newUserAddress ) {
            this.records = [
                SELECT 
                Email__c,
                Recording_Date__c,
                Sale_Date__c,
                External_ID__c, 
                Confirmation_Number__c, 
                Phone__c, 
                Sales_Price__c, 
                fFirstName__c, 
                fLastName__c,
                Address__r.Name,
                Address__r.City__c, 
                Address__r.State__c, 
                Address__r.Street__c, 
                Address__r.Zip_Code__c,
                Kunnect_Sync__c
                FROM User_Address__c 
                WHERE CreatedDate = TODAY AND
                Kunnect_Sync__c EXCLUDES('contact_metro_inbound')];
                this.currentUserAddreSize = this.records.size();
                this.start = 0;
        }
        return records;
    }

    /**
    * @author Jull Quintero | 27/04/2021 
    * @description: set nextRun param
    **/
    public Boolean sendEmail(integer start) {
        Boolean sendEmail = false;
        this.start = start;
        if( this.start >= this.currentUserAddreSize ) {
            this.newUserAddress = true;
            integer year  =System.Date.today().year();
            integer month = System.Date.today().month();
            integer day  = System.Date.today().day() + 1;
            if ( this.name == 'inboundUserAddress' ) {
                this.nextRun = System.now().addMinutes(35);
            }else if ( this.name == 'outboundGravel' ) {
                DateTime dTime = DateTime.newInstance(year, month, day, 2, 50, 0);
                this.nextRun = dTime;
            }else if(this.name == 'outboundSource') {
                DateTime dTime = DateTime.newInstance(year, month, day, 2, 20, 0);
                this.nextRun = dTime;
            }
            this.emailReport.clear();
            sendEmail = true;
        }
        return sendEmail;
    }
    /**
    * @author Jull Quintero | 9/04/2021 
    * @description: parse Json to KunnectScheduleSetting object
    * @param json(String) 
    **/
    public static KunnectScheduleSetting parse(String json) { 
        return (KunnectScheduleSetting)System.JSON.deserialize(json, KunnectScheduleSetting.class);
    }

    /**
    * @author Jull Quintero | 9/04/2021 
    * @description: parse Json to KunnectScheduleSetting object
    * @param obj(KunnectScheduleSetting) 
    **/
    public static String createJson(KunnectScheduleSetting obj) {            
        return (String) System.JSON.serialize(obj);
    } 

}