force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s primary address informations.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field holds the branch details</description>
    <inlineHelpText>Select the branch where the address resides in.</inlineHelpText>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Holds the City Name</description>
    <inlineHelpText>Enter the City Name</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Full_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Full_Zip_Code__c</fullName>
    <description>Used to store 10 digit zipcode.</description>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/MSA__c.field-meta.xml
<CustomField>
    <fullName>MSA__c</fullName>
    <label>MSA</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Austin-Round Rock-San Marcos TX</fullName>
            </value>
            <value>
                <fullName>Bakersfield Ca</fullName>
            </value>
            <value>
                <fullName>Dallas-Fort Worth-Arlington TX</fullName>
            </value>
            <value>
                <fullName>Houston-Sugar Land-Baytown TX</fullName>
            </value>
            <value>
                <fullName>Killeen-Temple TX</fullName>
            </value>
            <value>
                <fullName>Los Angeles--Riverside--Orange County Ca</fullName>
            </value>
            <value>
                <fullName>Phoenix-Mesa-Glendale AZ</fullName>
            </value>
            <value>
                <fullName>Provo-Orem Ut</fullName>
            </value>
            <value>
                <fullName>Salt Lake City-Ogden Ut</fullName>
            </value>
            <value>
                <fullName>San Antonio-New Braunfels TX</fullName>
            </value>
            <value>
                <fullName>San Diego-Carlsbad-San Marcos Ca</fullName>
            </value>
            <value>
                <fullName>Tucson AZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <label>Region Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Holds the state information</description>
    <inlineHelpText>Enter the state</inlineHelpText>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Holds the street information</description>
    <inlineHelpText>Enter the street information</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <description>It contains combination of primary shipping street, primary shipping city &amp; primary shipping state. eg, &lt;primary shipping street&gt;:&lt;primary shipping city&gt;:&lt;primary shipping state&gt;</description>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Used to store 5 digit zipCode.</description>
    <label>Primary Shipping Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Plus_Four__c.field-meta.xml
<CustomField>
    <fullName>Zip_Plus_Four__c</fullName>
    <label>Zip Plus Four</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/MSA__c.field-meta.xml
<CustomField>
    <fullName>MSA__c</fullName>
    <label>MSA</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>Used to hold Person Account&apos;s property informations.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/ZipCode__c.object-meta.xml
<CustomObject>
    <description>It contains all zip codes for the corresponding branches.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipCode__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Zip Codes</relationshipLabel>
    <relationshipName>Zip_code</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Zip Codes</relationshipLabel>
    <relationshipName>Zip_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/fields/MSA__c.field-meta.xml
<CustomField>
    <fullName>MSA__c</fullName>
    <label>MSA</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZipCode</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddressTriggerHelper.cls
/*
 * Diaco
 * @author             Jull Quintero Daza
 * Project:            Address Trigger
 * TestClass:          AddressTriggerTest
 * Description:        Helper
 *
 * Changes (Version)
 * _________________________________________
 *            No.        Date            Author                    Description
 *            ____    __________        __________________      _____________________________________
 * @version    1.0    12/10/2020         Jull Quintero D         Initial implementation of the class.
 **/

public class AddressTriggerHelper {

    private Set<String> addressUniqueKeys = new Set<String>();
    private Set<String> zipCodes = new Set<String>();

    /*
     * This method is responsible to change Address fields and 
        to Check for the duplicate address
     *
     * This method is run Before Insert and Before Update.
     * 
     * This method is used in:
     * AddressTriggerHandler
     * 
     * @param List newAddress
     * @param List oldAddress
     * @param Boolean IsInsert
     * @param Boolean IsUpdate
     **/
    public void setFieldsAddress(List<Address__c> currentAddress,Map<Id,Address__c> oldAddressMap, Boolean isInsert, Boolean isUpdate) {
        Integer currentAddressLength = currentAddress.size();
        for (Integer i = 0; i < currentAddressLength; i++) {
            Address__c address = currentAddress[i];
            Address__c oldAddress = isUpdate ? oldAddressMap.get(address.Id) : null;
            autoPopulateFields(address,oldAddress,isInsert,isUpdate);
            
        }

        // update the Branch,MSA and Region Code based on the Zip code value
        if( zipCodes.size() > 0 ) {
            updateRelatedBranch(currentAddress,zipCodes);
        }

        // Check for the duplicate address
        if( addressUniqueKeys.size() > 0 ) {
            duplicateAddressValidation(currentAddress,addressUniqueKeys);
        }

    }

    /*
     * This method is responsible to change address.Name, address.Full_Zip_Code__c,
        address.Unique_Key__c
     *
     * This method is run Before Insert and Before Update.
     * 
     * This method is used in:
     * setFieldsAddress - This class
     * 
     * @param Address__c newAddress
     * @param Address__c oldAddress
     * @param Boolean IsInsert
     * @param Boolean IsUpdate
     **/
    private void autoPopulateFields(Address__c address, Address__c oldAddress, Boolean isInsert, Boolean isUpdate) {

        Boolean ischangeName = false;
        Boolean ischangeUniqueKey = false;
        Boolean isChangeFullZipCode = false;
        Boolean isChangeZipCode = false;
        if( isInsert ) {
            ischangeName =  address.State__c != null && address.Street__c != null && address.City__c != null;

            ischangeUniqueKey = address.Street__c != null && address.Zip_Code__c != null;

            isChangeZipCode = address.Zip_Code__c != null;

            isChangeFullZipCode = address.Zip_Plus_Four__c != null && address.Zip_Code__c != null;

        }else if( isUpdate ) {
            ischangeName =  ( address.State__c != null && address.Street__c != null && address.City__c != null && 
                            (oldAddress.State__c != address.State__c || oldAddress.Street__c != address.Street__c || 
                            oldAddress.City__c != address.City__c) );

            ischangeUniqueKey = ( (address.Street__c != null && address.Zip_Code__c != null) && 
                                (oldAddress.Street__c != address.Street__c || 
                                oldAddress.Zip_Code__c != address.Zip_Code__c ) );

            isChangeZipCode = address.Zip_code__c != null && oldAddress.Zip_code__c != address.Zip_code__c;

            isChangeFullZipCode = ( address.Zip_Plus_Four__c != null && address.Zip_Code__c != null && 
                                    (oldAddress.Zip_Plus_Four__c != address.Zip_Plus_Four__c || 
                                    oldAddress.Zip_code__c != address.Zip_code__c) ); 
        }

        // Address name field population which contains combination of street , city & state
        if( ischangeName ) {
            address.Name = address.Street__c + ':' + address.City__c + ':' + address.State__c;
        }

        // Concatenate the values of Street and Zip_Code fields and store it in the
        // Unique_Key__c field upon address insertion.
        if( ischangeUniqueKey ) {
            address.Unique_Key__c = address.Street__c + ':' +address.Zip_Code__c;
            if(!addressUniqueKeys.contains(address.Unique_Key__c)){
                addressUniqueKeys.add(address.Unique_Key__c);
            }
            else{
                address.addError('Same address found in the incoming address records');
            }
        }

        // Concatenate the values of Zip code and Zip_Plus_Four__c fields and store it in the
        // full_zip_code__c field upon address insertion.
        if( isChangeZipCode ) {
            zipCodes.add(address.Zip_Code__c);
        } 
        if( isChangeFullZipCode ) {
            address.Full_Zip_code__c =  address.Zip_Code__c + '-' + address.Zip_Plus_Four__c;
        }
    }

    /*
     * This method is responsible to Check for the duplicate address
     * 
     * This method is run Before Insert and Before Update. 
     * 
     * This method is used in:
     * setFieldsAddress - This class
     * 
     * @param List<Address__c> Address
     * @param Set<String> addressUniqueKeys
     **/
    private void duplicateAddressValidation(List<Address__c> currentAddress,Set<String> addressUniqueKeys){
        Set<String> existingAddress = new Set<String>();

        Address__c[] allAddress =  [SELECT Id,Name,Unique_Key__c FROM Address__c WHERE Unique_Key__c IN:addressUniqueKeys];
        Integer allAddressLength = allAddress.size();
        for (Integer i = 0; i < allAddressLength; i++) {
            Address__c addr = allAddress[i];
            existingAddress.add(addr.Unique_Key__c);
        }

        // If duplicate address is found then the error would be thrown
        if(!existingAddress.isEmpty()){
            Integer currentAddressLength = currentAddress.size();
            for (Integer i = 0; i < currentAddressLength; i++) {
                Address__c address = currentAddress[i];

                if(existingAddress.contains(address.Unique_Key__c)){
                    address.addError('Address already exists');
                }
            }
        }
    }

    /*
     * This method If the zip code field has the value then update the related address.Zip_Code__c, 
        address.MSA__c, address.Region_Code__c

     * This method is run Before Insert and Before Update.

     * This method is used in:
     * setFieldsAddress - This class
     * 
     * @param List<Address__c> Address
     * @param Set<String> zipCodes
     **/
    private void updateRelatedBranch(List<Address__c> currentAddress,Set<String> zipCodesIds){
        Map<String,ZipCode__c> zipCodeMap = new Map<String,ZipCode__c>();
        //Get the list of zipcodes and branch names from the Custom object.
        ZipCode__c[] zipCodes = [SELECT Id,Name,Branch__c,MSA__c,Region_Code__c,ZipCode__c FROM ZipCode__c WHERE Name IN : zipCodesIds];
        Integer zipCodesLength = zipCodes.size();
        for (Integer i = 0; i < zipCodesLength; i++) {
            ZipCode__c zipCode = zipCodes[i];
            if(!zipCodeMap.containsKey(zipCode.Name)){
                zipCodeMap.put(zipCode.Name,zipCode);
            }
        } 
        
        Integer currentAddressLength = currentAddress.size();
        for (Integer i = 0; i < currentAddressLength; i++) {
            Address__c address = currentAddress[i];

            //Branch field population
            if(address.Zip_Code__c == null){
                address.Branch__c = null;
                address.MSA__c = '';
                address.Region_Code__c = '';
            }
            //if the address get inserted with zipcode then,
            //we auto populate Branch , MSA & Region Code based on the zipcode from Zipcode__c Custom Obj
            else if(zipCodeMap.containsKey(address.Zip_Code__c)){
                ZipCode__c zip = zipCodeMap.get(address.Zip_Code__c);
                address.Branch__c = zip.branch__c;
                address.MSA__c = zip.MSA__c;
                address.Region_Code__c = zip.Region_Code__c;
            }
            //if the address zipcode not match in the Zipcode__c custom obj then, set to Invalid Zip Code
            else{
                address.Branch__c = UtilClass.getBranchId('Invalid Zip Code');
                address.MSA__c = 'Invalid Zip Code';
                address.Region_Code__c = 'Invalid Zip Code';
            }
            //branch population end
        }
    }

    /*
     * This method is responsible to Update property.Name
     * 
     * This method is run After Update. 
     * 
     * This method is used in:
     * AddressTriggerHandler
     * 
     * @param List<Address__c> Address
     * @param Map<Id,Address__c> oldAddressMap
     **/

    //property name update
    public static void updatePropertyName(List<Address__c> currentAddress, Map<Id,Address__c> oldAddressMap){
        Map<Id,Address__c> addressMap = new Map<Id,Address__c>();
        integer currentAddressLength = currentAddress.size();
        for (Integer i = 0; i < currentAddressLength; i++) {
            Address__c address = currentAddress[i];
            Address__c oldAddress = oldAddressMap.get(address.Id);
            if(oldAddress.Name != address.Name){
                addressMap.put(address.Id,address);
            }
        }
        
        List<Property__c> toUpdateProperties = [SELECT Id,Name,Address__c FROM Property__c WHERE Address__c IN : addressMap.keyset()];
        if(!toUpdateProperties.isEmpty()){
            Integer toUpdatePropertiesLength = toUpdateProperties.size();
            for (Integer i = 0; i < toUpdatePropertiesLength; i++) {
                Property__c property = toUpdateProperties[i];
                if(addressMap.containskey(property.Address__c)) {
                    property.Name = addressMap.get(property.Address__c).Name;
                }
            }
        }    
        try {
            if(!toUpdateProperties.isEmpty()){
                update toUpdateProperties;
            }
        }
        catch(Exception e){
            System.debug('Error occured while updating the property'+e.getMessage());
        }
    }
}