force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>To keep the county name. It is not unique. The same county name can exist for different states.</description>
    <label>County</label>
    <nameField>
        <displayFormat>CN-{000}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>To hold the state of the branch</description>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeliveryEval.cls
/** 
 * Diaco
 * @author             Jull Quintero Daza
 * Project:            Delivery eval
 * TestClass:          DeliveryObjtTriggerTest
 * Description:        
 *
 * Changes (Version)
 * _________________________________________
 *            No.        Date            Author                    Description
 *            ____    __________        __________________      _____________________________________
 * @version    1.0    08-07-2021         Jull Quintero D         Initial implementation of the class.
 **/

public with sharing class DeliveryEval {
    public static Boolean addressNoNull(Delivery_Object__c delivery) {
        return  delivery.Street__c != null  || 
                delivery.City__c != null    ||
                delivery.State__c != null   || 
                delivery.Zip__c != null     || 
                delivery.County__c != null;
    }

    public static Boolean addressChange(Delivery_Object__c delivery, Delivery_Object__c oldelivery) { 
        return  delivery.Street__c != oldelivery.Street__c ||
                delivery.City__c != oldelivery.City__c ||
                delivery.State__c != oldelivery.State__c ||
                delivery.Zip__c != oldelivery.Zip__c || 
                delivery.County__c != oldelivery.County__c;
    }

    public static Boolean locationNoNull(Delivery_Object__c delivery) {
        return  delivery.Maps_latitude__c != null && 
                delivery.Maps_longitude__c != null;
    }

    public static Boolean locationChange(Delivery_Object__c delivery, Delivery_Object__c oldelivery) {
        return  delivery.Maps_latitude__c != oldelivery.Maps_latitude__c || 
                delivery.Maps_longitude__c != oldelivery.Maps_longitude__c;
    }

    public static Boolean geoCodeChange(Delivery_Object__c delivery, Delivery_Object__c oldelivery) { 
        return  !System.isBatch() &&
                !System.isFuture() &&
                DeliveryEval.locationNoNull(delivery) &&
                DeliveryEval.addressNoNull(delivery) && 
                (DeliveryEval.locationChange(delivery, oldelivery) || DeliveryEval.addressChange(delivery, oldelivery));
    }

    public static Boolean mapLayerChangeLocation(Delivery_Object__c delivery, Delivery_Object__c oldelivery) { 
        return  DeliveryEval.locationNoNull(delivery) &&    
                DeliveryEval.addressNoNull(delivery)  &&
                DeliveryEval.locationChange(delivery, oldelivery) && 
                !DeliveryEval.addressChange(delivery, oldelivery) &&
                UserInfo.getUserId() != label.Data_com_Clean_User_Id;
    }
}