force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/Delivery_Object__c.object-meta.xml
<CustomObject>
    <label>Delivery Object</label>
    <nameField>
        <label>Delivery Object  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries Object</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Object__c/fields/Branch_Object__c.field-meta.xml
<CustomField>
    <fullName>Branch_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Object</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Hung_Status__c.field-meta.xml
<CustomField>
    <fullName>Hung_Status__c</fullName>
    <label>Hung Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrived</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hung</fullName>
            </value>
            <value>
                <fullName>COMPLETED GATED</fullName>
            </value>
            <value>
                <fullName>Gated</fullName>
            </value>
            <value>
                <fullName>Cant Find</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Invld</fullName>
            </value>
            <value>
                <fullName>Remove: Management</fullName>
            </value>
            <value>
                <fullName>Too Far</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Wrong House Number</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Remove: Gated</fullName>
            </value>
            <value>
                <fullName>Remove: Aging</fullName>
            </value>
            <value>
                <fullName>Sent To Cheetah</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Gio - In Process</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Access Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Object__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Address</label>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Deliveries Object</relationshipLabel>
    <relationshipName>Deliveries_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL-Birmingham</fullName>
            </value>
            <value>
                <fullName>AL-Huntsville_DeCatur</fullName>
            </value>
            <value>
                <fullName>AR-Fayetteville_Springdale_Rogers</fullName>
            </value>
            <value>
                <fullName>AR-Little_Rock</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_East</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_North</fullName>
            </value>
            <value>
                <fullName>AZ-Phoenix_West</fullName>
            </value>
            <value>
                <fullName>AZ-Tucson</fullName>
            </value>
            <value>
                <fullName>CA-Bakersfield</fullName>
            </value>
            <value>
                <fullName>CA-Fresno</fullName>
            </value>
            <value>
                <fullName>CA-Los_Angeles</fullName>
            </value>
            <value>
                <fullName>CA-Modesto</fullName>
            </value>
            <value>
                <fullName>CA-Oakland</fullName>
            </value>
            <value>
                <fullName>CA-Orange_County</fullName>
            </value>
            <value>
                <fullName>CA-Palm_Springs</fullName>
            </value>
            <value>
                <fullName>CA-Palmdale_Lancaster</fullName>
            </value>
            <value>
                <fullName>CA-Riverside</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento</fullName>
            </value>
            <value>
                <fullName>CA-Sacramento_NE</fullName>
            </value>
            <value>
                <fullName>CA-San_Bernardino</fullName>
            </value>
            <value>
                <fullName>CA-San_Diego</fullName>
            </value>
            <value>
                <fullName>CA-San_Francisco</fullName>
            </value>
            <value>
                <fullName>CA-San_Jose</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_North</fullName>
            </value>
            <value>
                <fullName>CA-SF_East_Bay_South</fullName>
            </value>
            <value>
                <fullName>CA-SFV_West</fullName>
            </value>
            <value>
                <fullName>CA-Temecula</fullName>
            </value>
            <value>
                <fullName>CA-Ventura_Oxnard</fullName>
            </value>
            <value>
                <fullName>CA-Victorville_Barstow</fullName>
            </value>
            <value>
                <fullName>CO-Colorado_Springs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Branch_Object__c.field-meta.xml
<CustomField>
    <fullName>Branch_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Object</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Drivers (Branch Object)</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift_Card_Orders__c/Gift_Card_Orders__c.object-meta.xml
<CustomObject>
    <label>Gift Card Order</label>
    <nameField>
        <label>Gift Card Orders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Card Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Card_Orders__c/fields/Parent_Gift_Card_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gift_Card_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Gift Card Order</label>
    <referenceTo>Gift_Card_Orders__c</referenceTo>
    <relationshipLabel>Gift Card Orders</relationshipLabel>
    <relationshipName>Gift_Card_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift_Card_Orders__c/fields/User_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associating Gift Card under User Address Object</description>
    <label>User Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Parent_Gift_Card_Order__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User_Address__c</referenceTo>
    <relationshipLabel>Gift Card Orders</relationshipLabel>
    <relationshipName>Gift_Card_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hung_Status__c/Hung_Status__c.object-meta.xml
<CustomObject>
    <description>This object will different Hung Status details for the Products</description>
    <label>Hung Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Hung Status No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hung Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CreateDeliveryObjectTest.cls
/************************************************************************************************* 
* Class Name : DeliveryObjectTriggerHandlerTest
* Created By : Sailappa Vignesh P G
* Created Date : 2/18/2016
* Description : This class will cover the code coverage for 'CreateDeliveryObject' batch class. 
**************************************************************************************************/
@isTest(seeAllData = false) 
public class CreateDeliveryObjectTest { 
    /*Description : This method will load the test data for test cases.*/
    @testSetup static void loadTestData() {
        TestClassUtil.createZipcodeForBranch();
        TestClassUtil.createAccount(2);
        TestClassUtil.createCheetahGiftCardOrder();
        TestClassUtil.createDriver();  
        TestClassUtil.createProductAndHungStatus();
        //TestClassUtil.createPersonAddress();
        TestClassUtil.createBranch();
        TestClassUtil.createAddress(2);
        TestClassUtil.createUserAddress(2);
        TestClassUtil.createDeliveryParameter(1);
   } 
    /*Description : This method will check the Hung Status of the Delivery Object record and will create additional Delivery Object record and this method is to the 'Cant Find' status */
    public static testmethod void testCantFindStatus(){        
        Gift_Card_Orders__c giftCardOrder = [SELECT ID FROM Gift_Card_Orders__c LIMIT 1];
        Driver__c driver =  [SELECT ID FROM Driver__c LIMIT 1];
        //User_Address__c userAddress = [SELECT ID FROM User_Address__c LIMIT 1];
        Branch__c branch = [SELECT ID FROM Branch__c LIMIT 1];
        List<Delivery_Object__c> deliveryObjectLst = new List<Delivery_Object__c>();
        for(User_Address__c currUserAddress : [SELECT Id,UserAccount__c FROM User_Address__c]){
            Delivery_Object__c deliveryObject = new Delivery_Object__c();
            deliveryObject.Person_Account__c = currUserAddress.UserAccount__c;
            deliveryObject.User_Address__c = currUserAddress.Id;
            deliveryObject.Driver__c = driver.id;
            deliveryObject.name = '1';
            deliveryObject.Branch_Object__c = branch.id;
            deliveryObject.Parent_Gift_Card_Order__c = giftCardOrder.id;
          //  deliveryObject.User_Address__c = userAddress.id;
            deliveryObject.Hung_Status__c = 'Cant Find';            
            deliveryObjectLst.add(deliveryObject);
        }
        insert deliveryObjectLst;
        for(Delivery_Object__c currDeliveryObject : deliveryObjectLst){
            currDeliveryObject.Delivery_Date__c = System.now() - 1;    
        }
        update deliveryObjectLst;
        Test.startTest();
        CreateDeliveryObject DeliveryObjectBatch = new CreateDeliveryObject();
        Database.executeBatch(DeliveryObjectBatch); 
        Test.stopTest();
        //System.assertEquals(200, [SELECT ID FROM Delivery_Object__c].Size());
        System.assert(Limits.getDMLRows() * 100 / Limits.getLimitDMLRows() < 50);
        System.assert(Limits.getDMLStatements() * 100 / Limits.getLimitDMLStatements() < 50);
        System.assert(Limits.getAggregateQueries() * 100 / Limits.getLimitAggregateQueries() < 50);
        System.assert(Limits.getQueries() * 100 / Limits.getLimitQueries() < 50);
        System.assert(Limits.getQueryRows() * 100 / Limits.getLimitQueryRows() < 50);
    }
       /*Description : This method will check the Hung Status of the Delivery Object record and will create additional Delivery Object record and this method is to the 'Gated' status */
    public static testmethod void testGatedStatus(){        
        Gift_Card_Orders__c giftCardOrder = [SELECT ID FROM Gift_Card_Orders__c LIMIT 1];
        Driver__c driver =  [SELECT ID FROM Driver__c LIMIT 1];
        //User_Address__c userAddress = [SELECT ID FROM User_Address__c LIMIT 1];
        Branch__c branch = [SELECT ID FROM Branch__c LIMIT 1];
        List<Delivery_Object__c> deliveryObjectLst = new List<Delivery_Object__c>();
        for(User_Address__c currUserAddress : [SELECT Id,UserAccount__c FROM User_Address__c]){
            Delivery_Object__c deliveryObject = new Delivery_Object__c();
            deliveryObject.Person_Account__c = currUserAddress.UserAccount__c;
            deliveryObject.User_Address__c = currUserAddress.Id;
            deliveryObject.Driver__c = driver.id;
            deliveryObject.name = '1';
            deliveryObject.Branch_Object__c = branch.id;
            deliveryObject.Parent_Gift_Card_Order__c = giftCardOrder.id;
            deliveryObject.Hung_Status__c = 'Gated';  
            //deliveryObject.User_Address__c = userAddress.id;
            deliveryObjectLst.add(deliveryObject);
            
        }
        insert deliveryObjectLst;
        for(Delivery_Object__c currDeliveryObject : deliveryObjectLst){
            currDeliveryObject.Delivery_Date__c = System.now() - 7;    
        }
        update deliveryObjectLst;
        Test.startTest();
        CreateDeliveryObject DeliveryObjectBatch = new CreateDeliveryObject();
        Database.executeBatch(DeliveryObjectBatch);        
        Test.stopTest();
       // System.assertEquals(200, [SELECT ID FROM Delivery_Object__c].Size());
        System.assert(Limits.getDMLRows() * 100 / Limits.getLimitDMLRows() < 50);
        System.assert(Limits.getDMLStatements() * 100 / Limits.getLimitDMLStatements() < 50);
        System.assert(Limits.getAggregateQueries() * 100 / Limits.getLimitAggregateQueries() < 50);
        System.assert(Limits.getQueries() * 100 / Limits.getLimitQueries() < 50);
        System.assert(Limits.getQueryRows() * 100 / Limits.getLimitQueryRows() < 50);
    }
    /*Description : This method will check the Hung Status of the Delivery Object record and will create additional Delivery Object record and this method is to the 'Too Far' status */
    public static testmethod void testTooFarStatus(){        
        Gift_Card_Orders__c giftCardOrder = [SELECT ID FROM Gift_Card_Orders__c LIMIT 1];
        Driver__c driver =  [SELECT ID FROM Driver__c LIMIT 1];
        //User_Address__c userAddress = [SELECT ID FROM User_Address__c LIMIT 1];
        Branch__c branch = [SELECT ID FROM Branch__c LIMIT 1];
        List<Delivery_Object__c> deliveryObjectLst = new List<Delivery_Object__c>();
        for(User_Address__c currUserAddress : [SELECT Id,UserAccount__c FROM User_Address__c]){
            Delivery_Object__c deliveryObject = new Delivery_Object__c();
            deliveryObject.Person_Account__c = currUserAddress.UserAccount__c;
            deliveryObject.User_Address__c = currUserAddress.Id;
            deliveryObject.Driver__c = driver.id;
            deliveryObject.name = '1';
            deliveryObject.Branch_Object__c = branch.id;
            deliveryObject.Parent_Gift_Card_Order__c = giftCardOrder.id;
            deliveryObject.Hung_Status__c = 'Too Far';   
            //deliveryObject.User_Address__c = userAddress.id;
            deliveryObjectLst.add(deliveryObject);
            
        }
        insert deliveryObjectLst;
        for(Delivery_Object__c currDeliveryObject : deliveryObjectLst){
            currDeliveryObject.Delivery_Date__c = System.now() - 1;    
        }
        update deliveryObjectLst;
        Test.startTest();
        CreateDeliveryObject DeliveryObjectBatch = new CreateDeliveryObject();
        Database.executeBatch(DeliveryObjectBatch);
        Test.stopTest();
        //System.assertEquals(200, [SELECT ID FROM Delivery_Object__c].Size());
        System.assert(Limits.getDMLRows() * 100 / Limits.getLimitDMLRows() < 50);
        System.assert(Limits.getDMLStatements() * 100 / Limits.getLimitDMLStatements() < 50);
        System.assert(Limits.getAggregateQueries() * 100 / Limits.getLimitAggregateQueries() < 50);
        System.assert(Limits.getQueries() * 100 / Limits.getLimitQueries() < 50);
        System.assert(Limits.getQueryRows() * 100 / Limits.getLimitQueryRows() < 50);
    }
    /*Description : This method will check the Hung Status of the Delivery Object record and will create additional Delivery Object record and this method is to the 'Under Construction' status */
    public static testmethod void testUnderConstructionStatus(){        
        Gift_Card_Orders__c giftCardOrder = [SELECT ID FROM Gift_Card_Orders__c LIMIT 1];
        Driver__c driver =  [SELECT ID FROM Driver__c LIMIT 1];
        Branch__c branch = [SELECT ID FROM Branch__c LIMIT 1];
        //User_Address__c userAddress = [SELECT ID FROM User_Address__c LIMIT 1];
        List<Delivery_Object__c> deliveryObjectLst = new List<Delivery_Object__c>();
        for(User_Address__c currUserAddress : [SELECT Id,UserAccount__c FROM User_Address__c]){
            Delivery_Object__c deliveryObject = new Delivery_Object__c();
            deliveryObject.Person_Account__c = currUserAddress.UserAccount__c;
            deliveryObject.User_Address__c = currUserAddress.Id;
            deliveryObject.Driver__c = driver.id;
            deliveryObject.name = '1';
            deliveryObject.Branch_Object__c = branch.id;
            deliveryObject.Parent_Gift_Card_Order__c = giftCardOrder.id;
            deliveryObject.Hung_Status__c = 'Under Construction';   
            //deliveryObject.User_Address__c = userAddress.id;
            deliveryObjectLst.add(deliveryObject);
            
        }
        insert deliveryObjectLst;
        for(Delivery_Object__c currDeliveryObject : deliveryObjectLst){
            currDeliveryObject.Delivery_Date__c = System.now() - 30;    
        }
        update deliveryObjectLst;
        Test.startTest();
        CreateDeliveryObject DeliveryObjectBatch = new CreateDeliveryObject();
        Database.executeBatch(DeliveryObjectBatch);
        Test.stopTest();
       // System.assertEquals(200, [SELECT ID FROM Delivery_Object__c].Size());
        System.assert(Limits.getDMLRows() * 100 / Limits.getLimitDMLRows() < 50);
        System.assert(Limits.getDMLStatements() * 100 / Limits.getLimitDMLStatements() < 50);
        System.assert(Limits.getAggregateQueries() * 100 / Limits.getLimitAggregateQueries() < 50);
        System.assert(Limits.getQueries() * 100 / Limits.getLimitQueries() < 50); 
        System.assert(Limits.getQueryRows() * 100 / Limits.getLimitQueryRows() < 50);
    }
    /*Description : This method will check the Hung Status of the Delivery Object record and will create additional Delivery Object record and this method is to the 'Cancelled' status */
    public static testmethod void testCancelledStatus(){        
        Gift_Card_Orders__c giftCardOrder = [SELECT ID FROM Gift_Card_Orders__c LIMIT 1];
        Driver__c driver =  [SELECT ID FROM Driver__c LIMIT 1];
        //User_Address__c userAddress = [SELECT ID FROM User_Address__c LIMIT 1];
        Branch__c branch = [SELECT ID FROM Branch__c LIMIT 1];
        List<Delivery_Object__c> deliveryObjectLst = new List<Delivery_Object__c>();
        for(User_Address__c currUserAddress : [SELECT Id,UserAccount__c FROM User_Address__c]){
            Delivery_Object__c deliveryObject = new Delivery_Object__c();
            deliveryObject.Person_Account__c = currUserAddress.UserAccount__c;
            deliveryObject.User_Address__c = currUserAddress.Id;
            deliveryObject.Driver__c = driver.id;
            deliveryObject.name = '1';
            deliveryObject.Branch_Object__c = branch.id;
            deliveryObject.Parent_Gift_Card_Order__c = giftCardOrder.id;
            deliveryObject.Hung_Status__c = 'Cancelled';   
            //deliveryObject.User_Address__c = userAddress.id;
            deliveryObjectLst.add(deliveryObject);
            
        }
        insert deliveryObjectLst;
        for(Delivery_Object__c currDeliveryObject : deliveryObjectLst){
            currDeliveryObject.Delivery_Date__c = System.now() - 1;    
        }
        update deliveryObjectLst;
        Test.startTest();
        CreateDeliveryObject DeliveryObjectBatch = new CreateDeliveryObject();
        Database.executeBatch(DeliveryObjectBatch);
        Test.stopTest();
       // System.assertEquals(200, [SELECT ID FROM Delivery_Object__c].Size());
        System.assert(Limits.getDMLRows() * 100 / Limits.getLimitDMLRows() < 50);
        System.assert(Limits.getDMLStatements() * 100 / Limits.getLimitDMLStatements() < 50);
        System.assert(Limits.getAggregateQueries() * 100 / Limits.getLimitAggregateQueries() < 50);
        System.assert(Limits.getQueries() * 100 / Limits.getLimitQueries() < 50);
        System.assert(Limits.getQueryRows() * 100 / Limits.getLimitQueryRows() < 50);
    } 
}