force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Available_ZipCodes__c.field-meta.xml
<CustomField>
    <fullName>Available_ZipCodes__c</fullName>
    <description>Zip Codes available for the branch</description>
    <label>Available ZipCodes</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Branch__c.Active_for_Campaigns__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Zip_Codes__c.field-meta.xml
<CustomField>
    <fullName>Zip_Codes__c</fullName>
    <label>Zip Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>35004</fullName>
            </value>
            <value>
                <fullName>35005</fullName>
            </value>
            <value>
                <fullName>35007</fullName>
            </value>
            <value>
                <fullName>35020</fullName>
            </value>
            <value>
                <fullName>35022</fullName>
            </value>
            <value>
                <fullName>35023</fullName>
            </value>
            <value>
                <fullName>35040</fullName>
            </value>
            <value>
                <fullName>35043</fullName>
            </value>
            <value>
                <fullName>35051</fullName>
            </value>
            <value>
                <fullName>35061</fullName>
            </value>
            <value>
                <fullName>35062</fullName>
            </value>
            <value>
                <fullName>35064</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZipCode__c/ZipCode__c.object-meta.xml
<CustomObject>
    <description>It contains all zip codes for the corresponding branches.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipCode__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Zip Codes</relationshipLabel>
    <relationshipName>Zip_code</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZipCode</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/updateZipCode.cls
global class updateZipCode implements Database.Batchable<sObject>, Schedulable {
    
    String query;
    
    global updateZipCode() {
      
            query = 'SELECT Id, Name, zip_codes__c,Branch__c from Product2 WHERE createdDate = Today'; 
   }
    
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new updateZipCode(), 25);
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
       
        Map<Id,String> productsBranchMap = new Map<Id, String>();
        Map<String,Set<String>> zipforBranchMap = new Map<String, Set<String>>();
      
        for(Product2 currProd: (List<Product2>)scope) {
           
            productsBranchMap.put(currProd.id,currProd.Branch__c);
        }
       
       
        for(ZipCode__c zipCode : [SELECT Id,Name,Branch__c FROM ZipCode__c WHERE Branch__c =: productsBranchMap.values()])
        {
           if(zipforBranchMap.containskey(zipCode.Branch__c))
           {
               zipforBranchMap.get(zipCode.Branch__c).add(zipCode.name);
        
           }
           else
           {
               zipforBranchMap.put(zipCode.Branch__c, new Set<String>{zipCode.name});
           
           }
        } 
        
        
        List<Product2> updateProducts = new List<Product2>();
        
        for(Product2 currProd: (List<Product2>)scope)
        {
          if(zipforBranchMap.containsKey(currProd.Branch__c))
          {
             Product2 updateProd = new Product2();
             updateProd.id = currProd.id;
             String zipVal='';
             for(String zip : zipforBranchMap.get(currProd.Branch__c))
             {
               zipVal += zip + ';';
             }
             zipVal = zipVal.removeEnd(';');
             
             updateProd.Available_ZipCodes__c = zipVal;
             updateProducts.add(updateProd);
          }
        
        }
        
        if(updateProducts.size() > 0)
                update updateProducts;
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
    
  }