force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Parameter__c/Delivery_Parameter__c.object-meta.xml
<CustomObject>
    <description>Used to hold delivery parameters.</description>
    <label>Delivery Parameter</label>
    <nameField>
        <displayFormat>DP-{0}</displayFormat>
        <label>Delivery Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Parameter__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identification of which delivery parameter currently active. if more than one delivery parameter exists for a branch.</description>
    <inlineHelpText>Unchecking this box will turn off this delivery parameter.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Delivery_Parameter__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Delivery Parameters</relationshipLabel>
    <relationshipName>Delivery_Parameters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Delivery_Parameter__c/fields/Delivery_Number__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Number__c</fullName>
    <description>Number of delivered counts.</description>
    <label>Delivery Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DeliveryParameterTriggerHandler.cls
/******************************************************************************
Created By : Sankar Marappan
Created Date : 2/9/2016
Author : MST Developer
Description : Inactive the old delivery parameters and make the recent delivery parameter
as active.
*******************************************************************************/
public class DeliveryParameterTriggerHandler {
    public static void updateDeliveryParameter(List<Delivery_Parameter__c> paramList){
        
        Set<Id> branchIds = new Set<Id>();
        Set<Id> deliveryParamIds = new Set<Id>();
        Set<Integer> deliveryNumbers = new Set<Integer>();
        
        for(Delivery_Parameter__c param : paramList){
            if(param.Branch__c != null){
                branchIds.add(param.Branch__c);
            }
            deliveryParamIds.add(param.id);
            deliveryNumbers.add((Integer)param.delivery_number__c);
        }
        List<Delivery_Parameter__c> activeParamList = [SELECT id,Active__c FROM Delivery_Parameter__c WHERE Active__c = true AND Branch__c IN: branchIds AND Id NOT IN: deliveryParamIds AND Delivery_Number__c IN: deliveryNumbers ];
        System.debug('@@activeParamList: '+activeParamList);
        if(activeParamList.size() > 0){
            for(Delivery_Parameter__c param : activeParamList){
                param.Active__c = false;
            }            
            update activeParamList;
        }
    }
}