force-app/main/default/objects/Text_Settings_Appt__c/Text_Settings_Appt__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Text Settings</label>
</CustomObject>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Appt_Confirmed_HA__c.field-meta.xml
<CustomField>
    <fullName>Appt_Confirmed_HA__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Appt. Confirmed - HA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Appt_Confirmed_SO__c.field-meta.xml
<CustomField>
    <fullName>Appt_Confirmed_SO__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Appt. Confirmed - SO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Appt_Confirmed_WA__c.field-meta.xml
<CustomField>
    <fullName>Appt_Confirmed_WA__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Appt. Confirmed - WA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Appt_Confirmed_WI__c.field-meta.xml
<CustomField>
    <fullName>Appt_Confirmed_WI__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Appt. Confirmed - WI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Appt_Set_HA__c.field-meta.xml
<CustomField>
    <fullName>Appt_Set_HA__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Appt. Set - HA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Appt_Set_SO__c.field-meta.xml
<CustomField>
    <fullName>Appt_Set_SO__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Appt. Set - SO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Appt_Set_WA__c.field-meta.xml
<CustomField>
    <fullName>Appt_Set_WA__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Appt. Set - WA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Appt_Set_WI__c.field-meta.xml
<CustomField>
    <fullName>Appt_Set_WI__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Appt. Set - WI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_Confirmation_Text_Home_A__c.field-meta.xml
<CustomField>
    <fullName>Installation_Confirmation_Text_Home_A__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - Confirmation Text Home A</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_Confirmation_Text_Pest_C__c.field-meta.xml
<CustomField>
    <fullName>Installation_Confirmation_Text_Pest_C__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - Confirmation Text Pest C</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_Confirmation_Text_Solar__c.field-meta.xml
<CustomField>
    <fullName>Installation_Confirmation_Text_Solar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - Confirmation Text Solar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_Confirmation_Text_Water__c.field-meta.xml
<CustomField>
    <fullName>Installation_Confirmation_Text_Water__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - Confirmation Text Water</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_Confirmation_Text_Window__c.field-meta.xml
<CustomField>
    <fullName>Installation_Confirmation_Text_Window__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - Confirmation Text Window</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_In_Transit_Home_Automati__c.field-meta.xml
<CustomField>
    <fullName>Installation_In_Transit_Home_Automati__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - In Transit Home Automati</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_In_Transit_Pest_Control__c.field-meta.xml
<CustomField>
    <fullName>Installation_In_Transit_Pest_Control__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - In Transit Pest Control</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_In_Transit_Solar__c.field-meta.xml
<CustomField>
    <fullName>Installation_In_Transit_Solar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - In Transit Solar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_In_Transit_Water__c.field-meta.xml
<CustomField>
    <fullName>Installation_In_Transit_Water__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - In Transit Water</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_In_Transit_Window__c.field-meta.xml
<CustomField>
    <fullName>Installation_In_Transit_Window__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - In Transit Window</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_New_Appointment_Home_Aut__c.field-meta.xml
<CustomField>
    <fullName>Installation_New_Appointment_Home_Aut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - New Appointment Home Aut</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_New_Appointment_Pest_Con__c.field-meta.xml
<CustomField>
    <fullName>Installation_New_Appointment_Pest_Con__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - New Appointment Pest Con</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_New_Appointment_Solar__c.field-meta.xml
<CustomField>
    <fullName>Installation_New_Appointment_Solar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - New Appointment Solar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_New_Appointment_Water__c.field-meta.xml
<CustomField>
    <fullName>Installation_New_Appointment_Water__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - New Appointment Water</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Installation_New_Appointment_Window__c.field-meta.xml
<CustomField>
    <fullName>Installation_New_Appointment_Window__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation - New Appointment Window</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_Confirmation_Text_Home_Automation__c.field-meta.xml
<CustomField>
    <fullName>Sale_Confirmation_Text_Home_Automation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Automatic Text - Confirmation Text</description>
    <label>Sale - Confirmation Text Home Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_Confirmation_Text_Pest_Control__c.field-meta.xml
<CustomField>
    <fullName>Sale_Confirmation_Text_Pest_Control__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - Confirmation Text Pest Control</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_Confirmation_Text_Solar__c.field-meta.xml
<CustomField>
    <fullName>Sale_Confirmation_Text_Solar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - Confirmation Text Solar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_Confirmation_Text_Water__c.field-meta.xml
<CustomField>
    <fullName>Sale_Confirmation_Text_Water__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - Confirmation Text Water</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_Confirmation_Text_Window__c.field-meta.xml
<CustomField>
    <fullName>Sale_Confirmation_Text_Window__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - Confirmation Text Window</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_In_Transit_Home_Automation__c.field-meta.xml
<CustomField>
    <fullName>Sale_In_Transit_Home_Automation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - In Transit Home Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_In_Transit_Pest_Control__c.field-meta.xml
<CustomField>
    <fullName>Sale_In_Transit_Pest_Control__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - In Transit Pest Control</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_In_Transit_Solar__c.field-meta.xml
<CustomField>
    <fullName>Sale_In_Transit_Solar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - In Transit Solar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_In_Transit_Water__c.field-meta.xml
<CustomField>
    <fullName>Sale_In_Transit_Water__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - In Transit Water</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_In_Transit_Window__c.field-meta.xml
<CustomField>
    <fullName>Sale_In_Transit_Window__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - In Transit Window</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_New_Appointment_Home_Automation__c.field-meta.xml
<CustomField>
    <fullName>Sale_New_Appointment_Home_Automation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - New Appointment Home Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_New_Appointment_Pest_Control__c.field-meta.xml
<CustomField>
    <fullName>Sale_New_Appointment_Pest_Control__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - New Appointment Pest Control</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_New_Appointment_Solar__c.field-meta.xml
<CustomField>
    <fullName>Sale_New_Appointment_Solar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - New Appointment Solar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_New_Appointment_Water__c.field-meta.xml
<CustomField>
    <fullName>Sale_New_Appointment_Water__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - New Appointment Water</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_New_Appointment_Window__c.field-meta.xml
<CustomField>
    <fullName>Sale_New_Appointment_Window__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - New Appointment Window</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomSetting_test.cls
@isTest
public class CustomSetting_test {
    
    @isTest static void Test(){  
        
        Text_Settings_Appt__c CSetting = new  Text_Settings_Appt__c(
            Name='a4Z0m0000008gcZ',
            Appt_Confirmed_HA__c = true, 
            Appt_Confirmed_SO__c = true, 
            Appt_Confirmed_WA__c = true, 
            Appt_Confirmed_WI__c = true, 
            Appt_Set_HA__c = true,
            Appt_Set_SO__c = true, 	
            Appt_Set_WA__c = true,
            Appt_Set_WI__c = true,
            Sale_Confirmation_Text_Home_Automation__c = true, 
            Sale_Confirmation_Text_Pest_Control__c = true, 
            Sale_Confirmation_Text_Solar__c = true,
            Sale_Confirmation_Text_Water__c = true, 
            Sale_Confirmation_Text_Window__c = true, 
            Sale_New_Appointment_Home_Automation__c = true, 
            Sale_New_Appointment_Pest_Control__c = true,
            Sale_New_Appointment_Solar__c = true, 
            Sale_New_Appointment_Water__c = true, 
            Sale_New_Appointment_Window__c = true, 
            Sale_In_Transit_Home_Automation__c = true, 
            Sale_In_Transit_Pest_Control__c = true,
            Sale_In_Transit_Solar__c = true, 
            Sale_In_Transit_Water__c = true, 
            Sale_In_Transit_Window__c = true,
            Installation_Confirmation_Text_Home_A__c = true, 
            Installation_Confirmation_Text_Pest_C__c = true, 
            Installation_Confirmation_Text_Solar__c = true,
            Installation_Confirmation_Text_Water__c = true, 
            Installation_Confirmation_Text_Window__c = true, 
            Installation_New_Appointment_Home_Aut__c = true,
            Installation_New_Appointment_Pest_Con__c = true, 
            Installation_New_Appointment_Solar__c = true, 
            Installation_New_Appointment_Water__c = true,
            Installation_New_Appointment_Window__c = true, 
            Installation_In_Transit_Home_Automati__c = true, 
            Installation_In_Transit_Pest_Control__c = true,
            Installation_In_Transit_Solar__c = true, 
            Installation_In_Transit_Water__c = true, 
            Installation_In_Transit_Window__c = true 
        );
        
        upsert CSetting;
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(CSetting);
        customSettings cs = new customSettings(sc);
        cs.getcustomsetting();
        cs.test();
        customSettings.getRecordId();
        customSettings.SaveInformation(CSetting);
        
        Test.stopTest();   
    }
    
}