force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/assigned__c.field-meta.xml
<CustomField>
    <fullName>assigned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>assigned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Sales Rabbit</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>WebSite</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Self Gen</fullName>
            </value>
            <value>
                <fullName>Gravel Call Center</fullName>
            </value>
            <value>
                <fullName>Networx</fullName>
            </value>
            <value>
                <fullName>Thumbtack</fullName>
            </value>
            <value>
                <fullName>Google PPC</fullName>
            </value>
            <value>
                <fullName>Yelp</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Canvas</fullName>
            </value>
            <value>
                <fullName>Salesforce Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Qualifying</fullName>
            </value>
            <value>
                <fullName>Appointment Set</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Sale Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment_RecordType_mtd__c/Appointment_RecordType_mtd__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Appointment_RecordType_mtd</label>
</CustomObject>

force-app/main/default/objects/Appointment_RecordType_mtd__c/fields/RT_Appointment_Id__c.field-meta.xml
<CustomField>
    <fullName>RT_Appointment_Id__c</fullName>
    <label>RT_Appointment_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Appointment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Appointment_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Home Services</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Appt_Sale_Status__c.field-meta.xml
<CustomField>
    <fullName>Appt_Sale_Status__c</fullName>
    <label>Appt Sale Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale Approved</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Sale Turn Down</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Sales Rabbit</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>WebSite</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Self Gen</fullName>
            </value>
            <value>
                <fullName>Gravel Call Center</fullName>
            </value>
            <value>
                <fullName>Networx</fullName>
            </value>
            <value>
                <fullName>Thumbtack</fullName>
            </value>
            <value>
                <fullName>Google PPC</fullName>
            </value>
            <value>
                <fullName>Yelp</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Warm Transfer</fullName>
            </value>
            <value>
                <fullName>Canvas</fullName>
            </value>
            <value>
                <fullName>Salesforce Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/query__c.field-meta.xml
<CustomField>
    <fullName>query__c</fullName>
    <defaultValue>false</defaultValue>
    <label>query</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateHsAppointmentApproved.cls
public  class UpdateHsAppointmentApproved  implements Queueable {
    private List<Home_Services__c> myHomeS;
    
    public UpdateHsAppointmentApproved(List<Home_Services__c> records) {
        this.myHomeS = records;
    }
    
    public void execute(QueueableContext context) {
        
        List<Appointment__c> appomts = new List<Appointment__c>();
        List<Home_Services__c> homeServices = new List<Home_Services__c>();
        integer myHomesLength = myHomeS.size();
        for (Integer i = 0; i < myHomesLength; i++) 
        {
            Home_Services__c hs = myHomeS[i];
            if( hs.Appt_Sale_Status__c == 'Sale Approved' ) {
                if( hs.Appointment_Lookup__c != null ) {
                    appomts.add( 
                        new Appointment__c(
                            id = hs.Appointment_Lookup__c,
                            Status__c = 'Sale Approved'
                    ));
                }else {
                    Appointment_RecordType_mtd__c homeServiceRtype = Appointment_RecordType_mtd__c.getValues(hs.RecordTypeId);
                    if( homeServiceRtype != null ) {
                        appomts.add(
                            new Appointment__c(
                                RecordTypeId = homeServiceRtype.RT_Appointment_Id__c,
                                assigned__c = true,
                                Person_Account__c = hs.Account__c,
                                Home_Service__c = hs.Id,
                                Status__c = 'Sale Approved',
                                Lead_Source__c = 'Automation'
                            )
                        );
                    }
                }
            }
        }
        if ( !appomts.isEmpty() ) {
            upsert appomts;

            integer appomtsLength = appomts.size();
            for (Integer i = 0; i < appomtsLength; i++) 
            {
                Appointment__c appmt = appomts[i];
                if( appmt.Lead_Source__c == 'Automation' ) {
                    homeServices.add(
                        new Home_Services__c(
                            Id = appmt.Home_Service__c,
                            Appointment_Lookup__c = appmt.Id,
                            query__c = true
                        )
                    );
                }
            }
            update homeServices;
        }    
    }
    
}