force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Appointment_Notes__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Notes__c</fullName>
    <label>Appointment Notes</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/assigned__c.field-meta.xml
<CustomField>
    <fullName>assigned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>assigned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Number_of_People_in_the_home__c.field-meta.xml
<CustomField>
    <fullName>Number_of_People_in_the_home__c</fullName>
    <label>Number of People in the home</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Number_of_Stories_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Stories_Picklist__c</fullName>
    <label>Number of Stories</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Rekey</fullName>
            </value>
            <value>
                <fullName>Pest</fullName>
            </value>
            <value>
                <fullName>Weed</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Energy Efficiencies</fullName>
            </value>
            <value>
                <fullName>Service Existing System</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Replace Existing Windows</fullName>
            </value>
            <value>
                <fullName>Repair Existing Window Glass</fullName>
            </value>
            <value>
                <fullName>Blinds/Shades</fullName>
            </value>
            <value>
                <fullName>Wood Shutters</fullName>
            </value>
            <value>
                <fullName>Vertical Blinds</fullName>
            </value>
            <value>
                <fullName>Electric Blind/Shade Opener</fullName>
            </value>
            <value>
                <fullName>Sprinkler System</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Trees/Shrubs</fullName>
            </value>
            <value>
                <fullName>Drainage System</fullName>
            </value>
            <value>
                <fullName>Wood Structure(s), Deck(s), Gazebo(s), etc</fullName>
                <label>Wood Structure(s), Deck(s), etc</label>
            </value>
            <value>
                <fullName>Concrete Patio/Walkway, etc</fullName>
            </value>
            <value>
                <fullName>Masonry/Brick/Stone work</fullName>
            </value>
            <value>
                <fullName>Fencing</fullName>
            </value>
            <value>
                <fullName>Retaining wall</fullName>
            </value>
            <value>
                <fullName>Landscape lighting</fullName>
            </value>
            <value>
                <fullName>Pool/Spa</fullName>
            </value>
            <value>
                <fullName>Storage Shed</fullName>
            </value>
            <value>
                <fullName>Built in BBQ</fullName>
            </value>
            <value>
                <fullName>Pergola</fullName>
            </value>
            <value>
                <fullName>Firepit Gas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Solar_Type__c.field-meta.xml
<CustomField>
    <fullName>Solar_Type__c</fullName>
    <label>Solar Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Energy Efficiency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Sub_Categories__c.field-meta.xml
<CustomField>
    <fullName>Sub_Categories__c</fullName>
    <label>Sub-Categories</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Windows &amp; Doors</fullName>
            </value>
            <value>
                <fullName>Blinds &amp; Shutters</fullName>
            </value>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>Garage Organization</fullName>
            </value>
            <value>
                <fullName>Garage Floor Coating</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
            <value>
                <fullName>Landscape Design</fullName>
            </value>
            <value>
                <fullName>Pool Install</fullName>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath</fullName>
            </value>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>Garage Door</fullName>
            </value>
            <value>
                <fullName>Handy Man</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/recordTypes/Solar.recordType-meta.xml
<RecordType>
    <fullName>Solar</fullName>
    <active>true</active>
    <label>Solar</label>
</RecordType>

force-app/main/default/objects/Appointment_RecordType_mtd__c/Appointment_RecordType_mtd__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Appointment_RecordType_mtd</label>
</CustomObject>

force-app/main/default/objects/Appointment_RecordType_mtd__c/fields/RT_Home_Service_Id__c.field-meta.xml
<CustomField>
    <fullName>RT_Home_Service_Id__c</fullName>
    <label>RT_Home_Service_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Appointment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Appointment_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Home Services</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/of_people_in_the_home_Home_Automation__c.field-meta.xml
<CustomField>
    <fullName>of_people_in_the_home_Home_Automation__c</fullName>
    <label>HA # of people in the home</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/People_in_the_home_solar__c.field-meta.xml
<CustomField>
    <fullName>People_in_the_home_solar__c</fullName>
    <description>Solar</description>
    <label>SO # of People in the home</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/People_in_the_home_water__c.field-meta.xml
<CustomField>
    <fullName>People_in_the_home_water__c</fullName>
    <label>WA # of people in the home</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Pest_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Pest_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Weed Control</fullName>
            </value>
            <value>
                <fullName>Pest/WeedControl</fullName>
                <label>Pest/Weed Control</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Pool_Home_Automation__c.field-meta.xml
<CustomField>
    <fullName>Pool_Home_Automation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pool.</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Pool_Solar__c.field-meta.xml
<CustomField>
    <fullName>Pool_Solar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pool</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Solar_Type__c.field-meta.xml
<CustomField>
    <fullName>Solar_Type__c</fullName>
    <label>Solar Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Energy Efficiency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Sub_Categories__c.field-meta.xml
<CustomField>
    <fullName>Sub_Categories__c</fullName>
    <label>Sub-Categories</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Windows &amp; Doors</fullName>
            </value>
            <value>
                <fullName>Blinds &amp; Shutters</fullName>
            </value>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>Garage Organization</fullName>
            </value>
            <value>
                <fullName>Garage Floor Coating</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
            <value>
                <fullName>Landscape Design</fullName>
            </value>
            <value>
                <fullName>Pool Install</fullName>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath</fullName>
            </value>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>Garage Door</fullName>
            </value>
            <value>
                <fullName>Handy Man</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/X2_Story__c.field-meta.xml
<CustomField>
    <fullName>X2_Story__c</fullName>
    <defaultValue>false</defaultValue>
    <label>2 Story</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DiacoAppointmentCreateHs.cls
/**
* Diaco
* @author 			Jeison Hernandez href=<jeison14.99@gmail.com>
* Project:			Appointment Object
* Description:		Class to create a Home services.  
*
* Changes (Version)
* -------------------------------------
*			No.		Date			Author					Description
*			-----	----------		--------------------	----------------------------
* @version	1.0		06/08/2020		Jeison Hernandez (JH)	Create A Hs of a Appointment
**/
public class DiacoAppointmentCreateHs {
	@InvocableMethod 
    public static void createHs(List<Appointment__c> AppointId){

        Id EventRecordTypeId = Schema.SObjectType.Event.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        Map<String,String> relatetofields = DiacoAppointmentHomeFields.getRelatoFields();
        List<Home_Services__c> homes = new List<Home_Services__c>();
        List<Appointment__c> appointment = new List<Appointment__c>();

        List<Event> events = new List<Event>();

        for(Appointment__c App:AppointId) {
            Appointment_RecordType_mtd__c appointmentRtype = Appointment_RecordType_mtd__c.getValues(App.recordTypeId);
            String recordTypeName = Schema.SObjectType.Appointment__c.getRecordTypeInfosById().get(App.recordTypeId).getname();
            if(appointmentRtype != null || Test.isRunningTest()) {
				
                Home_Services__c home = new Home_Services__c(Account__c=App.Person_Account__c,Appointment_Lookup__c=App.Id);
                if(!Test.isRunningTest()){
                    home.RecordTypeId = appointmentRtype.RT_Home_Service_Id__c;
                }

                for (String appointmentField : relatetofields.keySet()) {
                    
                    if( App.get(appointmentField) != null) {
                        String homeServiceFields = relatetofields.get(appointmentField);
                        home.put(homeServiceFields, App.get(appointmentField));
                    }
                }
                
                if(App.get('Number_of_Stories_Picklist__c')!=null){
                    home.put('X2_Story__c', (App.get('Number_of_Stories_Picklist__c')!='2'?false:true));
                }
                
                if(recordTypeName=='Home Automation'){
                    if(App.get('Pool__c')!=null){
                        home.put('Pool_Home_Automation__c', App.get('Pool__c'));
                    }
                    if(App.get('Number_of_People_in_the_home__c')!=null){
                        home.put('of_people_in_the_home_Home_Automation__c', App.get('Number_of_People_in_the_home__c'));
                    }  
                }else if(recordTypeName=='Water Filtration'){
                    if(App.get('Number_of_People_in_the_home__c')!=null){
                        home.put('People_in_the_home_water__c', App.get('Number_of_People_in_the_home__c'));
                    }
                }else if(recordTypeName=='Solar'){
                    if(App.get('Number_of_People_in_the_home__c')!=null){
                        home.put('People_in_the_home_solar__c', App.get('Number_of_People_in_the_home__c'));
                    }
                    if(App.get('Pool__c')!=null){
                        home.put('Pool_Solar__c', App.get('Pool__c'));
                    }
                    if(App.get('Project_Type__c')!=null){
                        home.put('Solar_Type__c', App.get('Project_Type__c'));
                    }
                }else if(recordTypeName=='Pest Control'){
                    if(App.get('Project_Type__c')!=null){
                        home.put('Pest_Service_Type__c', App.get('Project_Type__c'));
                    }
                }else if(recordTypeName=='Kitchen Remodel' || recordTypeName=='Bathroom Remodel'){
                    home.put('Sub_Categories__c', 'Kitchen & Bath');
                }

                homes.add(home);
                events.add(new Event(Description=App.Appointment_Notes__c,
                                    StartDateTime = App.Appointment_Start_Time__c, 
                                    EndDateTime=App.Appointment_End_Time__c,
                                    RecordTypeId=EventRecordTypeId));
            }
        }

        if( !homes.isEmpty() ) {

            insert homes;

            for(Integer i=0;i<AppointId.size();i++) {
                events[i].WhatId=homes[i].Id;
                events[i].Home_Service__c=homes[i].Id;

                Appointment__c appoint = (Appointment__c)JSON.deserialize(JSON.serialize(AppointId[i]), Appointment__c.class);
                appoint.assigned__c=true;
                if(!Test.isRunningTest()) appoint.Home_Service__c=homes[i].Id;
                appointment.add(appoint);
            }
            if(!Test.isRunningTest()){
                insert events;
            	upsert appointment;
            }
            
        }
    }     
}