force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/recordTypes/HVAC.recordType-meta.xml
<RecordType>
    <fullName>HVAC</fullName>
    <active>true</active>
    <label>HVAC</label>
</RecordType>

force-app/main/default/objects/Appointment__c/recordTypes/Solar.recordType-meta.xml
<RecordType>
    <fullName>Solar</fullName>
    <active>true</active>
    <label>Solar</label>
</RecordType>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Appointment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Home_Services_Status__c.field-meta.xml
<CustomField>
    <fullName>Home_Services_Status__c</fullName>
    <label>Sales Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Dispatch</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Bid Submitted</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Rehash</fullName>
            </value>
            <value>
                <fullName>Sale Pending</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Won/Canceled</fullName>
            </value>
            <value>
                <fullName>Closed Won / Service Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Hot_Lead__c.field-meta.xml
<CustomField>
    <fullName>Hot_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hot Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Industry_Formula__c.field-meta.xml
<CustomField>
    <fullName>Industry_Formula__c</fullName>
    <formula>IF(
CONTAINS( RecordType.Name , &quot;Home Automation&quot; ), &quot;Home Automation&quot;, 
IF(
CONTAINS(RecordType.Name, &quot;Solar&quot; ), &quot;Solar&quot;,
IF(
CONTAINS(RecordType.Name, &quot;Water&quot; ), &quot;Water Treatment&quot;,
IF(
CONTAINS(RecordType.Name, &quot;Remodel&quot; ), &quot;Remodel&quot;,
IF(
CONTAINS(RecordType.Name, &quot;Pest Control&quot; ), &quot;Pest Control&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Carpet &amp; Tile Cleaning&quot; ), &quot;Carpet &amp; Tile Cleaning&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Flooring&quot; ), &quot;Flooring&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Garage Doors&quot; ), &quot;Garage Doors&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Garage Floor Coating&quot; ), &quot;Garage Floor Coating&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Handy Man&quot; ), &quot;Handy Man&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Internet-Cable-Satellite&quot; ), &quot;Internet-Cable-Satelite&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Kitchen &amp; Bath&quot; ), &quot;Kitchen &amp; Bath&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Lock Smith&quot; ), &quot;Lock Smith&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Maid Service&quot; ), &quot;Maid Service&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Painting&quot; ), &quot;Painting&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Pool Maintenance&quot; ), &quot;Pool Maintenance&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;HVAC&quot; ), &quot;HVAC&quot;, 
&quot;&quot;)))))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry:</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Revenue_Note__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Note__c</fullName>
    <label>Revenue Note</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DiacoMyHomeServicesManageController.cls
public class DiacoMyHomeServicesManageController {
    public static Map<String, List<String>> industries{get; set;}
    /*
    0{'label': 'Aqua Bright Water', 'value': 'Aqua Bright Water'},
    1{'label': 'Protection Source', 'value': 'Protection Source'},
    2{'label': 'Latch', 'value': 'Latch'},
    3{'label': 'Jax Pest Control', 'value': 'Jax Pest Control'},
    4{'label': 'N-Ergy', 'value': 'N-Ergy'},
    5{'label': 'Rescue On Air', 'value': 'Rescue On Air'},*/
    public static void generateIndustries() {
        industries = new Map<String, List<String>>();
        List<String> aux;
        aux = new List<String>{'\'Pool Maintenance\'', '\'Water Treatment\''};
        industries.put('Aqua Bright Water', aux);
        aux = new List<String>{'\'Home Automation\''};
        industries.put('Protection Source', aux);
        aux = new List<String>{'\'Garage Doors\'', '\'Internet-Cable-Satelite\'', '\'Lock Smith\'', '\'Maid Service\'', '\'Remodel\'', '\'Carpet & Tile Cleaning\'', '\'Garage Floor Coating\''};
        industries.put('Latch', aux);
        aux = new List<String>{'\'Pest Control\''};
        industries.put('Jax Pest Control', aux);
        aux = new List<String>{'\'Solar\''};
        industries.put('N-Ergy', aux);
        aux = new List<String>{'\'HVAC\''};
        industries.put('Rescue On Air', aux);
        
        
        List<String> all = new List<String>{'\'Pool Maintenance\'', '\'Water Treatment\'', '\'Home Automation\'','\'Garage Doors\'', '\'Internet-Cable-Satelite\'',
                                            '\'Lock Smith\'', '\'Maid Service\'', '\'Remodel\'', '\'Carpet & Tile Cleaning\'', '\'Garage Floor Coating\'', '\'Pest Control\'', '\'Solar\'',
                                            '\'HVAC\''};
        industries.put('all', all);
            
     }
    
    @AuraEnabled
    public static List<Home_Services__c> getHomeServices(){
        generateIndustries();    
        String aux = '(' + String.join( industries.get('all'), ',' ) + ')';
        String query = 'select Id, Name, Home_Services_Status__c, Marketing__c, Data__c, Appointment__c, Hot_Lead__c, Revenue_Note__c, CreatedDate, Industry_Formula__c'
            + ' from Home_Services__c'
            + ' where Industry_Formula__c in ' + aux
            + ' order by CreatedDate desc';
        
        system.debug(aux);
        system.debug(query);
        List<Home_Services__c> HSList = Database.query(query);
        
        return HSList;
    }
    
    @AuraEnabled
    public static List<Home_Services__c> getFilterHomeServices(List<String> data, Date dateFrom, Date dateTo){
        generateIndustries();        
        /*system.debug(data[4]);
        system.debug(industries);
        system.debug(industries.get(data[4]));*/
        String query;
        DateTime dateTimeFrom;
        DateTime dateTimeTo;
        if(dateFrom == null){
            query = 'select Id, CreatedDate'
                + ' from Home_Services__c'
                + ' order by CreatedDate asc limit 1';
            
            system.debug(query);
            List<Home_Services__c> HS = Database.query(query);
            dateTimeFrom = HS[0].CreatedDate;
        }else{
            dateTimeFrom = DateTime.newInstance(dateFrom, Time.newInstance(00, 00, 00, 0000));
        }
        
        if(dateTo == null){
            dateTimeTo = DateTime.now().AddDays(1);
        }else{
            dateTimeTo = DateTime.newInstance(dateTo.addDays(1), Time.newInstance(00, 00, 00, 0000));
        }
        
        
        //data[5] = dateTimeFrom.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
        //data[6] = dateTimeTo.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
        
        String aux = '(' + String.join( (data[4] != '' ? industries.get(data[4]) : industries.get('all')), ',' ) + ')';
        query = 'select Id, Name, Home_Services_Status__c, Marketing__c, Data__c, Appointment__c, Hot_Lead__c, Revenue_Note__c, CreatedDate, Industry_Formula__c'
            + ' from Home_Services__c'
            + ' where Marketing__c in ' + data[0].split(',')
            + ' and Data__c in ' + data[1].split(',')
            + ' and Appointment__c in ' + data[2].split(',')
            + ' and Hot_Lead__c in ' + data[3].split(',')
            + ' and Industry_Formula__c in ' + aux
            + ' and CreatedDate >= ' + dateTimeFrom.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'', 'GTM') 
            + ' and CreatedDate < ' + dateTimeTo.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'','GTM')
            + ' order by CreatedDate desc';
        
        system.debug(query);
        List<Home_Services__c> HSList = Database.query(query);
        return HSList;
    }
    
    @AuraEnabled
    public static void updateHomeServices(List<Home_Services__c> HS) {
        update HS;
    }
}