force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/fields/Kunnect_ID__c.field-meta.xml
<CustomField>
    <fullName>Kunnect_ID__c</fullName>
    <inlineHelpText>This is a Required field.  If this person does not have a Kunnect account please put &quot;none&quot;</inlineHelpText>
    <label>Kunnect ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/webForm__c/webForm__c.object-meta.xml
<CustomObject>
    <label>Web Form</label>
    <nameField>
        <label>webForm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/diacoWebFormNoRepTest.cls
@isTest
public class diacoWebFormNoRepTest {
   	@isTest static void testAll(){
        Personnel__c p = new Personnel__c();
        p.Name = 'Web NoRep';
        p.First_Name__c='Web';
        p.Last_Name__c='NoRep';
        p.Kunnect_ID__c='123456789';
        p.Active__c=true;
        upsert p;
        
        test.startTest();
        
        webForm__c w = new webForm__c();
        w.Name = 'test';
        insert w;
        
        String param=w.Id+',';
        List<String> params = new List<String>();
        params.add(param);
        
        diacoWebFormNoRep.noRep(params);
        
        test.stopTest();
    }
}