force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/fields/salesRabbitUserId__c.field-meta.xml
<CustomField>
    <fullName>salesRabbitUserId__c</fullName>
    <label>SalesRabbit User Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/SF_User__c.field-meta.xml
<CustomField>
    <fullName>SF_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Personnels2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/salesRabbitSchedule__c/salesRabbitSchedule__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>this object is responsible of organize the schedules to update records in salesforce when some record in salesrabbit has been updated and delete some record in salesrabbit after some time.</description>
    <label>SalesRabbit Schedule</label>
</CustomObject>

force-app/main/default/objects/salesRabbitSchedule__c/fields/deleteAfter__c.field-meta.xml
<CustomField>
    <fullName>deleteAfter__c</fullName>
    <label>Delete After</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/salesRabbitSchedule__c/fields/maxSalePrice__c.field-meta.xml
<CustomField>
    <fullName>maxSalePrice__c</fullName>
    <label>maximun sale price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/salesRabbitSchedule__c/fields/minSalePrice__c.field-meta.xml
<CustomField>
    <fullName>minSalePrice__c</fullName>
    <label>minimum sale price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/salesRabbitSchedule__c/fields/token__c.field-meta.xml
<CustomField>
    <fullName>token__c</fullName>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/User_Address__c.object-meta.xml
<CustomObject>
    <description>It acts as a junction object between Person Account &amp; Address. And also, its hold Person Account&apos;s housing details.</description>
    <label>User Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Person Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Address__c/fields/Confirmation_Number__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Number__c</fullName>
    <description>It holds the confirmation number of the account. And it should be greater than lead id value.</description>
    <externalId>true</externalId>
    <label>Confirmation Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/creationDate__c.field-meta.xml
<CustomField>
    <fullName>creationDate__c</fullName>
    <label>Creation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/deletionDate__c.field-meta.xml
<CustomField>
    <fullName>deletionDate__c</fullName>
    <label>Deletion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/fAddress__c.field-meta.xml
<CustomField>
    <fullName>fAddress__c</fullName>
    <formula>Address__r.Street__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fAddress</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/fCity__c.field-meta.xml
<CustomField>
    <fullName>fCity__c</fullName>
    <formula>Address__r.City__c</formula>
    <label>fCity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/fEmail__c.field-meta.xml
<CustomField>
    <fullName>fEmail__c</fullName>
    <formula>UserAccount__r.PersonEmail</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fEmail</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/fFirstName__c.field-meta.xml
<CustomField>
    <fullName>fFirstName__c</fullName>
    <formula>UserAccount__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fFirstName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/fLastName__c.field-meta.xml
<CustomField>
    <fullName>fLastName__c</fullName>
    <formula>UserAccount__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fLastName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/fState__c.field-meta.xml
<CustomField>
    <fullName>fState__c</fullName>
    <formula>TEXT (Address__r.State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fState</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/fzipCode__c.field-meta.xml
<CustomField>
    <fullName>fzipCode__c</fullName>
    <formula>Address__r.Zip_Code__c</formula>
    <label>fzipCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/knock_counter__c.field-meta.xml
<CustomField>
    <fullName>knock_counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>knock counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/PersonMobilePhone__c.field-meta.xml
<CustomField>
    <fullName>PersonMobilePhone__c</fullName>
    <description>This field will store the person Mobile Phone number</description>
    <label>PersonMobilePhone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field will store the person Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/sales_rabbit_leadId__c.field-meta.xml
<CustomField>
    <fullName>sales_rabbit_leadId__c</fullName>
    <label>salesrabbit lead Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Address__c/fields/UserAccount__c.field-meta.xml
<CustomField>
    <fullName>UserAccount__c</fullName>
    <description>It keeps the person name that corresponds to the person address</description>
    <inlineHelpText>Select the person to associate with this address</inlineHelpText>
    <label>UserAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Address</relationshipLabel>
    <relationshipName>User_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/diacoBacheableSendToSROldSUserAddress.cls
/**
* Diaco
* @author 			Jorge Martinez href=<jorgeality29@gmail.com>
* Project:			SalesRabbit Integration
* Description:		method responsible for getting all user address with the necessary features and sends them to salesrabbit.  
*
* Changes (Version)
* -------------------------------------
*			No.		Date			Author					Description
*			-----	----------		--------------------	---------------
* @version	1.0		19/09/2018		Jorge Martinez (JM)		Initial implementation of the class.
**/
global class diacoBacheableSendToSROldSUserAddress implements Database.Batchable<sObject>, /*Schedulable, */Database.AllowsCallouts, Database.Stateful {
    
    public List<salesRabbitSchedule__c> settingList{get;set;}
    public salesRabbitSchedule__c salesRabbitSchedule{get;set;}
    
    
    //constructor
    public diacoBacheableSendToSROldSUserAddress(){
        settingList =  new List<salesRabbitSchedule__c>();
        salesRabbitSchedule = new salesRabbitSchedule__c();
        settingList = [select Id, deleteAfter__c, minSalePrice__c,
                       maxSalePrice__c,
                       token__c from  salesRabbitSchedule__c];
        salesRabbitSchedule = settingList[0];
    }
    /***
     * 
     * method responsible for starting the batch
     * 
     * @param BC the  batch context.
     * 
     * @return a list with user address not sent to salesrabbit.
     */
    global Database.QueryLocator start(Database.BatchableContext bc) {
          
        Date today = Date.today();
        Date before = today.addDays(-Integer.valueOf(settingList[0].deleteAfter__c));
        
        
        return Database.getQueryLocator([select Id, name, status__c, UserAccount__c, sales_rabbit_leadId__c, Sales_Price__c, CreatedDate, knock_counter__c, CreatedById,
                                         fFirstName__c, fLastName__c, Phone__c, PersonMobilePhone__c, fAddress__c, fCity__c, fState__c, fzipCode__c, fEmail__c, Confirmation_Number__c,
                                         creationDate__c, deletionDate__c
                                from User_Address__c 
                                where sales_rabbit_leadId__c = null and CreatedDate >= :before and CreatedDate <= :today 
                                and (knock_counter__c = null or knock_counter__c = 0) 
                                and Sales_Price__c >= :salesRabbitSchedule.minSalePrice__c and Sales_Price__c <= :salesRabbitSchedule.maxSalePrice__c]);
    }
    
    /***
     * 
     * method reponsible for executing the batch, take the user address not sent to salesrabbit, sends them and update them in salesforce database.
     * 
     * @param BC the  batch context.
     * @param records to process
	 */
    global void execute(Database.BatchableContext bc, List<sObject> records){
        List<User_Address__c> userList = (List<User_Address__c>) records;
        system.debug('list Size: ' + userList.size());
        if(userList != null && userList.size() > 0){
            system.debug('list Size: ' + userList.size());
            for(User_Address__c use : userList){
                if(use.status__C == null || use.status__C == ''){
                    use.status__C = 'New Lead';  
                }
                system.debug('use : '+ use);
                String [] sObjectFields = new String[]{'fFirstName__c','fLastName__c','Phone__c','PersonMobilePhone__c','fAddress__c','fCity__c','fState__c','fzipCode__c','status__c','fEmail__c'};
                String [] apiFields = new String[]{'firstName','lastName','phonePrimary','phoneAlternate','street1','city','state','zip','status','email' };
                Personnel__c per =[select Id,salesRabbitUserId__c, SF_User__c from Personnel__c where SF_User__c = :use.CreatedById limit 1];
                Integer i = 0;
                Map<String, String> mapFields = new Map<String, String>();
                
                for(String field : sObjectFields){
                    if(String.valueOf(use.get(field)) != null){
                        mapFields.put(apiFields[i], String.valueOf(use.get(field)));
                    }
                    i++;
                }
                String json = '{"data": {"userId":'+per.salesRabbitUserId__c+',';
                for(String key : mapFields.keySet()){
                    json += '"'+key+'":"' +mapFields.get(key)+'",';
                }
                json +='"customFields": {'+'"salesForceId": "'+use.Id+'",'+'"confirmationNumber": "'+use.Confirmation_Number__c+'"'+'}'+'}'+'}';
                system.debug(use.Sales_Price__c + '>='+salesRabbitSchedule.minSalePrice__c +'&&'+use.Sales_Price__c +'<'+ salesRabbitSchedule.maxSalePrice__c);
                if(use.Sales_Price__c >= salesRabbitSchedule.minSalePrice__c && use.Sales_Price__c < salesRabbitSchedule.maxSalePrice__c){
                    system.debug('token__c : '+ salesRabbitSchedule.token__c);
                    system.debug('json : '+ json);
                    
                    HttpResponse responseFsR =  DiacoSalesRabbitIntegration.createLeads(salesRabbitSchedule.token__c, json);
                    responsesFromSalesRabbit newLead = DiacoSalesRabbitIntegration.newLeadData(responseFsR);
                    use.sales_rabbit_leadId__c = String.valueOf(newLead.data.id);
                    use.creationDate__c = Date.today();
                    use.deletionDate__c = Date.today().addDays(Integer.valueOf(salesRabbitSchedule.deleteAfter__c));
                    
                }
                
                json = '';
            }
            update userList;
        }
        
    }    
    
    /***
     *
     * method responsible for ending the batch. 
     * 
     * @param BC the  batch context.
     * 
     */
    global void finish(Database.BatchableContext bc){
        
    }    
    
    /*
     *method responsible for  executing the schedule interface
     * 
     * @param SC scheduler context
     * 
     *
    global void execute(SchedulableContext SC)
	{
		database.executebatch(new diacoBacheableSendToSROldSUserAddress(),100);
	}*/
}