force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/City_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>City_Tax_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>City Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/City_Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>City_Tax_Rate__c</fullName>
    <formula>Home_Service__r.Account__r.City_lookup__r.Tax_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City Tax Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/County_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>County_Tax_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>County Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/County_Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>County_Tax_Rate__c</fullName>
    <formula>Home_Service__r.Account__r.County_Lookup__r.Tax_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>County Tax Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Line Items (HS)</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items (Product)</relationshipLabel>
    <relationshipName>Line_Items_Product</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Taxable__c.field-meta.xml
<CustomField>
    <fullName>Taxable__c</fullName>
    <formula>Product__r.Taxable__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Taxable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Total_Sales_Price_p__c.field-meta.xml
<CustomField>
    <fullName>Total_Sales_Price_p__c</fullName>
    <label>Total Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product HS</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products HS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LineItemTriggerHelper.cls
public class LineItemTriggerHelper {
    
    public static void taxFields(List<Line_Item__c> newList){
        List<Line_Item__c> liNews =new List<Line_Item__c>();
        for (Line_Item__c li : newList) {
            System.debug('Total sales '+ li.Total_Sales_Price_p__c);
            if(li.Product__c != null && li.Total_Sales_Price_p__c!=null &&
               li.Home_Service__c != null && (li.City_Tax_Rate__c!= null||li.County_Tax_Rate__c!= null)
               && li.Taxable__c){
                   System.debug(li);
                   li.City_Tax_Amount__c = li.Total_Sales_Price_p__c * li.City_Tax_Rate__c ;
                   li.County_Tax_Amount__c = li.Total_Sales_Price_p__c * li.County_Tax_Rate__c ;
                   liNews.add(li);
                   System.debug(li.City_Tax_Amount__c+ ', '+li.County_Tax_Amount__c);
               }
        }
    }
    
}