force-app/main/default/objects/Event/recordTypes/Installation.recordType-meta.xml
<RecordType>
    <fullName>Installation</fullName>
    <active>true</active>
    <label>Installation</label>
</RecordType>

force-app/main/default/objects/Event/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/ApptSetter__c.field-meta.xml
<CustomField>
    <fullName>ApptSetter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appointment Setter</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Personnel__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Personnel__c.Appt_Setter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Home Services (Appointment Setter)</relationshipLabel>
    <relationshipName>Home_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.FirstName),&apos;&apos;,Account__r.FirstName)</formula>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Home Service</relationshipLabel>
    <relationshipName>Home_Service</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <label>Installation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation__c/fields/Home_Service__c.field-meta.xml
<CustomField>
    <fullName>Home_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Service</label>
    <referenceTo>Home_Services__c</referenceTo>
    <relationshipLabel>Installation</relationshipLabel>
    <relationshipName>Installation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/diacoEventRecordTypeTest.cls
@isTest
public class diacoEventRecordTypeTest {
    @isTest static void testAll(){
        Personnel__c person = new Personnel__c (
            First_Name__c = 'Test Personnel'
        );
        insert person;
        Account acc = new Account(
            FirstName = 'Test acc',
            LastName = 'last test'
        );
        insert acc;
        Home_Services__c hs = new Home_Services__c(
            Name = 'test',
            Account__c = acc.Id,
            ApptSetter__c = person.Id
        );
        insert hs;
        Installation__c install = new Installation__c(
        	Name='test',
            Home_Service__c =hs.Id
        );
        insert install;
        User u = new user();
        u.LastName = 'Test Event';
        u.Email = 'test@test.com';
        u.Alias = 'Tcode';
        u.Username = 'TestEvent@test.com';
        u.CommunityNickname = 'test12';
        u.LocaleSidKey = 'en_US';
        u.TimeZoneSidKey = 'GMT';
        u.ProfileID = '00e41000001hNuFAAU';
        u.LanguageLocaleKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        insert u;
        User u2 = new user();
        u2.LastName = 'Test Public Calendar';
        u2.Email = 'test2@test.com';
        u2.Alias = 'PubliCa';
        u2.Username = 'TestEvent2@test.com';
        u2.CommunityNickname = 'test122';
        u2.LocaleSidKey = 'en_US';
        u2.TimeZoneSidKey = 'GMT';
        u2.ProfileID = '00e41000001hNuFAAU';
        u2.LanguageLocaleKey = 'en_US';
        u2.EmailEncodingKey = 'UTF-8';
        insert u2;
        // user = [Select Id, ProfileID, Name from User where Id='005410000028YIRAA2'];
        Event event = new Event(
            Home_Service__c = hs.Id,
            RecordTypeId = '012410000013G9CAAU',
            DurationInMinutes=1,
            ActivityDateTime= Date.Today(),
            OwnerId = u.Id
        );
        insert event;
        
        Event event2 = new Event(
            //Home_Service__c = null,
            RecordTypeId = '012410000013G9AAAU',
            DurationInMinutes=1,
            ActivityDateTime= Date.Today(),
            OwnerId =u2.Id,
            Installation__c=install.Id
        );
        insert event2;
        System.debug('-------------Test Evenet----------------');
        System.debug(event2.Home_Service__c);
        /*Event event3 = new Event(
            Home_Service__c = hs.Id,
            RecordTypeId = '012410000013G9DAAU',
            DurationInMinutes=1,
            ActivityDateTime= Date.Today(),
            OwnerId =u2.Id
        );
        insert event3;*/
        test.startTest();
        String param = event.Id+',Sales';
        List<String> params = new List<String>();
        params.add(param);
        String param2 = event2.Id+',Installation';
        List<String> params2 = new List<String>();
        params2.add(param2);
        //String param3 = event3.Id+',Service Technician';
        //List<String> params3 = new List<String>();
        //params3.add(param3);
        diacoEventRecordType.REcordTypeEvent(params);
        diacoEventRecordType.REcordTypeEvent(params2);
        diacoEventRecordType rt = new diacoEventRecordType();
        rt.EventsRT(event2.Id,'Installation', false);
        rt.EventsRT(event.Id,'Sales', false);
        diacoEventPublic.Ispublic(params2);
        //diacoEventRecordType.REcordTypeEvent(params3);
        test.stopTest();
    }
}