force-app/main/default/objects/Event/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Home Services (Account)</relationshipLabel>
    <relationshipName>Home_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Appointment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date_Time__c</fullName>
    <label>Appointment Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/ApptSetter__c.field-meta.xml
<CustomField>
    <fullName>ApptSetter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appointment Setter</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Personnel__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Personnel__c.Appt_Setter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Personnel__c</referenceTo>
    <relationshipLabel>Home Services (Appointment Setter)</relationshipLabel>
    <relationshipName>Home_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Confirmation_Call_Count__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Call_Count__c</fullName>
    <label>Confirmation Call Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.FirstName),&apos;&apos;,Account__r.FirstName)</formula>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.LastName),&apos;&apos;,Account__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Personnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/fields/Kunnect_ID__c.field-meta.xml
<CustomField>
    <fullName>Kunnect_ID__c</fullName>
    <inlineHelpText>This is a Required field.  If this person does not have a Kunnect account please put &quot;none&quot;</inlineHelpText>
    <label>Kunnect ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personnel__c/fields/SF_User__c.field-meta.xml
<CustomField>
    <fullName>SF_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Personnels2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/User/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiacoCmpEventTest.cls
@isTest
public class DiacoCmpEventTest {
    @isTest static void testAll(){
	User usr = [Select Id from User where Name='Cody Garrett' limit 1];
    	Account acc   = new Account();
        acc.FirstName = 'Test';
        acc.LastName  = 'test';
        Upsert acc;
        Personnel__c personel  = new Personnel__c();                                                                             // Creo Personel: Requisito del HS
        personel.Kunnect_ID__c = 'test';
        personel.First_Name__c = 'test';
        personel.Last_Name__c  = 'test';
        personel.SF_User__c=usr.Id;
        Upsert personel;
        Id rtId = Schema.SObjectType.Home_Services__c.getRecordTypeInfosByName().get('Water Treatment Sales').getRecordTypeId(); // ID del RT - HS Water
        Home_Services__c hs = new Home_Services__c();                                                                             // Creo HS
        hs.Name                             = 'Test Test - Water Treatment Sales';
        hs.RecordTypeId                     = rtId;
        hs.Account__c                       = acc.Id;
        hs.ApptSetter__c                    = personel.Id;
        hs.Confirmation_Call_Count__c       = 5;                                                                                  // Se supone que esto se llena al crear 5 Task pero nos da error de SOQL, entonces hice igual que tu.
        hs.Appointment_Date_Time__c         =null;
        Upsert hs;
        Event ev2   = new Event();
        ev2.Subject = 'Test';
        ev2.StartDateTime = System.now();
        ev2.EndDateTime=System.now();
        ev2.Home_Service__c=hs.Id;
        ev2.WhatId=hs.Id;
        ev2.IsPublic__c= false;
        test.startTest();
        DiacoCmpEvent.saveDataEvent(ev2);
        test.stopTest();
    }
}