force-app/main/default/objects/SMS_Notification_Status__c/SMS_Notification_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SMS Notification Status</description>
    <label>SMS Notification Status</label>
</CustomObject>

force-app/main/default/objects/SMS_Notification_Status__c/fields/conditions__c.field-meta.xml
<CustomField>
    <fullName>conditions__c</fullName>
    <description>possible values OR, AND,CUSTOM_lOGIC</description>
    <inlineHelpText>possible values OR, AND,CUSTOM_lOGIC</inlineHelpText>
    <label>conditions</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Customize_Logic__c.field-meta.xml
<CustomField>
    <fullName>Customize_Logic__c</fullName>
    <description>Customize the logic for the filter conditions that you specified. For example: 1 &amp;&amp;  (2 || 3)</description>
    <inlineHelpText>Customize the logic for the filter conditions that you specified. For example: 1 &amp;&amp; (2 || 3)</inlineHelpText>
    <label>Customize Logic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Diaco_SenderId__c.field-meta.xml
<CustomField>
    <fullName>Diaco_SenderId__c</fullName>
    <label>Diaco SenderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Diaco_TemplateId__c.field-meta.xml
<CustomField>
    <fullName>Diaco_TemplateId__c</fullName>
    <label>Diaco TemplateId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_SenderId__c.field-meta.xml
<CustomField>
    <fullName>Magic_SenderId__c</fullName>
    <label>Magic SenderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_Source__c.field-meta.xml
<CustomField>
    <fullName>Magic_Source__c</fullName>
    <label>Magic Source</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_TemplateId__c.field-meta.xml
<CustomField>
    <fullName>Magic_TemplateId__c</fullName>
    <label>Magic TemplateId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Object_ApiName__c.field-meta.xml
<CustomField>
    <fullName>Object_ApiName__c</fullName>
    <label>Object ApiName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/ParentId_ApiName__c.field-meta.xml
<CustomField>
    <fullName>ParentId_ApiName__c</fullName>
    <label>ParentId ApiName</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/PhoneNumber_ApiName__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber_ApiName__c</fullName>
    <label>PhoneNumber ApiName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/SMSText__c.field-meta.xml
<CustomField>
    <fullName>SMSText__c</fullName>
    <description>Text Message</description>
    <inlineHelpText>You&apos;ll ignore the Template Id when If this field is populated</inlineHelpText>
    <label>SMSText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiacoSMSNotificationController.cls
/**
 * @description       : 
 * @author            : William Aldana
 * @group             : 
 * @last modified on  : 01-08-2021
 * @last modified by  : William Aldana
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   12-23-2020   William Aldana   Initial Version
**/
public class DiacoSMSNotificationController {

    @AuraEnabled
    public static WrapperResponse getRecordId() {
        List<SMS_Notification_Status__c> sett = [SELECT Id,Name,ParentId_ApiName__c,Active__c,Category__c,Diaco_SenderId__c,Diaco_TemplateId__c,
                                                        SMSText__c,Magic_SenderId__c,Magic_Source__c,Magic_TemplateId__c,conditions__c,Customize_Logic__c,Object_ApiName__c,Provider__c,Type__c,PhoneNumber_ApiName__c
                                                FROM SMS_Notification_Status__c];
        // key will be category
        Map<String, Map<String, DiacoSMSNotificationDTO.typeNot>> mapPrefill = new Map<String, Map<String, DiacoSMSNotificationDTO.typeNot>>();
        List<SMS_Notification_Status__c> allNotifications = new List<SMS_Notification_Status__c>();
        for (SMS_Notification_Status__c notSt : sett) {
            String key = notSt.Category__c == null ? 'Not Categorised' : notSt.Category__c;
            if(mapPrefill.get(key) == null){
                mapPrefill.put(key, new Map<String, DiacoSMSNotificationDTO.typeNot>());        
            }
            String type = notSt.Type__c == null ? 'Not Typed' : notSt.Type__c;
            if(mapPrefill.get(key).get(type) == null){
                mapPrefill.get(key).put(type, new DiacoSMSNotificationDTO.typeNot());
            }
            
            if(mapPrefill.get(key).get(type).notifications == null){
                mapPrefill.get(key).get(type).type = type;
                mapPrefill.get(key).get(type).notifications = new List<SMS_Notification_Status__c>(); 
            }

            mapPrefill.get(key).get(type).notifications.add(notSt);    
            allNotifications.add(notSt);        
        }

        // create List of (DiacoSMSNotificationDTO) to sent to the aura
        List<DiacoSMSNotificationDTO> SMSettings = new List<DiacoSMSNotificationDTO>();
        
        for(String key : mapPrefill.keySet()){
            DiacoSMSNotificationDTO smSetting = new DiacoSMSNotificationDTO();
            smSetting.category = key;
            smSetting.TypeNotList = new List<DiacoSMSNotificationDTO.typeNot>();
            Map<String, DiacoSMSNotificationDTO.typeNot> item = mapPrefill.get(key);
            for (String typeS : item.keySet()) {
                smSetting.TypeNotList.add(item.get(typeS));
            }

            SMSettings.add(smSetting);
        }

        Boolean isSystemAdmin = false;
        Profile[] systemAdmin = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        if ( !systemAdmin.isEmpty() ) {
            isSystemAdmin = systemAdmin[0].Id == UserInfo.getProfileId();
        }
        WrapperResponse response = new WrapperResponse();
        response.SMSettings = SMSettings;
        response.allNotifications = allNotifications;
        response.isSystemAdmin = isSystemAdmin;
        return response;
    }
    
	@AuraEnabled
    public static void SaveInformation(List<SMS_Notification_Status__c> notifications){
        update notifications;
    }
    
    @AuraEnabled
    public static void Createinformation(List<SMS_Notification_Status__c> notifications){
        insert notifications;
    }

    public class WrapperResponse {
        @AuraEnabled
        public List<DiacoSMSNotificationDTO> SMSettings;
        @AuraEnabled
        public  List<SMS_Notification_Status__c> allNotifications;
        @AuraEnabled 
        public Boolean isSystemAdmin;
    } 

}