force-app/main/default/objects/SMS_Notification_Status__c/SMS_Notification_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SMS Notification Status</description>
    <label>SMS Notification Status</label>
</CustomObject>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Diaco_SenderId__c.field-meta.xml
<CustomField>
    <fullName>Diaco_SenderId__c</fullName>
    <label>Diaco SenderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Diaco_TemplateId__c.field-meta.xml
<CustomField>
    <fullName>Diaco_TemplateId__c</fullName>
    <label>Diaco TemplateId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_SenderId__c.field-meta.xml
<CustomField>
    <fullName>Magic_SenderId__c</fullName>
    <label>Magic SenderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_Source__c.field-meta.xml
<CustomField>
    <fullName>Magic_Source__c</fullName>
    <label>Magic Source</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/Magic_TemplateId__c.field-meta.xml
<CustomField>
    <fullName>Magic_TemplateId__c</fullName>
    <label>Magic TemplateId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/ParentId_ApiName__c.field-meta.xml
<CustomField>
    <fullName>ParentId_ApiName__c</fullName>
    <label>ParentId ApiName</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/PhoneNumber_ApiName__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber_ApiName__c</fullName>
    <label>PhoneNumber ApiName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Notification_Status__c/fields/SMSText__c.field-meta.xml
<CustomField>
    <fullName>SMSText__c</fullName>
    <description>Text Message</description>
    <inlineHelpText>You&apos;ll ignore the Template Id when If this field is populated</inlineHelpText>
    <label>SMSText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Send_Condition__c/SMS_Send_Condition__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SMS Send Condition</description>
    <label>SMS Send Condition</label>
</CustomObject>

force-app/main/default/classes/CreateSMS.cls
/*
 * Diaco
 * @author             Jull Quintero D
 * Project:            SMS
 * TestClass:          CreateSMSTest
 * Description:        Create Diaco SMS OR Magic SMS
 *
 * Changes (Version)
 * _________________________________________
 *            No.        Date            Author                    Description
 *            ____    __________        __________________      _____________________________________
 * @version   1.0    19/12/2020         Jull Quintero D          Initial implementation of the class.
 **/

public class CreateSMS extends DiacoSMSettings {

    /*
     * @Author: Jull Q Daza - 19/12/2020
     *
     * This Constructor is responsible to Create Diaco SMS OR Magic SMS
     *  
     * @param List (SObject)
     * @param Map (SObject) 
     * @param String (Object ApiName)
     * @param Boolean (Update)
     */
    public CreateSMS(SObject[] currents, Map<Id, SObject> oldMap,Boolean isInsert,Boolean isUpdate) {
        if( !currents.isEmpty() ) {
            Id recordId = (Id)currents[0].get('Id');
            String objectApiName = recordId.getSObjectType().getDescribe().getName();        
            NotCondData notCondactives = getConditionsToEvaluate(objectApiName,isInsert,isUpdate);
    
            Integer currentLgth = currents.size();
            if(notCondactives != null && notCondactives.conditionsByNot != null && !notCondactives.conditionsByNot.isEmpty()) {

                for (Integer i = 0; i < currentLgth; i++) {
                    SObject current = currents[i];
                    SObject old = isUpdate ? oldMap.get(current.Id) : null;
        
                    for (Id notToEval : notCondactives.notifications.keyset()) {
                        SMS_Notification_Status__c notification = notCondactives.notifications.get(notToEval);
                        List<SMS_Send_Condition__c> conditions = notCondactives.conditionsByNot.get(notToEval);
                        if( notification != null && conditions != null  )
                            if ( evaluateConditions(notification,conditions,current,old,isUpdate) ) {
                                makeSMS(current,notification);
                            }  
                    }
                }

                sendSMS();
            }
        }
    }

    public static void sendSMS() {

        // Insert SMS
        System.debug('MagicSMS ' + MagicSMS.listSmsMagics);
        if( !MagicSMS.listSmsMagics.isEmpty() ) {
            Database.insert(MagicSMS.listSmsMagics, true);
            MagicSMS.listSmsMagics.clear();
        }
        
        System.debug('DiacoSMS ' + DiacoSMS.listSmsDiaco);
        if( !DiacoSMS.listSmsDiaco.isEmpty() ) {
            if( !Test.isRunningTest() )Database.insert(DiacoSMS.listSmsDiaco, true);
            DiacoSMS.listSmsDiaco.clear();
        }
    }

    public static void makeSMS(SObject current, SMS_Notification_Status__c notification) {
        if( notification.active__c ) {
            // create sms
            Id parentId = (Id)current.get(notification.ParentId_ApiName__c);
            String phoneNumber = (String)current.get(notification.PhoneNumber_ApiName__c);
            System.debug('>> parentId ' + parentId);
            System.debug('>> phoneNumber ' + phoneNumber); 
            if( parentId != null && phoneNumber!= null ) {
                if( notification.Provider__c == 'Diaco SMS' ) { 
                    // Diaco SMS
                    new DiacoSMS(
                        parentId,
                        notification.Diaco_SenderId__c,
                        notification.Diaco_TemplateId__c,
                        notification.SMSText__c,
                        phoneNumber,
                        DateTime.now(),
                        true
                    );            
                } 
                
                if( notification.Provider__c == 'Magic SMS' || Test.isRunningTest() ) { 
                    // Magic SMS
                    new MagicSMS(
                        parentId,
                        notification.Magic_SenderId__c,
                        notification.Magic_TemplateId__c,
                        notification.SMSText__c,
                        phoneNumber,
                        notification.Magic_Source__c
                    );
                }
            }
        }
    }
}