force-app/main/default/objects/Diaco_SMS_Setting__mdt/Diaco_SMS_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Diaco SMS Setting</label>
    <pluralLabel>Diaco SMS Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/Home_Services__c.object-meta.xml
<CustomObject>
    <label>Home Service</label>
    <nameField>
        <label>Home Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Services__c/fields/Appt_Window_Time__c.field-meta.xml
<CustomField>
    <fullName>Appt_Window_Time__c</fullName>
    <formula>IF( 
ISBLANK(Appointment_Date_Time__c ),&quot;&quot;, 

IF( 
OR( 
VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24), 12, 2 ) ) = 0, 
VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24 ), 12, 2 ) ) = 12 
), 
&quot;12&quot;, 
TEXT( VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24), 12, 2 ) ) 
- 
IF( 
VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24), 12, 2 ) ) &lt; 12, 
0, 
12 
) 
) 
) 
&amp; &quot;:&quot; &amp; 
MID( TEXT(  Appointment_Date_Time__c  - 7/24 ), 15, 2 ) 
&amp; &quot; &quot; &amp; 
IF( 
VALUE( MID( TEXT( Appointment_Date_Time__c - 7/24), 12, 2 ) ) &lt; 12, 
&quot;AM&quot;, 
&quot;PM&quot;) 

+ &quot; - &quot; + 

IF( 
OR( 
VALUE( MID( TEXT( Appt_End_Time__c - 7/24), 12, 2 ) ) = 0, 
VALUE( MID( TEXT( Appt_End_Time__c - 7/24 ), 12, 2 ) ) = 12 
), 
&quot;12&quot;, 
TEXT( VALUE( MID( TEXT( Appt_End_Time__c - 7/24), 12, 2 ) ) 
- 
IF( 
VALUE( MID( TEXT( Appt_End_Time__c - 7/24), 12, 2 ) ) &lt; 12, 
0, 
12 
) 
) 
) 
&amp; &quot;:&quot; &amp; 
MID( TEXT( Appt_End_Time__c - 7/24 ), 15, 2 ) 
&amp; &quot; &quot; &amp; 
IF( 
VALUE( MID( TEXT( Appt_End_Time__c - 7/24), 12, 2 ) ) &lt; 12, 
&quot;AM&quot;, 
&quot;PM&quot; 
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Appt Window Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Automatic_Text_Confirmation_C__c.field-meta.xml
<CustomField>
    <fullName>Automatic_Text_Confirmation_C__c</fullName>
    <formula>IF(  $Setup.Text_Settings_Appt__c.Sale_Confirmation_C_Home_Automation__c  = TRUE, 
&quot;Home Automation&quot;+BR(),&quot;&quot;)+ 
IF(  $Setup.Text_Settings_Appt__c.Sale_Confirmation_C_Pest_Control__c  = TRUE, &quot;Pest Control&quot;+BR(),&quot;&quot;)+ 
IF(  $Setup.Text_Settings_Appt__c.Sale_Confirmation_C_Solar__c  = TRUE,&quot;Solar&quot;+BR(),&quot;&quot;)+ 
IF(  $Setup.Text_Settings_Appt__c.Sale_Confirmation_C_Water__c  = TRUE,&quot;Water&quot;+BR(),&quot;&quot;)+ 
IF(  $Setup.Text_Settings_Appt__c.Sale_Confirmation_C_Window__c  =TRUE,&quot;Remodel&quot;+BR(),&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Automatic Text - Confirmation &quot;C&quot;</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Confirmation_Call_Count__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Call_Count__c</fullName>
    <label>Confirmation Call Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>IF(ISBLANK(Account__r.FirstName),&apos;&apos;,Account__r.FirstName)</formula>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Industry_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Industry_Company_Name__c</fullName>
    <formula>IF( 
CONTAINS( RecordType.Name , &quot;Home Automation&quot; ), &quot;Protection Source&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Solar&quot; ), &quot;N-Ergy&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Water&quot; ), &quot;Aqua Bright Water&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Remodel&quot; ), &quot;Latch&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Pest Control&quot; ), &quot;Jax Pro Pest&quot;, 
RecordType.Name)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry Company Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Industry_Formula__c.field-meta.xml
<CustomField>
    <fullName>Industry_Formula__c</fullName>
    <formula>IF(
CONTAINS( RecordType.Name , &quot;Home Automation&quot; ), &quot;Home Automation&quot;, 
IF(
CONTAINS(RecordType.Name, &quot;Solar&quot; ), &quot;Solar&quot;,
IF(
CONTAINS(RecordType.Name, &quot;Water&quot; ), &quot;Water Treatment&quot;,
IF(
CONTAINS(RecordType.Name, &quot;Remodel&quot; ), &quot;Remodel&quot;,
IF(
CONTAINS(RecordType.Name, &quot;Pest Control&quot; ), &quot;Pest Control&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Carpet &amp; Tile Cleaning&quot; ), &quot;Carpet &amp; Tile Cleaning&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Flooring&quot; ), &quot;Flooring&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Garage Doors&quot; ), &quot;Garage Doors&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Garage Floor Coating&quot; ), &quot;Garage Floor Coating&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Handy Man&quot; ), &quot;Handy Man&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Internet-Cable-Satellite&quot; ), &quot;Internet-Cable-Satelite&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Kitchen &amp; Bath&quot; ), &quot;Kitchen &amp; Bath&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Lock Smith&quot; ), &quot;Lock Smith&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Maid Service&quot; ), &quot;Maid Service&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Painting&quot; ), &quot;Painting&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;Pool Maintenance&quot; ), &quot;Pool Maintenance&quot;, 
IF( 
CONTAINS(RecordType.Name, &quot;HVAC&quot; ), &quot;HVAC&quot;, 
&quot;&quot;)))))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry:</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Services__c/fields/Phone_Number_1__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_1__c</fullName>
    <formula>Account__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone Number 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/Text_Settings_Appt__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Text Settings</label>
</CustomObject>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_Confirmation_C_Home_Automation__c.field-meta.xml
<CustomField>
    <fullName>Sale_Confirmation_C_Home_Automation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - Confirmation &quot;C&quot; Home Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_Confirmation_C_Pest_Control__c.field-meta.xml
<CustomField>
    <fullName>Sale_Confirmation_C_Pest_Control__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - Confirmation &quot;C&quot; Pest Control</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_Confirmation_C_Solar__c.field-meta.xml
<CustomField>
    <fullName>Sale_Confirmation_C_Solar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - Confirmation &quot;C&quot; Solar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_Confirmation_C_Water__c.field-meta.xml
<CustomField>
    <fullName>Sale_Confirmation_C_Water__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - Confirmation &quot;C&quot; Water</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Text_Settings_Appt__c/fields/Sale_Confirmation_C_Window__c.field-meta.xml
<CustomField>
    <fullName>Sale_Confirmation_C_Window__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sale - Confirmation &quot;C&quot; Window</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ConfirmationCallSms.cls
/*
 * Diaco
 * @author             Jull Quintero D
 * Project:            SMS
 * TestClass:          ConfirmationCallSmsTest
 * Description:        Create Confirmation "C" In Diaco SMS Or Magic SMS
 *
 * Changes (Version)
 * _________________________________________
 *            No.        Date            Author                    Description
 *            ____    __________        __________________      _____________________________________
 * @version   1.0    02/12/2020         Jull Quintero D          Initial implementation of the class.
 * @version   1.1    15/12/2020         Jull Quintero D          implementation SMS Class

 **/

public class ConfirmationCallSms extends DiacoSMSettings {
    private static final List<String> SDIACOPHONENUMBERS = new List<String>{'Water','Pest','Remodel','HA','Solar'};
    private static final List<String> SMAGICLABELS = new List<String>{'Sales:Water','Sales:Pest','Sales:Remodel','Sales:HA','Sales:Solar'};
    private static final List<String> SMAGICTEMPLATES = new List<String>{'Sales Appt Confirmation "C"'};

    /*
    *@Author: Jull Q Daza - 02/12/2020
     * This Constructor is responsible to create SALES CONFIRMATION CALL SMS
     * 
     * Is used in:
     * 
     * HomeServicesTriggerHelper.cls
     * 
     * @param List Home_Services__c newHS, List Home_Services__c oldHS
     */

    public ConfirmationCallSms(List<Home_Services__c> homeServices, Map<Id,Home_Services__c> oldHServiceMap) {

        Integer homeServiceLength = homeServices.size();
        for (Integer i = 0; i < homeServiceLength; i++) {
            Home_Services__c currentHS = homeServices[i];
            Home_Services__c oldHS = oldHServiceMap.get(currentHS.Id);
            if( currentHS.Confirmation_Call_Count__c == 5 &&  
                String.isNotBlank(currentHS.Phone_Number_1__c) &&
                String.isNotBlank(currentHS.Appt_Window_Time__c) &&
                String.isNotBlank(currentHS.Automatic_Text_Confirmation_C__c) &&
                currentHS.Confirmation_Call_Count__c != oldHS.Confirmation_Call_Count__c )
            {   
                Sms water = new Sms(
                    currentHS,oldHS,DiacoSMSettings.getTextSetting.Sale_Confirmation_C_Water__c,
                    'Water','Sale_Confirmation_C_Water','Water','Sales:Water','Sales Appt Confirmation "C"'
                ); 
                if( water.sendSMS() ) continue;

                Sms pestControl = new Sms(
                    currentHS,oldHS,DiacoSMSettings.getTextSetting.Sale_Confirmation_C_Pest_Control__c,
                    'Pest Control','Sale_Confirmation_C_Pest_Control','Pest','Sales:Pest','Sales Appt Confirmation "C"'
                ); 
                if( pestControl.sendSMS() ) continue;

                Sms remodel = new Sms(
                    currentHS,oldHS,DiacoSMSettings.getTextSetting.Sale_Confirmation_C_Window__c,
                    'Remodel','Sale_Confirmation_C_Remodel','Remodel','Sales:Remodel','Sales Appt Confirmation "C"'
                ); 
                if( remodel.sendSMS() ) continue;

                Sms HomeAutomation = new Sms(
                    currentHS,oldHS,DiacoSMSettings.getTextSetting.Sale_Confirmation_C_Home_Automation__c,
                    'HA','Sale_Confirmation_C_Home_Automation','HA','Sales:HA','Sales Appt Confirmation "C"'
                ); 
                if( HomeAutomation.sendSMS() ) continue;

                Sms solar = new Sms(
                    currentHS,oldHS,DiacoSMSettings.getTextSetting.Sale_Confirmation_C_Solar__c,
                    'Solar','Sale_Confirmation_C_Solar','Solar','Sales:Solar','Sales Appt Confirmation "C"'
                ); 
                if( solar.sendSMS() ) continue;
            }
        }
        if( !MagicSMS.listSmsMagics.isEmpty() ) {
            Database.insert(MagicSMS.listSmsMagics, false);
            MagicSMS.listSmsMagics.clear();
        }
        
        if( !DiacoSMS.listSmsDiaco.isEmpty() ) {
            if( !Test.isRunningTest() )Database.insert(DiacoSMS.listSmsDiaco, false);
            DiacoSMS.listSmsDiaco.clear();
        }

    }

    private static String getMessage(Home_Services__c currentHS) {
        String message = 'Hello ' + currentHS.first_name__c + ', this is ' + currentHS.Industry_Company_Name__c + ' with a friendly reminder for your ' + currentHS.Industry_Formula__c + ' appointment tomorrow between ' + currentHS.appt_window_time__c + 
        '. Please text “C” to confirm. We look forward to meeting with you!';
        return message;
    }

    /*@Author: Jull Q Daza - 15/12/2020
     * This method is responsible to create SMS With Magic Or Diaco SMS for Home Service Record type;
     * Water, Pest, Remodel,Home Automation, Solar
     * 
     * This method is used in:
     * Constructor class ConfirmationCallSms
     * 
     *@param Home_Services__c new Home Service
     *@param Home_Services__c old Home Service 
     *@param Text_Settings_Appt__c Custom Setting(Hierarchy)
     *@param String RecordType Name
     *@param Diaco_SMS_Setting__mdt Custom Metadata Type
     *@param dsms__Phone_Number__c SMS Diaco Sender Name
     *@param smagicinteract__SMS_SenderId__c SMS Magic Sender Name 
     *@param smagicinteract__SMS_Template__c SMS Magic Template Name 
     */
    private class Sms{
        private Home_Services__c currentHS{get;set;}
        private Home_Services__c oldHS{get;set;}
        private Boolean textActive{get;set;}
        private String oType{get;set;}
        private String diacoSmsMtd{get;set;}
        private String dSMSenderName{get;set;}
        private String mgicSenderName{get;set;}
        private String magicTemplateName{get;set;}

        private Sms(Home_Services__c currentHS,Home_Services__c oldHS,Boolean textActive,
                    String oType,String diacoSmsMtd,String dSMSenderName,
                    string mgicSenderName, string magicTemplateName) 
        {
            this.currentHS = currentHS;
            this.oldHS = oldHS;
            this.textActive = textActive;
            this.oType = oType;
            this.diacoSmsMtd = diacoSmsMtd;
            this.dSMSenderName = dSMSenderName;
            this.mgicSenderName = mgicSenderName;
            this.magicTemplateName = magicTemplateName;
        }

        public Boolean sendSMS() {
            if( containsRecordtype(this.currentHS.RecordTypeId,this.textActive,this.oType,'Home_Services__c') ) {
                // create sms
                Boolean smsDiacoActivate = diacoSMSActive(this.diacoSmsMtd);
                if( smsDiacoActivate ) {
                    // diaco sms
                    String message = getMessage(this.currentHS);
                    String senderId = getDiacoSMSenderId(SDIACOPHONENUMBERS).get(this.dSMSenderName);
                    if( senderId != null ) 
                        new DiacoSMS(
                            senderId,
                            this.currentHS.Id,
                            this.currentHS.Phone_Number_1__c,
                            message,// messages
                            DATE.today(),
                            true
                        );             
                }
                if( !smsDiacoActivate || Test.isRunningTest() ) {
                    // magic sms
                    String senderId = getMagicSenderId(SMAGICLABELS).get(this.mgicSenderName);
                    Id templateId = getMagicTemplate(SMAGICTEMPLATES).get(this.magicTemplateName);
                    if( templateId != null && senderId != null )
                        new MagicSMS(
                            templateId,
                            senderId,
                            'Home_Services__c',
                            this.currentHS.Id,
                            this.currentHS.Phone_Number_1__c,
                            '1495' //source
                        );
                }
                return true;
            }return false;
        } 
    }
}