force-app/main/default/objects/CheckResultsJob__c/CheckResultsJob__c.object-meta.xml
<CustomObject>
    <label>Check Results Job</label>
    <nameField>
        <displayFormat>Job-{0000000}</displayFormat>
        <label>Check Results Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Results Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CheckResultsJob__c/fields/CallCountFiltered__c.field-meta.xml
<CustomField>
    <fullName>CallCountFiltered__c</fullName>
    <label>Call Count Filtered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CheckResultsJob__c/fields/Job_Result__c.field-meta.xml
<CustomField>
    <fullName>Job_Result__c</fullName>
    <label>Job Result</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CheckResultsJob__c/fields/MatchingInventory__c.field-meta.xml
<CustomField>
    <fullName>MatchingInventory__c</fullName>
    <label>Matching Inventory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CheckResultsJob__c/fields/OBCMUserAddress__c.field-meta.xml
<CustomField>
    <fullName>OBCMUserAddress__c</fullName>
    <label>OBCM User Address</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CheckResultsJob__c/fields/UnmatchingInventory__c.field-meta.xml
<CustomField>
    <fullName>UnmatchingInventory__c</fullName>
    <label>Unmatching Inventory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/nuhome_Call_Center_Batch_Test.cls
/* Created By : MST Solutions
* Created Date : Jan/18/2017
* Description : This test class created for nuHome_Call_Center_Batch_AC class.
* */
@isTest
public class nuhome_Call_Center_Batch_Test {
    
    private static testMethod void nuHomeCallCenter_testbatch(){
        Test.startTest();
        // To insert call center campaign and get campaign Id
        Id CallCampaignId = TestNuHomeCallCenterUtill.insertCallCenterCampaign();
        Test.stopTest();
        // To call the method from controller
        CheckResultsJob__c Check =[SELECT id,Name,Job_Result__c,OBCMUserAddress__c,MatchingInventory__c,UnmatchingInventory__c,CallCountFiltered__c FROM CheckResultsJob__c];
        Check.Job_Result__c =2;
        Check.OBCMUserAddress__c =2;
        Check.MatchingInventory__c =2;
        Check.UnmatchingInventory__c =2;
        update Check;
        
        
        
        nuHome_Call_Center_AC nuHomeCallCenter = new nuHome_Call_Center_AC();
        //To send call center priorities values to controller method
        nuHomeCallCenter.selectedPriorityCampaign = CallCampaignId;
        nuHomeCallCenter.priorityInst.DailyCallCount__c = 5;
        nuHomeCallCenter.priorityInst.OBCMMatchingInventories__c = 5;
        nuHomeCallCenter.priorityInst.OBCMUnMatchingInventories__c = 0;
        nuHomeCallCenter.priorityInst.RespondDateMinRange__c = '0';
        nuHomeCallCenter.priorityInst.RespondDateMaximumRange__c = '5';
        
        
        nuHomeCallCenter.checkResults();
        nuHomeCallCenter.priorityInst.Id = nuHomeCallCenter.selectedPriorityId;
        nuHomeCallCenter.createCallLogs();
        nuHomeCallCenter.rolloverRefresh();
        
        // Database.executeBatch(new nuHome_Call_Center_Batch_AC(query),200);
    }
    
    private static testMethod void nuHomeCallCenter_testUnMatch(){
        
        TestNuHomeCallCenterUtill.insertCallRecords();
        
        
    }
    
}